### ISSUE TITLE
Request textDocument/hover not sent for C++.

### ISSUE THREAD

**Issue by hifall** [TypeFox/monaco-languageclient#102]
When I hover over a C++ construct (namespace, class, etc.), I expect a popover to appear. However, none does.

Here is the response I got from the server during initialization:

`{"id":0,"jsonrpc":"2.0","result":{"capabilities":{"codeActionProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":[".",">",":"]},"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix"]},"renameProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"textDocumentSync":1}}}`

The reason why there is no hover popover when a construct is hovered is, no textDocument/hover request is sent from the client. This is confirmed by looking at the ws traffic.

Is this behavior expected?

**Comment by akosyakov** [comment]
It looks like C++ LS does not support hover. It should return `hoverProvider: true` if it does.

**Comment by hifall** [comment]
Thanks @akosyakov.

It seems they added textDocument/hover recently: [[clangd] Code hover for Clangd](https://reviews.llvm.org/D35894). Maybe it's available in the next version of clangd.
