### ISSUE TITLE
Organize imports support

### ISSUE THREAD

**Issue by akosyakov** [TypeFox/monaco-languageclient#104]
Depends on:
- https://github.com/Microsoft/vscode-languageserver-node/issues/388
- https://github.com/Microsoft/monaco-editor/issues/995

**Comment by CGNonofr** [comment]
I don't really know about the status of this issue, nor what it was exactly about, but I noticed that with the v2, this appeared:
![Capture d’écran du 2022-06-22 14-28-58](https://user-images.githubusercontent.com/23257479/175029275-2c0fcb1d-5a14-4061-b966-2c8fd59f878d.png)

**Comment by kaisalmen** [comment]
@CGNonofr me neither. Shouldn't we close all issues that seem outdated / stale and where we think no progress will happen?

**Comment by CGNonofr** [comment]
I agree.

If an issue is important enough, it'll reappear

**Comment by kaisalmen** [comment]
Closure agreed above.
