### ISSUE TITLE
Upgrade to Monaco 0.14.x

### ISSUE THREAD

**Issue by akosyakov** [TypeFox/monaco-languageclient#105]
Apparently, it was released 2 days ago: https://www.npmjs.com/package/monaco-editor/v/0.14.2

**Comment by akosyakov** [comment]
sure, no hurry :)

**Comment by Twinside** [comment]
Ah missed this ticket, there is a pull request for the version 0.14.2

**Comment by akosyakov** [comment]
fixed with https://github.com/TypeFox/monaco-languageclient/pull/107
