### ISSUE TITLE
handle `Connection got disposed` errors

### ISSUE THREAD

**Issue by akosyakov** [TypeFox/monaco-languageclient#109]
If a connection got lost, for example on ws reconnectoin, `vscode-jsonrpc` rejects all pending requests with `Connection got disposed` errors, since we don't handle them, it pollutes the console immensely.

We should catch such errors where it is possible and handle them, for example by returning empty results.

**Comment by akosyakov** [comment]
cannot reproduce it with an example, seems to happen only with Theia

**Comment by hifall** [comment]
I am seeing this issue consistently. Often times it generates hundreds of `Connection got disposed` errors in the console, which I am trying to fix.

Did you make any progress on this one?
