### ISSUE TITLE
How do I suppress certain LSP features?

### ISSUE THREAD

**Issue by hifall** [TypeFox/monaco-languageclient#110]
I have a full-featured language server, with completion, hover, diagnostics, etc., enabled. For some reason, I'd like to disable the diagnostics feature when connecting to a language server, using Monaco language client.

How can I do this?

**Comment by akosyakov** [comment]
The language client allows registering your custom services by analogy with https://github.com/TypeFox/monaco-languageclient/blob/master/src/monaco-services.ts. 
Particularly to disable diagnostics, you can subclass `MonacoLanguages` and remove `createDiagnosticCollection` method, i.e. by assigning it to `undefined` in the constructor.

**Comment by hifall** [comment]
Thanks, @akosyakov! Will try that later.
