### ISSUE TITLE
Crash on signature.

### ISSUE THREAD

**Issue by hifall** [TypeFox/monaco-languageclient#115]
Monaco-editor version: 0.14.3
Monaco-language client: 0.8.0
Browser: Chrome 67.0.3396.99
OS: macOS 10.12

It crashes when trying to invoke a function signature in certain scenarios. See [Monaco Editor issue 1045](https://github.com/Microsoft/monaco-editor/issues/1045) for details.

**Comment by rcjsuen** [comment]
1. Can you see and confirm in the debugger that the code added in #112 is being run? Is it correctly adding a zero-length array to the JavaScript object?
1. Do you have a reproducible test case that we can `git clone` to check the problem?

**Comment by hifall** [comment]
Were you able to reproduce the original issue WITHOUT your fix?

**Comment by rcjsuen** [comment]
@hifall Please see attached.

![image](https://user-images.githubusercontent.com/15629116/45215536-bd2eb600-b26b-11e8-9c82-0ba08503f470.png)

**Comment by hifall** [comment]
Now I have confirmed that your fix works. It doesn't crash any more in that situation.

It's cool!
