### ISSUE TITLE
Allow to use alternative monaco-editor-core packages

### ISSUE THREAD

**Issue by akosyakov** [TypeFox/monaco-languageclient#117]
The last release of Monaco broke Theia, since they removed unused code which is used by Theia. For Theia we are going to publish an alternative package to monaco-editor-core with needed code. Here, we are going to remove runtime dependency and the client will be responsible to provide Monaco.

**Comment by nikeee** [comment]
If I understand this right, shouldn't this be a  [`peerDependency`](https://nodejs.org/en/blog/npm/peer-dependencies/)?

**Comment by akosyakov** [comment]
@nikeee hi, I've tried it, but they have 2 drawbacks:
- they don't get installed, so you cannot use their APIs - we obviously need it to use APIs in `monaco-languageclient`
- they are required to be installed by a client -  we don't want it, we want to install our packages providing APIs similar to `monaco-editor-core`, e.g. `@typefox/moanco-editor-core`

**Comment by nikeee** [comment]
Two drawbacks when using a devDependency:
- You are forced to use the specified version. This may conflict with other libraries used like `react-monaco-editor`.
- It only gets installed if you develop this package. When using this library no devDependency is installed.
See: https://stackoverflow.com/a/22004559

When using a peerDependency, you also get a warning when the required package is not installed.
