### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by lugreen** [TypeFox/monaco-languageclient#118]
Hi,
When i  run "browser" sample, i encounter this problem :
-----------------------------------------------------------------------------------------------------------------
Microsoft Windows [Version 10.0.17134.228]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd G:\JDYUN\monaco-languageclient\example

C:\WINDOWS\system32>g:

G:\JDYUN\monaco-languageclient\example>npm install
npm ERR! path G:\JDYUN\monaco-languageclient\example\node_modules\.staging\monaco-languageclient-58482376\node_modules\@types\node
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'G:\JDYUN\monaco-languageclient\example\node_modules\.staging\monaco-languageclient-58482376\node_modules\@types\node' -> 'G:\JDYUN\monaco-languageclient\example\node_modules\.staging\@types\node-54c47832'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\9dsoft\AppData\Roaming\npm-cache\_logs\2018-09-06T09_01_05_703Z-debug.log

G:\JDYUN\monaco-languageclient\example>
-----------------------------------------------------------------------------------------------------------------

**Comment by akosyakov** [comment]
Did you run `npm install` in the root first?

**Comment by lugreen** [comment]
Hi,
No,I run 'npm install' in 'example'  directory first.
I also  run in 'monaco-languageclient ' directory  then run in 'example' directory, the same problem.

**Comment by akosyakov** [comment]
`example` is using local `monaco-languageclient`, so you have to build it first by running `npm install` in the root

**Comment by lugreen** [comment]
Hi,
'G:\JDYUN\monaco-languageclient '  is monaco-languageclient 's  root directory.
Did you means  that :
First i run 'npm install ' in G:\JDYUN\monaco-languageclient,
then run  'npm install ' in  G:\JDYUN\monaco-languageclien\example.
Is right?

**Comment by rcjsuen** [comment]
@lugreen Yes, please do that.

**Comment by lugreen** [comment]
@rcjsuen  @akosyakov 
Hi,
I have tried that.,but the same problem.
Reference https://github.com/mapbox/node-sqlite3/issues/900#issuecomment-359225381, i delete the package-lock.json,now i can install successful.
Anyway, I want to thank you.

**Comment by paulyoung** [comment]
I'm seeing the same thing on OS X. If I remove the `package-lock.json` first then it works.

**Comment by cdietrich** [comment]
if we have all to delete the package-lock.json why is there checked in in the current state at all
