### ISSUE TITLE
'cp' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by lugreen** [TypeFox/monaco-languageclient#120]
Hi,
I think that the scripts in package.json isn't  suitable for windows.

![image](https://user-images.githubusercontent.com/1725996/45275215-f9714900-b4ed-11e8-9b1b-baa2a3f09d8e.png)

**Comment by rcjsuen** [comment]
Hi, @lugreen. Thank you for raising this issue.

It seems to be the same problem as #113 so I am closing this as a duplicate.
