### ISSUE TITLE
Triggering DidSaveTextDocument.

### ISSUE THREAD

**Issue by hifall** [TypeFox/monaco-languageclient#121]
I have a scenario where the language server's [(R#27)](https://github.com/REditorSupport/languageserver/issues/27) completion on custom-defined function doesn't work until the file is saved. It sounds like I need to send some request like DidSaveTextDocument from the language client to satisfy this requirement.

How can I send a DidSaveTextDocument request from monaco language client?

Thanks!

**Comment by akosyakov** [comment]
@hifall Hi, [default Monaco workspace](https://github.com/TypeFox/monaco-languageclient/blob/master/src/monaco-workspace.ts) does not support saving. You need to extend it and implement `onDidSaveTextDocument` to fire save events: https://github.com/TypeFox/monaco-languageclient/blob/facffc14c01b401ece95f9c2937563892c44d6d2/src/services.ts#L230
