### ISSUE TITLE
Only subscribe to events for documents within the root URI

### ISSUE THREAD

**Issue by gatesn** [TypeFox/monaco-languageclient#122]
Currently the MonacoWorkspace subscribes to events for all Monaco models. I believe it should subscribe to events only for models that sit under the root URI.

e.g. 
```
rootUri = scheme://path/to/root
modelUri = scheme://path/to/root/document.txt
notUsedModelUri = scheme://different/path
```

https://github.com/TypeFox/monaco-languageclient/blob/facffc14c01b401ece95f9c2937563892c44d6d2/src/monaco-workspace.ts#L41

**Comment by akosyakov** [comment]
Does LSP prohibit to open a file outside of a workspace?

I don't know that is your use case but in Theia (and VS Code) it is fine to open any file from the fs while working in some workspace and it should have a language support.

**Comment by gatesn** [comment]
That’s reasonable. My use case is that we use Monaco for more than just the code editor on a single page. For instance, a REPL.

Perhaps a more reasonable thing is to ensure the same URI scheme?

**Comment by akosyakov** [comment]
@gatesn You can subclass `MonacoWorkspace` and customize to your use cases. I don't think LSP enforce any constraints on URIs. In Theia, we have our own implementation as well to separate editors' models from inline editors' models, as a REPL.

**Comment by gatesn** [comment]
Yup, that’s what we do now. Was wondering if it was worth upstreaming the change. But seems reasonable not to given the variety of use cases.
