### ISSUE TITLE
Suggest: Too many logs

### ISSUE THREAD

**Issue by Aaaaash** [TypeFox/monaco-languageclient#123]
![图片](https://dn-coding-net-production-pp.codehub.cn/c9b293a6-a8e5-40f3-b55d-a0e41cda837c.png)

How to disable these outputs?

Or we can add an option to support closing the log output.

**Comment by rcjsuen** [comment]
Perhaps you can try looking at [`console-window.ts`](https://github.com/TypeFox/monaco-languageclient/blob/facffc14c01b401ece95f9c2937563892c44d6d2/src/console-window.ts).

**Comment by Aaaaash** [comment]
Thank for you reply, I have created a pull request: [add logEnabled option for ConsoleWindow.](https://github.com/TypeFox/monaco-languageclient/pull/124)

**Comment by Aaaaash** [comment]
> It looks that a language server is running in the verbose mode. Usually, a language server allows to configure it.

Thank you very much!

**Comment by GNSubrahmanyam** [comment]
@akosyakov @rcjsuen How to disable server logs 
![image](https://user-images.githubusercontent.com/18217008/99658737-ea02c880-2a85-11eb-9de7-833900f7e237.png)

**Comment by rcjsuen** [comment]
@GNSubrahmanyam You could try commenting stuff out in [`console-window.ts`](https://github.com/TypeFox/monaco-languageclient/blob/fb587b3ff258d48194c8667a6ade2d0fd87d06bd/client/src/console-window.ts) as I [previously suggested](https://github.com/TypeFox/monaco-languageclient/issues/123#issuecomment-434650955) or try out #124 from @Aaaaash.
