### ISSUE TITLE
Disproportionately large font in hover popover.

### ISSUE THREAD

**Issue by hifall** [TypeFox/monaco-languageclient#126]
I am using Monaco Language Client to connect to [Swift LS](https://github.com/apple/sourcekit-lsp). When testing the hover feature, I am seeing a larger-than-normal header in the hover popover window. I wonder if this is a Monaco Language Client issue or a Swift LS issue?

I am unable to to get the screenshot, as when I try to capture it using Shift+Cmd+4, the popover fades away.

Thanks!

**Comment by rcjsuen** [comment]
@hifall Have you tested how things look in the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html)? Nothing is done here that changes how Monaco draws hovers...

**Comment by hifall** [comment]
Things are fine in the playground -- actually this happens with the Swift LS only, others LS'es are fine.

**Comment by rcjsuen** [comment]
@hifall You should see what's going on in the `textDocument/hover` requests then. If you can't get a screenshot, maybe you can try taking some pictures with your smartphone?

You should also try some other browsers to see if the same behaviour is exhibited elsewhere.

**Comment by hifall** [comment]
Here is the screenshot :)

<img width="575" alt="screen shot 2018-11-23 at 10 43 48 pm" src="https://user-images.githubusercontent.com/5734293/48949230-4653b000-ef72-11e8-81dc-a4d63db9e919.png">
