### ISSUE TITLE
Upgrade to latest Monaco

### ISSUE THREAD

**Issue by benbenqiang** [TypeFox/monaco-languageclient#131]
I successfully ran the demo（0.9.0）, but when I migrated to my project, I used monaco-editor （0.15.1）instread of monaco-editor-core and got the following error:

Uncaught TypeError: Cannot read property 'TriggerCharacter' of undefined
    at MonacoToProtocolConverter.webpackJsonp../node_modules/monaco-languageclient/lib/monaco-converter.js.MonacoToProtocolConverter.asTriggerKind (monaco-converter.js:88)
    at MonacoToProtocolConverter.webpackJsonp../node_modules/monaco-languageclient/lib/monaco-converter.js.MonacoToProtocolConverter.asCompletionContext (monaco-converter.js:82)
    at MonacoToProtocolConverter.webpackJsonp../node_modules/monaco-languageclient/lib/monaco-converter.js.MonacoToProtocolConverter.asCompletionParams (monaco-converter.js:77)
    at Object.provideCompletionItems (monaco-languages.js:86)
    at suggest.js:48
    at Array.map (<anonymous>)
    at suggest.js:44
    at loop (async.js:169)
    at first (async.js:177)
    at provideSuggestionItems (suggest.js:76)
    at SuggestModel.webpackJsonp../node_modules/monaco-editor/esm/vs/editor/contrib/suggest/suggestModel.js.SuggestModel.trigger (suggestModel.js:305)
    at suggestModel.js:253
    at async.js:204

What should I do to be compatible with monaco-editor？

**Comment by akosyakov** [comment]
The latest compatible version is 0.14.x. Please check the change log.

**Comment by akosyakov** [comment]
PRs are welcomed to upgrade to Monaco 0.15.x.

**Comment by nikeee** [comment]
I'd like to take a look at this.

**Comment by nikeee** [comment]
I started working on this issue here: https://github.com/TypeFox/monaco-languageclient/compare/master...nikeee:monaco-upgrade

However, I think there are some breaking changes. For example, the `textEdit` property of `CompletionItem` was dropped. Instead, `insertText` and `insertTextRules` should be used. Also, `SnippetString` was removed.

**Comment by benbenqiang** [comment]
@akosyakov  Thanks

**Comment by nikeee** [comment]
I think this is more work than I initially thought. It seems that they introduced `strictNullChecks` on `monaco.d.ts`. If someone wants to pick this up, feel free to take my branch. I'm currently lacking the time for this.

**Comment by nikeee** [comment]
Meanwhile, Version 0.17.0 is out for some time now. Any chance that we will get an update? Or is this project dead? If so, is there any replacement?

**Comment by asual** [comment]
I managed to update monaco and various other vscode related dependencies to their latest versions:
https://github.com/asual/monaco-languageclient/commit/638e3a0a62f23298d851add4972b59420c6ad7f8

I'll be glad to create a PR but this one needs to be properly addressed first:
https://github.com/TypeFox/vscode-ws-jsonrpc/pull/9

/cc @akosyakov  @svenefftinge

**Comment by akosyakov** [comment]
We have plans to upgrade it latest by end of July.

**Comment by akosyakov** [comment]
@asual Would you be interested in https://github.com/TypeFox/monaco-languageclient/issues/164?

**Comment by asual** [comment]
@akosyakov Thanks for asking! I'm quite interested in having this properly maintained since I'm currently using it at my job. Unfortunately I cannot guarantee that this will be the case in the long term and would prefer to contribute on a case by case basis.

**Comment by akosyakov** [comment]
@asual i understand, my idea was to have big enough pool of maintainers which can do such case per case fixes and release new minor versions. So one time you do, another time somebody else. Otherwise it can be another year when i come back to the project 😬

**Comment by akosyakov** [comment]
0.10.0 was released with support of Monaco 0.17.0 and LSP 5.3.0
