### ISSUE TITLE
Not getting suggestions for functions of a new header file while using LSP of cpp.

### ISSUE THREAD

**Issue by amarnath-mishra** [TypeFox/monaco-languageclient#133]
I have used language server of https://github.com/MaskRay/ccls with monaco-languageclient, and it is working perfectly fine except it is _**not showing results for new header files (for e.g. it should show strcpy(...), if we include #include <string.h>) included at runtime**_ (Although it shows if that header file was already included in rootUri before starting the monaco-languageclient).I have checked [ccls LSP](https://github.com/MaskRay/ccls) is working perfectly fine with other ide's for e.g. VS code only. And I have run monaco-languageclient with other LSP's like java, python etc, they are also working well.

Following are some highlighted changes I have made as per the documentation of monaco-languageclient.

I am starting my LSP with this command in json-server-launcher.ts file in the example folder-
**ccls --init='{"cacheDirectory": "", "cacheFormat":"json", "index": {"onChange": true, "trackDependency":2}}'** 
 and I have .ccls file in the **rooturi** whose content is: 

> %clang
> %c -std=gnu11
> %cpp -std=gnu++14
> %objective-c %objective-cpp -DGNUSTEP
> %c %cpp -DFOO
> -pthread
> 
> -I/usr/include/
> -I/usr/local/include/
> -I.
> -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include
> -I/Library/Developer/CommandLineTools/usr/include

And obviously I have provided a sample file also in the rootUri.

**Comment by xihaoxiaohao** [comment]
Hi @amarnath-mishra I face the same issue using ccls, did you solve it?  and do you mind sharing how you get the java language server working? I have my configuration in #139 
Thanks.

**Comment by haridnr** [comment]
Hi @amarnath-mishra / @xihaoxiaohao ,

Please can you share your setup to connect to an external language server like ccls or cquery for Java or c++. I am trying to get this to work with ccls but I am unable to start the language server correctly.

I keep getting an error related to "missing rootUri".

Thanks,
Hari

**Comment by amarnath-mishra** [comment]
Hi @xihaoxiaohao ,I have tried on a new build of ccls, and this issue was resolve in it.

**Comment by anonymous9915** [comment]
> I have used language server of https://github.com/MaskRay/ccls with monaco-languageclient, and it is working perfectly fine except it is _**not showing results for new header files (for e.g. it should show strcpy(...), if we include #include <string.h>) included at runtime**_ (Although it shows if that header file was already included in rootUri before starting the monaco-languageclient).I have checked [ccls LSP](https://github.com/MaskRay/ccls) is working perfectly fine with other ide's for e.g. VS code only. And I have run monaco-languageclient with other LSP's like java, python etc, they are also working well.
> 
> Following are some highlighted changes I have made as per the documentation of monaco-languageclient.
> 
> I am starting my LSP with this command in json-server-launcher.ts file in the example folder- **ccls --init='{"cacheDirectory": "", "cacheFormat":"json", "index": {"onChange": true, "trackDependency":2}}'** and I have .ccls file in the **rooturi** whose content is:
> 
> > %clang
> > %c -std=gnu11
> > %cpp -std=gnu++14
> > %objective-c %objective-cpp -DGNUSTEP
> > %c %cpp -DFOO
> > -pthread
> > -I/usr/include/
> > -I/usr/local/include/
> > -I.
> > -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include
> > -I/Library/Developer/CommandLineTools/usr/include
> 
> And obviously I have provided a sample file also in the rootUri.

Hi 
I am working on external language servers with jdlts. But it is taken lot of ram. Can you help to figure this and suggest the best way to integrate it in the backend.
