### ISSUE TITLE
Connected to jdtls but no auto competition 

### ISSUE THREAD

**Issue by xihaoxiaohao** [TypeFox/monaco-languageclient#139]
I was able to connect to the java language server which I use is the eclipse's jdtls. On the `json-server-launcher.ts` file, I changed the `serverConnection` like below:
```
const serverConnection = server.createServerProcess('JSON', 'jdtls');
```

My `jdtls` script:

```
#!/bin/sh
# update is a path according to my local environment

java -Declipse.application=org.eclipse.jdt.ls.core.id1 \
     -Dosgi.bundles.defaultStartLevel=4 \
     -Declipse.product=org.eclipse.jdt.ls.core.product \
     -Dlog.protocol=true \
     -Dlog.level=ALL \
     -noverify \
     -Xmx1G \
     -jar <UPDATE>/plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar \
     -configuration <UPDATE>/config_linux \
     --add-modules=ALL-SYSTEM \
     --add-opens java.base/java.util=ALL-UNNAMED \
     --add-opens java.base/java.lang=ALL-UNNAMED
```

On the `client.ts`:

I set the file uri and root uri like below:

```
model: monaco.editor.createModel(value, 'json', monaco.Uri.parse('file:///Users/user/Documents/Main.java')),
```

```
MonacoServices.install(editor, {rootUri: '/Users/user/Desktop'});
```

I can see the language server is initialized and ready, but why I don't get any auto completion?

![Screen Shot 2019-04-08 at 10 20 27 AM](https://user-images.githubusercontent.com/9826637/55744274-68157700-59e9-11e9-8141-64174dba7989.png)

**Comment by Naaman-Saif** [comment]
Did you find a solution to this?

**Comment by yyy2015** [comment]
> I was able to connect to the java language server which I use is the eclipse's jdtls. On the `json-server-launcher.ts` file, I changed the `serverConnection` like below:
> 
> ```
> const serverConnection = server.createServerProcess('JSON', 'jdtls');
> ```
> 
> My `jdtls` script:
> 
> ```
> #!/bin/sh
> # update is a path according to my local environment
> 
> java -Declipse.application=org.eclipse.jdt.ls.core.id1 \
>      -Dosgi.bundles.defaultStartLevel=4 \
>      -Declipse.product=org.eclipse.jdt.ls.core.product \
>      -Dlog.protocol=true \
>      -Dlog.level=ALL \
>      -noverify \
>      -Xmx1G \
>      -jar <UPDATE>/plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar \
>      -configuration <UPDATE>/config_linux \
>      --add-modules=ALL-SYSTEM \
>      --add-opens java.base/java.util=ALL-UNNAMED \
>      --add-opens java.base/java.lang=ALL-UNNAMED
> ```
> 
> On the `client.ts`:
> 
> I set the file uri and root uri like below:
> 
> ```
> model: monaco.editor.createModel(value, 'json', monaco.Uri.parse('file:///Users/user/Documents/Main.java')),
> ```
> 
> ```
> MonacoServices.install(editor, {rootUri: '/Users/user/Desktop'});
> ```
> 
> I can see the language server is initialized and ready, but why I don't get any auto completion?
> 
> ![Screen Shot 2019-04-08 at 10 20 27 AM](https://user-images.githubusercontent.com/9826637/55744274-68157700-59e9-11e9-8141-64174dba7989.png)

hi, I want to know if you have solved this problem. I have connected the eclipse jdt and successfully send the initialize request. When the lsp server send a 'client/registerCapability' request to the client, the client responses a -32604, Unhandled method client/registerCapability. Really appreciate for your reply.

the server sent to the client:

```json
{"jsonrpc":"2.0","id":"1","method":"client/registerCapability","params":{"registrations":[{"id":"e5afb329-a31c-43e0-abd4-57f35629bc51","method":"textDocument/completion","registerOptions":{"resolveProvider":true,"triggerCharacters":[".","@","#","*"]}}]}}
```

the client responsed:

```json
{"jsonrpc":"2.0","id":"1","error":{"code":-32601,"message":"Unhandled method client/registerCapability"}}
```
