### ISSUE TITLE
Catch up with LSP changes

### ISSUE THREAD

**Issue by gatesn** [TypeFox/monaco-languageclient#141]
https://microsoft.github.io/language-server-protocol/specification#version_3_14_0

**Comment by akosyakov** [comment]
We have plans to upgrade it latest by end of July.

**Comment by senn412** [comment]
Is this upgrade still coming?

**Comment by akosyakov** [comment]
0.10.0 was released with support of Monaco 0.17.0 and LSP 5.3.0
