### ISSUE TITLE
Example pulls two versions of vscode-jsonrpc

### ISSUE THREAD

**Issue by spoenemann** [TypeFox/monaco-languageclient#142]
The example seems to use a wrong version of `vscode-languageserver`, which leads to two versions of `vscode-jsonrpc`:
```
gitpod /workspace/monaco-languageclient/example $ npx npm-why vscode-jsonrpc
npx: installed 4 in 1.856s

  Who required vscode-jsonrpc:

  @monaco-languageclient/example > monaco-languageclient > vscode-base-languageclient > vscode-languageserver-protocol > vscode-jsonrpc@3.6.2
  @monaco-languageclient/example > monaco-languageclient > vscode-jsonrpc@3.6.2
  @monaco-languageclient/example > vscode-languageserver > vscode-languageserver-protocol > vscode-jsonrpc@4.0.0
  @monaco-languageclient/example > vscode-ws-jsonrpc > vscode-jsonrpc@3.6.2
```

A consequence of this is that cancellation responses are not detected, but logged as errors:

```
Error: The request (id: 18, method: 'textDocument/hover') has been cancelled
```

This problem is also present in Theia. All users of this package should check their dependencies.

**Comment by spoenemann** [comment]
`vscode-base-languageclient` version `4.4.0` depends on `vscode-languageserver-protocol` version `^3.10.0`. This includes version `3.13.0`, which depends on `vscode-jsonrpc` with version `^4.0.0`.

There has been a major version update in `vscode-languageserver-protocol` 👎

**Comment by akosyakov** [comment]
So the only way is to pin `vscode-languageserver-protocol` for `vscode-base-languageclient`?

**Comment by spoenemann** [comment]
Can we update `vscode-jsonrpc` to 4.0.0?

**Comment by spoenemann** [comment]
Clients using Yarn can solve this by adding

```.json
  "resolutions": {
    "**/vscode-languageserver-protocol": "3.12.0"
  }
```

but a better solution would be to update this package to the latest version of vscode.
