### ISSUE TITLE
Is there any way to send the complete editor text on didChange?

### ISSUE THREAD

**Issue by Aayush04** [TypeFox/monaco-languageclient#145]
Is there any way to send the complete editor text on didChange? As I integrated with [omnisharp-roslyn](https://github.com/OmniSharp/omnisharp-roslyn) for the csharp language. But it seems like the server is not properly handling the changes on didChange message. It is not giving proper completion results but when I am sending the completer editor text it is working fine.

**Comment by rcjsuen** [comment]
@Aayush04 I think you'll have to look into modifying the `onDidChangeContent(*)` function to force it to send everything.

https://github.com/TypeFox/monaco-languageclient/blob/4716d0fb6e6c3a99513a1357005ee5c758ff7dcc/src/monaco-workspace.ts#L50-L63

**Comment by Progyan1997** [comment]
@Aayush04 Hey, I am trying to setup similar architecture. How far are you with integrating monaco with Omnisharp?
