### ISSUE TITLE
Cannot read property 'language' of null

### ISSUE THREAD

**Issue by Aayush04** [TypeFox/monaco-languageclient#146]
Getting console error when the language server returns null content on hover.

```
errors.js:58 Uncaught Error: Cannot read property 'language' of null

TypeError: Cannot read property 'language' of null
    at ProtocolToMonacoConverter.asMarkdownString (monaco-converter.ts:687)
    at monaco-converter.ts:663
    at Array.map (<anonymous>)
    at ProtocolToMonacoConverter.asHoverContent (monaco-converter.ts:663)
    at ProtocolToMonacoConverter.asHover (monaco-converter.ts:656)
    at monaco-languages.ts:120
    at async Promise.all (:3000/index 0)
    at errors.js:58
```

Request:
```{"jsonrpc":"2.0","id":1,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///root/lspData/workspace/csharp/e79f527e-7402-4bc3-a2c2-b0a552f5d45e/UserMainCode.cs"},"position":{"line":14,"character":18}}}```

Response: 
```{"protocolVersion":"2.0","id":1,"result":{"contents":[null,null]}}```

**Comment by rcjsuen** [comment]
What language server are you using, @Aayush04? The response looks invalid.

**Comment by Aayush04** [comment]
I am using csharp language server from [omnisharp-roslyn](https://github.com/OmniSharp/omnisharp-roslyn)

**Comment by rcjsuen** [comment]
@Aayush04 Can you reproduce this consistently? Can you reproduce this with a simple C# file and share it here?

**Comment by israelvaldez** [comment]
I also get the issue; I only get the problem when hovering over strings, ints, longs, decimals.
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("hovering over here fails");
        }
    }
}`

**Comment by rcjsuen** [comment]
@israelvaldez I imagine this is an issue with the language server. Unfortunately, I can't really reproduce the problem as I can't even build the language server due to OmniSharp/omnisharp-roslyn#1500. :(

**Comment by rcjsuen** [comment]
@Aayush04 @israelvaldez I was able to reproduce the problem. I also noticed that others have encountered this problem in the past. See OmniSharp/omnisharp-roslyn#1087.

**Comment by GNSubrahmanyam** [comment]
![image](https://user-images.githubusercontent.com/18217008/78367288-720f8d00-75df-11ea-8963-43080a1678ec.png)
@rcjsuen I am also getting this error.

Also Autocomplete is not working. Omisharp roslyn version 1.34.15

**Comment by rcjsuen** [comment]
@GNSubrahmanyam Then I suggest you comment in OmniSharp/omnisharp-roslyn#1087 and OmniSharp/omnisharp-roslyn#1671 unless you think the `monaco-languageclient` library is doing something wrong.

**Comment by GNSubrahmanyam** [comment]
Nothing is wrong with monaco-languageclient. python lsp is up and running. Issue with  mniSharp/omnisharp-roslyn

**Comment by rcjsuen** [comment]
> Nothing is wrong with monaco-languageclient. python lsp is up and running. Issue with mniSharp/omnisharp-roslyn

@GNSubrahmanyam Thank you for confirming. Then you need to take it up with the developers working on `omnisharp-roslyn`.

**Comment by GNSubrahmanyam** [comment]
@rcjsuen Thank you so much.
