### ISSUE TITLE
Can we use monaco-languageclient in Electron without using websockets, probably using ipc

### ISSUE THREAD

**Issue by satishbabariya** [TypeFox/monaco-languageclient#148]

**Comment by gins3000** [comment]
@satishbabariya A long time ago, I have made an example how to do this here https://github.com/gins3000/monaco-electron-ipc-example

It is definitely outdated, but maybe it helps. If there are difficulties getting my example to work with the newest versions of the language-client and monaco, I would appreciate an Issue so I can address it (or even better, a pull request ;) )

**Comment by satishbabariya** [comment]
@gins3000 thanks, I'll look into it.
