### ISSUE TITLE
How to change uri in jsonrpc protocol

### ISSUE THREAD

**Issue by Phantomape** [TypeFox/monaco-languageclient#15]
I am trying to using monaco-languageclient to connect to my external language server. However, it seems that the server could not recognize the uri sent by the client side:
`2017-08-02 01:55:18,887 UTC - ERROR - pyls.language_server - CAUGHT
Traceback (most recent call last):
  File "/home/phantomape/Tools/anaconda2/lib/python2.7/site-packages/pyls/language_server.py", line 67, in wrapped
    return func(*args, **kwargs)
  File "/home/phantomape/Tools/anaconda2/lib/python2.7/site-packages/pyls/python_ls.py", line 108, in m_text_document__did_open
    self.workspace.put_document(textDocument['uri'], textDocument['text'], version=textDocument.get('version'))
  File "/home/phantomape/Tools/anaconda2/lib/python2.7/site-packages/pyls/workspace.py", line 41, in put_document
    doc_uri, content, sys_path=self.syspath_for_path(path), version=version
  File "/home/phantomape/Tools/anaconda2/lib/python2.7/site-packages/pyls/workspace.py", line 69, in syspath_for_path
    files = config.find_parents(self.root, path, ['setup.py']) or []
  File "/home/phantomape/Tools/anaconda2/lib/python2.7/site-packages/pyls/config.py", line 74, in find_parents
    raise ValueError("Path %s not in %s" % (path, root))
ValueError: Path /1 not in `
Any idea how to fix it ?

**Comment by akosyakov** [comment]
The URI is hard coded in the client code: https://github.com/TypeFox/monaco-languageclient/blob/master/example/src/client.ts#L26.

Particularly about the error you should open an issue for the py language server.

**Comment by Phantomape** [comment]
Actually, if you remove the monaco.Uri.parse(...) part, the editor will automatically assign a uri like inmemory://model/1. Since this uri points to some resources in my computer, can I get the file path based on this uri?

**Comment by akosyakov** [comment]
You should provide a file URI pointing to the file on your computer to Monaco.

**Comment by Phantomape** [comment]
Solve the problem by providing a new file URI for the monaco-languageclient

**Comment by gatesn** [comment]
@Phantomape I've filed a bug for the Python error you're seeing: https://github.com/palantir/python-language-server/issues/89

@akosyakov I'm having trouble figuring out how to set the rootUri in the MonacoWorkspace? From some of the other tickets it appears you suggest subclassing and overriding functionality, would this also be the solution here?

**Comment by akosyakov** [comment]
@gatesn right now yes, could you open an issue to allow providing a URI to `MonacoWorkspace`

**Comment by rcjsuen** [comment]
@gatesn Did you ever get around to opening a ticket about the missing `rootUri` property?

I found sourcegraph/javascript-typescript-langserver#372 and it seems to stem from the same problem of that property not being included in the `initialize` request.

**Comment by rcjsuen** [comment]
Never mind, looks like this was fixed by #31! :)

**Comment by akosyakov** [comment]
@rcjsuen just released a patch version with these changes

**Comment by FoxDaxian** [comment]
sorry to disturb~
I has some problem, when start client and server, the rpc event get wrong textDocument.uri of request params like this:

![image](https://user-images.githubusercontent.com/19708789/163781747-774db556-648d-4931-8b99-2e19e6d6ba1f.png)

my client  part code: 
```javascript
new MonacoLanguageClient({
                name: 'Monaco language client',
                clientOptions: {
                    documentSelector: [
                        {
                            language: 'vue',
                        },
                    ],
                    errorHandler: {
                        error: () => ErrorAction.Continue,
                        closed: () => CloseAction.Restart,
                    },
                },

                connectionProvider: {
                    get: (errorHandler, closeHandler) => {
                        return Promise.resolve(
                            createConnection(
                                connection,
                                errorHandler,
                                closeHandler
                            )
                        );
                    },
                },
            });
```
and lsp use vls and just forward it to socket.

**Comment by FoxDaxian** [comment]
I guess process of work is pass correct document content(or path), relative location and matched method. then lsp will get those info via socket. after receive, lsp will get source code of document and do parse for get ast info. in order can do corrsponed method. 
lsp will send result when above work done. and client like vscode or monaco-editor will show result.

But the rpc request params is incorrect for me. I don't know how to resolve this..

so need help please. I would appreciate any answer.

Thanks again~

**Comment by CGNonofr** [comment]
When you create a model, you can provide an URI. If undefined, it fallback on a `inmemory` url

**Comment by FoxDaxian** [comment]
@CGNonofr but I pass the value to monaco-editor.  not file. so maybe immemory is right?

**Comment by CGNonofr** [comment]
You need to create the model by hands then give it to the editor

**Comment by FoxDaxian** [comment]
> You need to create the model by hands then give it to the editor

yeap. I created an model like this: 
```javascript
          const code = ['const a = 123;', 'console.log(languageDefinitions);'];
          const editorOptions = {
                model: monaco.editor.createModel(
                    code.join('\n'),
                    'vue',
                    monaco.Uri.parse('/Users/xx/github/lsp-adventure/app/src/utils/language.js')
                )
            };
```

and get some result what not I expected:
![image](https://user-images.githubusercontent.com/19708789/163970455-2cf38011-26a2-4736-8826-60ac28f94094.png)

rpc body as below:

```javascript
{
  jsonrpc: '2.0',
  id: 7,
  method: 'textDocument/definition',
  params: {
    textDocument: {
      uri: 'file:///Users/fengshiyu/github/lsp-adventure/app/src/utils/language.js'
    },
    position: { line: 1, character: 14 }
  }
}
```

**Comment by CGNonofr** [comment]
So it seems that the URI is fine now, isn't it?

Why is that error not expected?

**Comment by FoxDaxian** [comment]
because it not correct refer corrsponding variable:
![image](https://user-images.githubusercontent.com/19708789/163972235-3fe91f1d-dbd9-49ad-92e0-c0831c3b47e2.png)

**Comment by CGNonofr** [comment]
This is an issue with your language server implementation then, it doesn't seem to be related to this library

**Comment by FoxDaxian** [comment]
> This is an issue with your language server implementation then, it doesn't seem to be related to this library

well. I already file related issue in vls repo.

Could you help me check the usage is correct in [this repo](https://github.com/FoxDaxian/lsp-adventure)? 😊 🙏🏻

**Comment by CGNonofr** [comment]
You should probably start by updating versions, `vscode-ws-jsonrpc` is not updated and should be replaced by `@codingame/monaco-jsonrpc`

Then, in your workspace folder, `/` is not a valid url (and you don't need to hack it in the server, you better set it in the client)
Btw, it's probably not a good idea to open `/` directly

**Comment by FoxDaxian** [comment]
thank~  awesome man~ thank what you gived suggestion~

> You should probably start by updating versions, `vscode-ws-jsonrpc` is not up to date and should be replaced by `@codingame/monaco-jsonrpc`

I will try update this.
 
> Then, in your workspace folder, `/` is not a valid url (and you don't need to hack it in the server, you better set it in the client) Btw, it's probably not a good idea to open `/` directly

I don't wanna set worlspace folder yet. but...
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/19708789/163976784-cbaad3e4-3153-4b78-a924-4f43b8782f8d.png">

maybe I can resolve this if I hava more time..  😢
