### ISSUE TITLE
Call 'workspace/executeCommand' programmatically

### ISSUE THREAD

**Issue by merzbird** [TypeFox/monaco-languageclient#161]
Could you please provide an example of code to execute some command on server from monaco-languageclient programmatically? 
Something like
```
MonacoServices.commands.executeCommand(commandId, args)
```

Unfortunately, I cannot grasp how to do it from reading the docs/source code.

**Comment by akosyakov** [comment]
It should be something like ´languageClient.sendRequest(...)`

**Comment by merzbird** [comment]
Thanks.
