### ISSUE TITLE
Connecting the Monaco Editor with an own Xtext language server

### ISSUE THREAD

**Issue by nmaoez** [TypeFox/monaco-languageclient#162]
I'm trying to connect the Monaco Editor with a language server where my own Xtext language is loaded. Before I start to build the dsl, I wanted to get a basic communication between the language server and the editor running. So therefore I'm testing with the `Hello World` [basic example model](https://www.eclipse.org/Xtext/documentation/102_domainmodelwalkthrough.html). I was able to get the web socket connection running thanks to following examples:
[cdietrich/xtext-languageserver-example](https://github.com/cdietrich/xtext-languageserver-example)
[TypeFox/monaco-languageclient](https://github.com/TypeFox/monaco-languageclient/tree/master/example)

Also I was able to reproduce the JSON example successfully on the fontend side, so frontend wise everything should be fine.

Nethertheless I am failing to connect the Monaco Editor to a language server with a self defined Xtext language. My current state is pushed at [nmaoez/composer-language-server](https://github.com/nmaoez/composer-language-server) where I describe how to get both sides (client/server) running for further investigation. In the Chrome network tab and in my Eclipse console I can see all messages, which are sent between server and client but the editor doesn't show anything regarding i.e. highlighting:
![lsp-monaco](https://user-images.githubusercontent.com/34936364/62780738-a9f91b80-bab6-11e9-9385-77f851fcc7e1.png)

It seems that the client and the server are connected through the web sockets, but the messages are not forwarded to the language server.

I've been analyzing a lot of different projects, like [theia-ide/sprotty](https://github.com/theia-ide/sprotty) or the [OpenKieler/elkgraph-web](https://github.com/OpenKieler/elkgraph-web) project, but unfortunatly I wasn't able to figure it out. Has anyone been able to connect the Monaco Editor with their own language server and/or provide me an example? Is there maybe another approach on the backend side to get the connection running?

I am happy about any help and thanks!

**Comment by cdietrich** [comment]
i am not sure what you are exactly testing but there is no server side highlighting in this scenario.
thus you would have to provoke a parse error or add a validation to test this.

**Comment by nmaoez** [comment]
My initial goal is to get a complete vertical connection between all components. My expectation was just that I would get to see anything in the frontend like the highlighting (or anything else, just like an indicator for a running connection).

I start the `main()`-method in the `com.novomind.language.server.expression.websockets`-subproject manually in Eclipse. For the most part, I focused on the project [cdietrich/xtext-languageserver-example](https://github.com/cdietrich/xtext-languageserver-example). There are 3 `RunWebSocketServer.xtend` classes in xtext-languageserver-example. Is my assumption correct that it is sufficient to start one of the classes manually in order to establish a complete connection (not only web socket connection) or are these classes not intended for this purpose?

**Comment by cdietrich** [comment]
no the 3 is correct.
the server runs but it seems it cannot handle your uris. 
they are bad / not expected

better
```
`inmemory:/demo/${guid()}.${LANGUAGE_ID}`
```

**Comment by cdietrich** [comment]
you may also have a look at 
https://github.com/eclipse/lsp4j/issues/203
https://github.com/eclipse/lsp4j/pull/314
https://github.com/OpenKieler/elkgraph-web/pull/13/files#diff-c6a79430e3155eaa1b62ade47757e09f

(requires lsp 0.8.0 snapshot)

**Comment by nmaoez** [comment]
I changed the URI and tried to connect the editor with the web socket server in xtext-languageserver-example (`RunWebSocketServer3.xtend`). Now I get following error:

```
gogogo
start
open
message: {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"rootPath":null,"rootUri":null,"capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"]}},"definition":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true},"implementation":{"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true}}},"trace":"off","workspaceFolders":null}}
{"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":["."]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":true,"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"renameProvider":true,"executeCommandProvider":{"commands":["mydsl.a","mydsl.b","mydsl.c"]},"semanticHighlighting":{"scopes":[]}}}}
message: {"jsonrpc":"2.0","method":"initialized","params":{}}
message: {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"inmemory:/demo/e3c2a3c8-3590-a4ff-cf30-b7f604e9a6f6.mydsl","languageId":"mydsl","version":1,"text":"Hello Xtext!"}}}
message: {"jsonrpc":"2.0","id":1,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"inmemory:/demo/e3c2a3c8-3590-a4ff-cf30-b7f604e9a6f6.mydsl"},"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"context":{"diagnostics":[]}}}
message: {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":1}}
message: {"jsonrpc":"2.0","id":2,"method":"shutdown","params":null}
{"jsonrpc":"2.0","id":1,"error":{"code":-32800,"message":"The request (id: 1, method: \u0027textDocument/codeAction\u0027) has been cancelled"}}
{"jsonrpc":"2.0","id":2,"result":{}}
message: {"jsonrpc":"2.0","method":"exit","params":null}
```

Okay I will have a look at your suggested links. Thank you very much for your help so far.

**Comment by cdietrich** [comment]
Please debug your server

**Comment by cdietrich** [comment]
BTW this seems as you explicitly call the stuff so you may restart everything / close the editors. This code is not working with more than one client

**Comment by cdietrich** [comment]
you use "monaco-editor": "^0.17.1",
but https://github.com/TypeFox/monaco-languageclient/pull/163 is not done yet.
=> you should use monaco 14 (or 15 - have not tested that)

**Comment by nmaoez** [comment]
Sorry for the late reply. I was on vacation last week.

After some local testing and debugging I managed to get the smallest example running. The current state is pushed into my personal project. The main issues were firstly the wrong URI and lastly I had a typo in the language id...

Nethertheless thank you very much for your help. Now I can continue on my main task.
