### ISSUE TITLE
looking for maintainers

### ISSUE THREAD

**Issue by akosyakov** [TypeFox/monaco-languageclient#164]
We don't have enough time to catch up with LSP and Monaco changes regularly, so we would be glad a help with it. If you are interested leave a comment here.

Each maintainer is added as `Admin` to this project. He is free to help as it suits him in following areas:
- upgrading to latest LSP and Monaco
- releasing new versions (you will be added as a collaborator on npmjs with publish access right)
- reviewing, testing and landing PRs
- helping community, i.e. handling issues

Generally, for TypeFox it is important:
- that minor releases don't break Theia, i.e. you should identify breaking changes and do a major release
- big new contributions are accepted only if a contributor is ready to maintain them, i.e. a contributor should be ready to become a maintainer to help with upgrading and testing examples with new versions of LSP and Monaco; otherwise it is an unnecessary maintenance burden

@rcjsuen  @brokun @johnwiseheart @jroitgrund @gins3000 @zewa666 @gatesn mentioned you because you did contributions before, if you are not interested, sorry for bothering, just ignore it

**Comment by johnwiseheart** [comment]
We'd be happy to maintain it - but probably don't have the resources to keep it up to date outside of what is required by us - eg updating LSP and Monaco when we need the new versions.

Theres not a whole lot of activity here, so handling issues is probably not a huge problem.

**Comment by mofux** [comment]
I'd be happy to maintain this repo too. @akosyakov @johnwiseheart How do you feel about setting up a slack workspace for the project maintainers, so we can synchronize more easily?

**Comment by akosyakov** [comment]
@mofux as you negotiate with others, as far as I understood all of us have other projects to work on, so probably there won't be much chatting going on :)

**Comment by zewa666** [comment]
I cant sadly focus on an additional OSS project due to time constraints, aka the nice way to say that my newborn son eats up all my sparetime ;)

So while I cant help out as maintainer, as part of my job my Team and I can make sure to try out PRs with our product and help out that way.

**Comment by akosyakov** [comment]
> So while I cant help out as maintainer, as part of my job my Team and I can make sure to try out PRs with our product and help out that way.

@zewa666 any help is welcome, trying out is the big part of maintenance work.

**Comment by gins3000** [comment]
@akosyakov Thank you for including me in this list, and it's good to hear that @johnwiseheart  and @mofux expressed interest in keeping this repo up, even if it is just the minimal maintenance.

Like @zewa666 , at the moment I can only offer to continue using this repo and provide "field feedback" and the occasional PR.

Good luck!

**Comment by akosyakov** [comment]
Theia dropped using of monaco-languageclient and switched completely to VS Code extensions. It means that Theia commiters won't be able to assist in the future. Existing committers with merge rights interested in new PRs please feel free to merge them. Each time new `next` version will be provided.

**Comment by CGNonofr** [comment]
I am willing to help keeping monaco-languageclient up-to-date!

**Comment by CGNonofr** [comment]
and https://github.com/TypeFox/vscode-ws-jsonrpc as well (I need to update it first)

**Comment by CGNonofr** [comment]
Is it possible to get access on vscode-ws-jsonrpc as well?

**Comment by RomanNikitenko** [comment]
@akosyakov 
could you take a look https://github.com/TypeFox/monaco-languageclient/issues/164#issuecomment-721607947

**Comment by akosyakov** [comment]
@CGNonofr Could you fork please `vscode-ws-jsonrpc`? `vscode-ws-jsonrpc` is still used in Theia and we don't have capacity to retest it now. Maybe it can be even merged in this repo instead, as another package, i.e. `monaco-jsonrpc`

**Comment by CGNonofr** [comment]
Fine, I'll take a look at vscode-jsonrpc, thanks for the tip!

**Comment by dkattan** [comment]
> @CGNonofr Could you fork please `vscode-ws-jsonrpc`? `vscode-ws-jsonrpc` is still used in Theia and we don't have capacity to retest it now. Maybe it can be even merged in this repo instead, as another package, i.e. `monaco-jsonrpc`
> 
> BTW latest vscode-jsonrpc seems to support web sockets too, so maybe we should use it directly now

For anyone who might be reading this (perhaps future me), vscode-jsonrpc does not appear to natively support websockets, although I'm sure it could be wired up with a little extra work. It provides the following implementations of AbstractMessageReader and AbstractMessageWriter:

- ReadableStreamMessageReader
- WriteableStreamMessageWriter
- BrowserMessageReader
- BrowserMessageWriter

The constructors for these objects don't natively accept a WebSocket type.

vscode-ws-jsonrpc on the other hand exports 
* WebSocketMessageReader
* WebSocketMessageWriter

Which both take a WebSocket type, making them very easy to instantiate from the calling code.

**Comment by spoenemann** [comment]
I wrote an update to the state of this repository in https://github.com/TypeFox/monaco-languageclient/issues/313#issuecomment-1041232925.

This project is certainly still open to welcoming new contributors and maintainers. We want to establish a transparent open source community around it. But since there is no longer a pressing urge to find new maintainers, I'll close this issue.

Thank you @akosyakov for the initial development of this package, and thank you @CGNonofr for [taking it over two years ago](#issuecomment-721607947).
