### ISSUE TITLE
Question: Angular with monaco editor and monaco-languageclient

### ISSUE THREAD

**Issue by ph-fuergy** [TypeFox/monaco-languageclient#171]
Hi,
I am created a github [project](https://github.com/ph-fuergy/angular-monaco-languageclient) as example for using angular with monaco editor and monaco-languageclient.

But I have some questions for best practice of using monaco and monaco-languageclient and a few problems. Can you @akosyakov review my solution and give me some hints.

Later I want to make my project as public with goal to show a solution for integrating monaco into angular application.

**Comment by alexander-makarevich** [comment]
Hello
There is an [example](https://github.com/Louis-7/angular-monaco-languageclient) how to integrate monaco editor with angular using LSP. The modules are used in the example are deprecated. Could you share your project to actualize information about the integration?

**Comment by ph-fuergy** [comment]
Yes I could, but first I want to make it good. Now it is a private project. I can add you as collaborator too.
I was inspired with project you mention. But I am not sure that it is good as example now. Can you help me with that?

**Comment by Louis-7** [comment]
@alexander-makarevich, I update my [example ](https://github.com/Louis-7/angular-monaco-languageclient)and now it's available
