### ISSUE TITLE
migrate to monaco 0.18.x

### ISSUE THREAD

**Issue by akosyakov** [TypeFox/monaco-languageclient#176]

**Comment by PHameete** [comment]
What needs to be done for this upgrade? 

I'm unclear how the LanguageClient exactly connects to the Monaco editor. Is this just a matter of updating `MonacoToProtocolConverter` and `ProtocolToMonacoConverter` to correspond with https://github.com/microsoft/monaco-editor/blob/master/monaco.d.ts ?

**Comment by akosyakov** [comment]
- Bump up the version
- fix all compilation errors
- try out examples and make sure that they work

then ping me to publish the dev version for a PR that it can be tested in downstreams

**Comment by PHameete** [comment]
I'll try to open a PR today.

**Comment by PHameete** [comment]
Its already done actually :-) please take a look when you can. I've tried the examples and they are working.

**Comment by rcjsuen** [comment]
Looks like Monaco 0.19.0 has been released. 🤔

**Comment by PHameete** [comment]
@rcjsuen lets get this merged first, then we can look at 0.19.0 :-)

Hopefully @akosyakov can find some time for reviewing/merging.

**Comment by zerocewl** [comment]
any news here @akosyakov ?
