### ISSUE TITLE
Allow defining a language client supplier that is called on activation event

### ISSUE THREAD

**Issue by gatesn** [TypeFox/monaco-languageclient#18]
Register a language client supplier that is run when the given activation event is triggered.

https://code.visualstudio.com/docs/extensionAPI/activation-events

**Comment by akosyakov** [comment]
Could you elaborate?

**Comment by akosyakov** [comment]
Could you elaborate on `when the given activation event is triggered`? Monaco is not VS code, but just its editor, there are no activation events. I would like to understand why you need it?

This repo only provides the language client for Monaco and don't care how it will be activated. I will argue that is out of the scope and the responsibility of the user code, e.g. in Theia the template method is used to return a promise resolved when the language client should be activated: https://github.com/theia-ide/theia/blob/master/packages/languages/src/browser/language-client-contribution.ts#L48.

**Comment by gatesn** [comment]
This question doesn't really make sense now I look back at it...
