### ISSUE TITLE
How to use peek definition and goto definition

### ISSUE THREAD

**Issue by kimolank** [TypeFox/monaco-languageclient#180]
I was able to connect monaco to a real language server using monaco-languageclient. Somethings work but things like peek definition and find references don't.

I understand that I have to add `overrides` when doing `monaco.editor.create` but they are undocumented and the examples on monaco-editor repo only work on older versions.

Any documentation for these overrides? I tried copying Theia here 
https://github.com/eclipse-theia/theia/blob/ee4cbce82e86c1dd969cf07d8cf4aee6d5e9b71f/packages/monaco/src/browser/monaco-editor-provider.ts#L118-L125

which made goto defintion work by ways of `codeEditorService.openCodeEditor` but peek definition does not trigger any methods to be called.

**Comment by NLueg** [comment]
Did you set the boolean `definitionProvider: true` in your ServerCapabilities?
I had the same issue some time ago, but I just forgot to tell the client that the server supports it.

**Comment by kimolank** [comment]
Yeah, I tried it with 5 language servers that used to work on Monaco 14 used to work, but not 17. The theia ide uses internals of this package and it's a bit more complicated.

Idk how to debug it.

I use it as an editor for my VPS happy to share code.

**Comment by kimolank** [comment]
What is the override service responsible for peek definition?
