### ISSUE TITLE
How to use your plugin with php language server?

### ISSUE THREAD

**Issue by ElDarco** [TypeFox/monaco-languageclient#181]
Hello. Firstly, thanks for your tremendous work.
Please could you help me. There was a task to get functionality for editing php files on the site. I connected monaco-editor via webpack, but I needed the ability to auto-complete the code. I found such a server (https://hub.docker.com/r/felixfbecker/php-language-server/) and your plugin, but I can’t figure it out for a long time, is there any way to do this without using nodejs?
Thanks for your help.

**Comment by rcjsuen** [comment]
@ElDarco It should be possible to talk to any language server assuming it follows the protocol. I suggest you check the example and try to change how the server is initialized.

https://github.com/TypeFox/monaco-languageclient/blob/602e7606c046036d3627b59064bbfb4b67e7d2e8/example/src/json-server-launcher.ts#L14-L19

**Comment by ElDarco** [comment]
@rcjsuen Fine. Thanks for the answer. But I followed the example in the "examples / browser" folder, but as far as I understand, in order for it to work correctly, do I need to add a socket connection and rewrite the provideCompletionItems method?

**Comment by rcjsuen** [comment]
@ElDarco No, you shouldn’t have to do any of that from my experience.
