### ISSUE TITLE
'vscode' typings bleeding into monaco-languageclient interfaces

### ISSUE THREAD

**Issue by mhintzke** [TypeFox/monaco-languageclient#183]
I need to hook into the MonacoLanguageClient middleware so I could handle Diagnostics in our application. However, when I tried to do so, the typings from `vscode` aren't available to the application as 'vscode' is not a dependency of the application itself.  There seems to also be a `Diagnostic` type in the monaco-languageclient library itself, but the interface we are interacting with comes directly from vscode-languageclient which is the problem.

This is the signature that is inside this file:

https://github.com/microsoft/vscode-languageserver-node/blob/153fa6316ab8991dfae25836780b66217f92efe2/client/src/client.ts#L448

The `LanguageClientOptions` interface comes from `vscode-languageclient` which references types from `vscode`.

And this is how I am trying to use it:

![image](https://user-images.githubusercontent.com/8990993/67509965-f4ffe500-f648-11e9-8a94-786e2ecff471.png)

As you can see, I don't have access to the `Diagnostic` and `Uri` types from the `vscode` library.  Have you worked around that at all yet? I'm not sure what the consequences would be if I tried to install 'vscode' myself as there is already that compatibility library being monkey patched into the build via webpack.

**Comment by mhintzke13** [comment]
**UPDATE**

I have tried just installing the latest version of `vscode` directly and so far everything seems to be working fine. Should `vscode` become a peer dependency now of this library or am I doing this wrong?

**Comment by Louis-7** [comment]
Check this out: https://github.com/TypeFox/monaco-languageclient/blob/602e7606c046036d3627b59064bbfb4b67e7d2e8/example/webpack.config.js#L36
The error is not related to vscode missing. Actually, it's another dependency. 
The error was gone after I add this line to my webpack configuration.
