### ISSUE TITLE
donot use  next version dependency

### ISSUE THREAD

**Issue by zhixzhan** [TypeFox/monaco-languageclient#184]
version@0.10.2

```
// monaco-languageclient/package.json
  "dependencies": {
    "glob-to-regexp": "^0.3.0",
    "vscode-jsonrpc": "^4.1.0-next",
    "vscode-languageclient": "^5.3.0-next",
    "vscode-uri": "^1.0.5"
  },

```
after install, error appears, the next version package interface do not match

<img width="782" alt="Screen Shot 2019-11-03 at 9 37 30 PM" src="https://user-images.githubusercontent.com/49866537/68086017-2f0b8b00-fe82-11e9-908e-1e3930c3bf07.png">

<img width="1083" alt="Screen Shot 2019-11-03 at 9 18 25 PM" src="https://user-images.githubusercontent.com/49866537/68085778-82c8a500-fe7f-11e9-81f4-fae56b45b59b.png">

`ColorRegistrationOptions, ColorOptions` those two api actually
 are removed by the latest next package.
So I would suggest we do not use unstable version

**Comment by asual** [comment]
This concerns me too but I believe that it also needs to be addressed in TypeFox/vscode-ws-jsonrpc.

**Comment by akosyakov** [comment]
Not sure whether we can avoid not using `next` version. It was done to get latest features.

**Comment by marechal-p** [comment]
@akosyakov how about pinning to `5.3.0-next.6` (from this repo yarn.lock) or the version just before the current breakage?

I think it would be enough to fix this issue and dependents. Right now the version constraint is too large.

**Comment by akosyakov** [comment]
We will need to pin it here https://github.com/microsoft/vscode-languageserver-node/blob/430b9686a88781315996fd2cc252292faf82f46e/protocol/package.json#L19 It is not feasible. 

Pinning in dependent projects don't help, because yarn/npm will pull another version anyway from the primary package.
