### ISSUE TITLE
How to uninstall services and close socket connection

### ISSUE THREAD

**Issue by lilifan** [TypeFox/monaco-languageclient#185]
Hello. Firstly, thanks for your tremendous work.
I have successfully integrated your example code into my project, but then I come across two problems after I close the editor and then reopen it.
1、"Error: Language Client services has been overridden" : because `MonacoServices.install(editor) `  doesn't return a proper unInstall function.  So when I run these code again, console error comes out although the editor still works.
2、The old web socket connection seems still alive when the new editor opens a new socket connection, I think this may influence the client and server performances when user grows.
Thanks again~

**Comment by minazukie** [comment]
https://github.com/TypeFox/monaco-languageclient/pull/156
