### ISSUE TITLE
Is there any way to run the LSP Service supporting monaco editor with Webassembly

### ISSUE THREAD

**Issue by quank123wip** [TypeFox/monaco-languageclient#186]
I thought we can run Linux container in browser,use a minimal filesystem, but we don't have x86-64 support and it's not pretty useable(not that fast).
If we compile language server(such as ccls) as WebAssembly, redirect all read/write actions into a minimal Linux filesystem, and redirect the websocket service into the monaco editor. Is that possible? I think it's a better solution than run the Language Server on server

**Comment by akosyakov** [comment]
Language server needs access to local binaries to work. I don't think browser provide such access. Even if they would what would be the point of such solution if a user have to install runtime for language server locally?

**Comment by quank123wip** [comment]
> Language server needs access to local binaries to work, i.e. to `node`, `java`, `ccls` probably to C compiler. I don't think browser provide such access. It would be insecure to allow any remote content run processes on your machine. Even if they would what would be the point of such solution if a user have to install runtime for language server locally?

No, I mean that make a minimal Linux FS and pack it some way, redirect all read or write actions direct to the Linux FS File

**Comment by quank123wip** [comment]
All work provided by a webassembly service , just "simulate" a developing machine

**Comment by quank123wip** [comment]
Maybe we can use [jvilk/BrowserFS](https://github.com/jvilk/BrowserFS) and [Emscripten](https://github.com/emscripten-core/emscripten) to deal with the problem :)

**Comment by akosyakov** [comment]
> Maybe we can use

@quank123wip The scope of this package is already fixed, many projects depend on it. The best choice of action would to create another package and experiment there.

**Comment by LukePrior** [comment]
@quank123wip did you have any luck with this?
