### ISSUE TITLE
Scala Metals Integration

### ISSUE THREAD

**Issue by chris-rr** [TypeFox/monaco-languageclient#187]
Hi There!

First of all, awesome piece of work, very exciting possibility to be able to connect a web-based editor to language servers in a general way, and with so much in the way of support and examples due to the VS Code association.

I am interested to better understand the means by which other language servers can be connected - I'm looking at a Scala Metals integration myself, and struggling to figure out how exactly to perform the integration.  The main issue is that in the examples, the vscode-json-languageservice is used to perform the necessary actions to generate the vscode-languageserver-types from the raw LSP messages; of course, such a service does not exist for scala-metals.  Investigating the VS code integration metals-vscode, it seems in this case the server is just fetched via coursier and then the details for launching passed to the LanguageClient constructor, which internally handles the connection to the server as well as doing the necessary to construct the languageserver types from the LSP messages in order to provide the "IDE" features to the editor.  It is of course possible to forward the rpc messages from the metals language server to a socket connection (not something I have done, but seems it should be relatively straightforward), and then use this as the connection provider for the monaco-languageclient, but then I am not sure if/how the conversion from LSP to the vscode language types is to be handled?  Is it necessary to write something similar to the json service, or is there some generic converter (perhaps borrowed from the vscode language client) that can be used?  Or perhaps there is the same internal structure  to the MonacoLanguageClient that is called on if no more specific implementation is given?

Hope I have been clear enough; if I have misunderstood something please let me know so I can correct my understanding and revert 😄

**Comment by rcjsuen** [comment]
> The main issue is that in the examples, the vscode-json-languageservice is used to perform the necessary actions to generate the vscode-languageserver-types from the raw LSP messages; of course, such a service does not exist for scala-metals.

Not entirely true. There are two means of launching the language server in the example. You want to look at the code where the language server is launched via an external process and change that to suit your needs.

https://github.com/TypeFox/monaco-languageclient/blob/602e7606c046036d3627b59064bbfb4b67e7d2e8/example/src/json-server-launcher.ts#L17-L19

> I am not sure if/how the conversion from LSP to the vscode language types is to be handled?

This is basically handled for free by the library. You do not have to do anything.

**Comment by chris-rr** [comment]
Many thanks for prompt reply @rcjsuen ! 
Ok, so basically I would just modify the launcher to create a server connection via Java executed on the Metals server jar with appropriate args (following metals-vscode essentially), and the integration should work with the "LSP->protocol_>monaco" conversions achieved internally by the MonacoLanguageClient?  That would be amazing 👍

**Comment by rcjsuen** [comment]
@chris-rr Only one way to find out...


![](https://i.pinimg.com/236x/8b/34/d8/8b34d8efa280959af733f542aee3a116--programming-humor-o-reilly.jpg)

**Comment by chris-rr** [comment]
Thanks again, will let you know once I have a result so this can be closed.

**Comment by chris-rr** [comment]
@rcjsuen Alright, did as suggested and have managed to get this working 👍 

Ran into an issue with the rootUri setting by `MonacoServices.install` -  the `rootUri` passed as `Options` seems only to populate the workspace details, but doesn't cause the `rootUri` property of the initialization message params to be set - Metals requires this parameter to be populated so I have just set it at the init logic in the launcher, but probably this should be done automatically by the `install`/`create` methods?

The other issue is that if using `inmemory` provider for the model URI (the default if not set explicitly),  Metals complains that  `inmemory` provider is not installed - I'm not sure what needs to be done about this, possibly I need some provider handler for this installed for Scala?  Any advice on this also appreciated.

In any case, super cool to get full language server features in a browser 😁

**Comment by rcjsuen** [comment]
1. I'm not familiar with that flag in the context of this library (as I've never had to work with it) but it does sound suspicious. There's not too much context to go on in the original report in #31 that brought about the change.
1. You need to give it a URI that it expects. For most cases this is likely a `file` URI. How the language server uses that information (along with `rootUri`) is non-deterministic and varies from language servers. There are language servers that don't really care about URIs (if it's only looking at one files like JSON or YAML) and then there are those that do (Java enforces folder structures with its packages and so on).
