### ISSUE TITLE
Support UTF-8 for the LSP protocol

### ISSUE THREAD

**Issue by XVilka** [TypeFox/monaco-languageclient#188]
See the lengthy discussion here: https://github.com/microsoft/language-server-protocol/issues/376

It seems that monaco-languageclient is one of a few that uses UTF-16 https://github.com/Avi-D-coder/lsp-range-unit-survey

Would be nice if it will have UTF-8 support as well, at least optionally.

**Comment by akosyakov** [comment]
Monaco language client is based on vscode-languageserver and monaco-editor-core (VS Code editor). First it should be adopted there.
