### ISSUE TITLE
Any plans for supporting protocol v3.15

### ISSUE THREAD

**Issue by vitalybaev** [TypeFox/monaco-languageclient#189]
Hi! I'd like to use the latest Golang server - gopls. Unfortunately, now gopls supports 3.15 protocol. This cause issue with `tagSupport` schema: in 3.14 it's bool, in 3.15 it's different struct.
Thanks

**Comment by rcjsuen** [comment]
@vitalybaev Can you share a stacktrace of the error in question?

**Comment by rcjsuen** [comment]
@vitalybaev I cannot find the string `tagSupport` anywhere in the [3.14 specification](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/).

**Comment by vitalybaev** [comment]
@rcjsuen yes, I've not found too. But the following message has sent:
<img width="764" alt="Снимок экрана 2019-12-02 в 20 53 08" src="https://user-images.githubusercontent.com/724423/69982613-f1b02100-1545-11ea-9a6c-dbc3ff6d7b2e.png">

I can't show error right now. 

In 3.15 it is here:
https://github.com/golang/tools/blob/ecd32218bd7f33fd31c1abbfb74283690bedd093/internal/lsp/protocol/tsprotocol.go#L431

I have no idea how tagSupport from publishDiagnostics can be related to completion item. I'll sent you ws logs tomorrow
