### ISSUE TITLE
Support of "LocationLink" for the "onDefinition"-Method

### ISSUE THREAD

**Issue by NLueg** [TypeFox/monaco-languageclient#190]
Hello everyone.

First of all, thank you for the work so far. The client helped very much with implementing an editor.

Background
--------------------------
I currently work on a [language-server](https://github.com/NLueg/ov-language-server) for the DSL [openVALIDATION](https://github.com/openvalidation/openvalidation).
During the implementation, I considered most of the functions of the LSP, including the "GoTo-Definition" function.

My Problem
--------------------------
During to the fact, that openVALIDATION is close to a natural language, we don't have any brackets or use the indentation for separating different elements of the grammar. That's why I need to consider the exact range of the definition of a variable.
This is also part of the LSP, but not of the monaco-languageclient.

The monaco-languageclient can only use the class `Location`, which holds the range and the name of the requested reference. The LSP provides the class `LocationLink` which additionally holds the range of the definition of the variable. 
Therefore I wanted to use this class for implementing the feature. This actually leads to an uncaught error inside the monaco-languageclient. The vscode-language-client can work fine with the same implementation.

Additional Context
--------------------------

In the following, I use a sample openVALDATION-Code which consists of a rule and a variable.
The variable is named `underage` and is located in the first two lines. Inside the second block, you can find the rule, which uses the variable in the first condition. I won't explain the rest of it, because this is are the relevant points of the following code:

![image](https://user-images.githubusercontent.com/48101693/70133273-0c89af00-1686-11ea-9065-5e3167d8295c.png)

As I said, openVALIDATION doesn't use any brackets or indentations to separate elements.
The elements of openVALIDATION are separated with blank lines.
If I am correct, the monaco-client uses the `Location` class and tries to find the whole definition with the defined brackets. 
I now try to look at the definition of the variable `underage` with the corresponding reference inside the rule. The "brackets-problem" yields to the following documentation:

![image](https://user-images.githubusercontent.com/48101693/70133489-802bbc00-1686-11ea-93fb-a8ac8b4c8048.png)

As you cant see, just the whole code will be displayed, because monaco doesn't recognize the end of the variable.

That's why I started using the class `LocationLink` and integrated this solution inside VSCode.
This leads to the following result:

![image](https://user-images.githubusercontent.com/48101693/70133756-06e09900-1687-11ea-8657-7c2e66496cc5.png)

The exact same code yields to the following error inside the monaco-languageclient, because the `LocationLink` class is unkown to the client.

![image](https://user-images.githubusercontent.com/48101693/70134195-e238f100-1687-11ea-8e83-4cde5adc5bc0.png)

<br/><br/>

I tried to implement the support for `LocationLink` by myself to create a pull request, but frankly, I wasn't very successful. Sorry for the long post but I wanted to provide all relevant information.
Thank you very much for helping me.

**Comment by rcjsuen** [comment]
@NLueg Did you look the `asLocation` function at line 635 of `ProtocolToMonacoConverter`? What does the `item` look like? I guess its `uri` property is `undefined`?

**Comment by rcjsuen** [comment]
Based on the capabilities that are being sent to the language servers, `linkSupport` is advertised as being `true` so `LocationLink` should be supported.

**Comment by NLueg** [comment]
@rcjsuen Thank you for your fast response! 
Yes, I looked at the `asLocation` function and there is the problem I think.
The `uri` is `undefined` in this case, because the attribute has another name in the `LocationLink` object.

Here the definition for `Location`:

```ts
export interface Location {
    uri: string;
    range: Range;
}
```

and the definition for `LocationLink`:

```ts
export interface LocationLink {
    originSelectionRange?: Range;
    targetUri: string;
    targetRange: Range;
    targetSelectionRange: Range;
}
```

As you can see, the naming of the attributes is quite different.
In the `asLocation` is an object required, that contains an `uri` and `range` attribute which is not the case in the `LocationLink`.
