### ISSUE TITLE
Help regarding Language Server deployment

### ISSUE THREAD

**Issue by mehulmpt** [TypeFox/monaco-languageclient#195]
Hello there!
So I've been stuck more or less 2 days on setting up a language server for Java and I think I'm close but I have no clue where to go now. The thing is, I'm running this https://github.com/georgewfraser/java-language-server language server inside a docker container and I've started the server with the provided `././lang_server_linux.sh` script in that repo.

Now, how do I link this running server inside docker to JSON RPC API in node? I see that there's this line in `json-server-launcher.ts`:

```js
const serverConnection = server.createServerProcess('JSON', 'node', [extJsonServerPath])
```

But because the process (server?) is already running in a docker container, I suppose I should not create it again right? How do I link the existing process running inside the docker with the node backend? I see there are other methods like `createWebSocketConnection` available for Node too, but I honestly have no idea how to use it, and neither did I find any support material online.

I'm new to the JSON RPC API so any help would be really appreciated!

**Comment by CGNonofr** [comment]
Hello !

The simplest way is to keep the demo code (in process mode), and just replace le process execution (`JSON node file.js`) by the `docker run -it --rm ...`

I don't know about this particular implementation but most use stdin/out to communicate, so your can't just 'connect' to it, your need to launch it (well with docker your can attach afterward but there's no point here)

The next step is to replace it by a proper docker client (for instance dockerode)

good luck!

(btw, there is an eclipse-managed implementation for java: https://github.com/eclipse/eclipse.jdt.ls which handle diagnostics and is very active)
