### ISSUE TITLE
Upgrade to vscode-language-client 6.0.0

### ISSUE THREAD

**Issue by apupier** [TypeFox/monaco-languageclient#196]
it would be nice to upgrade to 6.0.0
https://github.com/Microsoft/vscode-languageserver-node/blob/master/README.md#3150-protocol-600-client--600-server

there is especially fixed devDependencies to make it easier to use:
https://github.com/microsoft/vscode-languageserver-node/blob/0b7a2b3c3f00c596fe799b31d6a34a594a53e26b/client/package.json#L22 

https://github.com/microsoft/vscode-languageserver-node/blob/a61f308d22a54c4e187b01fda00f061cf21b184c/client/package.json#L22

**Comment by akosyakov** [comment]
@azatsarynnyy @RomanNikitenko It would be nice to make together with upgrade to latest Monaco, without going over everything twice.

**Comment by azatsarynnyy** [comment]
closed by https://github.com/TypeFox/monaco-languageclient/pull/199
Thanks @RomanNikitenko!
