### ISSUE TITLE
How to set configurations to client?

### ISSUE THREAD

**Issue by zerocewl** [TypeFox/monaco-languageclient#201]
Is there a way to send client config settings to a language client, e.g pyls?

I read the example from #32, where a simple example was provided. However the vscode api changed, in fact the provided example does not work.
I tried to adapt the example to the changed api, but my config is not send to `pyls`.

Is there any minimal working example for this?

**Comment by raxod502** [comment]
@TypeFox Any update here? There is no documentation provided on how to do this, and without such documentation it is impossible to use this project with Python language servers among others.

**Comment by raxod502** [comment]
Oh thank god I finally figured it out (by spending some hours inspecting the innards of `vscode-languageserver-node`). You have to add a middleware, like this:

```typescript
new MonacoLanguageClient({
  name: "Your Name",
  clientOptions: {
    documentSelector: [{ pattern: "**" }],
    middleware: {
      workspace: {
        configuration: (params, token, configuration) => {
          return [{ foo: "bar" }];
        },
      },
    },
  },
  connectionProvider: {
    get: (errorHandler, closeHandler) =>
      Promise.resolve(
        createConnection(connection, errorHandler, closeHandler)
      ),
  },
})
```

(I won't guarantee the other stuff in that code will work for you, I had to hack a bunch of other things as well. But the middleware key should be correct. Of course you must adjust the actual content of the LSP configuration to taste.)

The relevant part of `vscode-languageserver-node` is [where the middleware is pulled out and turned into config](https://github.com/microsoft/vscode-languageserver-node/blob/6243e2753b9efbf6ad69d076e77af5d8a7d1f3a9/client/src/common/configuration.ts#L38-L41).

**Comment by umesh-timalsina** [comment]
Hello @raxod502. What is the middleware key are you referring to? Is it the name of the language server? Or is it something else?

**Comment by raxod502** [comment]
By "middleware key" I simply meant the data that appears immediately after `middleware:` in the sample code.

**Comment by umesh-timalsina** [comment]
In Riju, I see that you are using Microsoft's python language server. Is the binary available somewhere? Also, what steps did you take to configure it. It would be helpful for my use case to use a standalone server written in a single language rather than a patchwork of different libraries and extensions.

**Comment by raxod502** [comment]
I suggest referring to the code.

* [Installation](https://github.com/raxod502/riju/blob/6cdc5b0822f2b817d7de3f28391d70c09f843782/scripts/docker-install-phase4.bash#L239-L245)
* [Configuration](https://github.com/raxod502/riju/blob/6cdc5b0822f2b817d7de3f28391d70c09f843782/backend/src/langs.ts#L1939-L1950)

**Comment by itthought** [comment]
I am running Microsoft's python language server on a separate machine and want to connect with the monaco editor. And as per language server documentation I need to pass `"python.linting.enabled": true` config setting to the language server for enabling linting support. 
  
I am using below config for creating MonacoLanguageClient instance.

```
new MonacoLanguageClient({
      name: 'Simple Client',
      clientOptions: {
        // use a language id as a document selector
        documentSelector: ['python'],
        initializationOptions: {
          interpreter: {
            properties: {
              UseDefaultDatabase: true,
              Version: '2.7',
              InterpreterPath: '/usr/bin/python',
              LibraryPath: '/usr/lib/python2.7'
            }
          },
          asyncStartup: true,
        },

        middleware: {
          workspace: {
            configuration: (params, token, configuration) => {
              return[{python: { linting: {enabled: true}}}];
            },
          }
        },
        synchronize: {
          configurationSection: ''
        },

        // disable the default error handler
        errorHandler: {
          error: () => ErrorAction.Continue,
          closed: () => CloseAction.DoNotRestart
        }
      },
      // create a language client connection from the JSON RPC connection on demand
      connectionProvider: {
        get: (errorHandler, closeHandler) => {
          return Promise.resolve(createConnection( connection as any, errorHandler, closeHandler));
        }
      }
    });
```
Its always sending blank setting to language server.
`{"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{}}}`

Is there anyway to send custom setting to language server?

**Comment by raxod502** [comment]
I can't speak for the didChangeConfiguration message, Riju (linked above) has support for setting the initializationOptions in the initialize method (key `init` in Riju language configuration) as well as sending configuration in response to the workspace/configuration message (key `config` in Riju language configuration, currently unused but I just tested that it does work).

**Comment by dkattan** [comment]
@itthought did you ever have any success populating the settings payload?

@raxod502 it looks like Riju was taken down, did you perhaps rename it?

**Comment by raxod502** [comment]
> it looks like Riju was taken down, did you perhaps rename it?

Unfortunately, that's not what happened. Please see https://intuitiveexplanations.com/tech/replit/ for the details.
