### ISSUE TITLE
Missing cleanup / dispose for MonacoWorkspace `onDidCreateModel`

### ISSUE THREAD

**Issue by zerocewl** [TypeFox/monaco-languageclient#202]
As a workaround for changing the workspace uri (see #200) i tried to dispose and recreate the MonacoService.
I use the `dispose()` (#156) method for the service. Additional i call the monaco editor `dispose` method.
This seems to work well, but if i recreate/ reinit the Monaco editor i get following error:

```
Error: Language Client services has not been installed
    at push.../../node_modules/monaco-languageclient/lib/services.js.Services.get (services.js:24)
    at Object.match (vscode-api.js:209)
    at DidOpenTextDocumentFeature.textDocumentFilter [as _selectorFilter] (client.js:238)
    at DidOpenTextDocumentFeature.callback (client.js:254)
    at CallbackList.invoke (events.js:62)
    at Emitter.fire (events.js:120)
    at MonacoWorkspace.addModel (monaco-workspace.js:33)
    at monaco-workspace.js:16
    at e.fire (event.ts:563)
    at t.createModel (modelServiceImpl.ts:282)
```

From the depending stacktrace the call comes from the listener attached in the `MonacoWorkspace`, which was used before.
In the Constructor the listeners are attached, but there is no use of the `Disposable` which is returned from the `onDidCreateModel` (see [Monaco api](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#ondidcreatemodel)).

Code snippet for listeners without `Disposable` in `MonacoWorkspace`:
```
export class MonacoWorkspace implements Workspace {
 ...
    constructor(
...
        monaco.editor.onDidCreateModel(model => this.addModel(model));
        monaco.editor.onWillDisposeModel(model => this.removeModel(model));
...
    }
```

**Comment by lingxiao-Zhu** [comment]
same error for me

**Comment by suhaskurade8** [comment]
same error for me

**Comment by CGNonofr** [comment]
The install method doesn't take the editor as parameter anymore, so there's no need to uninstall it anymore
