### ISSUE TITLE
Colouring Configuration

### ISSUE THREAD

**Issue by benblayer** [TypeFox/monaco-languageclient#203]
Hi,

Can you please provide further details regarding colouring?

I.e how do I configure client & server in order to color language's special syntax?

Thanks

**Comment by CGNonofr** [comment]
Hi

Syntax Highlighting is not done by LSP !

(except in very recent version which supports semantic tokens but it doesn't concern the whole document)

Monaco editor can out-of-the-box highlight some languages, if you want more, you can give a try to monaco-ace-tokenizer or vscode-textmate

**Comment by benblayer** [comment]
Thanks for the response!

And what about completion? How do I configure that?
I noticed sometimes the client sends textDocument/completion message but doesn't get any related response.

**Comment by CGNonofr** [comment]
Without any context, it's difficult to answer. 

There is a functional example in this repo

**Comment by rcjsuen** [comment]
> And what about completion? How do I configure that?
> I noticed sometimes the client sends textDocument/completion message but doesn't get any related response.

That should just happen automatically.

1. Confirm that the client is sending the JSON request.
1. Confirm that the server is receiving said JSON request.
1. Confirm that the server is sending back a) a non-empty result or b) a promise that resolves to a valid result.
1. Confirm that the client is receiving said JSON response.
1. Confirm that the client is converting the JSON response correctly to a format that Monaco understands.

**Comment by benblayer** [comment]
...
> Monaco editor can out-of-the-box highlight some languages, if you want more, you can give a try to monaco-ace-tokenizer or vscode-textmate

How is it done? can you give me an example?

**Comment by benblayer** [comment]
> > And what about completion? How do I configure that?
> > I noticed sometimes the client sends textDocument/completion message but doesn't get any related response.
> 
> That should just happen automatically.
> 
> 1. Confirm that the client is sending the JSON request.
> 2. Confirm that the server is receiving said JSON request.
> 3. Confirm that the server is sending back a) a non-empty result or b) a promise that resolves to a valid result.
> 4. Confirm that the client is receiving said JSON response.
> 5. Confirm that the client is converting the JSON response correctly to a format that Monaco understands.

They do send and receive JSON-RPC. but server doesn't send any completion info.

**Comment by rcjsuen** [comment]
> They do send and receive JSON-RPC. but server doesn't send any completion info.

Well, if the client's request looks good to you then that implies the server has a bug somewhere and then that is not a fault of the `monaco-languageclient` library.

**Comment by benblayer** [comment]
For example if I want the Monaco Editor to color the word "hello" with color red, how do I configure that?

**Comment by rcjsuen** [comment]
> For example if I want the Monaco Editor to color the word "hello" with color red, how do I configure that?

You can take a look at the [Monarch documentation](https://microsoft.github.io/monaco-editor/monarch.html) and/or browse through the language definitions defined in the [Microsoft/monaco-languages repository](https://github.com/microsoft/monaco-languages).

**Comment by benblayer** [comment]
thanks
