### ISSUE TITLE
Connect Monaco Editor with a language server written in OCaml

### ISSUE THREAD

**Issue by chengtie** [TypeFox/monaco-languageclient#205]
I want to make a web page that contains an editor of code in OCaml. I prefer to use Monaco Editor. 

There is a language server of OCaml written in OCaml: [ocaml-lsp](https://github.com/ocaml/ocaml-lsp).

Does anyone know how to connect the Monaco Editor to this ocaml-lsp? How could we achieve this with monaco-languageclient?

Thank you.

**Comment by rcjsuen** [comment]
@chengtie I suggest looking at the existing example and modifying the code that launches the server procecss as a start.

https://github.com/TypeFox/monaco-languageclient/blob/c54b09fb6e43cfe3ecd28c061654226f77da5ad3/example/src/json-server-launcher.ts#L17-L19

**Comment by chengtie** [comment]
I have made a public repository which contains `monaco-languageclient` and `ocaml-lsp`: https://github.com/chengtie/monaco-languageclient/tree/a0abcc87f5506862d88d82b2e73af7c55a22aef0

The example of `monaco-languageclient` works on the language server of JSON; `ocaml-lsp` works on its test. What we need to do is to connect these two tools.

Unfortunately, I'm not very familiar with the interface thing... Could you help me get started? I think it is a very interesting use case of monaco-languageclient.

**Comment by rcjsuen** [comment]
> Unfortunately, I'm not very familiar with the interface thing... Could you help me get started? I think it is a very interesting use case of monaco-languageclient.

1. Being able to run the tests is not good enough. Have you confirmed that you are able to start the server from the command line?
1. Do you know how the server communicates with an LSP client? Does it expect to use sockets or stdin/stdout?
1. There are many issues in this repository about your particular question. Perhaps #47 can help you a little.

**Comment by chengtie** [comment]
> 1. Being able to run the tests is not good enough. Have you confirmed that you are able to start the server from the command line?

Yes,  running `ocamllsp` when it is in your scope should be enough.
If we installed it through opam, `opam exec ocamllsp`
If we just have a binary somewhere, `./path/to/ocamllsp/binary`

> 2. Do you know how the server communicates with an LSP client? Does it expect to use sockets or stdin/stdout?

From https://github.com/ocaml/ocaml-lsp/blob/master/ocaml-lsp-server/test/e2e/src/LanguageServer.ts, it seems that they use stdin/stdout.
