### ISSUE TITLE
 on change language how to close current language server connection and start new lanugage server connection

### ISSUE THREAD

**Issue by GNSubrahmanyam** [TypeFox/monaco-languageclient#210]
Hi @rcjsuen, 
If i change language from python3 to csharp then python3 connection should close and start csharp connection.

![image](https://user-images.githubusercontent.com/18217008/80302987-04641480-87cb-11ea-8d48-09cf93661590.png)

**Comment by rcjsuen** [comment]
@GNSubrahmanyam Sorry, I've never had this use case for my own requirements so I can't help you here.
