### ISSUE TITLE
Will lsp functionality breaks if we use socket.io instead of ws?

### ISSUE THREAD

**Issue by GNSubrahmanyam** [TypeFox/monaco-languageclient#218]
@rcjsuen Need your thoughts on this?

**Comment by rcjsuen** [comment]
> @rcjsuen Need your thoughts on this?

@GNSubrahmanyam No idea, I do not have this use case.

**Comment by cdietrich** [comment]
i assume yes cause of headers see also 
https://github.com/TypeFox/monaco-languageclient/issues/212
https://github.com/TypeFox/vscode-ws-jsonrpc/issues/6

**Comment by skykick-cm-2** [comment]
I am actually using PSES on top of socket-io with this library and so far it has worked just fine. Granted we are using a limited set of functionality, I haven't seen any issues with it.

**Comment by mhintzke** [comment]
I am actually using PSES on top of socket-io with this library and so far it has worked just fine. Granted we are using a limited set of functionality, I haven't seen any issues with it.
