### ISSUE TITLE
Can't create a language server client

### ISSUE THREAD

**Issue by boroda4436** [TypeFox/monaco-languageclient#222]
Hi! I am trying to create a web socket client to my Java language server.
As instruction, I am using [this example](https://github.com/TypeFox/monaco-languageclient/blob/602e7606c046036d3627b59064bbfb4b67e7d2e8/example/src/client.ts)

However, I am receiving the following error when I am running `createWebSocket` function:
```
[ error ] ./node_modules/vscode-jsonrpc/lib/pipeSupport.js
Module not found: Can't resolve 'net' in '/usr/src/frontend/node_modules/vscode-jsonrpc/lib'
```

vscode versions:
```    
    "vscode-jsonrpc": "^5.0.1",
    "vscode-languageserver": "^6.1.1",
    "vscode-ws-jsonrpc": "^0.2.0"
```

Is there any way how to create a WebSocket without a vscode-jsonrpc module or how to fix the error?

Thanks!

**Comment by CGNonofr** [comment]
Hi, If you're using webpack, you'll need to customize your configuration a little

see https://github.com/TypeFox/monaco-languageclient/blob/master/examples/browser/webpack.config.js

especially this part:
```
    node: {
        fs: 'empty',
        child_process: 'empty',
        net: 'empty',
        crypto: 'empty'
    },
```

**Comment by xgyyx** [comment]
> Hi, If you're using webpack, you'll need to customize your configuration a little
> 
> see https://github.com/TypeFox/monaco-languageclient/blob/master/examples/browser/webpack.config.js
> 
> especially this part:
> 
> ```
>     node: {
>         fs: 'empty',
>         child_process: 'empty',
>         net: 'empty',
>         crypto: 'empty'
>     },
> ```

That's a greate way to support client & server in one package
