### ISSUE TITLE
How to disable capabilities like docmentations, codelens, hover and linters for all language servers 

### ISSUE THREAD

**Issue by GNSubrahmanyam** [TypeFox/monaco-languageclient#223]
@rcjsuen Can you help me to do that. Lsp like java eclipse taking more than 500 Mb. We can allocate 500 mb for each user / client. Concurrently 100+ java users comes in our  use case

**Comment by rcjsuen** [comment]
@GNSubrahmanyam I guess you might be able to get around this by subclassing `MonacoLanguageClient` and then overriding `registerBuiltinFeatures` so you only get what you want?

https://github.com/TypeFox/monaco-languageclient/blob/fb587b3ff258d48194c8667a6ade2d0fd87d06bd/client/src/monaco-language-client.ts#L88

**Comment by GNSubrahmanyam** [comment]
Any example ?

**Comment by rcjsuen** [comment]
> Any example ?

Without seeing your code it's hard to comment. You could try just copy/pasting the current implementation and then commenting stuff out I guess.

https://github.com/TypeFox/monaco-languageclient/blob/fb587b3ff258d48194c8667a6ade2d0fd87d06bd/client/src/monaco-language-client.ts#L88-L108

Perhaps you can try working with the existing example and trying to change things from there?

https://github.com/TypeFox/monaco-languageclient/blob/fb587b3ff258d48194c8667a6ade2d0fd87d06bd/example/src/client.ts#L51-L70

**Comment by GNSubrahmanyam** [comment]
Go it thanks
