### ISSUE TITLE
How to disable auto import in eclipse java jdt

### ISSUE THREAD

**Issue by GNSubrahmanyam** [TypeFox/monaco-languageclient#224]
@rcjsuen In our use case we want to disable autoimport. How to stop sending completionItem/resolve

![image](https://user-images.githubusercontent.com/18217008/87225328-b7471600-c3a9-11ea-8ec8-c518397a2992.png)

**Comment by rcjsuen** [comment]
@GNSubrahmanyam Either use a middleware to intercept the request or change the `CompletionOptions` from the server so that you make it seem like it actually doesn't support the `resolveProvider`.

You can look at https://github.com/microsoft/vscode-languageserver-node/pull/322 or https://github.com/microsoft/vscode-languageserver-node/issues/628 for some middleware examples I guess.

**Comment by GNSubrahmanyam** [comment]
I tried using middleware to intercept the request but still auto import is happening in Java eclipse language server

**Comment by rcjsuen** [comment]
@GNSubrahmanyam What does your middleware code look like?

Whenever you ask for help, you should always share your code if at all possible.

**Comment by GNSubrahmanyam** [comment]
@rcjsuen I did that


resolveCompletionItem: (items, token, next) => {
          console.log(items)
          next({}, token)
        },

**Comment by rcjsuen** [comment]
> resolveCompletionItem: (items, token, next) => {
> console.log(items)
> next({}, token)
> },

I'm surprised the language server hasn't died since you're sending nothing back. You don't want to talk to the server at all, right? Why are you calling `next`?

**Comment by GNSubrahmanyam** [comment]
I agree with you even i am surpised that language server hasn't died :D. I tried removing next call but still autoimport is happening and that's strange

![image](https://user-images.githubusercontent.com/18217008/87227977-ea92a080-c3bb-11ea-8a65-6910f4e1e51a.png)

**Comment by rcjsuen** [comment]
@GNSubrahmanyam Then you need to keep debugging to see what's going on and/or reach out to the JDT Language Server team.

**Comment by GNSubrahmanyam** [comment]
@rcjsuen https://github.com/eclipse/eclipse.jdt.ls/issues/1505. In JDT language server this not no option to disable auto import

**Comment by rcjsuen** [comment]
> @rcjsuen [eclipse/eclipse.jdt.ls#1505](https://github.com/eclipse/eclipse.jdt.ls/issues/1505). In JDT language server no option to disable auto import

Oh, that's too bad.

**Comment by GNSubrahmanyam** [comment]
Any alternative way to prevent via client middleware or server middleware.

**Comment by rcjsuen** [comment]
> Any alternative way to prevent via client middleware or server middleware.

@GNSubrahmanyam Well, did you figure out where the auto-imports are coming from?

**Comment by GNSubrahmanyam** [comment]
![image](https://user-images.githubusercontent.com/18217008/87294673-b33e0400-c521-11ea-99f2-fa4063f48937.png)
![image](https://user-images.githubusercontent.com/18217008/87294715-c18c2000-c521-11ea-8786-92c15e44ee1a.png)
Yes, Through additionalTextEdits

**Comment by rcjsuen** [comment]
@GNSubrahmanyam OK, did you try deleting them then?

**Comment by GNSubrahmanyam** [comment]
Will try. How can i modifiy the request from lsp backend?

**Comment by rcjsuen** [comment]
@GNSubrahmanyam You can just modify the result in your middleware, no?

**Comment by GNSubrahmanyam** [comment]
in middleware which method ?

**Comment by GNSubrahmanyam** [comment]
@rcjsuen did this and it is working

import { has, get, map, omit, set} from "lodash";
import * as rpc from "vscode-ws-jsonrpc";
export const launch = (request: http.IncomingMessage, socket: rpc.IWebSocket) => {
if (rpc.isResponseMessage(message)) {
          if (typeof message.result === 'object' && has(message.result, 'isIncomplete')) {
            let items = map(get(message.result, 'items'), (item) => {
              if (has(item, 'additionalTextEdits')) {
                item = omit(item, 'additionalTextEdits')
                return item;
              }
              return item;
            })

            set(message.result, 'items', items)

          }
        }

**Comment by rcjsuen** [comment]
@GNSubrahmanyam Thank you for sharing your solution! OK to close this?

**Comment by GNSubrahmanyam** [comment]
@rcjsuen Thanks :)

**Comment by Gilwe** [comment]
@GNSubrahmanyam how did you connect the server side of `monaco-languageclient` to the java language server?

In python i've done it by `pip instal pyls` and changed in the server side of languageclient:

```
const serverConnection = bridgeServer.createServerProcess('python','pyls');
```


How is it done in Java?

**Comment by amitbkumar** [comment]
Hey @Gilwe, did you get solution?

> @GNSubrahmanyam how did you connect the server side of `monaco-languageclient` to the java language server?
> 
> In python i've done it by `pip instal pyls` and changed in the server side of languageclient:
> 
> ```
> const serverConnection = bridgeServer.createServerProcess('python','pyls');
> ```
> 
> How is it done in Java?

**Comment by CGNonofr** [comment]
Their document is pretty [exhaustive](https://github.com/eclipse/eclipse.jdt.ls#running-from-the-command-line)

just run the provided command line instead of `python pyls`
