### ISSUE TITLE
Support of code completions based on workspace

### ISSUE THREAD

**Issue by jbymy2000** [TypeFox/monaco-languageclient#23]
Suppose I have two different files in the same workspace, how to do code completions based on them, say one file is imported in another file. Right now I can only provide code completions for only one file.

**Comment by akosyakov** [comment]
Could you provide more information, please? How many editors do you have? Which language server do you use?

It is the responsibility of the language server to provide completions given that proper `rootUri` is provided, i.e. pointing to the location of workspace on the disk.

**Comment by akosyakov** [comment]
I am going to close this issue if there are no objections.
