### ISSUE TITLE
update needed

### ISSUE THREAD

**Issue by OliverwengFiltered** [TypeFox/monaco-languageclient#231]
Hi community,

Due to the recent update from `monaco-editor` repo. I think we need this one to be updated as well.

it seems `monaco-editor` removed the dynamic command from `editor._commandService` so it complaints `editor._commandService.addCommand` not a function error.

**Comment by harshadsindhav** [comment]
Hey team,
I am also facing the same issue.
**operating system:** windows
**browser:** chrome

Please check attached screen shot and help if possible.

Thank you very much.

![addCommand error](https://user-images.githubusercontent.com/13543626/94141014-c3f7e800-fe89-11ea-8a0b-b88b4c665dda.jpg)

**Comment by joshuataylor** [comment]
Downgrading to the previous version fixes this issue. 0.21.2 has a lot of changes from 0.20.0, and will require a few updates in the monaco-languageclient codebase to make it work.

**Comment by CGNonofr** [comment]
here is the commit that removed the feature: https://github.com/microsoft/vscode/commit/3c2423086cd00526fbad9d0e9ac043c64928f1a3

**Comment by nikeee** [comment]
Maybe the way to do it now is something like mentioned here:
https://github.com/microsoft/monaco-editor/issues/1857#issuecomment-594457013

**Comment by CGNonofr** [comment]
It seems to not only work, but also to be a better solution since it allows to use more than one editor in the same page without the requirement to "hack" the `MonacoCommands`

Let's hope it wont break anything, I'm working on it

**Comment by CGNonofr** [comment]
I need https://github.com/TypeFox/vscode-ws-jsonrpc/pull/25 to be merged and published to be able to create the MR on monaco-languageclient

**Comment by CGNonofr** [comment]
@nikeee monaco-languageclient doesn't depend on monaco-editor nor monaco-editor-core, and I didn't find any way to get the `CommandRegistry` from the editor instance

**Comment by CGNonofr** [comment]
I found a way, I'm ready to create the MR as soon as https://github.com/TypeFox/vscode-ws-jsonrpc/pull/25 is published

**Comment by CGNonofr** [comment]
version `0.13.1-next.4` published

**Comment by mattborghi** [comment]
Hi, I have a problem while I updated to the version `0.13.1-next.4` in my `react v.17` app using `webpack v.5` 

```
ERROR in ./node_modules/monaco-languageclient/lib/services.js 26:13-69
Module not found: Error: Can't resolve 'vscode-languageserver-protocol/lib/common/api' in '/home/borghi/Desktop/umc/UniversalMC-Frontend/node_modules/monaco-languageclient/lib'
```
Using the following package versions

```
    "monaco-editor": "^0.21.2",
    "monaco-editor-webpack-plugin": "^2.0.0",
    "monaco-languageclient": "^0.13.1-next.4",
```

In order to work I had to downgrade them (as shown below) but I need to make it work with the latest `monaco-editor` version because it supports julia language. 

```
    "monaco-editor": "^0.20.0",
    "monaco-editor-webpack-plugin": "^1.9.1",
    "monaco-languageclient": "^0.13.0",
```

Thanks in advance.

**Comment by CGNonofr** [comment]
Hello!

What is the version of `vscode-languageserver-protocol` in your package-lock (or yarn.lock)?

**Comment by mattborghi** [comment]
```
"vscode-languageserver-protocol": "^3.15.3"
```

**Comment by mattborghi** [comment]
So, it turns out that installing the version `vscode-languageserver-protocol@3.16.0-next.11` solves this problem but I have a new one

```
client.js:1727 Uncaught (in promise) TypeError: this.commandRegistry.registerCommand is not a function
    at MonacoCommands.registerCommand (monaco-commands.js:9)
    at Object.registerCommand (vscode-api.js:847)
    at ExecuteCommandFeature.register (client.js:1682)
    at ExecuteCommandFeature.initialize (client.js:1662)
    at MonacoLanguageClient.initializeFeatures (client.js:2504)
    at eval (client.js:2189)
```

**Comment by CGNonofr** [comment]
You can refer to the anticipated changelog: https://github.com/TypeFox/monaco-languageclient/blob/master/CHANGELOG.md

**Comment by mattborghi** [comment]
> You can refer to the anticipated changelog: https://github.com/TypeFox/monaco-languageclient/blob/master/CHANGELOG.md

Indeed, that solve the issue, thank you!

**Comment by OliverwengFiltered** [comment]
> You can refer to the anticipated changelog: https://github.com/TypeFox/monaco-languageclient/blob/master/CHANGELOG.md

Hi @CGNonofr 

I'm using pure javascript when using monaco-languageclient, 

I'm getting same error, after everything upgrades to latest and greatest.

in my case, I can't use "require('monaco-editor-core/esm/vs/platform/commands/common/commands').CommandsRegistry" because it requires build.

I have a bundle js file which exports all the library vars into a global variable, "webpackBundleInstance", where I get access to things like `webpackBundleInstance.monaco.editor...`

previously I was using `webpackBundleInstance.MonacoServices.install(editor)`
I'm wondering what's the param should be for the install statement in my case.

Thanks

**Comment by OliverwengFiltered** [comment]
> > You can refer to the anticipated changelog: https://github.com/TypeFox/monaco-languageclient/blob/master/CHANGELOG.md
> 
> Hi @CGNonofr
> 
> I'm using pure javascript when using monaco-languageclient,
> 
> I'm getting same error, after everything upgrades to latest and greatest.
> 
> in my case, I can't use "require('monaco-editor-core/esm/vs/platform/commands/common/commands').CommandsRegistry" because it requires build.
> 
> I have a bundle js file which exports all the library vars into a global variable, "webpackBundleInstance", where I get access to things like `webpackBundleInstance.monaco.editor...`
> 
> previously I was using `webpackBundleInstance.MonacoServices.install(editor)`
> I'm wondering what's the param should be for the install statement in my case.
> 
> Thanks
> ![Screen Shot 2020-12-23 at 5 49 06 PM](https://user-images.githubusercontent.com/28814939/103042464-b06f2280-4547-11eb-8071-1a6e762b8477.png)

it's all set, got this working.
