### ISSUE TITLE
How to support Groovy Auto-Completion

### ISSUE THREAD

**Issue by cxwSuperman** [TypeFox/monaco-languageclient#232]
How to support Groovy Auto-Completion.

**Comment by cxwSuperman** [comment]
Now I only know how to introduce the example of "vscode-json-languageservice", but I don't have a clue about groovy. I really want to know how to introduce it on the client side, please help

**Comment by GNSubrahmanyam** [comment]
Use https://github.com/prominic/groovy-language-server.
