### ISSUE TITLE
Any plans for long polling support

### ISSUE THREAD

**Issue by GNSubrahmanyam** [TypeFox/monaco-languageclient#233]
In many organization websocket is blocked in that case long polling helps

**Comment by GNSubrahmanyam** [comment]
@akosyakov @rcjsuen Any update ?

**Comment by CGNonofr** [comment]
TypeFox is not maintaining anymore monaco-languageclient so I don't think they'll answer you

However, the transport is handled by https://www.npmjs.com/package/vscode-ws-jsonrpc, your best chance is to fork it and replace the websocket implementation by sockjs/socketio/whatever

**Comment by rcjsuen** [comment]
@GNSubrahmanyam I don't have this use case so I do not have anything to add here unfortunately.
