### ISSUE TITLE
How does the client initialize different events for the monaco editor?

### ISSUE THREAD

**Issue by miko1991** [TypeFox/monaco-languageclient#238]
Hello, I've been reviewing this repo, and there are basically 2 clients, one in example folder, and one in example/browser folder. the browser one provides code for suggestions, hover etc, but not the first one (example/client.ts). How do the suggestions come up then? How are they connected?

**Comment by CGNonofr** [comment]
If I remember correctly, the browser example does everything client-side using `vscode-json-languageservice`

While the main example is using a websocket connection with a node server using LSP and `vscode-json-languageservice` server-side

All the magic is done inside the `createLanguageClient` function (client.ts:46)
