### ISSUE TITLE
Examples/browser doesn't seem to work.

### ISSUE THREAD

**Issue by Gilwe** [TypeFox/monaco-languageclient#239]
Hi, I'm using mac BigSur(11.1) and trying the browser example but it doesn't seem to work.
yarn version = 1.21.1

Running `yarn` like the setup instructions says leads to those errors:
<img width="556" alt="Screen Shot 2020-12-17 at 13 51 37" src="https://user-images.githubusercontent.com/21289132/102484559-1d2d7d00-406f-11eb-8ac7-beb7935f82de.png">
<img width="1091" alt="Screen Shot 2020-12-17 at 13 53 06" src="https://user-images.githubusercontent.com/21289132/102484628-36cec480-406f-11eb-9e7b-ab1aeb8c7e88.png">

I noticed that no node_modules were created at all, so I ran `npm install`, that did create the node_modules but other error popped up in the node_modules:

The cmd and output:
<img width="1428" alt="Screen Shot 2020-12-17 at 13 54 27" src="https://user-images.githubusercontent.com/21289132/102484820-7695ac00-406f-11eb-9f6c-0567cd4c65d8.png">

One of the errors:
<img width="985" alt="Screen Shot 2020-12-17 at 13 55 40" src="https://user-images.githubusercontent.com/21289132/102484909-95943e00-406f-11eb-8421-78ffb8e94532.png">

Try it out yourself, and/or ask me if you need more info.

Thank you.

**Comment by Gilwe** [comment]
My package.json, is just what resides in master at the moment:

```
{
  "private": true,
  "name": "browser-example",
  "version": "0.13.0",
  "dependencies": {
    "file-loader": "^4.3.0",
    "monaco-languageclient": "^0.13.0",
    "vscode-json-languageservice": "^3.10.0",
    "vscode-languageserver-types": "^3.16.0-next.4"
  },
  "scripts": {
    "prepare": "yarn run clean && yarn run build",
    "compile": "tsc",
    "watch": "tsc -w",
    "clean": "rimraf lib",
    "copy": "cp src/index.html lib/index.html",
    "build": "yarn run compile && webpack && yarn run copy",
    "update:file-deps": "yarn run clean:file-deps && yarn install",
    "clean:file-deps": "yarn run clean:monaco-languageclient",
    "update:monaco-languageclient": "yarn run clean:monaco-languageclient && yarn install",
    "clean:monaco-languageclient": "rimraf node_modules/monaco-languageclient"
  }
}

```

**Comment by rcjsuen** [comment]
Hm, it seems OK for me.
```Sh
$ yarn
$ cd examples/browser
$ yarn
$ yarn run build
```
All these commands completed for me.

**Comment by Gilwe** [comment]
My problem was that I didn't run the `yarn` in the root directory beforehand
