### ISSUE TITLE
Migrate to vscode-languageclient instead of vscode-base-languageclient

### ISSUE THREAD

**Issue by gatesn** [TypeFox/monaco-languageclient#24]
As per https://github.com/Microsoft/vscode-languageserver-node/issues/88, an abstract BaseLanguageClient has now been exposed in the library.

It looks like a pretty significant change to monaco-languageclient to implement this, however it does unfork the library so probably worth taking on.

**Comment by akosyakov** [comment]
BaseLanguageClient merged in https://github.com/Microsoft/vscode-languageserver-node/issues/88 is only abstract from node env, but has dependencies on vscode and cannot be used with Monaco.

I'm fond of an idea of dropping vscode-base-languageclient in favor of vscode-languageclient instead. To make it happens the following should be done:
- vscode-base-languageclient should be rebased on vscode-langaugeclient
- the PR should be opened to merge vscode-base-languageclient to vscode-languageclient (https://github.com/Microsoft/vscode-languageserver-node/issues/88 should be reopened)

Actually, the first step should be done anyway to catch up with the latest changes.

**Comment by akosyakov** [comment]
We had to keep this issue due to https://github.com/TypeFox/monaco-languageclient/pull/89#issuecomment-408805291.

**Comment by johnwiseheart** [comment]
While we wait, is it possible to release a new version of `vscode-base-languageclient`? Merged some changes to their repo which I'd like to use. Not sure how/where the differences are, so if I need to make the changes elsewhere let me know and I can do it.

**Comment by akosyakov** [comment]
@johnwiseheart We do it soon, latest by end of July.

Generally i'm thinking to refactor and move language-client to backend (node) and forward monaco APIs between frontend-backend. It will allow to use `vscode-languageclient` directly. It is not something which will happen soon, if it will at all.

**Comment by akosyakov** [comment]
We've decided to go with es6 dependencies and kill our fork. Clients will need to target es6 as well our use babel to down level monaco-langaugeclient and its dependencies to es5. I will explain how it can be done in the CHANGELOG.

**Comment by akosyakov** [comment]
0.10.0 was released with support of Monaco 0.17.0
