### ISSUE TITLE
connection.end not a function

### ISSUE THREAD

**Issue by OliverwengFiltered** [TypeFox/monaco-languageclient#241]
Hi @CGNonofr ,

I'm wondering if you can reproduce the below issue.

whenever I call monacoLanguageClientConnection.dispose, it throws an error says connection.end is not a function.

here is some screenshots for details.

<img width="573" alt="Screen Shot 2020-12-23 at 9 06 05 PM" src="https://user-images.githubusercontent.com/28814939/103050817-4795a380-4563-11eb-9ce1-64c2fdd21a64.png">
<img width="631" alt="Screen Shot 2020-12-23 at 9 06 00 PM" src="https://user-images.githubusercontent.com/28814939/103050819-482e3a00-4563-11eb-90cd-16c11f6f31f6.png">
<img width="624" alt="Screen Shot 2020-12-23 at 9 12 01 PM" src="https://user-images.githubusercontent.com/28814939/103050910-87f52180-4563-11eb-826e-5bccdb5e2ef1.png">

**Comment by CGNonofr** [comment]
Hi!

`vscode-ws-jsonrpc` wasn't updated, you're now supposed to use `@codingame/monaco-jsonrpc` instead

I think it's your issue

**Comment by OliverwengFiltered** [comment]
> Hi!
> 
> `vscode-ws-jsonrpc` wasn't updated, you're now supposed to use `@codingame/monaco-jsonrpc` instead
> 
> I think it's your issue

Yup, thank you for the tips.

after using the @codingame/monaco-jsonrpc, it hits another issue which I created a PR towards the open source jsonrpc project.

wondering if you have any insight around this.

https://github.com/microsoft/vscode-languageserver-node/pull/719
