### ISSUE TITLE
Listen to 'textDocument/definition' results

### ISSUE THREAD

**Issue by Gilwe** [TypeFox/monaco-languageclient#243]
Hi, I'm trying to listen to the event of the results of go-to-definition coming in to the language-client.

I used the example here (not the browser one), connected it to a python-language-server and it is working as expected, go-to definition returns the wanted files.
My problem is that I want to listen to the results coming in and use them.

I have 2 options as I see:
1. use `monaco.languages.registerDefinitionProvider()` and `.then` it, but that requires me to implement the go-to-definition by my own but:
    - I want to use the default langauge-client implementation, for easier support
    - If I'd try to implement on my own, I see in the browser example that it is possible to be done by using the `getLanguageService` of `vs-code-json-langservice` but I have no idea if that's possible to integrate with the first example (+ is that relevant for other language other than JSON?)

2. Instead of implementing the function, I am looking for a way to subscribe to the event of the results coming in.
I tried using onRequest / onNotification:

```
languageClient.onReady().then(() => {
            console.log("Client ready")

            languageClient.onRequest('textDocument/definition', (...params: any[]) => {
                console.log("got definitions!, params: "+ params)
                } 
            ) 
        })
```

But that doesn't work unfortunately, as the log doesn't happen although the results coming in perfectly.

Thank you.

**Comment by CGNonofr** [comment]
Hi

Maybe you can try using the middleware:
```typescript
  const client = new MonacoLanguageClient({
    ...
    clientOptions: {
      ...
      middleware: {
        provideDefinition: (document, position, token, next) => {
          const definition = next(document, position, token)

          return definition
        }
      }
    }
  })
```
I think `languageClient.onRequest` doesn't work because it's not a request, it's a response
