### ISSUE TITLE
Can 0.14.0 please be published?

### ISSUE THREAD

**Issue by Gilwe** [TypeFox/monaco-languageclient#247]
Right now the examples in this repo are using new libraries, which are up-to-date for November 2020, like:

- @CodinGame/monaco-jsonrpc 0.3.0
- vscode-jsonrpc 6.0.0
- vscode-languageserver 7.0.0

But, when one wants to use `monaco-languageclient` @0.13.0 (which predates to April 2020), he/she will have to resort to use older version of those libraries and missing out on features that are possible in the examples.

No new version was introduced when the package.json was updated in  https://github.com/TypeFox/monaco-languageclient/commit/f8df3598e9a181c3de5026881f97184228a8e6ce

So, kicking the version up to 0.14.0 would be great!
Thank you!

**Comment by CGNonofr** [comment]
I don't think I have the required permission to do so

What is the process @akosyakov ?

In the meantime, you can use the @next version

**Comment by katspaugh** [comment]
I've made a PR to make it easier for you: #251
@CGNonofr could you check?

**Comment by Gilwe** [comment]
@CGNonofr what do you mean by 'use the next version'? I want to use the version that is in the master branch of this repo.
but no new version was published since April of 2020 (v0.13.0).

@akosyakov is there a way to publish the current master?

**Comment by CGNonofr** [comment]
monaco-languageclient@0.13.1-next.9 was published one month ago
