### ISSUE TITLE
LSP semantic tokens dont work

### ISSUE THREAD

**Issue by Vadimtro** [TypeFox/monaco-languageclient#256]
I have semantic tokens working in vscode (LSP protocol circa 3.16+). It doesn't appear working in Monaco. All other LSP messages, such as hover, folding, etc are fine in both products.

**Comment by mofux** [comment]
I think the Semantic Tokens Feature was just added recently (#253 - @CGNonofr correct me if I'm wrong with that assumption) and should be available in `monaco-languageclient@0.13.1-next.9`. I haven't yet been able to test this feature myself because I am not using a language server that supports semantic tokens. What language server are you testing with?

**Comment by CGNonofr** [comment]
Indeed, monaco-languageclient supports semantic tokens since the last next version.

Howener, monaco doesn't support it out of the box:
- You need to provide `'semanticHighlighting.enabled'` as true in the editor options to enable the feature
- You need to provide a custom theme (see the example: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-semantic-tokens-provider-example) with your semantic token styles

**Comment by Vadimtro** [comment]
I have modified client.ts like this:

```
monaco.editor.defineTheme('myCustomTheme', {
    base: 'vs',
    inherit: true,
    rules: [
        { token: 'comment', foreground: 'aaaaaa', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'ce63eb' },
        //...
        { token: 'property', foreground: '3e5bbf' },
        { token: 'label', foreground: '615a60' },

        { token: 'type.static', fontStyle: 'bold' },
        { token: 'class.static', foreground: 'ff0000', fontStyle: 'bold' }
    ],
    encodedTokensColors: [],   // added to make ts compiler happy
    colors:  {}               // ditto
});

monaco.editor.create(document.getElementById("container")!, {
    model: monaco.editor.createModel('initial editor content', 'json', monaco.Uri.parse('inmemory://model.sql')),
    glyphMargin: true,
    lightbulb: {
        enabled: true
    },
    theme: 'myCustomTheme',
    'semanticHighlighting.enabled': true
});
```

Now, the client advertices its semantic color capabilities like this:
``
`"semanticTokens":{"dynamicRegistration":true,"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator"],"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"],"formats":["relative"],"requests":{"range":true,"full":{"delta":true}},"multilineTokenSupport":false,"overlappingTokenSupport":false}`

which seems to be identical to vs-code. However, unlike vscode, it never issues the message

`{"jsonrpc":"2.0","id":14,"method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":...`

**Comment by rcjsuen** [comment]
I'd suggest putting breakpoints and/or print statements in a few places to see where things are going wrong. Need to make sure the provider is being called and registered to Monaco for starters I think.

https://github.com/TypeFox/monaco-languageclient/blob/a9a4d3855e5d7d6c33cf2f2403016a51580f127d/client/src/monaco-languages.ts#L520-L527

https://github.com/TypeFox/monaco-languageclient/blob/7012751e797d2fe154745bf232242af8564797cf/client/src/vscode-api.ts#L728-L745

https://github.com/TypeFox/monaco-languageclient/blob/a9a4d3855e5d7d6c33cf2f2403016a51580f127d/client/src/monaco-languages.ts#L520-L527

**Comment by CGNonofr** [comment]
What language server are you using? it's difficult to find one that supports the 3.16 specs on that feature

**Comment by Vadimtro** [comment]
IIRC I forked lsp4j. Then adding one more message handler for textDocument/semanticTokens/full was not bid deal. (For monaco I had to add low [level message framing](url=https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#format) to elevate socket to websocket -- not sure if this can be achieved easier).

**Comment by rcjsuen** [comment]
> What language server are you using? it's difficult to find one that supports the 3.16 specs on that feature

My [Dockerfile language server](https://github.com/rcjsuen/dockerfile-language-server-nodejs) supports this feature. I believe [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer) also supports this feature...?

**Comment by Vadimtro** [comment]
@rcjsuen 

I'm not hitting any breakpoints in the sources you mentioned. I'm hitting this:
![debug client](https://user-images.githubusercontent.com/8160323/110857671-fe094a80-826d-11eb-9f9e-c933796d2a1b.png)

**Comment by rcjsuen** [comment]
@Vadimtro OK, that's something. We need more information on the `options` parameter. Can you expand it and show what's in the `options` parameter?

**Comment by Vadimtro** [comment]
![debug client](https://user-images.githubusercontent.com/8160323/110868621-c5716d00-827d-11eb-9139-a8adcc8b3372.png)

{"legend":{"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator"],"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"]},"documentSelector":["json","sql"]}

**Comment by rcjsuen** [comment]
@Vadimtro What is your server sending back for `ServerCapabilities`? Can you share the JSON?

**Comment by rcjsuen** [comment]
@Vadimtro Also, are you using dynamic registration at all?

**Comment by Vadimtro** [comment]
```
{
	"jsonrpc": "2.0",
	"id": 0,
	"result": {
		"capabilities": {
			"completionProvider": {
				"triggerCharacters": [
					"."
				],
				"hoverProvider": true
			},
			"codeLensProvider": {
				"resolveProvider": true
			},
			"dynamicRegistration": true,
			"hoverProvider": true,
			"definitionProvider": true,
			"documentFormattingProvider": true,
			"foldingRangeProvider": true,
			"hasDiagnosticRelatedInformationCapability": true,
			"hasConfigurationCapability": true,
			"colorProvider": true,
			"documentSymbolProvider": true,
			"textDocumentSync": 1,
			"executeCommandProvider": {
				"commands": [
					"workspace/executeCommand",
					"run-command"
				]
			},
			"semanticTokensProvider": {
				"legend": {
					"tokenTypes": [
						"namespace",
						"type",
						"class",
						"enum",
						"interface",
						"struct",
						"typeParameter",
						"parameter",
						"variable",
						"property",
						"enumMember",
						"event",
						"function",
						"method",
						"macro",
						"keyword",
						"modifier",
						"comment",
						"string",
						"number",
						"regexp",
						"operator"
					],
					"tokenModifiers": [
						"declaration",
						"definition",
						"readonly",
						"static",
						"deprecated",
						"abstract",
						"async",
						"modification",
						"documentation",
						"defaultLibrary"
					]
				}
			},
			"workspace": {
				"workspaceFolders": {
					"changeNotifications": true
				}
			}
		}
	}
}
```

Again, it works in VS Code.

**Comment by rcjsuen** [comment]
@Vadimtro Your returned `ServerCapabilities` is the issue. You need to include `"full": true`. I use `"full": { "delta": false }` in my language server but they should mean the same thing.

```JSON
{
    "semanticTokensProvider": {
        "full": true,
        "legend": { "...": "..." }
    }
}
```

**Comment by CGNonofr** [comment]
I just tried the docker language server by tweaking the example and it seems pretty fine:
![Capture d’écran du 2021-03-12 19-04-06](https://user-images.githubusercontent.com/23257479/110980298-fe850c80-8365-11eb-92ed-f323fb5c92c3.png)

(there is a `textDocument/semanticTokens/full`)

I even have some highlighting without any additional configuration

**Comment by Vadimtro** [comment]
It works. Thank you very much!

![semantic tokens](https://user-images.githubusercontent.com/8160323/110982661-a9250d00-831d-11eb-9654-e6bba7b95b6a.png)

**Comment by CGNonofr** [comment]
Are you implementing a SQL language server ?

**Comment by Vadimtro** [comment]
Yes. 
https://web.archive.org/web/20210129200900/https://vadimtropashko.wordpress.com/2021/01/06/switching-to-the-new-ide-platform/
