### ISSUE TITLE
No docs for how to implement react-monaco-editor with Django backend

### ISSUE THREAD

**Issue by madatbay** [TypeFox/monaco-languageclient#257]
Hi, I have been researching for a while to how to implement Monaco editor autocomplete for python language and come up with PYLS. To use PYLS with react-monaco editor I know i have to use monaco-languageclient but cannot find any extensive docs about this repo. To use this app should I configure client and server side on the same time or client side is enough?  If should use both, how to implement django backend?

**Comment by CGNonofr** [comment]
Hello!

There is cooking recipe, you'll need a backed able to run a `pyls` program per client that need it. Docker is a good candidate to do so but not a requirement.

The doc is poor but I think the provided example says it all

**Comment by madatbay** [comment]
When I read docs about `pyls` saw we should use websockets. I will try. Thank u so much
