### ISSUE TITLE
Module not found: Can't resolve 'vscode' in ...

### ISSUE THREAD

**Issue by madatbay** [TypeFox/monaco-languageclient#258]
Hi, I'm using react-monaco-editor (tried @monaco-editor/react too, but gave same result) for creating browser based code editor with react with python language server (`LSP`). When I try to import `monaco-languageclient` to react app, app crashes with error code:
`./node_modules/monaco-languageclient/node_modules/vscode-languageclient/lib/declaration.js
Module not found: Can't resolve 'vscode' in '/home/madat/Documents/playground/react/monaco-lang-server/node_modules/monaco-languageclient/node_modules/vscode-languageclient/lib'`
I have done some debugging and know that problem comes with `monaco-languageclient` becuase when I comment import statement error goes away
I import like this:
`import {
  MonacoLanguageClient,
  CloseAction,
  ErrorAction,
  MonacoServices,
  createConnection,
} from "monaco-languageclient";`

**Comment by CGNonofr** [comment]
Hi,

You can refer to the example: https://github.com/TypeFox/monaco-languageclient/blob/f020bfd815bc7bb7fec000ed08cc59ccec8124a4/example/webpack.config.js#L40

You need to have an alias

**Comment by madatbay** [comment]
Solved my problem, thank you!
