### ISSUE TITLE
How to integrate with react-monaco-editor

### ISSUE THREAD

**Issue by madatbay** [TypeFox/monaco-languageclient#259]
Hi, how to integrate `monaco-languagecliet` with `react-monoco-editor`. I see docs of `monaco-languageclient` for pure `monaco` editor that uses `monaco` instance and so on... renders it. But `react-monoco-editor` gives simple usage for react app. How to use with react app&

**Comment by CGNonofr** [comment]
https://github.com/react-monaco-editor/react-monaco-editor#how-to-interact-with-the-monacoeditor-instance

**Comment by madatbay** [comment]
In this docs we see this:
`Using the first parameter of editorDidMount` we can get `monaco` instance. So i tried to install MonacoServices by this instance, I got error: 

`ReferenceError: monaco is not defined`

My code sample is this:
`
editorDidMount(editor, monaco) {
    console.log(editor)
    MonacoServices.install(editor)
  }
`

**Comment by CGNonofr** [comment]
With the last monaco editor version, you need to use monaco-languageclient@next (and `MonacoServices.install` doesn't take the editor as parameter anymore)
