### ISSUE TITLE
JS config to get messages

### ISSUE THREAD

**Issue by madatbay** [TypeFox/monaco-languageclient#260]
Hi, again. I think this is my last question. I have configured everything, `python rpc` server and so on. My client connects to language server. I know that from logs, but not sending messages (From browser ws network tab) or not giving any suggesting. I'm not using `Typescript` so I have to convert type script code into `JS` like code.
My `CreateLanguageClient` function is below:

```
function createLanguageClient(connection) {
  return new MonacoLanguageClient({
      name: "Sample Language Client",
      clientOptions: {
          // use a language id as a document selector
          documentSelector: ['py'],
          // disable the default error handler
          errorHandler: {
              error: () => ErrorAction.Continue,
              closed: () => CloseAction.DoNotRestart
          }
      },
      // create a language client connection from the JSON RPC connection on demand
      connectionProvider: {
          get: (errorHandler, closeHandler) => {
              return Promise.resolve(createConnection(connection, errorHandler, closeHandler))
          }
      }
  });
}
```

> When I convert into JS I have to remove MessageConnection part

**Comment by CGNonofr** [comment]
So what is your question?

Here is to report issues and bugs with monaco-languageclient.

If you are experiencing difficulties to make your backend work, do not hesitate to refer to the provided example and to compare the transfered frames with it.

If the python lsp implementation you use doesn't seem to work, please use their bug tracker.

**Comment by madatbay** [comment]
Question is about `monaco-languageclient`. I try to connect python language server and client with the help of `monaco-languageclient` but this is not working. I have changed ts code in example into js and this convertion removed `MessageConnection` part from  CreateLanguageClient part. So connection not working in this way. How should I solve problem?

**Comment by CGNonofr** [comment]
You are providing too few hints on what you're trying to do to be able to help you

**Comment by madatbay** [comment]
I'm using react-monaco-editor

**Comment by madatbay** [comment]
I'm using those:
```
import React, { Component } from "react";
import MonacoEditor from "react-monaco-editor";
import {
  MonacoLanguageClient,
  MessageConnection,
  CloseAction,
  ErrorAction,
  MonacoServices,
  createConnection } from "monaco-languageclient";
import {  w3cwebsocket as W3CWebSocket } from "websocket";
import { listen } from "vscode-ws-jsonrpc";
```
I have set up language server that works properly. And I create websocket like this:
```
const webSocket = new W3CWebSocket('ws://localhost:3001/python');
```
And when editor mounts I try to connect to server via new created socket:
```
  editorDidMount(editor, monaco) {
    MonacoServices.install(monaco)
    webSocket.onopen = () => {
      console.log('WebSocket Client Connected');
      listen({
        webSocket,
        onConnection: connection => {
          const languageClient = createLanguageClient(connection)
          const disposable = languageClient.start()
          connection.onClose(() => disposable.dispose())
        }
      })
    };
    webSocket.onmessage = (message) => {
      console.log(message);
    };
  }
```
Everythink is working properly without any problem, I get feedback from server when I connect to server. It is succesful. 
**Problem starts here:**
I need to create _Language Client_ to create messaging communication between client and server. From your examples I know I have to create Language Client like this:
```
function createLanguageClient(connection: MessageConnection): MonacoLanguageClient {
    return new MonacoLanguageClient({
        name: "Sample Language Client",
        clientOptions: {
            // use a language id as a document selector
            documentSelector: ['json'],
            // disable the default error handler
            errorHandler: {
                error: () => ErrorAction.Continue,
                closed: () => CloseAction.DoNotRestart
            }
        },
        // create a language client connection from the JSON RPC connection on demand
        connectionProvider: {
            get: (errorHandler, closeHandler) => {
                return Promise.resolve(createConnection(connection, errorHandler, closeHandler))
            }
        }
    });
}
```
**But this is TypeScript Solution**, I'm not using React with TypeScript, just using simple React with JavaScript, so, I cannot use code above directly; need to convert it into JS code, result is this:
```
function createLanguageClient(connection) {
  return new MonacoLanguageClient({
      name: "Sample Language Client",
      clientOptions: {
          // use a language id as a document selector
          documentSelector: ['py'],
          // disable the default error handler
          errorHandler: {
              error: () => ErrorAction.Continue,
              closed: () => CloseAction.DoNotRestart
          }
      },
      // create a language client connection from the JSON RPC connection on demand
      connectionProvider: {
          get: (errorHandler, closeHandler) => {
              return Promise.resolve(createConnection(connection, errorHandler, closeHandler))
          }
      }
  });
}
```
I think, issue starts here when I convert code

**Comment by CGNonofr** [comment]
I don't think this is related near of far to your typescript to javascript "convertion" since you just removed the types

**Comment by madatbay** [comment]
But I'm not using `MessageConnection` import from `monaco-languageclient` anywhere. Since I think I have to use it somewhere because of your Node.js example. Don't we need it?

**Comment by CGNonofr** [comment]
MessageConnection is just a type, it has no impact on the executed code

or I don't understand what you mean?

**Comment by madatbay** [comment]
No, I think you understood. I was thinking it has impact on code. Okay thank you so much, I'll continue to debug, if there is any issue related to your package, 'll let you onow
