### ISSUE TITLE
Webpack 5 import incompatibility

### ISSUE THREAD

**Issue by madatbay** [TypeFox/monaco-languageclient#261]
Hi, when I import `monaco-languageclient` I get error
```
Uncaught ReferenceError: Buffer is not defined
```
I tried to debug when this error happens I see that when I import this package I get this error
My import is like this:
```
import {
  MonacoLanguageClient,
  CloseAction,
  ErrorAction,
  MonacoServices,
  createConnection,
} from "monaco-languageclient";
```

By the way, this is react app without create-react-app so I know this is not related to cra
My packages looks like this:
```
"monaco-editor-webpack-plugin": "^3.0.1",
"monaco-languageclient": "^0.13.0",
"react-monaco-editor": "^0.43.0",
"webpack": "^5.30.0",
"webpack-cli": "^4.6.0",
"webpack-dev-server": "^3.11.2"
```

**Comment by JoshOY** [comment]
> Hi, when I import `monaco-languageclient` I get error
> 
> ```
> Uncaught ReferenceError: Buffer is not defined
> ```
> 
> I tried to debug when this error happens I see that when I import this package I get this error
> My import is like this:
> 
> ```
> import {
>   MonacoLanguageClient,
>   CloseAction,
>   ErrorAction,
>   MonacoServices,
>   createConnection,
> } from "monaco-languageclient";
> ```
> 
> By the way, this is react app without create-react-app so I know this is not related to cra
> My packages looks like this:
> 
> ```
> "monaco-editor-webpack-plugin": "^3.0.1",
> "monaco-languageclient": "^0.13.0",
> "react-monaco-editor": "^0.43.0",
> "webpack": "^5.30.0",
> "webpack-cli": "^4.6.0",
> "webpack-dev-server": "^3.11.2"
> ```

Hi @madatbay have you tried to bump this library to version `"monaco-languageclient": "0.13.1-next.9"` ?
It seems works for me for the same issue.

**Comment by madatbay** [comment]
Hi, @JoshOY thank you for your response. I will try it as soon as possible
