### ISSUE TITLE
MonacoServices: monaco is not defined

### ISSUE THREAD

**Issue by madatbay** [TypeFox/monaco-languageclient#262]
I'm trying to integrate `monaco-languageclient` with `react-monaco-editor`. When I try to install MonacoServices get get error `monaco is not defined` but I can interact with monaco itself.

```
  editorDidMount = (editor, monaco) => {
    MonacoServices.install(monaco); <<<<< **Problem comes with this line**
    webSocket.onopen = () => {
      console.log("WebSocket Client Connected");
      listen({
        webSocket,
        onConnection: (connection) => {
          const languageClient = createLanguageClient(connection);
          const disposable = languageClient.start();
          connection.onClose(() => disposable.dispose());
        },
      });
    };
    webSocket.onmessage = (message) => {
      console.log(message);
    };
  };
```

You can see my code above. When I try to install services I get monaco is not defined. Tried both parameters (editor, monaco) but result is same. Even when I console.log(monaco) I can see instance on console. It's interacting fine

**Comment by CGNonofr** [comment]
Try the @next version of monaco-languageclient

**Comment by Shubham567** [comment]
yes got the same when trying out react-editor-core 
![image](https://user-images.githubusercontent.com/17148450/119217271-bff29780-baf6-11eb-900f-5b2acff54b06.png)

**Comment by CGNonofr** [comment]
The solution for it was given just before your message
