### ISSUE TITLE
'createServerProcess' of ccls always fails

### ISSUE THREAD

**Issue by Fromnowon** [TypeFox/monaco-languageclient#263]
I am using monaco editor to handle c++ codes. 

In ```json-server-launcher.ts``` I set  to this:

```
const serverConnection = server.createServerProcess('ccls', "G://dev//ccls.exe");
```
Server can run but returns null, then I change to this:
```
const serverConnection = server.createServerProcess('ccls', "G://dev//ccls.exe  --init=\"{\\\"index\\\":{\\\"onChange\\\":true}}\"");
``` 
I get an error:
```
Launching ccls Server failed: Error: spawn G://dev//ccls.exe  --init="{\"index\":{\"onChange\":true}}" ENOENT
```
I copy this code and test in **cmd.exe**, it runs perfectly. 

I have search for solution for tow days but find nothing. 

Apologize for my bad English :)

**Comment by CGNonofr** [comment]
Hello

You can provide all the arguments in a single string:

- wrong: `server.createServerProcess('ccls', "G://dev//ccls.exe  --init=\"{\\\"index\\\":{\\\"onChange\\\":true}}\"")`
- correct: `server.createServerProcess('ccls', "G://dev//ccls.exe", "--init=\"{\\\"index\\\":{\\\"onChange\\\":true}}\"")`

**Comment by Fromnowon** [comment]
@CGNonofr Hi, thanks for helping!

```server.createServerProcess('ccls', "G://dev//ccls.exe", "--init=\"{\\\"index\\\":{\\\"onChange\\\":true}}\"")```

But the third arg couldn't be a string, so I change to:

```server.createServerProcess('ccls', "G://dev//ccls.exe", ["--init=\"{\\\"index\\\":{\\\"onChange\\\":true}}\""])```

It still gives me error :(

![image](https://user-images.githubusercontent.com/2792725/115675903-9e7c7f80-a381-11eb-8e32-ec3348032402.png)

I have found many samples like ```createServerProcess('sample', 'java', ['-h', 'xxx'])```, but ccls needs ```--init='{json}'```. I really don't know how to fill in the args...

**Comment by CGNonofr** [comment]
I think you have too many "\"

**Comment by Fromnowon** [comment]
> I think you have too many "\"

Thanks! I will try it :)
