### ISSUE TITLE
workspace/semanticTokens/refresh closes existing connection?

### ISSUE THREAD

**Issue by Jazzpirate** [TypeFox/monaco-languageclient#264]
This might be caused by one of several components, including my implementation of an LSP-Server but my current best guess is that this is a problem with the monaco-languageclient component:

If the serves sends a workspace/semanticTokens/refresh notification to the client, the client seems to react by a) first sending a null-response to aknowledge the request, but b) afterwards *closing* the current connection and establishing a *new* connection with the server, rather than just sending a new textDocument/semantikTokens/full request (which is the behaviour I would have expected). Is this true? If so, is this expected behavior? And if so, what is the actual intended method to notify the client to re-request semantic tokens, if the server has asynchronously computed new semantic tokens between requests?

**Comment by CGNonofr** [comment]
There is not many implementations that use semantic tokens, and I don't think the `workspace/semanticTokens/refresh` was really tested, so maybe it makes the client crash.

Isn't there any error in the console?

**Comment by Jazzpirate** [comment]
There isn't an error, but there is a line `RWS: handleClose {shouldRetry: true}` at `reconnecting-websocket/dist/index.js:78` following the notification, so it looks like the connection is being *intentionally* closed...?

**Comment by CGNonofr** [comment]
If your server doesn't close the connection, maybe it's a real issue in monaco-languageclient

Can you provide a language server binary reproducing the issue?

**Comment by Jazzpirate** [comment]
Unfortunately, I can't, or rather, it would be a huge amount of work to turn my half-baked sub-sub-LSP-module of a huge main-project into a standalone binary that can be easily executed on its own :(

**Comment by Jazzpirate** [comment]
I would guess however, that having *any* language server send a workspace/semanticTokens/refresh-notification to the client should reproduce the error - if not, that would probably be evidence that the problem is not with the client after all

**Comment by CGNonofr** [comment]
I just tried with the json server (faking the semantic token capability and injecting a `workspace/semanticTokens/refresh`) and it did not crash anything, but the server doesn't really support it so...

btw you are talking about a notification, while it's a request, is it not your issue?

**Comment by Jazzpirate** [comment]
I'm not sure whether it's supposed to "crash" - the behavior is that it seemingly deliberately *closes* the connection and establishes a new one, after sending a null-response. Since I don't get an error message, I don't think there's a crash happening somewhere...?

What's the *expected* behavior? Can you confirm that the client *should* issue a `workspace/semanticTokens/full` request (or something along those lines) and is that what's happening in your test example? If not, I would guess that there's maybe some issue with the registered capabilities...?

> btw you are talking about a notification, while it's a request, is it not your issue?

I'm not sure what the difference is (I was assuming that a "request" demands a non-trivial json-RPC-response, whereas a notification just requires an "OK"-response)... I'm using lsp4j on the server side, where I just call `client.refreshSemanticTokens()`, which issues the relevant notification/request/whatever.

**Comment by CGNonofr** [comment]
I'm running out of idea then! :-\
I think it is crashing because there is a reconnect-on-failure mecanism in this library

(The difference between a notification and a request is that a request has an id and require a response while a notification doesn't expect anything)

**Comment by Jazzpirate** [comment]
Can you explore what the *consequence* of a `workspace/semanticTokens/refresh`-request is in your toy example? e.g. does the client issue a  `workspace/semanticTokens/full` request in response or something?
