### ISSUE TITLE
ESM module and ESM browser example

### ISSUE THREAD

**Issue by kurtcodemander** [TypeFox/monaco-languageclient#267]
I import monaco-editor in the browser as an ESM module with Skypack.dev: 

import * as monaco from 'https://cdn.skypack.dev/monaco-editor';

I would also like to import monaco-languageclient as an ESM module in the browser. 

I tried the Skypack version: 

https://cdn.skypack.dev/monaco-languageclient

But it has many errors such as

```
import "/error/unknown:vscode-languageserver-protocol?from=monaco-languageclient";
;
import vscode_jsonrpc_1 from "/-/vscode-jsonrpc@v5.0.1-Y9ZWShgpP6lEl8RwiacQ/dist=es2020,mode=imports/optimized/vscode-jsonrpc.js";
import "/error/unknown:vscode-languageserver-protocol?from=monaco-languageclient";
;
import "/error/unknown:vscode-languageserver-protocol?from=monaco-languageclient";
;
```

(That's from https://cdn.skypack.dev/-/monaco-languageclient@v0.13.0-hlkzGii4r6o6RIIMEjaN/dist=es2020,mode=imports/optimized/monaco-languageclient.js)

Is it possible to create support for ESM in monaco-languageclient? 

If so, what needs to be done?

**Comment by CGNonofr** [comment]
Hi,

I can't say I really understand the errors you have.

However, there is a concern that doesn't have a solution I think: we some libraries that depends on "vscode".

To make this library work, we need to "[hack](https://github.com/TypeFox/monaco-languageclient/blob/f020bfd815bc7bb7fec000ed08cc59ccec8124a4/example/webpack.config.js#L40)" `vscode` imports

**Comment by babutabhavya** [comment]
+1

**Comment by kaisalmen** [comment]
v2.0.0+ generates esm code.

**Comment by kurtcodemander** [comment]
Thanks!
