### ISSUE TITLE
Uncaught (in promise) Error: Unknown parameter structure byName

### ISSUE THREAD

**Issue by bigbigDreamer** [TypeFox/monaco-languageclient#269]
When I used Monaco, I encountered such a problem, and finally I solved it. I think it is necessary to put forward an issue record to facilitate other developers to trace the problem. I am sorry to disturb you.

I think we can also optimize it in the next version of this package.

## Q

`Uncaught (in promise) Error: Unknown parameter structure byName`

## Resolve

```bash
$ npm ls vscode-jsonrpc

```

![image](https://user-images.githubusercontent.com/39019913/121151070-a2535b00-c876-11eb-8cdf-e6a40ae539ac.png)

Multiple `vscode-jsonrpc` cause this problem to occur.

```bash

$  npm dedupe vscode-jsonrpc

```

Now my program is working！

**Comment by CGNonofr** [comment]
(sorry for the delay): btw monaco-jsonrpc is replacing vscode-ws-jsonrpc, you can remove it!
