### ISSUE TITLE
How to use tcp connection instead of websocket to connect language server?

### ISSUE THREAD

**Issue by huanghantao** [TypeFox/monaco-languageclient#271]
In `example/src/client.ts`, I noticed that the client was using WebSocket:

```ts
const url = createUrl('/sampleServer')
const webSocket = createWebSocket(url);
// listen when the web socket is opened
listen({
    webSocket,
    onConnection: connection => {
        // create and start the language client
        const languageClient = createLanguageClient(connection);
        const disposable = languageClient.start();
        connection.onClose(() => disposable.dispose());
    }
});
```

But the Language server I use does not support WebSocket. So how to to use tcp connection instead of websocket to connect language server?

**Comment by CGNonofr** [comment]
You can't use raw sockets from the browser, you can only use websockets.

You'll need a server "proxy"

See the [example](https://github.com/TypeFox/monaco-languageclient/tree/master/example)

**Comment by huanghantao** [comment]
Thank you!
