### ISSUE TITLE
When will monaco-languageclient send textDocument/didOpen request to LSP server?

### ISSUE THREAD

**Issue by huanghantao** [TypeFox/monaco-languageclient#272]
So far, I have successfully sent an initialized request using `monaco-languageclient`, which seems to have been sent by calling `MonacoLanguageClient.start`. But, how to trigger a `TextDocument/DidOpen` request?

Does `monaco-languageclient ` automatically send the `TextDocument/DidOpen` request? Or I need to call a function manually?

This is the network request obtained through tcpdump:

[lsp.txt](https://github.com/TypeFox/monaco-languageclient/files/6691890/lsp.txt)

**Comment by CGNonofr** [comment]
Just open a model that match the DocumentSelector and that's it

**Comment by huanghantao** [comment]
Thank you!
