### ISSUE TITLE
vscode undefined

### ISSUE THREAD

**Issue by y912765390** [TypeFox/monaco-languageclient#273]
I NPM I monaco-languageclient alone. Then import monaco-languageClient. NPM run serve start project will say

* vscode in ./node_modules/vscode-languageclient/lib/common/declaration.js

To install it, you can run: npm install --save vscode

**Comment by CGNonofr** [comment]
Please have a look at the provided example: https://github.com/TypeFox/monaco-languageclient/blob/f020bfd815bc7bb7fec000ed08cc59ccec8124a4/example/webpack.config.js#L40
