### ISSUE TITLE
Language Client Services Overriding Problem.

### ISSUE THREAD

**Issue by ed-roh** [TypeFox/monaco-languageclient#274]
I'm having the same issue as this: https://github.com/TypeFox/monaco-languageclient/issues/225. And unable to find a solution for this problem. 
Doesn't seem to be a way to dispose previously installed Client Language Services triggering the 'error: Language Client services has been overridden' after installing via `MonacoServices.install(editor)`

This issue: https://github.com/TypeFox/monaco-languageclient/pull/156/files#diff-544ff078317aa067b00c24927238a8131ce5f71ba00704ec4b927e40b6935d32R55
is only referring to disposing within Services. This is an issue because if you install it through MonacoServices and not Services, you won't have access to the disposable function.

Question is, is there any potential problems of overriding the Language Client Services and also is there a way or workaround to suppress the Error?

**Comment by CGNonofr** [comment]
What about:
```typescript
const services = MonacoServices.create(monaco);
const disposable = Services.install(services);
```

?

**Comment by the3ddy** [comment]
unfortunately doesn't work. When it attempts to dispose via disposable.dispose() the Error:
`Error: Language Client services has not been installed` appears.
I attempted to install both Services and MonacoServices as well but get the Error the language services has been overridden. I suppose the error isn't really affecting the expected functionality as far as I can tell, just an ugly error message in console.
