### ISSUE TITLE
monaco is not defined

### ISSUE THREAD

**Issue by helloworldmygithub** [TypeFox/monaco-languageclient#275]
An error occurred when my program reached the following statement
         `MonacoServices.install(editor)`
The error message is as follows
    client.js:26 ReferenceError: monaco is not defined
        at new MonacoWorkspace (monaco-workspace.js:13)
        at create (monaco-services.js:21)
        at Object.install (monaco-services.js:27)
I want to know why ‘monaco is not defined’ in MonacoWorkspace‘s constructor

    "monaco-editor": "^0.26.0",
    "monaco-languageclient": "^0.13.0"

**Comment by helloworldmygithub** [comment]
Although I still don't know why, it doesn't report any mistakes now. I just changed the version number of "Monaco editor": "to 0.19.3

**Comment by CGNonofr** [comment]
With the last version of monaco editor, you need to use the next version of monaco-languageclient
