### ISSUE TITLE
Can MonacoServices only control match Model

### ISSUE THREAD

**Issue by yunlei23** [TypeFox/monaco-languageclient#276]
In my project,I create one editor instance, and multiple models。when user change edit tab,I change current model by use setModel api.  And models have different languages.
Now when using MonacoServices.install, all model will bind to MonacoService.Is there some methods to excute models that  in other languages.
I tried DocumentSelector and languageId in /example/src/client. 

`
     // create languageclient
     new MonacoLanguageClient({
        name: "my Language Client",
        clientOptions: {
            documentSelector: ['json'],
        },
    });

  // create model
   monaco.editor.createModel("", 'js', monaco.Uri.parse('inmemory://model.js'))
`
this model create will not send textDocument/didOpen request to server.but when editing it will send textDocument/didChange request . It leads to server error.

I looking into sourcecode . MonacoWorkspace class constructor code
`
    constructor(
        protected readonly p2m: ProtocolToMonacoConverter,
        protected readonly m2p: MonacoToProtocolConverter,
        protected _rootUri: string | null = null) {
        for (const model of monaco.editor.getModels()) {
            this.addModel(model);
        }
        monaco.editor.onDidCreateModel(model => this.addModel(model));
        monaco.editor.onWillDisposeModel(model => this.removeModel(model));
    }
`
It seems model create event binding in there.can i add model filter here?

thanks for you help

**Comment by CGNonofr** [comment]
I'm not sure to understand, why would it send a `textDocument/didChange` event on a `js` file with a `json` document selector?

**Comment by yunlei23** [comment]
> I'm not sure to understand, why would it send a `textDocument/didChange` event on a `js` file with a `json` document selector?

i find it . There is a unexpectedly editor.setModelLanguage called in my project。create Model is right，but language is incorrectly set

**Comment by yunlei23** [comment]
> I'm not sure to understand, why would it send a `textDocument/didChange` event on a `js` file with a `json` document selector?

I try to use setTimeout dynamic change model language. 
when change json to js,it will send a textDocument/didChange event without textDocument/didOpen
you can use code below in src/example/src/client
in language client, can dynamic change model language trigger didOpen event?

`
const model = monaco.editor.createModel(value, 'js', monaco.Uri.parse('inmemory://model.js'))

setTimeout(() => {
monaco.editor.setModelLanguage(model,'json')
console.log(`change language`)
}, 5000);

`
