### ISSUE TITLE
An error appears when it calls languageClient.start()

### ISSUE THREAD

**Issue by cztflove** [TypeFox/monaco-languageclient#278]
I follow the example to use the language client
but I have no idea why it goes wrong when it calls languageClient.start()
![image](https://user-images.githubusercontent.com/16745191/128196397-fa49c038-0cc1-4922-b6de-09db8dee6116.png)
the message is:  Request initialize failed with message: The \"path\" argument must be of type string or an instance of Buffer or URL. Received null

**Comment by CGNonofr** [comment]
Can you provide more context please? What is the object you're printing?

**Comment by cztflove** [comment]
> Can you provide more context please? What is the object you're printing?
my object is printed from the function addMessageToQueue of vscode-jsonrpc
![image](https://user-images.githubusercontent.com/16745191/128201223-5693d06f-f8f1-446d-860f-dcc338331398.png)

**Comment by rcjsuen** [comment]
@cztflove It's strange because there is no `path` on the `initialize` request. There is `rootPath` and `rootUri` though.

What language server are you trying to connect to?

**Comment by rcjsuen** [comment]
> > What language server are you trying to connect to?
> 
> typescript

Which one though?

Since you're in a debugger you can clearly step through the code. Are you able to pause execution and see what the `initialize` request you are sending to the server looks like?

**Comment by cztflove** [comment]
> > > What language server are you trying to connect to?
> > 
> > 
> > typescript
> 
> Which one though?
> 
> Since you're in a debugger you can clearly step through the code. Are you able to pause execution and see what the `initialize` request you are sending to the server looks like?
I use https://github.com/theia-ide/typescript-language-server

the initialize request is the following image
![image](https://user-images.githubusercontent.com/16745191/128217911-a2f4a09d-cbcd-4c7d-9b6b-beaa89ce83e0.png)
![image](https://user-images.githubusercontent.com/16745191/128218017-0c8a6f4c-14ea-4326-b3ef-7a79d41ff459.png)

**Comment by rcjsuen** [comment]
@cztflove Looks like your `rootPath` and `rootUri` are `null` so that's probably your problem.

**Comment by cztflove** [comment]
> @cztflove Looks like your `rootPath` and `rootUri` are `null` so that's probably your problem.

I am confused about the use of `rootUri`, it looks like the uri must

**Comment by cztflove** [comment]
@rcjsuen I am so confused about the use of rootUri, can you please explain for me? 
According to the example of typescript-language-server, it points to a local file path, but in a real case, we have no such dictionary in the project

**Comment by rcjsuen** [comment]
> @rcjsuen I am so confused about the use of rootUri, can you please explain for me?
> According to the example of typescript-language-server, it points to a local file path, but in a real case, we have no such dictionary in the project

Where is your language server running? Inside a Docker container? Just give it a path to an empty folder for now. It doesn't matter if there are files in it or not so don't think about it too much right now.

We're still in the debugging and experimenting phase and trying to see if this is a solution/workaround.

**Comment by naeil** [comment]
i think you need resolve alias 
{
"vscode-jsonrpc": path.resolve("./node_modules/@codingame/monaco-jsonrpc/node_modules/vscode-jsonrpc")
}


// new version "vscode-jsonrpc\lib\common\messages.js"
class AbstractMessageSignature {
    constructor(method, numberOfParams) {
        this.method = method;
        this.numberOfParams = numberOfParams;
    }
    get parameterStructures() { << is new
        return ParameterStructures.auto;
    }
}

**Comment by pawansingh00** [comment]
@cztflove Hi, Were you able to solve it?
I am getting the same error, when trying to run it with typescript language server.

**Comment by kaisalmen** [comment]
@cztflove please, try again with the latest version.
I am closing this issue. If there are further questions please open a discussion: https://github.com/TypeFox/monaco-languageclient/discussions

If you think there is an issue, please open a new one.

Thank you
