### ISSUE TITLE
change languageId don't tigger textDocument/didOpen

### ISSUE THREAD

**Issue by yunlei23** [TypeFox/monaco-languageclient#280]
when i debugger this question #276 , find change languageId don't tigger textDocument/didOpen. look in [LSP document](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_didOpen)

> The DidOpenTextDocumentParams contain the language id the document is associated with. If the language Id of a document changes, the client needs to send a textDocument/didClose to the server followed by a textDocument/didOpen with the new language id if the server handles the new language id as well.

According to the document，change other languageId to match language should request textDocument/didClose and textDocument/didOpen.change match language to other should request textDocument/didClose.

Here is my repetition steps

1 add this code in demo client
<img width="1135" alt="截屏2021-08-05 下午3 44 07" src="https://user-images.githubusercontent.com/40014319/128315494-a1caf669-fd7a-4d36-81ab-eb991e85f9ad.png">

2 click change language button.this is the message in console.not send didOpen,but other document request
<img width="811" alt="截屏2021-08-05 下午3 44 41" src="https://user-images.githubusercontent.com/40014319/128318754-eb3ff489-5e2b-45d7-994e-6f7c1108bb6d.png">

**Comment by CGNonofr** [comment]
You're right, well spotted, here is the PR: https://github.com/TypeFox/monaco-languageclient/pull/281

**Comment by CGNonofr** [comment]
If you want to give it a try, I already published it at `@codingame/monaco-languageclient`

I don't have the permission to publish in to `monaco-languageclient` and the automatic job was unplugged

**Comment by yunlei23** [comment]
> If you want to give it a try, I already published it at `@codingame/monaco-languageclient`
> 
> I don't have the permission to publish in to `monaco-languageclient` and the automatic job was unplugged

thank for you help ，i try what you fix and  it works well.  i will keep a private version in our repo now .  after monaco-languageclient publish ,then replace it
