### ISSUE TITLE
Issue when connecting to JAVA LSP

### ISSUE THREAD

**Issue by pawansingh00** [TypeFox/monaco-languageclient#299]
Hi,

I am trying to connect to JAVA LSP -  java language server (https://github.com/eclipse/eclipse.jdt.ls)

By changing this line -- https://github.com/TypeFox/monaco-languageclient/blob/69f41d2c2d9b37bcbb9a080d86ec2eed838d6885/example/src/json-server-launcher.ts#L19 

as below 

```
const serverConnection = server.createServerProcess('JSON', 'java', [
            '-Declipse.application=org.eclipse.jdt.ls.core.id1', 
            '-Dosgi.bundles.defaultStartLevel=4',
            '-Declipse.product=org.eclipse.jdt.ls.core.product',
            '-Dlog.level=ALL',
            '-noverify',
            '-Xmx1G',
            '-jar /home/pawansingh/projects/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar',
            '-configuration /home/pawansingh/projects/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/config_linux',
            '-data /home/pawansingh/projects/monaco-languageclient/example/src/java',        
            '--add-modules=ALL-SYSTEM',
            '--add-opens java.base/java.util=ALL-UNNAMED',
            '--add-opens java.base/java.lang=ALL-UNNAMED',
            '-DCLIENT_PORT=4000'
        ]);

```
and it seems to give the following error -- 

![image](https://user-images.githubusercontent.com/27332582/140698971-6ada864b-713c-4650-9694-990f5f7743ae.png)

Need help with this.
Any example of integrating it with **java/python/go** LSP will do it too.

**Comment by CGNonofr** [comment]
Hello,

The error is pretty clear, and is not related to this library

You can't put 2 arguments in a single argument

**Comment by pawansingh00** [comment]
Hi @CGNonofr Thanks so much for the Quick reply -- 

The Error is gone after I changed it to -- 

```javascript
        const serverConnection = server.createServerProcess('JSON', 'java', [
            '-Declipse.application=org.eclipse.jdt.ls.core.id1', 
            '-Dosgi.bundles.defaultStartLevel=4',
            '-Declipse.product=org.eclipse.jdt.ls.core.product',
            '-Dlog.level=ALL',
            '-noverify',
            '-Xmx1G',
            '-jar',
            '/home/pawansingh/projects/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar',
            '-configuration',
            '/home/pawansingh/projects/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/config_linux',
            '-data',
            '/home/pawansingh/projects/monaco-languageclient/example/src/java',        
            '--add-modules=ALL-SYSTEM',
            '--add-opens java.base/java.util=ALL-UNNAMED',
            '--add-opens java.base/java.lang=ALL-UNNAMED',
            '-DCLIENT_PORT=4000'
        ]);
```

But, completion still doesn't show up -- 

![Screenshot from 2021-11-08 13-37-33](https://user-images.githubusercontent.com/27332582/140706078-3007538d-61e3-4ec4-9a08-1144a5229667.png)


It might not be an issue with this repository, but pretty much new to this LSP stuff, so not so sure on where to add it, adding it here in case anybody has faced similar thing while trying to connect to JAVA LSP with Monaco.

**Comment by CGNonofr** [comment]
I don't think you can autocomplete an `inmemory` file, you'll need it to be on the filesystem and probably even need a pom.xml.

Since it's not related to this library, do not hesitate to ask for help in stackoverflow or the jtd.ls project

**Comment by pawansingh00** [comment]
Thanks @CGNonofr

**Comment by pawansingh00** [comment]
In case if it is of any help to somebody.
This started to work by changing this line - 

https://github.com/TypeFox/monaco-languageclient/blob/69f41d2c2d9b37bcbb9a080d86ec2eed838d6885/example/src/client.ts#L28

as below - 

```javascript
    model: monaco.editor.createModel(value, 'java', monaco.Uri.parse('file:///home/pawansingh/projects/monaco-languageclient/example/demo/java/file.java')),
```

after creating an empty file as this -- `monaco-languageclient/example/demo/java/file.java`

![Screenshot from 2021-11-08 15-11-47_1](https://user-images.githubusercontent.com/27332582/140910716-ce1bf0e7-1555-4a65-bf6d-fab2ac07379e.png)

**Comment by pawansingh00** [comment]
Now I want to Use **Syntax highlighting** and other features provided by monaco editor and for that I want to replace -- **_monaco-editor-core_** with **monaco-editor** package, but ended-up with lot of errors. 

Is it the correct way to just replace `monaco-editor-core` with `monaco-editor` and all the imports?

or do we have any pointer on how to go about replacing --  `monaco-editor-core` with `monaco-editor`

**Comment by rvignesh123** [comment]
Yes we should add file URI to show suggesions.

But the file loaded as non-project file releated to java. You can see that in your screenshot.
How to tell the JDT LS that this file path is belongs to Java project and how to show suggesions based on that ???

Could you find any ?

**Comment by rvignesh123** [comment]
> 

I found it ... I did not passed rootUri and the --data path should not directly point to the repository it self, it should point the parent folder. It works

**Comment by chaitanya71998** [comment]
@rvignesh123 
> did not passed rootUri and the --data path should not directly point to the repository it self, it should point the parent folder. It works
here can you explain this in detail

**Comment by kaisalmen** [comment]
@chaitanya71998  Both options "rootUri" and "data" need to be set correctly when you start the Java Language Server.

**Comment by chaitanya71998** [comment]
@kaisalmen, after making both the JDT and file root directory ("/home") the suggestions are working fine for your example.
But i have got another issues:
->  i am creating all the file creation and updating content, etc stuff on server side. 
-> I also created the java language server to run on server itself. this was working fine.
issues: 
1. because of giving the -data attribute in args, I was getting some extra java files loading into that directory and getting stored. If that continous the unwanted files gets stored as below. how can we remove them?
![Screenshot from 2023-01-07 17-07-39](https://user-images.githubusercontent.com/46353549/211148789-e4da756a-8899-4002-9762-e4c194f20fb9.png)

2. Also not knowing why the suggestion are not coming when loading files over server side

**Comment by chaitanya71998** [comment]
Hi @kaisalmen 
Had an issue with setting the rootUri and data path. I was maintaining java project in a server and getting paths from server. When i was giving the path came from server i was not getting suggestions. i was using [@monaco-editor/react](https://github.com/suren-atoyan/monaco-react)
can you share an example implementation

**Comment by kaisalmen** [comment]
> can you share an example implementation

@chaitanya71998 I don't fully understand your question. If you provide a publicly accessible repository with your code/config and with instructions how to set it up, then maybe we can help. Please ask questions concerning your problem at one place (this is a closed issue!), e.g here: https://github.com/TypeFox/monaco-languageclient/discussions/450 or open a specific issue you have with the one of the two libraries we provide here. Thank you.

**Comment by LavanyaBurlagadda** [comment]
Hi @kaisalmen 

I tried integrating language Server with Monaco Editor. I have two issues
1 - Getting suggestions lately
2 - Language server is taking almost 1GB data, even if I use `"-Xmx512m"` 

```
  const args = [
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.level=ALL",
    "-noverify",
    "-XX:MinHeapFreeRatio=5",
    "-XX:MaxHeapFreeRatio=10",
    "-XX:GCTimeRatio=4",
    "-XX:AdaptiveSizePolicyWeight=90",
    "-Dsun.zip.disableMemoryMapping=true",
    "-Xmx512m",
    "-Xms100m",
    "-jar",
    `${jdtPath}/jdt-language-server-1.9.0-202203031534/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar`,
    "-configuration",
    `${jdtPath}/jdt-language-server-1.9.0-202203031534/config_linux`,
    "-data",
    `${dataPath}`,
    "--add-modules=ALL-SYSTEM",
    "--add-opens java.base/java.util=ALL-UNNAMED",
    "--add-opens java.base/java.lang=ALL-UNNAMED",
  ];
```

Is there anything that I am missing?

**Comment by kaisalmen** [comment]
Hi @LavanyaBurlagadda 

> 1 - Getting suggestions lately

Does this mean it worked before and if so what did you change?
How is it related to this thread?

**Comment by rick-chou** [comment]
@kaisalmen Hi ~ Sorry for disturbing you, I tried integrating language Server with Monaco Editor and got this error 
<img width="676" alt="Screenshot 2023-07-06 at 14 10 21" src="https://github.com/TypeFox/monaco-languageclient/assets/56244178/7dc7b368-2e6c-4897-aa40-47ea8fea2cc0">


```
[
  '-Declipse.application=org.eclipse.jdt.ls.core.id1',
  '-Dosgi.bundles.defaultStartLevel=4',
  '-Declipse.product=org.eclipse.jdt.ls.core.product',
  '-Dlog.level=ALL',
  '-Xmx1G',
  '--add-modules=ALL-SYSTEM',
  '-jar',
  '/Users/rick.zhou/Desktop/monaco-languageclient/server/resource/jdt-language-server-1.9.0-202203031534/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar',
  '-configuration',
  '/Users/rick.zhou/Desktop/monaco-languageclient/server/resource/jdt-language-server-1.9.0-202203031534/config_mac',
  '-data',
  '/Users/rick.zhou/Desktop/monaco-languageclient/server/resource/data',
  '--add-opens',
  'java.base/java.util=ALL-UNNAMED',
  '--add-opens',
  'java.base/java.lang=ALL-UNNAMED'
]
```

`monaco-languageclient/packages/examples/main/src/common.ts`
```
const filePath =
        "/Users/rick.zhou/Desktop/monaco-languageclient/packages/examples/main/src/react/test.java";
const uri = Uri.parse(filePath);
const modelRef = await createModelReference(uri, config.content);
......
```
I don't know what you mean by `"option "rootUri"` in your reply,, where should I configure it ？
or am I missing something?
