### ISSUE TITLE
Don't send didChange notification for every single keystroke

### ISSUE THREAD

**Issue by spoenemann** [TypeFox/monaco-languageclient#3]
Currently the client sends `didChange` for every editor keystroke. This leads to bad performance in some scenarios. The client should gather multiple keystrokes and send a bulk notification after a customizable timeout. The default timeout could be something like 200 ms.

**Comment by akosyakov** [comment]
[MonacoWorkspace ](https://github.com/TypeFox/monaco-languageclient/blob/master/src/workspace.ts) could accept as an arg timeout to buffer events, it should be optional and should be possible to disable it
