### ISSUE TITLE
Is it possible to use the same Server for 2 scripts open in 2 tabs

### ISSUE THREAD

**Issue by ArunGanesh88** [TypeFox/monaco-languageclient#307]
Based on the example given, each time we open the script in a monaco editor in a browser a new server is started, is there a way to reuse the already started server.

**Comment by CGNonofr** [comment]
The language server protocol is stateful, there is a handshake at start, so the protocol wasn't really designed for this, so there is no trivial way.

This being said, you can still implement a kind of "proxy" which play the role of the client to the server, and the role of the server to the client.
It can keep the language server up, and just send the DidOpenTextDocument notif when a client arrives and the DidCloseTextDocument when a client leaves

**Comment by CGNonofr** [comment]
Oh I didn't read the title properly!

If you want 2 clients on the same server, I guess it's still possible using the same kind of proxy, you'll just need a "main" client responsible for the file update, and a specific logic for each server notifications/requests

**Comment by ArunGanesh88** [comment]
Thanks for the update @CGNonofr . is there any example code for creating the proxy?.

**Comment by CGNonofr** [comment]
I'm not aware of any implementation of it but I didn't search much.

Btw I'll probably have this need in the soon future so stay tuned.

**Comment by arunganesh-a** [comment]
Hi @CGNonofr  is there any update on this?

**Comment by CGNonofr** [comment]
I think you can give a try to https://github.com/CodinGame/languageserver-mutualized.

It can do a little more than what you need (it allows multiple clients to edit the same file).

Do not hesitate to provide some feedback

**Comment by arunganesh-a** [comment]
Hi @CGNonofr ,

This solves most of the problem. I have one clarification..
Things are working as expected when opening file from same workspace in 2 different editor or browser tabs.. but when we try to open another file form a different workspace language it doesn't work as expected. How to handle this scenario.

Thanks
Arun

**Comment by CGNonofr** [comment]
Please open an issue on the other repo and close your issue here, we'll not disturb this repo ;)

**Comment by arunganesh-a** [comment]
Actually, in the earlier approach where we open separate server for each browser tab this scenario was working. Now with new approach this is not working

**Comment by CGNonofr** [comment]
So you have an issue using the languageserver-mutualized lib right? Why doesn't creating an issue there seem relevant to you?

Btw I need some clarifications on
> we try to open another file form a different workspace language it doesn't work as expected

What is a "workspace language"? What doesn't work?

**Comment by arunganesh-a** [comment]
I am using Java Language Server, In this each maven project is a separate workspace. 

I have created a new issue in the other repo. We can track this in the [new issue](issue-1146534724)
