### ISSUE TITLE
how to combine with vue language server 

### ISSUE THREAD

**Issue by FoxDaxian** [TypeFox/monaco-languageclient#314]
sorry to disturb you.

I wanna write web editor for .vue file, but there are some trouble around me. 
I need implement syntax highlighting and auto complete, go to definition and so on by lsp, but nowhere hint me [vls](https://github.com/vuejs/vetur/blob/master/server/README.md) how to work with monaco-languageclient.
I fell grateful if anyone can hint me or give sone available demo~

**Comment by CGNonofr** [comment]
There is already a demo using a json language server in the repo

**Comment by FoxDaxian** [comment]
thanks your reply. @CGNonofr 

but json lsp is completely different with vls.
could you show me vls demo~

**Comment by iceprosurface** [comment]
Have same issue with volar under volar server condition.

I try following codes:

```
import * as rpc from "@codingame/monaco-jsonrpc";
import { createLanguageServer } from '@volar/server/out/common'
import { createConnection } from 'vscode-languageserver/node';
export function launch(socket: rpc.IWebSocket) {
    const reader = new rpc.WebSocketMessageReader(socket);
    const writer = new rpc.WebSocketMessageWriter(socket);
    const connection = createConnection(reader, writer);
    createLanguageServer(connection)
}
```

but got :

<img width="788" alt="image" src="https://user-images.githubusercontent.com/16058059/155089583-9a9a788c-0ef6-4db6-99fc-6eb510fd5056.png">

Maybe `vscode-languageserver@^8.0.0-next.6` is not match `vscode-jsonrpc@6.0.0` ?

**Comment by CGNonofr** [comment]
@iceprosurface it looks like the issue is in volar itself
