### ISSUE TITLE
Get everything going again

### ISSUE THREAD

**Issue by kaisalmen** [TypeFox/monaco-languageclient#315]
Hi there, my name is Kai Salmen and I work at TypeFox since Feb 2021. We have neglected this repository far too long we are committed to contribute here again (see https://github.com/TypeFox/monaco-languageclient/issues/313#issuecomment-1041232925). I will be the first one from TypeFox jumping in again. I have not been involved here before, so I have a learning curve and of course don't know everything, but I will get there. 🙂 

I already agreed (https://github.com/TypeFox/monaco-languageclient/issues/313#issuecomment-1041284246) with @CGNonofr to open this uncluttered the dust issue. Let's gather topics here what needs to be done and then we can open other issue when needed:

Already Completed:
- Add tags from @codingame releases ✅ 
- Get the release process working again to be able to release npm packages under https://www.npmjs.com/package/monaco-languageclient (#318) ✅ 
- Update CHANGELOG.md (#318) ✅ 
- Fix build issues on Windows (#318) ✅ 
- Switch default and protected branch from `master` to `main` branch ✅ 
- Issue #331 & PR #340):
  - Some tools/libraries are now quite old (typescript for instance) ✅ 
  - The build has unexpected problems (#321) ✅  
  - Do we really need lerna? The only thing being released is the client. Would it make sense to switch to npm workspaces (this options wasn't available in 2018, of course)? ✅ 
  - Verify build on every commit: Let's use GitHub Actions. ✅ 
  - What about one **examples** folder. Move the content from `./example` to a new sub dir in `./examples`. Having two directories is confusing. ✅ 
  - #337 ✅ 
  - Do we still need the Reconnecting web socket? (https://github.com/TypeFox/monaco-languageclient/issues/313#issuecomment-1041298931) ✅ 
  - We should keep a webpack example #346
  - A new monaco-editor version was released, we should check the compatibility ✅ (#329)

Updates / General topics / Ideas to be handled in separate issues:
- Introduce semantic release (see https://github.com/TypeFox/monaco-languageclient/issues/365)
- Add eslint configuration (see https://github.com/TypeFox/monaco-languageclient/issues/366)
- Improve code where easily possible
- Should we make [@codingame/monaco-jsonrpc](https://github.com/CodinGame/monaco-jsonrpc) or [vscode-ws-jsonrpc](https://github.com/TypeFox/vscode-ws-jsonrpc) a sub-package of this repo? (see https://github.com/TypeFox/monaco-languageclient/issues/367)
- The examples/browser is confusing people since it doesn't use the whole lib but only the converters (see https://github.com/TypeFox/monaco-languageclient/issues/368)

Anything else? Please update the list or leave a comment. Thanks.

**Comment by spoenemann** [comment]
> Add tags from `@CodinGame` releases

We need your help on this, @CGNonofr. Once we have the tags, either you or @kaisalmen can publish them to `monaco-languageclient` (you should both have publishing access now).

**Comment by CGNonofr** [comment]
done :heavy_check_mark: 

There is no v0.17.1 and v0.17.2 because there is no commit on the main branch for it, they were mistakes

**Comment by kaisalmen** [comment]
@CGNonofr I am currently reconstructing the CHANGELOG and was wondering if we should really re-release your @codingame npm release or if it makes sense to converge on a `0.18.0` and then move onward together? What is your opinion on that?

**Comment by CGNonofr** [comment]
I'm not sure to really see the point of releasing previous versions, but it's your choice, not mine

**Comment by kaisalmen** [comment]
> I'm not sure to really see the point of releasing previous versions, but it's your choice, not mine

Yes, of course. Just saw that you released `0.17.4`. It makes sense to release `0.17.3` as [monaco-languageclient)](https://www.npmjs.com/package/monaco-languageclient) to have the status quo and then release future versions on the main package again (like `0.17.4`, `0.17.5` or `0.18.0`)?

**Comment by CGNonofr** [comment]
I released a new version including the currently open MR. I'll let you decide

**Comment by kaisalmen** [comment]
Ok, I will to a "release test" with a "next" tag first, something like `0.17.4-next.0` and if there are errors or unexpected behaviour release a another next version.
If #317 depends on next monaco-editor release then a new version needs to take this into account.

**Comment by kaisalmen** [comment]
Ok, we will publish versions 0.14.0 up to 0.17.3, so there is nothing missing. Next new version should then be `0.17.4` including at least the PR 317 and we don't need to wait for next monaco-editor release. 👍 
The CHANGELOG should be updated before next release and explain why you needed to have release the npm packages under your namespace and why we released the range of versions later on block to prevent confusion (I started this on the branch referenced above). PR will come, but I can't promise it today. I will start with updating releases first later today.

**Comment by kaisalmen** [comment]
Versions have been released ✅ 
![image](https://user-images.githubusercontent.com/21079138/155339508-1dd69f65-f336-4bfe-a3d9-b4065fdbec37.png)

**Comment by kaisalmen** [comment]
@CGNonofr would you favor switching from yarn to npm with workspaces? Today, I would not start a new project with yarn. This strange problem we just observed gives some supportive argument to it as well.

**Comment by CGNonofr** [comment]
I'm not used to yarn at all, so I would personally use npm as well

**Comment by kaisalmen** [comment]
@CGNonofr I will release `0.17.4` later today.

I would like to start working towards a 0.18.0 release at the end of the week. Form the above list I see alignment with monaco 0.32.1 / 0.33.0 (should be there soon), fixing build issues (yarn -> npm workspaces), unify example structure as the most important. WDYT?

**Comment by CGNonofr** [comment]
I'm not sure about monaco 0.33 release soon, what do you mean by `alignment`?

Do you expect some help? I won't be really available in the next days

**Comment by kaisalmen** [comment]
> I'm not sure about monaco 0.33 release soon, what do you mean by alignment?

Haven't checked/analysed thorougly, yet, but there seem to be API incompatibilities with monaco 0.30.1+.

> Do you expect some help? I won't be really available in the next days

I won't be able to do real work before Friday. Don't have a release date in mind, yet, so there is no pressure. If you have time help is welcome. I propose to open a specific next release specific issue where we put the things we really want to do and then we can pick things (if there is time). Sounds good?

**Comment by CGNonofr** [comment]
> Haven't checked/analysed thorougly, yet, but there seem to be API incompatibilities with monaco 0.30.1+.

I'm scared because I'm already using it with monaco 0.32 on production, what are you talking about?

> I won't be able to do real work before Friday. Don't have a release date in mind, yet, so there is no pressure. If you have time help is welcome. I propose to open a specific next release specific issue where we put the things we really want to do and then we can pick things (if there is time). Sounds good?

yep :+1:

btw, my goal was always to keep this library usable with the last version of monaco because my company is using it. My employer is not ok with me investing too much time for refactor/structure. I'll do what I can but don't expect big stuff from me

**Comment by kaisalmen** [comment]
> I'm scared because I'm already using it with monaco 0.32 on production, what are you talking about?

Build broke if I remember correctly, but I haven't investigated, yet.

> refactor/structure. I'll do what I can but don't expect big stuff from me

I guess, I do the refactor/structure work, but need your reviews/ your opinion on things 🙂

**Comment by CGNonofr** [comment]
I just tried the 0.19.0-next.0 and everything seem to work (after the vscode-compatibility fix)

Good job :+1:

**Comment by kaisalmen** [comment]
We introduced version 1.0.0 and 1.0.1 lately. Many tasks from the list above have been completed. I will open new issues for the remaining things and then close this issue.
