### ISSUE TITLE
Sending configuration options

### ISSUE THREAD

**Issue by jtokoph** [TypeFox/monaco-languageclient#32]
Is there an example of sending configuration options to the language server? For example, I'd like to be able to send a list of plugin options to the python language server. In vscode, it uses the synchronize option to send vscode config values. How would I go about manually sending config values from the monaco-language client?

These are the options I want to be able to send: https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json#L19

**Comment by akosyakov** [comment]
@jtokoph The monaco-languageclient is abstracted away from VS code via services, e.g. `Workspace` service provides an access to configurations which are used by the language client.
https://github.com/TypeFox/vscode-languageserver-node/blob/9449b41d27e4ffb0d72c1f5a85c47d1beead6073/client/src/services.ts#L144-L163

By the default, the subset of the services is implemented to support the standalone editor. You have to subclass `MonacoWorkspace` and provide support for configurations.
https://github.com/TypeFox/monaco-languageclient/blob/b901301fe10c7a51e3b6faa35863bb69c93fcd11/src/workspace.ts#L11

**Comment by akosyakov** [comment]
We could also pass an instance of `Configurations` to `MonacoWorkspace` via options (depends on https://github.com/TypeFox/monaco-languageclient/issues/31). And provide the default `InMemoryConfigurations` implementation.

**Comment by akosyakov** [comment]
PRs are welcomed. @jtokoph feel free to look into it

**Comment by cdietrich** [comment]
#31 is done now

**Comment by SamVerschueren** [comment]
I managed to get this working by implementing my own configuration class.

```ts
class WorkspaceConfiguration {
	constructor(
		config: any
	) {
		for (const key of Object.keys(config || {})) {
			this[key] = config[key];
		}
	}

	get<T>(section: string, defaultValue?: T) {
		console.log(this);
		return this[section] || defaultValue;
	}
}


class Configuration {
	private onConfigChanged: Function = () => {};

	getConfiguration(section?: string) {
		return new WorkspaceConfiguration(this[section]);
	}

	update(section: string, value: any, configurationTarget?: any) {
		this[section] = value;

		this.onConfigChanged();
	}

	onDidChangeConfiguration(cb: Function) {
		this.onConfigChanged = cb;
	}
}
```

After that, you can set the `workspace.configurations` object.

```ts
const config = new Configuration();

// create and start the language client
const languageClient = createLanguageClient(connection);
(languageClient.workspace as any).configurations = config;

config.update('pyls', {
	plugins: {
		pydocstyle: {
			enabled: false
		}
	}
});
```

If I find some time, I can do a PR.

**Comment by akosyakov** [comment]
@SamVerschueren feel free to open the PR
