### ISSUE TITLE
Cannot build exaple

### ISSUE THREAD

**Issue by john-schmitz** [TypeFox/monaco-languageclient#321]
From a fresh clonned when attempting to build the nodejs example I get:

```yarn && yarn prepare
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
warning monaco-languageclient@0.17.3: The engine "vscode" appears to be invalid.
warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
[3/4] Linking dependencies...
warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.3" has unmet peer dependency "@octokit/core@>=3".
warning "workspace-aggregator-0e515c18-a138-4628-afb7-bb719063b036 > node-example > file-loader@4.3.0" has incorrect peer dependency "webpack@^4.0.0".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
$ yarn run clean && yarn run build
yarn run v1.22.17
$ rimraf lib
Done in 0.05s.
yarn run v1.22.17
$ yarn run compile && webpack && yarn run copy
$ tsc
src/client.ts:10:8 - error TS2307: Cannot find module 'monaco-languageclient' or its corresponding type declarations.

10 } from 'monaco-languageclient';
          ~~~~~~~~~~~~~~~~~~~~~~~

src/client.ts:66:19 - error TS7006: Parameter 'errorHandler' implicitly has an 'any' type.

66             get: (errorHandler, closeHandler) => {
                     ~~~~~~~~~~~~

src/client.ts:66:33 - error TS7006: Parameter 'closeHandler' implicitly has an 'any' type.

66             get: (errorHandler, closeHandler) => {
                                   ~~~~~~~~~~~~


Found 3 errors
```

Did I miss any steps? How can I help you diagnosticate the issue

Any help would be appreciated

**Comment by kaisalmen** [comment]
Hi @john-schmitz  you have to run `yarn install` once on top level of the project on a fresh checkout. I can reproduce your problem if I don't do this. Once you do, the problem above disappears.

**Comment by CGNonofr** [comment]
I'm not familiar of yarn, but doesn't it mean the yarn.lock is broken?

**Comment by kaisalmen** [comment]
Good point. Something seems fishy here. I deleted the lock file and then did `yarn install` again and it had many more changes. I will push a new branch and open a PR once I am certain it works as expected.

**Comment by kaisalmen** [comment]
@CGNonofr  with PR #318 **@codingame/monaco-languageclient@^0.17.0** was removed from `yarn.lock` and it was **not** replaced by **monaco-languageclient@^0.17.3** what seems not logic, because the dependency is defined in both `example` and `examples/browser`. Even after manually removing the lock file and performing install in the project's root or the example it does not come back.!? 🤷‍♂️

**Comment by kaisalmen** [comment]
The workaround mentioned [above](https://github.com/TypeFox/monaco-languageclient/issues/321#issuecomment-1057699380) applies. I guess the build and dependency management needs some love (see #315).

**Comment by CGNonofr** [comment]
Since it's a yarn workspace, I don't think you should run yarn anywhere else than in the root (it's the case with npm workspace at least)

**Comment by kaisalmen** [comment]
Yes, I only did to see if I can provoke an effect. True, with npm workspace you should only install in the root, but there the installation of child dependencies works. The yarn issue must have some to do with self referencing the repo here

**Comment by john-schmitz** [comment]
Thanks everyone! I was able to run the example correctly!
