### ISSUE TITLE
Integrate latest monaco-languageclient with angular13

### ISSUE THREAD

**Issue by bguo3** [TypeFox/monaco-languageclient#323]
Hi, I am trying to integrate the latest monaco-languageclient("^0.17.3") with angular13. [My code](https://github.com/bguo3/Angular-Monaco-Editor).
When run ng build, the error as below:
 ⠹ Generating browser application bundles (phase: setup)... ./src/main.ts:4:0-45 - Error: Module not found: Error: Can't resolve './app/app.module' in 'C:\Work\WebProject\DSL\Angular-Monaco-Editor\src'

./src/main.ts:5:0-57 - Error: Module not found: Error: Can't resolve './environments/environment' in 'C:\Work\WebProject\DSL\Angular-Monaco-Editor\src'

Please help, thanks!

Or can you provide a sample code of integrating the latest monaco-languageclient("^0.17.3") with angular?

**Comment by CGNonofr** [comment]
Hello,

Your issue doesn't seem to be related to this library at all, feel free to ask some help on stackoverflow or any other platform providing help for developpers
