### ISSUE TITLE
Update example: monaco-languageclient doesn't export MessageConnection

### ISSUE THREAD

**Issue by dkattan** [TypeFox/monaco-languageclient#324]
The example here shows MessageConnection being imported from monaco-languageclient, but it isn't actually exported from there
https://github.com/TypeFox/monaco-languageclient/blob/42ecd6417473dfd7153ced741e03b873533c0930/example/src/client.ts#L7-L10

It appears to actually be exported by @codingame/monaco-jsonrpc or vscode-jsonrpc which we should probably merge or include in this repo.

**Comment by CGNonofr** [comment]
It seems it's imported via `index.ts` => `services.ts` (`export * from 'vscode-languageserver-protocol/lib/common/api'`) => `api.d.ts` (`export * from 'vscode-jsonrpc'`)

**Comment by dkattan** [comment]
I went to repro it this morning and wouldn't you know it works as expected. It appears to have been a caching issue with Vetur. My apologies. It is working fine now.
