### ISSUE TITLE
Update rootUri

### ISSUE THREAD

**Issue by mpociot** [TypeFox/monaco-languageclient#326]
Hi!

I am successfully starting an existing language client / websocket connection and everything works as expected.
I now want to add the ability to update the root URI, as if the user is changing the project path.
So far I've tried disposing the monaco service and install it again, but that does not trigger the initialization message, which I think is the necessary missing piece.

Can anybody help me on how I can change the root uri while the language client is active?

Thank you!

**Comment by CGNonofr** [comment]
Hello

I'm pretty sure the protocol doesn't support such thing, you'll need to stop the server and restart it.

That being said, you can probably rely on the workspaceFolders feature if your server supports it

**Comment by mpociot** [comment]
Hm but this shouldn't really have anything to do with the server, right?
I basically want to stop the current websocket connection from the client to the server, and re-initialize it with the new rootUri.
As far as I understand it, the server can just be kept alive.

I assume that I only need to somehow trigger the initialize command again, but I don't know how.

**Comment by CGNonofr** [comment]
I don't know which server you are using but most implementations don't support sending the initialize request a second time.

Why don't you just restart it?

**Comment by mpociot** [comment]
What exactly do you mean with "restart it"?

The thing I don't understand is, how can I install the language client service a second time using a different root uri?

I'm calling:

```
MonacoServices.install(monaco, {
    rootUri,
});
```

And at some later point, I basically want to re-initialize the language client using a new rootUri. I'm fine with restarting websocket servers/connections, but I'd like to avoid having to recreate the entire monaco instance if possible

**Comment by CGNonofr** [comment]
`MonacoServices.install` returns a Disposable, you can dispose it and execute MonacoServices.install a second time

**Comment by mpociot** [comment]
Thank you very much! That - in combination with closing the previous websocket connection did the trick! :)
