### ISSUE TITLE
Why is self used here?

### ISSUE THREAD

**Issue by MassMessage** [TypeFox/monaco-languageclient#328]
I'm trying to integrate monaco editor in my react application. The compiler complains about:

```
(self as any).MonacoEnvironment = {
    getWorkerUrl: () => './editor.worker.bundle.js'
}

```

giving the error:

`Unexpected use of 'self'  no-restricted-globals`

Why is self used here? where is it defined? visual code didn't find any reference. [Searching on the repo](https://github.com/TypeFox/monaco-languageclient/search?q=self)  I didn't get any definition either. Can I just get rid of it? maybe replace by window variable or nothing at all and just use:

```
MonacoEnvironment = {
    getWorkerUrl: () => './editor.worker.bundle.js'
}
```

**Comment by MassMessage** [comment]
> I think this is more related to monaco-editor than this library.
I think you're right, wrong place then. Sorry!
 
> You can replace it by `window`
is this totally safe then? any idea why self was used here?

**Comment by CGNonofr** [comment]
`self` or `global` may exist depending on the bundler, no big deal, that's the same thing. I think it exists for library where the window object doesn't exist

**Comment by MassMessage** [comment]
> `self` or `global` may exist depending on the bundler, no big deal, that's the same thing. I think it exists for library where the window object doesn't exist

I see, thanks!
