### ISSUE TITLE
Module not found: Can't resolve 'vscode'

### ISSUE THREAD

**Issue by MassMessage** [TypeFox/monaco-languageclient#334]
I have a alias like this in my webpack:
```javascript
  resolve: {
    alias: {
      '@Shared': path.resolve(__dirname, 'src/shared'),
      'vscode': require.resolve('@codingame/monaco-languageclient/lib/vscode-compatibility')
    }
}
```

however, when i went to build, the library that uses vscode, return the error:
```
./node_modules/vscode-languageclient/lib/common/client.js
Module not found: Can't resolve 'vscode' in 'C:\Users\jck\Desktop\merge\Newton\node_modules\vscode-languageclient\lib\common'
i'
```

How can I solve this?

**Comment by CGNonofr** [comment]
There is probably something wrong with your configuration, can you please provide a simple way to reproduce?

**Comment by MassMessage** [comment]
> There is probably something wrong with your configuration, can you please provide a simple way to reproduce?

check out [this ](https://github.com/MassMessage/vscodefailure)I managed to make a small simple, it contains both webpack settings files, package.json, etc all as in the original project and reproduce the same error

**Comment by CGNonofr** [comment]
I'm unable to do anything with this repo

There is an error: `node: bad option: --openssl-legacy-provider`

If I remove this option, there is a new error: `Error: Cannot find module '<>/vscodefailure/config-overrides'`

What am I supposed to run?

**Comment by MassMessage** [comment]
> I'm unable to do anything with this repo
> 
> _There is an error: `node: bad option: --openssl-legacy-provider`_ **edit**: is was due to my version of node
> 
> If I remove this option, there is a new error: `Error: Cannot find module '<>/vscodefailure/config-overrides'`
> 
> What am I supposed to run?

How have you tried to run that? I didn't use this config explictily.  Also I forgot to tell how build webpack. Try build and run like this:

```
yarn # to install the packages
yarn make # to build the web pack
```

then to run it:

`yarn run dev`

**Comment by CGNonofr** [comment]
I think it's more related to react-scripts than this library

btw, you using VERY old versions of almost everything so it's difficult to debug

**Comment by MassMessage** [comment]
> I think it's more related to react-scripts than this library

did you managed to reproduce this error?

> btw, you using VERY old versions of almost everything so it's difficult to debug

i did update but i got tons of errors so i went back and stick to what worked in the [code sample](https://github.com/TypeFox/monaco-languageclient/tree/master/example) used to setup monaco editor

**Comment by CGNonofr** [comment]
> did you managed to reproduce this error?

yes

> i did update but i got tons of errors so i went back and stick to what worked in the [code sample](https://github.com/TypeFox/monaco-languageclient/tree/master/example) used to setup monaco editor

I think the demo is up to date, isn't it?

**Comment by MassMessage** [comment]
> > did you managed to reproduce this error?
> 
> yes
> 
> > i did update but i got tons of errors so i went back and stick to what worked in the [code sample](https://github.com/TypeFox/monaco-languageclient/tree/master/example) used to setup monaco editor
> 
> I think the demo is up to date, isn't it?

it used some old libraries, i thoughut it was the ones you were talking about being old...  Aren't about those?

**Comment by MassMessage** [comment]
I think it was some issue with react-scripts, I don't know.. I just switch to use electron-forge build system and the error went away

**Comment by danimasa** [comment]
I'm using electron-forge and having the same error:
```
Module not found: Error: Can't resolve 'vscode' in '...\node_modules\vscode-languageclient\lib\common'
```
Do I need to change webpack configuration to resolve 'vscode' package?

**Comment by kaisalmen** [comment]
@danimasa have you added vscode to your `package.json` like this?
https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/package.json#L67
