### ISSUE TITLE
Is there a way to connect to the lsp via HTTP?

### ISSUE THREAD

**Issue by john-schmitz** [TypeFox/monaco-languageclient#335]
Inside the examples folder, I saw this function:
```ts
function createUrl(path: string): string {
    const protocol = location.protocol === 'https:' ? 'wss' : 'ws';
    return normalizeUrl(`${protocol}://${location.host}${location.pathname}${path}`);
}
```
It made me wonder, is there a way to connect to the lsp via HTTP?

**Comment by CGNonofr** [comment]
We need to be able to send messages from both client and server, so the most appropriate protocol is websocket.

I guess it's doable via long-polling or any other hack, your better chance is through socket.io or sockjs

What is your use-case?

**Comment by john-schmitz** [comment]
> What is your use-case?

Honestly I'm trying to limit the number of requests the editor can make to the LSP.

Or if possible supply a "stateless" way of analyzing, supplying completions, definitions, etc.
That way I could supply different  HTTP endpoints for each of those operations.
And throttle myself the requests via the HTTP layer.

I Know this is very hacky, but I'm trying to be the most efficient regarding messages being passed around the connection.

**Comment by CGNonofr** [comment]
The language server protocol was designed stateful

> Honestly I'm trying to limit the number of requests the editor can make to the LSP.
why?

> Or if possible supply a "stateless" way of analyzing, supplying completions, definitions, etc.
I don't know your use case but you can probably have a look at LSIF
