### ISSUE TITLE
Multiple Workspace Folder

### ISSUE THREAD

**Issue by arunganesh-a** [TypeFox/monaco-languageclient#339]
Hi,

Need help to understand how to pass multiple workspace folder, when initialising monaco language client.

Thanks

**Comment by CGNonofr** [comment]
Hi,

You need to have your custom implementation of `Workspace`/`MonacoWorkspace` and define a `workspaceFolders` field

**Comment by arunganesh-a** [comment]
Is there any example available for creating custom implementation of Workspace/MonacoWorkspace

**Comment by CGNonofr** [comment]
I don't think so but it's not hard, just extends `MonacoWorkspace` and use `Services.install` instead of `MonacoServices.install` to be be able to use your custom implementation

the best documentation is the code itself

**Comment by CGNonofr** [comment]
Didn't I just do it?

Replace the call to [MonacoServices.install](https://github.com/TypeFox/monaco-languageclient/blob/59730ee526400db4fdea9ec0bed7b6a9b370af12/client/src/monaco-services.ts#L34) by the content of it so you can change the workspace service implementation by your own
