### ISSUE TITLE
How to configure the language server through the client ? 

### ISSUE THREAD

**Issue by PedroCristovao-Movai** [TypeFox/monaco-languageclient#341]

**Comment by PedroCristovao-Movai** [comment]
I want to be able to configure pyflakes, flake8, pycodestyle through MonacoLanguageClient, like #32 #201. But couldn't understand the responses there. So made a new question here. thanks in advance

**Comment by PedroCristovao-Movai** [comment]
I would like to add a configuration `builtins` to `flake8` in [python-lsp](https://github.com/python-lsp/python-lsp-server)

**Comment by kaisalmen** [comment]
@PedroCristovao-Movai I am closing the issue. If there are further questions please open a discussion: https://github.com/TypeFox/monaco-languageclient/discussions

Thank you
