### ISSUE TITLE
how to connect to vls?

### ISSUE THREAD

**Issue by FoxDaxian** [TypeFox/monaco-languageclient#347]
here is the question [repo](https://github.com/FoxDaxian/lsp-adventure). please check it.
thank you very much~

**Comment by CGNonofr** [comment]
Hello,

What is your question?

**Comment by FoxDaxian** [comment]
@CGNonofr Hi~  thank your for your reply.

the question is TextDocument/didopen. TextDocuemt/hover etc not work when server run success in abover repo.

and I don't know how to fix this..

**Comment by CGNonofr** [comment]
There is a working example here.

If you want some help, please ask more specific questions

**Comment by FoxDaxian** [comment]
sorry. I will rephrase my problem。

I create an client and use **vscode-ws-jsonrpc** to connect server.
and use vscode-ws-jsonrpc to forward an vls subProcess in the server. in order to communicate with client.

now both them can be run and rpc message is success passed:

![image](https://user-images.githubusercontent.com/19708789/163971437-92c8a46e-b0da-4589-94c1-997fdadae00e.png)

but the monaco-editor is not do what I expect. I don't know how to handle this situation.

so please take a look [this repo](https://github.com/FoxDaxian/lsp-adventure), it will show my question.

thanks again 😊

**Comment by kaisalmen** [comment]
@FoxDaxian I am closing the issue. If there are further questions please open a discussion: https://github.com/TypeFox/monaco-languageclient/discussions

Thank you
