### ISSUE TITLE
Markdown hint code block syntax highlighting with language-server request

### ISSUE THREAD

**Issue by BusinessDuck** [TypeFox/monaco-languageclient#355]
### Markdown hover popup with code block, using custom language cannot tokenize and colorize tokens at code block section in rendered markdown.

**Expected behavior**: Language Server should receive tokenization request  from monaco editor, when markdown rendered code block language is same as server knows.

**Debug Details**:

Versions:    *"monaco-editor-core": "0.33.0"* and *monaco-languageclient": "0.18.1"*

![image](https://user-images.githubusercontent.com/10143411/169567606-4885632f-dbe3-438f-92be-58b21b939da1.png)

Hover markdown text:

```
```myLanguage
  (function) myLanguageFunctionSum(a, b) => number
```

All document syntax working fine, but markdown hover constructor does not request request anything from server tokenizer. 
Language id's are same between main document model and markdown popup and configured correctly.

I found some strange place in monaco editor markdown renderer see below

![image](https://user-images.githubusercontent.com/10143411/169568567-82d03837-22a6-4014-bd35-32f8690c6b3c.png)

Looks like `TokenizationRegistry` does not contains any registered languages for tokenizations, but why?

![image](https://user-images.githubusercontent.com/10143411/169568855-e832d582-7588-4c89-bc84-1b68a6064653.png)

`yield TokenizationRegistry.getOrCreate(languageId);` returns `false`

**Comment by CGNonofr** [comment]
> Language Server should receive tokenization request from monaco editor

The language server is not responsible for the syntax highlighting, what is a `server tokenizer`?

**Comment by BusinessDuck** [comment]
I mean `textDocument/semanticTokens/full` request, with custiom document `uri` from markdown popup. Server response with tokens. Then client should use it for highlight and rendering token is available from ServerCapabilities `TokenTypes` array on the client.

**Comment by CGNonofr** [comment]
Are you sure it's supposed to work this way? what would be the document uri?

Code in markdown are only code parts, I don't know how the server would be able to compute semantic tokens on it

Does it work that way in vscode?

**Comment by BusinessDuck** [comment]
We can see rendered markdown code for typescript language in vscode markdown block, idk how it works actually.

![image](https://user-images.githubusercontent.com/10143411/169572488-d44250ea-66b7-4e27-a23f-f774bf9fbe98.png)

Monaco editor uses his own default languages providers for rendering markdown blocks. Monaco Language Client overrides default providers by language server semantic provider that mean last one should be used for any language construction including for markdown code block with that language. Just my mind. I Not sure actually that should works at this way.

**Comment by BusinessDuck** [comment]
This may be be usefull, looks like something same in vscode behavior  https://github.com/microsoft/vscode/issues/11331

**Comment by CGNonofr** [comment]
I'm pretty sure the language server is not used to render markdown code block, even in vscode.

VSCode just use Textmate (instead of monarch for monaco) for the syntax highlighting and use is as well in markdown rendering.

**Comment by BusinessDuck** [comment]
Yes VSCode use TMGrammar =( https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example. 
I dont understand why same languages are using different sources of truth. Markdown block using TMGrammar, main document model using LSP :)

**Comment by CGNonofr** [comment]
> main document model using LSP

It's not the case, even the main document is using the TM grammar, the LSP just provides additional semantic tokenization and it's not mandatory.

**Comment by BusinessDuck** [comment]
I have full LSP tokenization, because i don't want to use editor API, because editor client may be changed from monaco to codemirror in any time. But one possible current solution looks like  register a client semantic tokens provider which use monaco API.

```typescript
monaco.languages.registerDocumentSemanticTokensProvider('myCustomLanguage', {
	getLegend: () => {
		return {
			tokenModifiers: [],
			tokenTypes: [
				'keyword',
			],
		};
	},

	provideDocumentSemanticTokens: () => {
		return {
			data: [
				0, 0, 4, 0, 0,
			],
		};
	},

	releaseDocumentSemanticTokens: () => {
	},
});

// install Monaco language client services
MonacoServices.install(monaco);
```

**Comment by CGNonofr** [comment]
Now that everything is clear, can this issue be closed?
