### ISSUE TITLE
Lots of codeAction requests on initialize

### ISSUE THREAD

**Issue by gatesn** [TypeFox/monaco-languageclient#36]
When starting a language client that supports code actions, for some reason 17 identical codeAction requests are sent to the server.

Will dig deeper into this, but wanted to file an issue in case others stumble across it.

**Comment by rcjsuen** [comment]
Can this bug be reproduced with the regular example? I can't seem to reproduce it but maybe I'm putting print statements in the wrong places?

**Comment by akosyakov** [comment]
@gatesn I close it, please reopen if it still relevant
