### ISSUE TITLE
Should we make @codingame/monaco-jsonrpc or vscode-ws-jsonrpc a sub-package of this repo?

### ISSUE THREAD

**Issue by kaisalmen** [TypeFox/monaco-languageclient#367]
This is an idea from https://github.com/TypeFox/monaco-languageclient/issues/315

The bespoke npm package could become a sub-package of this repository and separately released.

**Comment by CGNonofr** [comment]
I agree :+1:

**Comment by kaisalmen** [comment]
I am currently working on this...

**Comment by kaisalmen** [comment]
dev version is now available:
https://www.npmjs.com/package/vscode-ws-jsonrpc/v/0.5.0-dev.0
