### ISSUE TITLE
Support esm module as compiler target?

### ISSUE THREAD

**Issue by kaisalmen** [TypeFox/monaco-languageclient#369]
Currently it is not possible to build the library as ESM module.
Should we update the code / swtich to TypeScript 4.7?

If we think about this does make sense to rethink the vsode-compatibility approach along as proposed [here](https://github.com/TypeFox/monaco-languageclient/discussions/343#discussioncomment-2532003) by @CGNonofr?

**Comment by CGNonofr** [comment]
Actually, I'm already investigating this approach!

**Comment by CGNonofr** [comment]
Everything seems to work with the new approach :tada:. There will be a new package, the new package will include esm/cjs/amd

The PRs will be there is a few days

**Comment by CGNonofr** [comment]
=> https://github.com/TypeFox/monaco-languageclient/pull/373

**Comment by kaisalmen** [comment]
#373 has been merged
