### ISSUE TITLE
Question: multiple editors per language client now createMonacoServices takes an editor instance

### ISSUE THREAD

**Issue by richardmward** [TypeFox/monaco-languageclient#37]
Hi,

I have been using the monaco-languageclient library for a while, with my implementation based on the example in this project. Previously `createMonacoServices` did not take any arguments, but now it takes a single `editor` parameter. My (probably incorrect!) understanding of this call was to bind the language server protocols onto the monaco event handlers and vice-versa, and this was for the `monaco` instance as a whole, rather than to a specific editor.

Does this change mean that I would need to make a `BaseLanguageClient` for every editor instance I have open? (I have a multi editor interface, not dissimilar - but substantially more basic - than that of the `theia-ide`.) It seems odd that that would be the case - but then, I could easily have misunderstood something.

Many thanks in advance

**Comment by akosyakov** [comment]
Hi @richardmward!

> I have been using the monaco-languageclient library for a while

if you find it useful please star the repo :)

> Does this change mean that I would need to make a BaseLanguageClient for every editor instance I have open?

No, usually one per a language server for all editors. As for now, in the special scenario as yours, I won't use `creatMonacoServices` but create services myself. 

An idea was that default services created by `creatMonacoServices` are used in the case of the single standalone editor, not with multiple editors. We can discuss it and provide alternative signatures, i.e.:
```ts
export function createMonacoServices(options?: MonacoServicesOptions): BaseLanguageClient.IServices;
export function createMonacoServices(editor: monaco.editor.IStandaloneCodeEditor, options?: MonacoServicesOptions): BaseLanguageClient.IServices;
```

If you look at the code:
https://github.com/TypeFox/monaco-languageclient/blob/7a2963e7b808d42b50cee5225b32c712a2c134d2/src/services.ts#L12-L21
You can see that the editor is used only for commands at the moment and if you don't care about registering commands provided by language servers then you can pass any instance. We could look whether it is possible to implement commands service capable to register commands for all editors and use it if the editor is not provided. Do you want to look into it?

**Comment by richardmward** [comment]
Many thanks for the info - and star added!

At this time I am not registering any commands, so that isn't a concern. That said, I will be looking to start using the `codeAction` functionality in the future - will that require the commands service to be able to cope with multiple editors?

**Comment by akosyakov** [comment]
@richardmward yes, if your server provides commands
