### ISSUE TITLE
Monaco editor core compatibility

### ISSUE THREAD

**Issue by BusinessDuck** [TypeFox/monaco-languageclient#371]
**The problem:**

`import type * as monaco from 'monaco-editor/esm/vs/editor/editor.api';` cause error in typescript project with `monaco-editor-core` package only. 

**Hack solution:**

*tsconfig.json*
```typescript
"paths": {
    "monaco-editor/*": ["../node_modules/monaco-editor-core/*"]
}
```

Would you like to use `monaco-editor` package as peer-dependency? 
Also `monaco-editor` depends from `monaco-editor-core`, may be make a sense change types import to core?

**Comment by CGNonofr** [comment]
> import type * as monaco from 'monaco-editor/esm/vs/editor/editor.api'; cause error in typescript project with monaco-editor-core package only.

That's weird because this code shouldn't be in the output javascript

> Also monaco-editor depends from monaco-editor-core, may be make a sense change types import to core?

monaco-editor-core is not a dependency of monaco-editor, it's just there during the build and everything is duplicated/built from it, so it's not possible

**Comment by kaisalmen** [comment]
> It's error from typing d.ts files. monaco-editor-core or monaco-editor should be a devDependency

Thank you, this devDependency was never stated in the package.json of the lib (core or not), so at least I wasn't aware there was an impact beyond the examples.

**Comment by kaisalmen** [comment]
Do you use the `vscode` alias as shown here?
https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/client/webpack.config.js#L30-32

**Comment by kaisalmen** [comment]
@BusinessDuck due to the latest changes with v2.0.0+ we have a direct dependency to `monaco-editor`. See npm list output with depth 2:
```
└─┬ monaco-languageclient@2.0.2 -> .\packages\client
  ├── @types/glob-to-regexp@0.4.1
  ├── @types/node@16.11.7
  ├── @types/vscode@1.68.0
  ├── glob-to-regexp@0.4.1
  ├── vscode-jsonrpc@8.0.1
  ├─┬ vscode-languageclient@8.0.1
  │ ├── minimatch@3.1.2
  │ ├── semver@7.3.7
  │ └── vscode-languageserver-protocol@3.17.1
  ├── vscode-languageserver-textdocument@1.0.5
  ├── vscode-uri@3.0.3
  └─┬ vscode@npm:@codingame/monaco-vscode-api@1.68.4
    └── monaco-editor@0.33.0
```
We will add a workaround section to the README to make the problem visible to people, but we recommend to use `monaco-editor` and selectively import what is required.

**Comment by kaisalmen** [comment]
We have added a new Troubleshooting section in the README that also provides help regarding **monaco-editor-core**.

**Comment by amardeep911** [comment]
I tried changing tsconfig.json, still it showing error. 
![Screenshot 2024-05-04 at 4 08 54 PM](https://github.com/TypeFox/monaco-languageclient/assets/97588898/7c79f6d0-e291-423a-8001-9069b2f30e57)

**Comment by kaisalmen** [comment]
Hi @amardeep911 this is outdated, please look [here](https://github.com/TypeFox/monaco-languageclient/tree/main/packages/client#new-with-v8-use-monaco-vscode-editor-api-package-instead-of-monaco-editor) and take a look at the examples described [here](https://github.com/TypeFox/monaco-languageclient/blob/main/README.md#examples-overview).
