### ISSUE TITLE
Add export for monaco converter

### ISSUE THREAD

**Issue by char0n** [TypeFox/monaco-languageclient#375]
In 1.x releases we're no longer to be able to do following:

```
import { ProtocolToMonacoConverter } from 'monaco-languageclient/lib/monaco-converter.js';
```

Would it be possible to add new field to exports?

```json
  "exports": {
    ".": {
      "types": "./lib/index.d.ts",
      "default": "./lib/index.js"
    },
    "./monaco-converter": {
      "types": "./lib/monaco-converter.d.ts",
      "default": "./lib/monaco-converter.js"
    },    
    "./amd": {
      "types": "./dist/amd/index.d.ts",
      "default": "./dist/amd/index.js"
    },
    "./vscode-compatibility": {
      "types": "./lib/vscode-compatibility.d.ts",
      "default": "./lib/vscode-compatibility.js"
    },
    "./amd/vscode-compatibility": {
      "types": "./dist/amd/vscode-compatibility.d.ts",
      "default": "./dist/amd/vscode-compatibility.js"
    }
  },
```

We only need converter part and and only pull converter necessary files from the library.

**Comment by kaisalmen** [comment]
Hi @char0n you can do just this:
```javascript
import { ProtocolToMonacoConverter } from 'monaco-languageclient';
```

**Comment by kaisalmen** [comment]
But the they were in CommonJS format before 1.x. The package still contains the file at same location. How to you build your application?

**Comment by char0n** [comment]
@kaisalmen in 1.x.y you've introduce `exports` field in `package.json`. This makes custom imports impossible in Node.js and bundlers like Webpack@5 as  both Node.js and Webpack@5  respects the spec that defines behavior of `exports`. 

Basically anything that is not exported with `exports`, nobody it able to use it anymore.

**Comment by kaisalmen** [comment]
Do you make use of the `vscode` / `vscode-compatibility` alias? 
https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/client/webpack.config.js#L30-32

**Comment by char0n** [comment]
@kaisalmen nope, as `monaco-converter.js` or anything that it imports doesn't need `vscode` alias to be set.

**Comment by kaisalmen** [comment]
Yes, I know, but you would not get the full vscode dependencies as a workaround. I wasn't aware that:
```json
    ".": {
      "types": "./lib/index.d.ts",
      "default": "./lib/index.js"
    },
```
prevents you use case.

**Comment by kaisalmen** [comment]
Yes, we can expose the protocol converters directly. May be there is a better way. I have to see. Can you configure Webpack to be more relaxed? The files are there

**Comment by kaisalmen** [comment]
You can define an alias instruction that links @monaco-converter to some local path as workround. Couldn't you?

**Comment by char0n** [comment]
> You could define an alias instruction that links @monaco-converter to some local path as workaround, couldn't you?

You can, but you will get to the same error as you eventually have to do `require('monaco-languageclient/lib/monaco-converter.js');`

**Comment by char0n** [comment]
> You can give a direct node_moduls location on the file system. The it will take this during bundling. Did that before. There must be a way.

Yep, I tried that, but constraints of Create React App prevent to do this. This can be disabled by ejection but I want the bundle process to work without any overrides. 

> We will release a new version the upcoming days and fix this, but it will likely not happen today.

We'll wait. I can even issue a PR if that will help.

**Comment by char0n** [comment]
PR issued: https://github.com/TypeFox/monaco-languageclient/pull/376

Resulting imports will look as follows:

```js
import { ProtocolToMonacoConverter as a } from 'monaco-languageclient/monaco-converter';
import { ProtocolToMonacoConverter as b } from 'monaco-languageclient/amd/monaco-converter';
```

**Comment by CGNonofr** [comment]
Btw, I removed these files in https://github.com/TypeFox/monaco-languageclient/pull/373, should we keep them?

**Comment by kaisalmen** [comment]
See my idea: https://github.com/TypeFox/monaco-languageclient/pull/373#issuecomment-1149834766

**Comment by kaisalmen** [comment]
New release is out. Your fix is in, see updated [CHANGELOG](https://github.com/TypeFox/monaco-languageclient/blob/main/CHANGELOG.md)
https://www.npmjs.com/package/monaco-languageclient/v/1.1.0

**Comment by char0n** [comment]
@kaisalmen I can confirm that v1.1.0 works like a charm. Thanks for quick response!
