### ISSUE TITLE
vscode-compatibility issue webpack 5, Angular 12 , Language Client Version 1.1.0

### ISSUE THREAD

**Issue by tyagirajat200** [TypeFox/monaco-languageclient#377]
.An unhandled exception occurred: Package subpath './lib/vscode-compatibility' is not defined by "exports" in C:\Users\tyagi\Desktop\Codejudge Repos\judgepad\node_modules\monaco-languageclient\package.json

**Comment by CGNonofr** [comment]
Hello to you too!

How is your day?

`vscode-compatibility` was moved to `monaco-languageclient/scode-compatibility`

Have a very nice day!

**Comment by tyagirajat200** [comment]
Thanks, It is working.
But now I am getting below errors.
Error: node_modules/vscode-languageserver-protocol/lib/common/protocol.diagnostic.d.ts:159:10 - error TS1336: An index signature parameter type cannot be a type alias. Consider writing '[uri: string]: FullDocumentDiagnosticReport | UnchangedDocumentDiagnosticReport' instead.

159         [uri: DocumentUri]: FullDocumentDiagnosticReport | UnchangedDocumentDiagnosticReport;
             ~~~


Error: node_modules/vscode-languageserver-protocol/lib/common/protocol.diagnostic.d.ts:198:10 - error TS1336: An index signature parameter type cannot be a type alias. Consider writing '[uri: string]: FullDocumentDiagnosticReport | UnchangedDocumentDiagnosticReport' instead.

198         [uri: DocumentUri]: FullDocumentDiagnosticReport | UnchangedDocumentDiagnosticReport;
             ~~~


Error: node_modules/vscode-languageserver-protocol/lib/common/protocol.diagnostic.d.ts:218:10 - error TS1336: An index signature parameter type cannot be a type alias. Consider writing '[uri: string]: FullDocumentDiagnosticReport | UnchangedDocumentDiagnosticReport' instead.
iting '[uri: string]: TextEdit[]' instead.

887         [uri: DocumentUri]: TextEdit[];
             ~~~

Error: node_modules/vscode-languageserver-types/lib/umd/main.d.ts:911:10 - error TS1336: An index signature parameter type cannot be a type alias. Consider writing '[id: string]: ChangeAnnotation' instead.

911         [id: ChangeAnnotationIdentifier]: ChangeAnnotation;
             ~~


My Webpack config -> 

'use strict';
import * as webpack from 'webpack';

module.exports = (config: webpack.Configuration) => {
    //  do something..
    const item = {
        alias: require.resolve('monaco-languageclient/vscode-compatibility'),
        name: 'vscode',
    };

    if (config.resolve) {
        config.resolve.alias = [];
        config.resolve.alias.push(item);

        config.resolve.fallback = {
            buffer: require.resolve('buffer'),
            crypto: require.resolve('crypto-browserify'),
            path: require.resolve('path-browserify'),
            os: require.resolve('os-browserify/browser'),
            stream: require.resolve('stream-browserify'),
            net: false,
        };
    }

    return config;
};
