### ISSUE TITLE
What is rootUri in MonacoServices.install() for?

### ISSUE THREAD

**Issue by MassMessage** [TypeFox/monaco-languageclient#379]
From this line:
    
`MonacoServices.install(monaco, {rootUri: "file:///C:\\file\\path"})
`
Where is this uri used? I couldn't find docs for it nor it's clear looking over at source code

**Comment by CGNonofr** [comment]
The rootUri is only used to generate a default workspaceFolder if none is provided

Btw the api will probably slightly change in a near future

**Comment by MassMessage** [comment]
> The rootUri is only used to generate a default workspaceFolder if none is provided

but where is this default workspaceFolder used? for exe so i would do things like pass relative path in uri here when calling `monaco.editor.createModel()` and it would be combined with  default workspaceFolder, is that right?
 
> Btw the api will probably slightly change in a near future

hm how is that going to change?

**Comment by CGNonofr** [comment]
> but where is this default workspaceFolder used?

The the lsp `initialize` request

> for exe so i would do things like pass relative path in uri here when calling monaco.editor.createModel() and it would be combined with default workspaceFolder, is that right?

There is no such things as relative uri/path in vscode/monaco

> hm how is that going to change?

The rootPath and the workspaceFolders will be expected as parameters directly

**Comment by MassMessage** [comment]
> > but where is this default workspaceFolder used?
> 
> The the lsp `initialize` request

sorry i misunderstood that previously and still didnt get it, i'm not familiar with lsp's initialize... what is workspaceFolder  supposed to be? the project's folder or what?

> > for exe so i would do things like pass relative path in uri here when calling monaco.editor.createModel() and it would be combined with default workspaceFolder, is that right?
> 
> There is no such things as relative uri/path in vscode/monaco
> 
> > hm how is that going to change?
> 
> The rootPath and the workspaceFolders will be expected as parameters directly

**Comment by CGNonofr** [comment]
> sorry i misunderstood that previously and still didnt get it, i'm not familiar with lsp's initialize... what is workspaceFolder supposed to be? the project's folder or what?

Yes, a workspaceFolder is a project

**Comment by MassMessage** [comment]
> What is `exe`?
example 
> The language server protocol is [pretty well documented](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/)

i should rather be looking over this doc to find out about workspaceFolder thanks.

**Comment by kaisalmen** [comment]
@MassMessage I am closing the issue. If there are further questions please open a discussion: https://github.com/TypeFox/monaco-languageclient/discussions

Thank you
