### ISSUE TITLE
Question:How can i spawn language server remotely?

### ISSUE THREAD

**Issue by amarnath-mishra** [TypeFox/monaco-languageclient#38]
I am trying to keep my monaco language client and my language server on different machines. As I can see in the example folder we can start the language server externally from here --> const extJsonServerPath = path.resolve(__dirname, 'file to start the server..');  but my confusion is when my language server will be on a different machine, how it will have the access of file system of remote machine.
Thanks in advance.

**Comment by akosyakov** [comment]
Hi @amarnath-mishra! Could you elaborate on your case? What are you trying to achieve?
Generally, a language server should be spawned on the machine where the file system resides. 
In the example, the express server spawns a language server on the same machine and then exposes it via the web socket to the client, i.e. a user via the browser can access it.

**Comment by amarnath-mishra** [comment]
![flow](https://user-images.githubusercontent.com/17015419/32595757-1ce9d708-c557-11e7-8b40-c3256871d3ec.png)

Hi, yes you are right. But what i am trying to achieve is somewhat explained in the above diagram. basically i am trying to send language code from editor(monaco editor) to monaco language client which will decide which language server to start, though I am not yet sure if this is possible or not.

**Comment by akosyakov** [comment]
The Monaco language client can be run only in the browser. You can have multiple instances of language clients per a language and connect them to different servers.

As an alternative, i can imagine that you build a dispatching language server, deploy it on the router machine and connect the monaco language client from the browser to it.

**Comment by amarnath-mishra** [comment]
Yeah, I kind of did the same, thanks a lot..
