### ISSUE TITLE
Custom completion item provider getting stuck behind language client

### ISSUE THREAD

**Issue by Ehesp** [TypeFox/monaco-languageclient#391]
Early on in my application, I'm registering a custom completion provider via `monaco.languages.registerCompletionItemProvider`. The data is purely static from a local JSON file.

Without LSP, these show up instantly as expected. However, when installing the language client they will only display after the client has finished loading, which in this case can be 5-10 seconds. When hovering over the expected completion text the text `Loading...` appears.

Is there anyway we're able to show the custom providers even if the language client is loading?

**Comment by CGNonofr** [comment]
monaco-languageclient is just calling `registerCompletionItemProvider` like you did. So the bug is probably on the vscode/monaco-editor side

Are you up-to-date with monaco? I remember seeing a bugfix related to it some months ago

**Comment by Ehesp** [comment]
Thanks - yeah I'm on `"monaco-editor": "^0.33.0",`

Looks like [this comment] is relevant; https://github.com/microsoft/monaco-editor/issues/2755#issuecomment-1027889216

Quick suggestions only show when all providers have registered, but I guess the promise is hanging. That's unfortunate :(
