### ISSUE TITLE
Edit commands not being sent to server

### ISSUE THREAD

**Issue by martypitt** [TypeFox/monaco-languageclient#395]
First, thanks so much for resurrecting this project, and for the work in releasing 2.0.

I'm using `monaco-languageclient` in an Angular app (using `@materia-ui/ngx-monaco-editor`).

I've just upgraded to monaco-languageclient 2.0.2, and got everything compiling again.

Now, when I launch my app, I see the languageclient establish a connection with the language service correctly.
However, when editing inside the editor, there are no edits being sent back to the server.  Requests for code hints aren't sent either.

As a result, even though the editor and the language server are both working correctly, there's nothing happening between them.

It feels as though my monaco editor instance isn't connected to the `MonacoLanguageClient`.  I'm not sure how this is supposed to work, as looking through the examples, I can't see anything that connects an instance of the editor to the `MonacoLanguageClient`.

I appreciate this is a little vague of a question, but I'm not really sure where to start debugging.

Below is the code, but it's pretty much just the example:

```typescript
  private createMonacoEditor(): void {
    this.monacoLoaderService.isMonacoLoaded$.pipe(
      filter(isLoaded => isLoaded),
      take(1),
    ).subscribe(() => {
      monaco.editor.onDidCreateModel(model => {
        console.log('on did create model');
        this.monacoModel = model;
        monaco.editor.setModelLanguage(model, TAXI_LANGUAGE_ID);
        MonacoServices.install();
        this.startLanguageService();
      });
      monaco.languages.register({ id: TAXI_LANGUAGE_ID });
    });
  }


  createLanguageClient(id:string) {
    const wsUrl = this.websocketService.getWsUrl('/api/language-server');
    const webSocket = new WebSocket(wsUrl, []);

    // Implemented following the example here:
    // https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/client/src/client.ts#L56
    webSocket.onopen = () => {
      const socket = toSocket(webSocket);
      const reader = new WebSocketMessageReader(socket);
      const writer = new WebSocketMessageWriter(socket);

      const transports = {reader,writer}

      this.monacoLanguageClient = new MonacoLanguageClient({
        name: 'vyne-taxi-language-client',
        clientOptions: {
          // use a language id as a document selector
          documentSelector: [TAXI_LANGUAGE_ID],
          // disable the default error handler
          errorHandler: {
            error: () => ({ action: ErrorAction.Continue }),
            closed: () => ({ action: CloseAction.DoNotRestart })
          }
        },
        // create a language client connection from the JSON RPC connection on demand
        connectionProvider: {
          get: () => {
            return Promise.resolve(transports);
          }
        }
      });
      this.monacoLanguageClient.start();
    }
  }

```

**Comment by CGNonofr** [comment]
Hello,

This kind of issues are often related to dependency conflicts, if `monaco-editor` is duplicated in your node_modules.

What is the result of `npm list monaco-editor`? if there is more than 1 result, you have a problem

**Comment by CGNonofr** [comment]
Oh I read it too fast, you're using @materia-ui/ngx-monaco-editor, so it's probably related to https://github.com/TypeFox/monaco-languageclient/issues/387#issuecomment-1162877102

**Comment by martypitt** [comment]
Ok - I ditched ngx-monaco-editor, and things are working well -- thanks for the advice.

However, I still don't understand what wires these things together.  i.e., what connects the editor to the `MonacoLanguageClient`.

Is it anything to do with the `documentSelector` that gets passed in?  (Not an issue, but just for my own intellectual curiousity).

**Comment by CGNonofr** [comment]
The Language Client is calling monaco editor feature registration, that's all. Maybe I didn't understand your question ?
