### ISSUE TITLE
cache issue in monaco-languageclient version 2.0.2

### ISSUE THREAD

**Issue by OliverwengFiltered** [TypeFox/monaco-languageclient#396]
Hi there,

it looks like there is some issue in monaco-languageclient latest version.

so I recently started migrating all the old code to use latest monao-languageclient v 2.0.2 and latest vscode-ws-jsonrpc v1.0.1.

I can successfully connect monaco editor from browser to  my language server on node server. but what's weird is that, if a connection has been built, and then i make some code edit to see some error, and then I call `languageClient.stop()`, and then I re-trigger the connect procedure again (my connection procedure will reset the code model to its original state), languageclient will cache the previous error state on top of the default code. so I will get into a state where the previous error is showing on a fine code.

any insights ?

**Comment by CGNonofr** [comment]
Hello,

It may be related to https://github.com/TypeFox/monaco-languageclient/issues/387#issuecomment-1162948179, can yoi check ?

**Comment by OliverwengFiltered** [comment]
> Hello,
> 
> It may be related to [#387 (comment)](https://github.com/TypeFox/monaco-languageclient/issues/387#issuecomment-1162948179), can you check ?

yes, confirmed, instead of the time out, I did move the timing of the model.dispose to a later time, which solves the problem.
Thanks
