### ISSUE TITLE
How do I read the messages from server?

### ISSUE THREAD

**Issue by MassMessage** [TypeFox/monaco-languageclient#398]
I cannot figure out how to read the messages from the language server(messages from the parser/compiler etc sent back to the monaco) . How is that done? how do I read the messages from that socket? I've tried something like 

```
          connection.onNotification(not => {
                    console.log(`notification ${not}`);
                });
```

but those aren't the messages from language server. the code look like this:

```
 const options:MonacoServices.Options = {};
    // install Monaco language client services
    MonacoServices.install(monaco, options);

    // create the web socket
    const url = createUrl(`ws://localhost:${wsServerPort}/c`);
    const webSocket = createWebSocket(url);

    // listen when the web socket is opened
    listen({
        webSocket,
        onConnection: connection => {
            // create and start the language client
            const languageClient = createLanguageClient(connection);
            const disposable = languageClient.start();
            connection.onClose(() => disposable.dispose());
        }
    });
}

function createLanguageClient(connection: MessageConnection): MonacoLanguageClient {
    return new MonacoLanguageClient({
        name: "Sample Language Client",
        clientOptions: {
            // use a language id as a document selector
            documentSelector: ['c'],
            // disable the default error handler
            errorHandler: {
                error: () => ErrorAction.Continue,
                closed: () => CloseAction.DoNotRestart
            }
        },
        // create a language client connection from the JSON RPC connection on demand
        connectionProvider: {
            get: (errorHandler, closeHandler) => {
                
                connection.onNotification(not => {
                    console.log(`notification ${not}`);
                });
                
                return Promise.resolve(createConnection(connection, errorHandler, closeHandler));
            }
        }
    });
}

function createUrl(path: string): string {
    return normalizeUrl(path);
}

function createWebSocket(url: string): WebSocket {
    const socketOptions = {
        maxReconnectionDelay: 10000,
        minReconnectionDelay: 1000,
        reconnectionDelayGrowFactor: 1.3,
        connectionTimeout: 10000,
        maxRetries: Infinity,
        debug: false
    };
    return new (ReconnectingWebSocket as any)(url, [], socketOptions) as WebSocket;
}
```

**Comment by MassMessage** [comment]
> What are you trying to achieve? Do you want to see what is going through your connection?

the messages from the parser, for example, I have some C code like `f(1`, in the terminal I can see it output something like `missing parenthesis`. I'd like to read those kind of messages.

**Comment by CGNonofr** [comment]
What is the "parser"? Is it the language server? What is the "terminal"?

by doing
```javascript
          connection.onNotification(not => {
                    console.log(`notification ${not}`);
                });
```
You're only displaying notifications, and only those which aren't already catched

I guess you want to see the PublishDiagnostics notification? you should probably operate on a lower level, not on the connection but on the reader

**Comment by MassMessage** [comment]
by "parser" I mean the language server. I guess i'm looking for something like `PublishDiagnostics`. How can I read that? could you give some direction or code sample?

**Comment by CGNonofr** [comment]
You are the one forwarding the messages between the client and the server, I don't know how you manage it but there is a place is your code where your have the messages

**Comment by MassMessage** [comment]
> You are the one forwarding the messages between the client and the server, I don't know how you manage it but there is a place in your code where your have the messages

I figured out the server now.  The code that does that look like this:

```
function toSocket(webSocket: ws): rpc.IWebSocket {
  return {
      send: content => {
        //console.log(`contents = ${content}`);
        webSocket.send(content);
      },
      onMessage: cb => webSocket.onmessage = event => cb(event.data),
      onError: cb => webSocket.onerror = event => {
          if ('message' in event) {
              cb((event as any).message)
          }
      },
      onClose: cb => webSocket.onclose = event => cb(event.code, event.reason),
      dispose: () => webSocket.close()
  }
}


  const wss = new WebSocketServer({
    port: serverPort,
    perMessageDeflate: false
  }, onStarted);

  wss.on('connection', (client : ws, request : http.IncomingMessage) => {
    let langServer : string[] = [];

    Object.keys(languageServers).forEach((key) => {
      if (request.url === '/' + key) {
        langServer = languageServers[key];
      }
    });
    if (!langServer.length) {
      console.error('Invalid language server', request.url);
      client.close();
      return;
    }

    const localConnection = rpcServer.createServerProcess('Example', langServer[0], langServer.slice(1));
    const socket : rpc.IWebSocket = toSocket(client, onSentContent);
    const connection = rpcServer.createWebSocketConnection(socket);
    rpcServer.forward(connection, localConnection);
    socket.onClose((code, reason) => {
      //console.log('Client closed', reason);
      localConnection.dispose();
    });
  });
```

The part that does forward the contents is the event within the `toSocket` function, the part:

```
   send: content => {
        //console.log(`contents = ${content}`);
        webSocket.send(content);
      }
```

is the one forward the messages. In case i'd like to read those, is this the proper way to read them or is intercepting  this at this part of code "hacky"?

**Comment by CGNonofr** [comment]
I still have no idea what you are trying to do so difficult to say if it's hacky

**Comment by MassMessage** [comment]
> I still have no idea what you are trying to do so difficult to say if it's hacky

I mean let's say you have in source code `int f(` then there's the compiler error `expeced ')' instead of 'EOF'`. This is the error messages i'm trying to read. it seems to come from `textDocument/publishDiagnostics`

**Comment by CGNonofr** [comment]
Reading the error messages is a way, not a purpose, isn't it?

**Comment by CGNonofr** [comment]
you can use the `monaco.editor.getModelMarkers` and `monaco.editor.onDidChangeMarkers` apis for that

**Comment by MassMessage** [comment]
> you can use the `monaco.editor.getModelMarkers` and `monaco.editor.onDidChangeMarkers` apis for that

thanks, that does the job elegantly!
