### ISSUE TITLE
Question: compatibility with OmniSharp C# language server

### ISSUE THREAD

**Issue by gmichaud** [TypeFox/monaco-languageclient#40]
I recently discovered Monaco and the language client project - I reviewed the example included in this project and am now interested to modify it to work with the OmniSharp Language Server (https://github.com/OmniSharp/csharp-language-server-protocol). Before I spend too much time on this, I wanted to know if this had been attempted or if I should already expect some incompatibilities between both. Thanks! Starred the repository as well 👍

**Comment by svenefftinge** [comment]
We have not yet tried the omnisharp language server, but if it conforms to the LSP it should work. Anyways, let us know if you run into trouble and we will try to help.

**Comment by akosyakov** [comment]
I close it, please open if there is a concrete issue.

**Comment by gmichaud** [comment]
In case anyone is interested, I gave up trying to use the language server protocol and went for a simpler route - I connected the Monaco Editor directly to OmniSharp-Roslyn. I'll wait for full support in OmniSharp-Roslyn or in Monaco to be completed before attempting again. Thanks.

**Comment by hifall** [comment]
@gmichaud, I am interested in the Monaco/OmniSharp C# language server integration. Could you please share more of your experience? What issues you ran into made you give up? Should one attempt for this again now?

**Comment by gmichaud** [comment]
@hifall we never got much further than prototype stage. I definitely abandonned the idea of using LSP and used the native OmniSharp protocol instead... but that was many months ago, might be doable today!

**Comment by amarnath-mishra** [comment]
I tried this and got success also, but there is one problem there that, after initialisation of Language server, the language server is not is not able to pick the contents which I have already given in a file in my rootUri, And it is considering it as empty and giving results for textDocument/completion as should give for any empty file, as one can see in this attached screenshot of my machine.

<img width="1401" alt="Screen Shot 2019-05-13 at 3 54 21 PM" src="https://user-images.githubusercontent.com/17015419/57615323-0bcde600-7599-11e9-8f3f-990b7998fb34.png">


But when my LS successfully gets started, then if I am changing my editor's content using editor.setValue(content), OR if i just do a Cut and the Paste of all data in editor, then again it starts giving proper suggestion as it should give, see image:

<img width="1369" alt="Screen Shot 2019-05-13 at 4 09 40 PM" src="https://user-images.githubusercontent.com/17015419/57615891-792e4680-759a-11e9-8bb8-760f4f4bcbe2.png">

Anyhelp, would be appreciated, Thanks in advance.

**Comment by Progyan1997** [comment]
@amarnath-mishra Hey I was trying to setup a remote LSP with Monaco editor, but `textDocument/completion` event is not being called even when trigger character is present. Can you help?

```
id: 0
jsonrpc: "2.0"
result: {
  capabilities: {
    definitionProvider: false
    documentFormattingProvider: false
    documentHighlightProvider: false
    documentRangeFormattingProvider: false
    documentSymbolProvider: false
    experimental: {}
    hoverProvider: false
    referencesProvider: false
    textDocumentSync: 0
    workspaceSymbolProvider: false
  }
}
```

**Comment by akshay-zz** [comment]
@amarnath-mishra , Can you tell us how you achieved that in little detail?

**Comment by tavisca-ysant** [comment]
> In case anyone is interested, I gave up trying to use the language server protocol and went for a simpler route - I connected the Monaco Editor directly to OmniSharp-Roslyn. I'll wait for full support in OmniSharp-Roslyn or in Monaco to be completed before attempting again. Thanks.

@gmichaud . Please tell how you achieved this

**Comment by GNSubrahmanyam** [comment]
@amarnath-mishra @Progyan1997 How you guys managed kill csharp lsp on browser refresh or tab close. In my case lsp is not getting killed

Before tab close

root@b7abb90fe627:/app# ps -elLF
F S UID        PID  PPID   LWP  C NLWP PRI  NI ADDR SZ WCHAN    RSS PSR STIME TTY          TIME CMD
4 S root         1     0     1  0    1  80   0 -  1156 wait     668   3 13:38 ?        00:00:00 /bin/sh -c "node" "lib/server.js"
4 S root         6     1     6  0   11  80   0 - 151844 ep_pol 35184  2 13:38 ?        00:00:00 node lib/server.js
1 S root         6     1     7  0   11  80   0 - 151844 ep_pol 35184  0 13:38 ?        00:00:00 node lib/server.js
1 S root         6     1     8  0   11  80   0 - 151844 futex_ 35184  1 13:38 ?        00:00:00 node lib/server.js
1 S root         6     1     9  0   11  80   0 - 151844 futex_ 35184  0 13:38 ?        00:00:00 node lib/server.js
1 S root         6     1    10  0   11  80   0 - 151844 futex_ 35184  0 13:38 ?        00:00:00 node lib/server.js
1 S root         6     1    11  0   11  80   0 - 151844 futex_ 35184  0 13:38 ?        00:00:00 node lib/server.js
1 S root         6     1    12  0   11  80   0 - 151844 futex_ 35184  2 13:38 ?        00:00:00 node lib/server.js
1 S root         6     1    13  0   11  80   0 - 151844 futex_ 35184  2 13:42 ?        00:00:00 node lib/server.js
5 S root         6     1    14  0   11  80   0 - 151844 futex_ 35184  2 13:42 ?        00:00:00 node lib/server.js
5 S root         6     1    15  0   11  80   0 - 151844 futex_ 35184  0 13:42 ?        00:00:00 node lib/server.js
5 S root         6     1    16  0   11  80   0 - 151844 futex_ 35184  2 13:42 ?        00:00:00 node lib/server.js
4 S root        95     0    95  0    1  80   0 -  4625 wait    3356   3 13:46 pts/0    00:00:00 bash
0 S root       656     6   656  0    1  80   0 -  4593 wait    3028   2 14:20 ?        00:00:00 bash /opt/omnisharp/run -lsp
0 S root       661   656   661  0   21  80   0 - 364522 futex_ 172772 2 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   662  0   21  80   0 - 364522 futex_ 172772 0 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   663  0   21  80   0 - 364522 futex_ 172772 2 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   664  0   21  80   0 - 364522 futex_ 172772 2 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   665  0   21  80   0 - 364522 futex_ 172772 3 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   666  0   21  80   0 - 364522 futex_ 172772 2 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
5 S root       661   656   667  1   21  80   0 - 364522 futex_ 172772 1 14:20 ?        00:00:01 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   668  0   21  80   0 - 364522 futex_ 172772 3 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   669  0   21  80   0 - 364522 futex_ 172772 1 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   670  0   21  80   0 - 364522 futex_ 172772 2 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   671  0   21  80   0 - 364522 unix_s 172772 0 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
5 S root       661   656   672  2   21  80   0 - 364522 futex_ 172772 1 14:20 ?        00:00:01 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   673  0   21  80   0 - 364522 futex_ 172772 3 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   675  0   21  80   0 - 364522 futex_ 172772 3 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   676  0   21  80   0 - 364522 futex_ 172772 1 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   677  0   21  80   0 - 364522 futex_ 172772 2 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   678  0   21  80   0 - 364522 futex_ 172772 1 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   679  0   21  80   0 - 364522 futex_ 172772 0 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   680  0   21  80   0 - 364522 futex_ 172772 2 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661   656   681  0   21  80   0 - 364522 futex_ 172772 1 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
5 S root       661   656   682  0   21  80   0 - 364522 futex_ 172772 3 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
0 R root       704    95   704  0    1  80   0 -  8600 -       2704   3 14:21 pts/0    00:00:00 ps -elLF
After browser tab close

root@b7abb90fe627:/app# ps -elLF
F S UID        PID  PPID   LWP  C NLWP PRI  NI ADDR SZ WCHAN    RSS PSR STIME TTY          TIME CMD
4 S root         1     0     1  0    1  80   0 -  1156 wait     668   3 13:38 ?        00:00:00 /bin/sh -c "node" "lib/server.js"
4 S root         6     1     6  0   11  80   0 - 151844 ep_pol 34260  1 13:38 ?        00:00:00 node lib/server.js
1 S root         6     1     7  0   11  80   0 - 151844 ep_pol 34260  0 13:38 ?        00:00:00 node lib/server.js
1 S root         6     1     8  0   11  80   0 - 151844 futex_ 34260  2 13:38 ?        00:00:00 node lib/server.js
1 S root         6     1     9  0   11  80   0 - 151844 futex_ 34260  2 13:38 ?        00:00:00 node lib/server.js
1 S root         6     1    10  0   11  80   0 - 151844 futex_ 34260  0 13:38 ?        00:00:00 node lib/server.js
1 S root         6     1    11  0   11  80   0 - 151844 futex_ 34260  0 13:38 ?        00:00:00 node lib/server.js
1 S root         6     1    12  0   11  80   0 - 151844 futex_ 34260  2 13:38 ?        00:00:00 node lib/server.js
1 S root         6     1    13  0   11  80   0 - 151844 futex_ 34260  2 13:42 ?        00:00:00 node lib/server.js
5 S root         6     1    14  0   11  80   0 - 151844 futex_ 34260  2 13:42 ?        00:00:00 node lib/server.js
5 S root         6     1    15  0   11  80   0 - 151844 futex_ 34260  0 13:42 ?        00:00:00 node lib/server.js
5 S root         6     1    16  0   11  80   0 - 151844 futex_ 34260  2 13:42 ?        00:00:00 node lib/server.js
4 S root        95     0    95  0    1  80   0 -  4625 wait    3356   3 13:46 pts/0    00:00:00 bash
0 S root       661     1   661  0   20  80   0 - 364646 futex_ 173336 2 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   662  0   20  80   0 - 364646 futex_ 173336 0 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   663  0   20  80   0 - 364646 futex_ 173336 2 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   664  0   20  80   0 - 364646 futex_ 173336 3 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   665  0   20  80   0 - 364646 futex_ 173336 2 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   666  0   20  80   0 - 364646 futex_ 173336 3 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
5 S root       661     1   667  0   20  80   0 - 364646 futex_ 173336 0 14:20 ?        00:00:01 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   668  0   20  80   0 - 364646 futex_ 173336 2 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   669  0   20  80   0 - 364646 futex_ 173336 1 14:20 ?        00:00:03 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   670  0   20  80   0 - 364646 futex_ 173336 2 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
5 S root       661     1   672  0   20  80   0 - 364646 futex_ 173336 2 14:20 ?        00:00:01 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   673  0   20  80   0 - 364646 futex_ 173336 3 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   675  0   20  80   0 - 364646 futex_ 173336 2 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   676  0   20  80   0 - 364646 futex_ 173336 0 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   677  0   20  80   0 - 364646 futex_ 173336 0 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   678  0   20  80   0 - 364646 futex_ 173336 3 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   679  0   20  80   0 - 364646 futex_ 173336 2 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   680  0   20  80   0 - 364646 futex_ 173336 1 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
1 S root       661     1   681  0   20  80   0 - 364646 futex_ 173336 3 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
5 S root       661     1   682  0   20  80   0 - 364646 futex_ 173336 0 14:20 ?        00:00:00 /opt/omnisharp/bin/mono /opt/omnisharp/omnisharp/OmniS
0 R root       705    95   705  0    1  80   0 -  8600 -       2732   0 14:25 pts/0    00:00:00 ps -elLF
root@b7abb90fe627:/app# ps -elLF
On browser tab close parent process is getting click but child PID 661 is orphan then PID1 adopts it.

0 S root       656     6   656  0    1  80   0 -  4593 wait    3028   2 14:20 ?        00:00:00 bash /opt/omnisharp/run -lsp
Need your help to understand what is wrong ?
