### ISSUE TITLE
Question around consuming NPM package

### ISSUE THREAD

**Issue by dkattan** [TypeFox/monaco-languageclient#401]
First I want to say I greatly appreciate the work that has been going into the repo recently!

The examples are great, but they appear to reference the ../../client which points to the source itself rather than the NPM package.

I want to be able to simply include the NPM package in my project. If I want this to run in the browser, do I still require webpack?

**Comment by CGNonofr** [comment]
> The examples are great, but they appear to reference the ../../client which points to the source itself rather than the NPM package.

[I'm not sure to understand what you mean](https://github.com/TypeFox/monaco-languageclient/blob/fbc2f1e314264f6aa092ed35faeb7cb31131aa6b/packages/examples/client/src/client.ts#L23), you should use the [monaco-languageclient](https://www.npmjs.com/package/monaco-languageclient) library

> I want to be able to simply include the NPM package in my project. If I want this to run in the browser, do I still require webpack?

ES modules are exported, they can probably be used directly by modern browsers but I do recommand using a bundler like webpack for many reasons. Also, some dependencies are CommonJS and will require a bundler.
