### ISSUE TITLE
Monaco Editor with Python Language Server

### ISSUE THREAD

**Issue by dirathea** [TypeFox/monaco-languageclient#41]
# Summary
I've tried to use  PYLS on Monaco Editor using [Monaco Language Client](https://github.com/TypeFox/monaco-languageclient) with the following configuration

```
this.editor.setModel(monaco.editor.createModel(exampleCode, 'python', monaco.Uri.parse('inmemory://dummy.py')););
    const services = createMonacoServices(this.editor);
```
And everything that [this blog](http://typefox.io/teaching-the-language-server-protocol-to-microsofts-monaco-editor) explained.

Everything works as expected but the auto complete. When I do `ctrl + space` on the editor, there's only "No Suggestions."  and I saw the PYLS logs error as follows

```
PYLS Server: 2017-12-08 09:56:21,029 UTC - ERROR - jsonrpc.manager - API Exception: {'message': "'Folder' object has no attribute 'read'", 'args': ("'Folder' object has no attribute 'read'",), 'type': 'AttributeError'}
Traceback (most recent call last):
  File "myVirtualEnv/lib/python2.7/site-packages/jsonrpc/manager.py", line 112, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "myVirtualEnv/lib/python2.7/site-packages/pyls/language_server.py", line 64, in wrapped
    return func(*args, **kwargs)
  File "myVirtualEnv/lib/python2.7/site-packages/pyls/python_ls.py", line 140, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "myVirtualEnv/lib/python2.7/site-packages/pyls/python_ls.py", line 70, in completions
    position=position
  File "myVirtualEnv/lib/python2.7/site-packages/pyls/_utils.py", line 113, in race_hooks
    for impl, result in pool.imap_unordered(_apply, impls, chunksize=1):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
AttributeError: 'Folder' object has no attribute 'read'
```

Could you help me? is it about the monaco URI that I pass ? `inmemory://dummy.py`

note: I've also asked this on [Python Language Server repo](https://github.com/palantir/python-language-server/issues/199) since I don't know on which side is the issue happened...

**Comment by akosyakov** [comment]
It looks like a python error from pyls.

**Comment by dirathea** [comment]
Ahh.. I see... thanks for previewing my issue @akosyakov 
Besides this issue, is there any "special configurations" for connecting monaco with pyls? I've checked [your PYLS fork](https://github.com/TypeFox/python-language-server) and wondering is there any changes on it.

**Comment by svenefftinge** [comment]
There is not, I think I once intended doing a PR but than didn't. Removed the fork.

**Comment by sally2015** [comment]
@dirathea Have you solve the question now, can you give me a simple demo, thanks

**Comment by sally2015** [comment]
@dirathea Actually, I don't know how to apply `Python Language Server`  to the `Monaco Editor` which is embeded in the online website. Can you give me the simple demo, thank you very much

**Comment by rcjsuen** [comment]
@sally2015 https://github.com/TypeFox/monaco-languageclient/issues/75#issuecomment-385163286 and https://github.com/TypeFox/monaco-languageclient/issues/75#issuecomment-385229537 might help you get started a little.

The main thing you usually have to figure out is how to start the language server. If you're able to do that from the command line just use the same invocation in `json-server-launcher.ts` and you should be good to go for a start. There may of course be additional configuration options that are needed but it's a start.

**Comment by anshullodha** [comment]
were you able to achieve that @sally2015.
Does anyone have any suggestion on how to implement a `Python Language Server` to the `Monaco Editor` which is embeded in the online website.

**Comment by akosyakov** [comment]
@sally2015 I see you were able to figure it out https://github.com/Microsoft/monaco-editor/issues/833#issuecomment-402301159

If you think there is something can be done to help other, like add a comment to [this line](https://github.com/TypeFox/monaco-languageclient/blob/master/example/src/json-server-launcher.ts#L19), you are welcome to open a PR :)

**Comment by anshullodha** [comment]
@akosyakov I was able to run the [example](https://github.com/TypeFox/monaco-languageclient/tree/master/example) provided with Monaco Language Client. The question of this thread, how to implement a `Python Language Server` for `Monaco Editor` on a online website?, is yet to be solved.

**Comment by rcjsuen** [comment]
@anshullodha What do you mean? If you got the example to run then you have a working website. Did I misunderstand something?

**Comment by shoorlyne** [comment]
I am also having trouble connecting Monaco language client to a "real" [C++ language server](https://github.com/theia-ide/theia-apps/issues/70) in this case) other than the simple JSON language server in the example.

I guess adding an end-to-end example of Monaco editor, Monaco language client, and a "real" language server like C++ or Java working together would greatly make things a lot easier for me to follow, and maybe for other who are on this path as well.

Thanks!

**Comment by shoorlyne** [comment]
@rcjsuen, have you been able to connect Monaco language client with any production language server other than JSON in the example?

**Comment by rcjsuen** [comment]
@shoorlyne Those language servers are generally more complicated because they rely on having access to some (virtual?) files. This compounds the difficulty in a browser-based environment as you have to hook up the files yourself. This repository does not help you deal with that (as it's not really in the scope of the project). That being said I don't deny the usefulness of such an example, I'm just saying it's not super straightforward.

As to your actual question, yes, I have hooked this project with my own [Dockerfile language server](https://github.com/rcjsuen/dockerfile-language-server-nodejs/). But again, you can't really compare that with a C++ or Java language server as Dockerfiles are like JSON files and are completely standalone and it doesn't care about whether your files are on-disk or in the cloud.

**Comment by shoorlyne** [comment]
@rcjsuen, since this repo already contains examples connecting with toy-ish language servers, I don't think it would be too off track to include a more complex/practical example though ;)

BTW, thanks for your Dockerfile language server, looks interesting!

**Comment by shoorlyne** [comment]
Yup, I have tried that too. The UX is superb due to it being pure browse.

**Comment by gatesn** [comment]
I have an example up here of hosting a stand-alone language server over a web socket. You then just need to hook up the Monaco-languageclient examples to point at it.

https://github.com/palantir/python-jsonrpc-server/blob/develop/examples/langserver_ext.py

**Comment by lilifan** [comment]
@rcjsuen Sir, could you please kindly tell me why is the "model.json" file?  and how does it being loaded into "memory".  Because I saw both the official example and your Dockerfile browser example contains this code :" var MODEL_URI = 'inmemory://model.json'; "

**Comment by rcjsuen** [comment]
@lilifan It's "loaded into memory" because the content of the file is created completely from code.

https://github.com/TypeFox/monaco-languageclient/blob/602e7606c046036d3627b59064bbfb4b67e7d2e8/example/src/client.ts#L22-L32

**Comment by lilifan** [comment]
@rcjsuen Thank you very much!  so "the content of the file"  is the value string contains of schema and line_endings?  
By the way, I was curious about how did you know to use the "inmemory://model.json"?  because I didn't find it in any documents and any repositories.

**Comment by lilifan** [comment]
It seems the example lacks syntax highlighting . Actually it has disabled the default syntax colorization Monaco editor provides.(https://microsoft.github.io/monaco-editor/)  
Is there anyway we can get it back ? 
@rcjsuen   @akosyakov

**Comment by rcjsuen** [comment]
@lilifan It is mentioned in the [VS Code repository](https://github.com/microsoft/vscode/blob/911eabf34a97b7aa5ab1242287abd0135c2de891/src/vs/base/common/network.ts#L11-L15).

**Comment by lilifan** [comment]
> @lilifan It is mentioned in the [VS Code repository](https://github.com/microsoft/vscode/blob/911eabf34a97b7aa5ab1242287abd0135c2de891/src/vs/base/common/network.ts#L11-L15).

Thx.
