### ISSUE TITLE
v3 client nests `vscode` dependency

### ISSUE THREAD

**Issue by Ehesp** [TypeFox/monaco-languageclient#411]
Hey all,

I'm struggling to understand why, but when upgrading from v2 of the language client (specifically `"monaco-languageclient": "^2.0.2",`), to `^3.0.0`, the `vscode` dependency is being nested within my node modules differently:

```
node_modules/vscode                                                                        <- v2
node_modules/monaco-languageclient/node_modules/vscode.   <- v3
```

This is causing other dependencies (e.g. `vscode-languageserver*`) to not find the `vscode` dependency anymore. I'll keep digging as to why this has happened, but it's confusing me!

**Comment by CGNonofr** [comment]
Hello

what is the result of a `npm list vscode`?

**Comment by Ehesp** [comment]
Oh jesus sorry for wasting your time. My package-lock file was out of sync causing issues. All working as expected.
