### ISSUE TITLE
monaco-languageclient doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module

### ISSUE THREAD

**Issue by Ehesp** [TypeFox/monaco-languageclient#413]
Hey, 

Using the latest version of `monaco-languageclient` (`3.0.1`) with Vite 3, and this error is spat out when using the package. Seems as though to remove the warning adding `"type": "module"` to the package.json should do it - everything is working but just adding this here for awareness.

**Comment by kaisalmen** [comment]
Thanks for making us aware 👍

**Comment by Ehesp** [comment]
Sorry, should have put the full message:

```
monaco-languageclient doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
```

**Comment by kaisalmen** [comment]
@Ehesp I am working on transforming everything to proper ESM. Can you give version `3.1.0-next.0` a try: https://www.npmjs.com/package/monaco-languageclient/v/3.1.0-next.0
Thanks 🙂

**Comment by Ehesp** [comment]
Cool will do. I'm away this coming week so will check it out after.
