### ISSUE TITLE
integrate with @monaco-editor/react

### ISSUE THREAD

**Issue by mbui0327** [TypeFox/monaco-languageclient#423]
I was able to make the code compile without error by 
1. add `"type": "module"` to the `packagage.json` of `monica-editor` 
2. add this to `next.config.js`
```
module.exports = {
    reactStrictMode: false,
    typescript: {
        // !! WARN !!
        // Dangerously allow production builds to successfully complete even if
        // your project has type errors.
        // !! WARN !!
        ignoreBuildErrors: true,
    },    
    webpack: (config, { dev }) => {
        // config.module.rules = config.module.rules.filter((r) => !r.oneOf);
        config.module.rules.push({
            test: /\.css$/i,
            use: ["style-loader", "css-loader"],
        });
        const rule = config.module.rules
            .find((rule) => rule.oneOf)
            .oneOf.find(
                (r) =>
                    // Find the global CSS loader
                    r.issuer && r.issuer.include && r.issuer.include.includes("_app")
            );
        if (rule) {
            rule.issuer.include = [
                rule.issuer.include,
                // Allow `monaco-editor` to import global CSS:
                /[\\/]node_modules[\\/]monaco-editor[\\/]/,
            ];
        }
        if (config.module.generator?.asset?.filename) {
            if (!config.module.generator["asset/resource"]) {
                config.module.generator["asset/resource"] = config.module.generator.asset;
            }
            delete config.module.generator.asset;
        }
        return config;
    },
};
```

4. Import `MonacoService` with this: 
```
const MonacoServices = dynamic(
    () => import("monaco-languageclient").then((module: any) => module.MonacoServices),
    { ssr: false }
);
```

The problem I run into now is `MonacoServices` is not loaded at all. It is not filled with the object from `monaco-languageclient` when I access it. Wonder if this is the same problem as one described in here https://github.com/TypeFox/monaco-languageclient/issues/412#issuecomment-1227289713. 

Appreciate any help here. Thanks.

**Comment by AXeL-dev** [comment]
Hello,

I think that the `@monaco-editor/react` & `monaco-language client` libraries uses a different monaco-editor instance, try to add the following in the root file of your project or at the top of your editor component file:

```typescript
import * as monaco from "monaco-editor";
import { loader } from "@monaco-editor/react";

loader.config({ monaco });
```

Also, make sure to have the `monaco-editor` dependency installed: `npm i monaco-editor`.

[source](https://github.com/suren-atoyan/monaco-react#use-monaco-editor-as-an-npm-package)

**Comment by yoavbls** [comment]
@AXeL-dev,= after a lot of tries making `monaco-languageclient` work with `@monaco-editor/react/` it worked with your solution! 
Thank you!

**Comment by kaisalmen** [comment]
This https://github.com/TypeFox/monaco-languageclient/issues/423#issuecomment-1255995975 will be added to the new Troubleshooting section in the README, see https://github.com/TypeFox/monaco-languageclient/issues/421

**Comment by kaisalmen** [comment]
README has been updated and is available on main branch. Will close this now.
