### ISSUE TITLE
Runtime error "Cannot call a class as a function" when using version 3 & higher

### ISSUE THREAD

**Issue by AXeL-dev** [TypeFox/monaco-languageclient#424]
Hello,

I'm using this library alongside with react & it works perfectly on dev mode, but once i build the app for production use, i receive the following error on runtime "`Cannot call a class as a function`":

![Screen Capture_select-area_20220921224751](https://user-images.githubusercontent.com/30635693/191617283-f9de178b-eca3-47dd-a190-e8c76018e27c.png)

The error only occurs with recent versions on this library (to know version 3 & 4), i tested with version 2 & i don't get any error at runtime (still upgrading to the latest version is needed to get the latest features & to keep monaco version updated as well).

After investigating, the error seems to come from the `super` call in the `RawContextKey` class in the `monaco-editor/esm/vs/platform/contextkey/common/contextkey.js` file:

![Screen Capture_select-area_20220921225704](https://user-images.githubusercontent.com/30635693/191618443-b7397ef7-e1f8-4f77-a0b4-052a185a2f01.png)

I also noticed that the same class is bundled in `vscode/dist/workspace.js` file of the [@codingame/monaco-vscode-api](https://github.com/CodinGame/monaco-vscode-api) package, so i'm wondering if the issue is coming from the fact that the class is declared twice, or maybe something else like the babel `@babel/runtime/helpers/esm/createSuper.js` module which is used/called just before the error occurs.

That's all i could figure out, any help to fix that issue would be appreciated :pray: .

Thanks.

**Comment by CGNonofr** [comment]
Hello!

`RawContextKey` is present in `monaco-vscode-api` just to `polyfill` the monaco one (see https://github.com/CodinGame/monaco-vscode-api/blob/83238e0cd128318f24b72e26cb9d09adb874f360/src/polyfill.ts#L99)
it's in workspace.js instead of polyfill.js because of rollup magic, I don't really know why but it shouldn't have any consequence

Can you have a look to the transpiled code? What is in contextkey.js around 1127:9?

**Comment by CGNonofr** [comment]
Btw, the issue probably comes from the fact that you're asking babel to transpile es6 classes to functions, while classes are supported by ALL browsers since at least [2016](https://caniuse.com/es6-class)

**Comment by AXeL-dev** [comment]
> Can you have a look to the transpiled code? What is in contextkey.js around 1127:9?

Yes sure, here is the transpiled code:

#### `contextkey.js around 1127:9`

![Screen Capture_select-area_20220922093911](https://user-images.githubusercontent.com/30635693/191700119-34f6dea9-e707-4e5d-8369-7049d6877d71.png)

#### `contextkey.js around 217:31`:

![Screen Capture_select-area_20220922094017](https://user-images.githubusercontent.com/30635693/191700452-3056b5db-b846-440f-8459-370a2f60184d.png)

> Btw, the issue probably comes from the fact that you're asking babel to transpile es6 classes to functions, while classes are supported by ALL browsers since at least [2016](https://caniuse.com/es6-class)

Do you think that this comes from a bad build configuration in my project :thinking:? if so do you have an idea about how to fix it?

**Comment by CGNonofr** [comment]
It isn't the transpiled code, it's the original code as your browser is using the sourcemap (as stated at the bottom of your screens)

**Comment by CGNonofr** [comment]
> Do you think that this comes from a bad build configuration in my project

I wouldn't say bad, but babel is known to transform pretty drastically the code and produce such errors, better just only use the transformations your need

**Comment by AXeL-dev** [comment]
My bad! how about this:

![Screen Capture_select-area_20220922095227](https://user-images.githubusercontent.com/30635693/191703020-4eb390ad-445b-4e7c-af1a-c55c35b50f8d.png)

**Comment by CGNonofr** [comment]
As expected, pretty unreadable. I have no other idea than keeping the classes, have a look at your browserlist configuration

**Comment by AXeL-dev** [comment]
Alright, i'll check that, thanks!

**Comment by AXeL-dev** [comment]
Fixed! @CGNonofr Thank you very much!

The fix was to change my browserlist `production` configuration to the same values in the `development` config (or to any recent browserlist config):

![Screen Capture_select-area_20220922104655](https://user-images.githubusercontent.com/30635693/191715440-804729e1-140f-4296-8210-ce265a02e831.png)
