### ISSUE TITLE
Remove all markers

### ISSUE THREAD

**Issue by tyagirajat200** [TypeFox/monaco-languageclient#426]
How we can remove  markers. 
monaco editor method  to remove markers "removeAllMarkers"  accept owner string. From where we get this owner string for languages registered by the language client. I tried to pass the language id as owner but it is not working.

**Comment by CGNonofr** [comment]
What is the use case? The point of the owner is that only it can remove its markers

**Comment by tyagirajat200** [comment]
So, I do not want these red lines and for this I tried to override registerBuiltinFeatures method and remove the code action features. I checked the socket messages and found this is triggered for textDocument/publishDiagnostics event for which there is no method to remove it.
So I want the owner id, so that I can remove all markers from the monaco editor.
![image](https://user-images.githubusercontent.com/40917672/193344457-ab5d3f87-2a8e-4f08-bc0a-bf4f5325d576.png)

**Comment by CGNonofr** [comment]
It's not clear to me
- What language server are you using?
- Why is there an error here? what is the error?

Instead of hacking it client side, I suggest you make the language server behave properly. Even if you remove it, the language server will put it back

**Comment by tyagirajat200** [comment]
1. I am using the Java Language Server.
2. return statement is missing here, so red lines are there, to alert the user to complete the function impletation.
Yes, I managed to disable it from the language server itself. Now it's working fine.
