### ISSUE TITLE
Language Client services has not been installed

### ISSUE THREAD

**Issue by KamiC6238** [TypeFox/monaco-languageclient#428]
Running the follow code would throw the Language Client services has not been installed

`
MonacoServices.install(monaco);
`

<img width="511" alt="image" src="https://user-images.githubusercontent.com/23523595/196879005-d5ed3c0b-7902-4552-b229-a06907fb9d5d.png">

how can i solve this problem?

versions:
monaco-editor: 0.24.0
monaco-languageclient: 0.14.0
@codingame/monaco-jsonrpc: 0.3.1

**Comment by CGNonofr** [comment]
Is there a reason you're still using very old versions?

**Comment by KamiC6238** [comment]
> 
because in my project, i use vscode theme in monaco-editor,  the vscode theme could not work when i try to upgrade the monaco-editor versions. That is why the monaco-editor versions is old.

the second reason is there has another error when i try to use the monaco-languageclient v4.0.0, so i choised the v0.14.0.

i’m not very good at english, i hope i made myself clear, thanks.

**Comment by CGNonofr** [comment]
We won't be able to provide support for old version of this library

Btw, you may have a look at `monaco-vscode-api` (which is used by this library) that allows to use vscode themes and textmate (but I'm not sure what you are doing with vscode themes exactly)

**Comment by KamiC6238** [comment]
> 



> We won't be able to provide support for old version of this library
> 
> Btw, you may have a look at `monaco-vscode-api` (which is used by this library) that allows to use vscode themes and textmate (but I'm not sure what you are doing with vscode themes exactly)
> 
> we can't probably help you on the error you get with the last version though

I have just upgraded monaco-languageclient to version 4.0, in the old version, i need write the follow code to void the.`Can not find module 'vscode'` ,
`vscode: require.resolve('monaco-languageclient/lib/vscode-compatibility')`

but now the version 4.0 not support that, so the error about `Can not find module 'vscode'` throw again. how can i solve this problem in the 4.0 version?

**Comment by KamiC6238** [comment]
> You should not try to resolve it by hands with the last version, it's supposed to work because `monaco-vscode-api` is installed as `vscode` (`npm install vscode@npm:@codingame/monaco-vscode-api`)
> 
> I don't know what's wrong with your project, you can try removing the package-lock and running `npm install` again

it works for me now. thanks very much!
