### ISSUE TITLE
[Question] How to connect to ccls language server through vscode-ws-jsonrpc

### ISSUE THREAD

**Issue by KamiC6238** [TypeFox/monaco-languageclient#431]
i tried many times and found many examples to connect the ccls server, but got the follow error.
<img width="546" alt="image" src="https://user-images.githubusercontent.com/23523595/197550799-35aad98b-000d-41cd-bfd8-9b528288f898.png">

and my code
```javascript
    try {
        const serverConnection = jsonrpcServer.createServerProcess('lsp-cpp', 'ccls', ["--init={\"cacheDirectory\":\"/path/to/cachedir\",\"cacheFormat\":\"json\",\"index\":{\"onChange\":true,\"trackDependency\":2}}"]);

        if (serverConnection) {
            jsonrpcServer.forward(socketConnection, serverConnection, message => {
                console.log('message: ', message);
                return message;
            });
        }
    
        connection.onNotification(notification, (param: string) => {
            console.log('notification: ', param);
        });
    
        connection.listen();
    } catch (e) {
        console.log('connection error: ', e);
    }
```

versions:
monaco-languageclient: 4.0.0
vscode-ws-jsonrpc: 2.0.0

**Comment by kaisalmen** [comment]
Hi @KamiC6238 have you verified that the `ccls` command + all its arguments works in a terminal?

**Comment by kaisalmen** [comment]
Please, next time you have a question, please open a it here: https://github.com/TypeFox/monaco-languageclient/discussions Thank you.

**Comment by kaisalmen** [comment]
@KamiC6238 Did you manage to start the ccls server properly? Now, you jumped to the client. Is it possible you share your code? It is really hard to understand what you are actually doing this way?

**Comment by KamiC6238** [comment]
> 



> Did you manage to start the ccls server properly? Now, you jumped to the client. Is it possible you share your code? It is really hard to understand what you are actually doing this way?

the follow code is client code, i write a node server on port 4200 to listen the client request, so when i start the client, i will create the localhost:4200 url

```javascript
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api.js';
import { MonacoLanguageClient, CloseAction, ErrorAction, MonacoServices, MessageTransports, createMessageConnection } from 'monaco-languageclient';
import {NotificationType} from 'vscode-jsonrpc';
import { toSocket, WebSocketMessageReader, WebSocketMessageWriter } from 'vscode-ws-jsonrpc';
import normalizeUrl from 'normalize-url';

export default class LanguageClient {
    private url = '';
    private websocket: WebSocket | null = null;
    private editor: monaco.editor.IStandaloneCodeEditor | null = null;

    constructor(editor: monaco.editor.IStandaloneCodeEditor) {
        this.editor = editor;
        this.install();
        this.url = this.createUrl('localhost', 4200, '/cpp');
        this.websocket = new WebSocket(this.url);
        this.initListener();
    }

    private install() {
        const modelUri = this.editor?.getModel()?.uri;
        MonacoServices.install({rootPath: `file://${modelUri?.authority}`});
    }

    private initListener() {
        this.websocket!.onopen = () => {
            const socket = toSocket(this.websocket!);
            const reader = new WebSocketMessageReader(socket);
            const writer = new WebSocketMessageWriter(socket);
            const notification = new NotificationType<string>('testNotification');
            const languageClient = this.createLanguageClient({
                reader,
                writer
            });
            languageClient
                .start()
                .then(() => {
                    console.log('monaco-languageclient was successfully started.');
                })
                .catch((e: Error) => {
                    console.log(`monaco-languageclient start was unsuccessful: ${e.message}`);
                });
            languageClient.sendNotification(notification, 'Hello world');
            reader.onClose(() => languageClient.stop());
      };
    }

    private createUrl (hostname: string, port: number, path: string): string {
        const protocol = location.protocol === 'https:' ? 'wss' : 'ws';
        return normalizeUrl(`${protocol}://${hostname}:${port}${path}`);
    }
    
    private createLanguageClient (transports: MessageTransports): MonacoLanguageClient {
      return new MonacoLanguageClient({
          name: 'lsp-cpp',
          clientOptions: {
              // use a language id as a document selector
              documentSelector: ['cpp'],
              // disable the default error handler
              errorHandler: {
                  error: () => ({ action: ErrorAction.Continue }),
                  closed: () => ({ action: CloseAction.DoNotRestart })
              }
          },
          // create a language client connection from the JSON RPC connection on demand
          connectionProvider: {
              get: () => Promise.resolve(transports)
          }
      });
    }
}

```

**Comment by kaisalmen** [comment]
Thanks, so the server now starts without errors only the client produces errors = you solved your initial problem?. Is that correct?

**Comment by KamiC6238** [comment]
> Thanks, so the server now starts without errors only the client produces errors = you solved your initial problem?. Is that correct?

the server starts without errors, but when the client send request to the. server, look likes some error config in my server code

![image](https://user-images.githubusercontent.com/23523595/197711866-42088096-1e14-4871-a314-c004380b6be0.png)

**Comment by CGNonofr** [comment]
The error is telling you it expect a list of workspace folders, you are supposed to provide them as parameter of the `MonacoServices.install` call

**Comment by KamiC6238** [comment]
> 

Hi @CGNonofr , i tried to set the workspaceFolders as parameter in the `MonacoServices.install` like the follow code.
```javascript
private install() {
    const modelUri = this.editor?.getModel()?.uri;
    
    if (modelUri?.path) {
        MonacoServices.install({rootPath: `file://${modelUri?.path}`, workspaceFolders: []});
    }
}
```

and the model uri in the elemetns.

![image](https://user-images.githubusercontent.com/23523595/197978805-693ec5cb-760c-4c76-9d99-5cc2b348a7ef.png)

when i restart my client, i got the another error, is there an error of the model uri ?

![image](https://user-images.githubusercontent.com/23523595/197979074-882fc8df-0a03-4e17-89bb-884311bcf329.png)

**Comment by CGNonofr** [comment]
I see 2 things wrong with your `rootPath`:
- it's an uri, not a path
- it's the uri of your file and not a directory

**Comment by KamiC6238** [comment]
> I see 2 things wrong with your `rootPath`:
> 
> * it's an uri, not a path
> * it's the uri of your file and not a directory

thanks for you help, but when i change the rootPath with the uri.path, the error still exist could you told my what can i do to resolve this problem?

```javascript
private install() {
    const modelUri = this.editor?.getModel()?.uri;
    
    if (modelUri) {
        const rootPath = modelUri.path.replace(/^\//, ''); // model.cpp
        MonacoServices.install({rootPath, workspaceFolders: []});
    }
}
```

<img width="582" alt="image" src="https://user-images.githubusercontent.com/23523595/198066770-563c5cd8-32a1-4efc-b4fa-2f0ab456bf1c.png">

**Comment by CGNonofr** [comment]
I have no idea why you removed the `/` from the path since it's the only thing you should have kept. you are asked for the rootPath of your workspace

What contains the init message sent to the server?

**Comment by CGNonofr** [comment]
It seems your service install are ignored, do you do it BEFORE creating a language client?

**Comment by CGNonofr** [comment]
Except if your model doesn't exist yet!

If that's not the issue, the only thing that I see is a duplicated dependency, what is the result of `npm list monaco-languageclient vscode`?

**Comment by KamiC6238** [comment]
> 

i am ensure the model exist before the `MonacoServices.install`, and the result of `npm list monaco-languageclient vscode` in the follow pic.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/23523595/198073912-b57ddc0f-d5af-40e6-8dfd-d0ec90db680d.png">

**Comment by KamiC6238** [comment]
[vue-monaco.zip](https://github.com/TypeFox/monaco-languageclient/files/9871196/vue-monaco.zip)

that is a simple vue3 project, I don't know if you've ever used vue3, but I think you only need to execute `yarn` and `yarn dev` to get started

**Comment by CGNonofr** [comment]
Ok it seems the rootPath is not even used, what you have to provide in at least one workspace folder (the rootPath/rootUri is retrieved from it)

**Comment by KamiC6238** [comment]
> 

thanks so so very much!!! This time i did.

use the follow code can start language client successfully!
```javascript
private async install() {
    const modelUri = this.editor?.getModel()?.uri;
    
    if (modelUri) {
        await MonacoServices.install({
            rootPath: modelUri.path,
            workspaceFolders: [{
                rootPath: modelUri.path,
                uri: modelUri
            }]
        });
    }
}
```

![image](https://user-images.githubusercontent.com/23523595/198243798-b0637d55-90c7-4c01-947a-2a790fe147e9.png)

**Comment by CGNonofr** [comment]
but still, you're not supposed to provide the model uri/path as workspace folder, it's supposed to be a folder

(and rootPath is useless, and the folder expect an index and a name, and not a rootPath, doesn't typescript complain about it?)

**Comment by KamiC6238** [comment]
> 
there is a diagnostics when i install `npm:@codingame/monaco-vscode-api` and  `@types/vscode`, i think this time i can start my monaco-languageclient journey, thank you very much.
```javascript
private async install() {
    const modelUri = this.editor?.getModel()?.uri;
    
    if (modelUri) {
        await MonacoServices.install({
            workspaceFolders: [{
                uri: modelUri,
                name: modelUri.path,
                index: 0
            }]
        });
    }
}
```
