### ISSUE TITLE
SyntaxError on firefox

### ISSUE THREAD

**Issue by LXYan2333** [TypeFox/monaco-languageclient#437]
`SyntaxError: import declarations may only appear at top level of a module`

Steps to reproduce:

1. clone this repo
2. build and start it following the README
3. open [http://localhost:8080/packages/examples/browser-lsp/index.html](http://localhost:8080/packages/examples/browser-lsp/index.html) in Firefox
4. notice the colour picker does't appear
5. open firefox console and notice the error message: `SyntaxError: import declarations may only appear at top level of a module [serverWorker.ts:1](http://localhost:8080/packages/examples/browser-lsp/src/serverWorker.ts)`

![图片](https://user-images.githubusercontent.com/15712263/204738314-850aab41-ef4f-4fc5-8aed-235369e0c32a.png)

It only happens on the firefox browser. This example works fine on the Edge browser.

**Comment by kaisalmen** [comment]
Hi @LXYan2333 this is a shortcoming of Firefox, It does not support module workers (https://bugzilla.mozilla.org/show_bug.cgi?id=1247687). All other major browsers support this, some for 5+ years.

Firefox worker support would require a build step that creates a worker in IIFE format.
I took the simple approach for this example excluding Firefox support. I propose to add a note on the page, so people are aware.

**Comment by kaisalmen** [comment]
I added the note with ebba8828f4c55e2df2fe5d2d6fe65767cd17e8b8 (main branch)
