### ISSUE TITLE
babel compile error when use getMessageServiceOverride

### ISSUE THREAD

**Issue by KamiC6238** [TypeFox/monaco-languageclient#439]
i am trying to use monaco-languageclient in my project like [examples](https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/react-client/src/app.tsx), and then when i re build my project in local, i got an error like that with babel.
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/23523595/207248852-760ffab2-2c0c-40fb-a73e-4486bbd096b6.png">

npm version:
monaco-vscode-api: 1.69.13
monaco-editor: 0.34.0

```typescript
StandaloneServices.initialize({
    ...getMessageServiceOverride(window.document.body),
})
```

And in the `monaco-vscode-api@1.69.13`, i saw the getMessageServiceOverride was deprecated.. 

![image](https://user-images.githubusercontent.com/23523595/207249148-26e0f1b9-5e79-42ba-a807-0e676fa51c72.png)

Could some one tell me how to solve this problem? it would be appreciated!!

**Comment by CGNonofr** [comment]
`getMessageServiceOverride` is deprecated just because it was split into `getNotificationServiceOverride` and `getDialogServiceOverride`, there's no big deal, I will add a documentation about it :+1:

But your error is not related to it, I already had it and didn't find any solution other than preventing babel from transforming classes into functions (which is probably not required 99.99% of the time)

**Comment by KamiC6238** [comment]
> `getMessageServiceOverride` is deprecated just because it was split into `getNotificationServiceOverride` and `getDialogServiceOverride`, there's no big deal, I will add a documentation about it 👍
> 
> But your error is not related to it, I already had it and didn't find any solution other than preventing babel from transforming classes into functions (which is probably not required 99.99% of the time). `vscode`/`monaco` uses `instanceof` quite often and it doesn't resist much to hardcode babel transformations like this one.

Thanks for you answer.

So i can assume that even removing the `getMessageServiceOverride` won't affect `monaco-languageclient` (Otherwise i cannot compile successfully locally)?

**Comment by CGNonofr** [comment]
Yep it's only used to display notifications and alert popins that some LSP implementations need, you can remove it, it will just use the default monaco implementation that logs it to the console

**Comment by KamiC6238** [comment]
> 

OK, thanks very much.
