### ISSUE TITLE
Should we stop re-exporting other libraries?

### ISSUE THREAD

**Issue by kaisalmen** [TypeFox/monaco-languageclient#447]
`vscode-ws-jsonrpc` re-exports things from `vscode-jsonrpc`.
`monaco-languageclient` also re-exports parts of the api of `vscode-jsonrpc` and `vscode-languageserver-protocol`. 

I am asking myself if we should continue doing that, because it hides the fact people are using other libraries and the re-export is a helpful, but necessarily good. This would be a major breaking change and bump versions to 3 and 5.

@CGNonofr what is your opinion about this?

**Comment by CGNonofr** [comment]
I don't have a strong opinion on it. It would probably be better and simpler to maintain

**Comment by kaisalmen** [comment]
It will have an impact on lib users when upgrading (wrong imports), but IMO it is better that people are made more directly aware we are "extending"/"incorporating" existing functionality of other libraries.
And if you take the whole modules approach seriously we should not do what we currently do. There are uses cases where it makes sense (as there always are exceptions to a rule), but here it is not the case.
A question I am asking myself: Do we piss off people and are we ok with x issues telling us that imports are broken after update to versions 3 and 5.

**Comment by CGNonofr** [comment]
My opinion is we should always do what's best for any new user of the library. If we break the compatibility, we can just change the major version, add a breaking change section and that's it. And we're just talking about changing import, it wouldn't be a so huge pain

**Comment by kaisalmen** [comment]
This is now implemented with version `vscode-ws-jsonrpc` version `3.0.0` and `monaco-languageclient` version `5.0.0`.
