### ISSUE TITLE
Unable to integrate language server

### ISSUE THREAD

**Issue by chaitanya71998** [TypeFox/monaco-languageclient#449]
Greetings, 
I was trying to integrate monaco language client to [suren-atoyan](https://github.com/suren-atoyan)/[monaco-react](https://github.com/suren-atoyan/monaco-react)
 but unable to get the suggestions. when working with the the example it was working fine, but when using this react package i was not getting suggestions, seems the server is detecting the changes.  Can you check what i was missing here?
 here is code link i was trying this approach in https://github.com/chaitanya71998/monaco-language-testing-with-java
![Screenshot from 2023-01-06 21-25-50](https://user-images.githubusercontent.com/46353549/211049162-1da58cc5-b5f8-48c6-9b01-898714de4b2c.png)

**Comment by CGNonofr** [comment]
> Monaco Editor for React · use the [monaco-editor](https://microsoft.github.io/monaco-editor/) in any [React](https://reactjs.org/) application without needing to use webpack (or rollup/parcel/etc) configuration files / plugins

This library can only work on the ESM version of monaco-editor, installed in the node_modules, so I doubt you will be able to make it work with [suren-atoyan](https://github.com/suren-atoyan)/[monaco-react](https://github.com/suren-atoyan/monaco-react) which I guess is using a CDN version of monaco editor

**Comment by CGNonofr** [comment]
It seems it's using `@monaco-editor/loader` like another library which had the same issue and there is a solution, but it'll make it depend on a bundler to work (I don't remember exactly the solution, it's somewhere in the issues)

**Comment by chaitanya71998** [comment]
@CGNonofr can you share the issue, i couldn't find it.

**Comment by CGNonofr** [comment]
Found it: https://github.com/TypeFox/monaco-languageclient/issues/423#issuecomment-1255995975

**Comment by chaitanya71998** [comment]
@CGNonofr  even i was doing same. 
https://github.com/chaitanya71998/monaco-language-testing-with-java

**Comment by chaitanya71998** [comment]
after making both the java eclipse server and file root directory ("/home") the suggestions are working fine for the above example.
But i have got another issues with a new apporach:
->  i am creating all the file creation and updating content, etc stuff on server side. 
-> I also created the java language server to run on server itself. this was working fine.
issues: 
1. because of giving the -data attribute in args, I was getting some extra java files loading into that directory and getting stored. If that continous the unwanted files gets stored as below. how can we remove them, cant we block them to form?
![Screenshot from 2023-01-07 17-07-39](https://user-images.githubusercontent.com/46353549/211148789-e4da756a-8899-4002-9762-e4c194f20fb9.png)

2. Also not knowing why the suggestion are not coming when loading files over server side

**Comment by chaitanya71998** [comment]
@kaisalmen do you have any idea on these random files created as shown above image?

**Comment by CGNonofr** [comment]
May I suggest asking it on the jdt.ls repo as they're the ones who create those files
