### ISSUE TITLE
update vscode-jsonrpc@6.0.0 to vscode-jsonrpc@latest

### ISSUE THREAD

**Issue by dxgi** [TypeFox/monaco-languageclient#451]
update vscode-jsonrpc@6.0.0 to vscode-jsonrpc@latest

having issues with vscode-ws-jsonrpc and monaco-jsonrpc because outdated and overdated

**Comment by CGNonofr** [comment]
vscode-ws-jsonrpc already uses the last version of vscode-jsonrpc, and monaco-jsonrpc is deprecated

**Comment by kaisalmen** [comment]
This is not an issue!
