### ISSUE TITLE
Cannot resolve vscode/services

### ISSUE THREAD

**Issue by CraigMeng** [TypeFox/monaco-languageclient#458]
Hi,

Thank you very much for the efforts!

I want to upgrade language client follow the documentation and troubleshooting recently but got compiling error.
I tried to remove lots of codes and managed to get a minimal example here: https://github.com/CraigMeng/monaco-webpack-node-12

The error I got:

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/4469305/217006336-febe7bb2-7d55-41fb-a8e4-11f72c2f8408.png">

**Comment by CraigMeng** [comment]
node version: 12.22.12

**Comment by CGNonofr** [comment]
Your  issue is probably related to the usage of webpack@4 which is not able to understand [subpath exports](https://nodejs.org/api/packages.html#subpath-exports). Webpack 5 is fine with it (and was released more than 2 years ago)

Btw, note that you have another issue: vscode is duplicated in your project and it will create issues:

![image](https://user-images.githubusercontent.com/23257479/217050041-8145ce84-9bca-4687-b642-83fd640f19d8.png)

@kaisalmen We have probably a too strict dependency version here, we're missing a `~`

**Comment by kaisalmen** [comment]
@CGNonofr yes, you are right. I just checked. The peerDependency definition is correct, but there is still a separate dependency that is strict. I will fix/remove this in the upcoming days

**Comment by CraigMeng** [comment]
@CGNonofr Thank you! Yes, it is webpack 4 issue and I confirm that it works very well after upgrade to webpack5
