### ISSUE TITLE
monaco-languageclient/lib/vscode-compatibility is nowhere to be found.

### ISSUE THREAD

**Issue by dxgi** [TypeFox/monaco-languageclient#460]
![image](https://user-images.githubusercontent.com/61899298/219934817-aa15699a-6cce-4160-94b7-178108b4ddb6.png)
![image](https://user-images.githubusercontent.com/61899298/219934820-1b3349d5-8eb1-48e6-a694-783ef6fe298d.png)

could not resolve the vscode-compatibility

**Comment by CGNonofr** [comment]
What documentation are you following? You need no alias.

The first one doesn't exist for months, the second one brakes everything by redirectong any subimport in vscode to the main export

**Comment by CGNonofr** [comment]
Check tour monaco editor version

**Comment by CGNonofr** [comment]
The lib wasn't updated yet to the 0.35

**Comment by CGNonofr** [comment]
Can you please explain how for others who may have the same issue ?

**Comment by kaisalmen** [comment]
Btw, we have these sections in the README:
https://github.com/TypeFox/monaco-languageclient#monaco-editor-compatibility-table
https://github.com/TypeFox/monaco-languageclient#troubleshooting

Didn't `yarn install` warn you about the incorrect peerDependency `monaco-vscode-api` demands?
