### ISSUE TITLE
Help needed for Angular Project

### ISSUE THREAD

**Issue by kaivalyapendse** [TypeFox/monaco-languageclient#467]
Hi, 
We have angular project and have used ngx-monaco-editor and now we want use monaco-language clinet for python syntax error checking and auto code completion. **We are at TS version 3.8.3**. When I install the compatible monaco-language version with respect to monaco editor, I keep getting compilation error for vscode npm modules such as vscode-languageclient, vscode-languageserver-protocol,vscode-languageserver-types mainly due to typescript version mismatch. Please help to use the monaco-languageclient for the TS version.

**Comment by CGNonofr** [comment]
Hello,

Please provide some error and I don't think anyone will be able to help.

Also what are the version of monaco-editor/monaco-languageclient you are using?

**Comment by kaivalyapendse** [comment]
![image](https://user-images.githubusercontent.com/42967267/224055133-56d0e681-8e13-4e50-8288-4e854d95ad89.png)

Similar errors for all vscode related modules.

**Comment by kaisalmen** [comment]
@kaivalyapendse did you check our own angular example?
https://github.com/TypeFox/monaco-languageclient/tree/main/packages/examples/angular-client
