### ISSUE TITLE
FindController is Not  Working

### ISSUE THREAD

**Issue by LavanyaBurlagadda** [TypeFox/monaco-languageclient#468]
We are monaco editor in our custom IDE.

We tried to integrate Java Language Server.

To do that we have used monaco-languageclient.

Now when I am adding config

`loader.config({ monaco });`

FindController Functionality is Not Working

When clicking on CTRL + F showing below warning and executing the functionality

![image](https://user-images.githubusercontent.com/48449639/225559900-24e69fbc-cf02-48ae-828d-d2e478e7131e.png)

**Comment by CGNonofr** [comment]
I don't know about that specific issue but the error message rings a bell to me. The last time I've seen it, it was because the babel config was transpiling classes into function (to support very old browser). I don't think it's required anymore

**Comment by kaisalmen** [comment]
@CGNonofr reality outlived this one?

**Comment by CGNonofr** [comment]
> reality outlived this one?

What do you mean?

**Comment by kaisalmen** [comment]
@CGNonofr do you think this problem will still appear in the current version?

**Comment by CGNonofr** [comment]
I do think so, as soon as you ask babel to transpile to very old javascript

**Comment by kaisalmen** [comment]
> The last time I've seen it, it was because the babel config was transpiling classes into function (to support very old browsers). I don't think it's required anymore

Ok, thanks... and if I had been able to read what you wrote a couple of months ago, I should have just closed the issue directly. 😆
