### ISSUE TITLE
Problem in connecting to an external Java language server

### ISSUE THREAD

**Issue by afroozeh** [TypeFox/monaco-languageclient#47]
I'm trying to use your library to connect monaco to an external Java Language Server.

I tried both https://github.com/eclipse/eclipse.jdt.ls and https://github.com/georgewfraser/vscode-javac.
It looks like that I can connect to the server, and the 'initialize' message is sent, but 
after that there is no communication between the client and server.

In order to connect to the external Java server, I modified the file 'json-server-launcher.ts'
and add this line:

```
const serverConnection = server.createServerProcess('Java', "java", args);`
```
where args are the arguments to run the Java language server. For example, for the
'vscode-javac' server, I use 

```
let fatJar = "fat-jar.jar";
         
const args = [
    '-cp', fatJar, 
    '-Djavacs.port=' + 3000,
    '-Xverify:none', // helps VisualVM avoid 'error 62'
    'org.javacs.Main'
];
```

I also registered the Java language to monaco languages, and use `documentSelector: ['java']`.

Is this the way I am supposed to connect to a non-node language server?

**Comment by akosyakov** [comment]
`createServerProcesss` will use stdin/stdout for communications, it seems that `vscode-javac` is using sockets instead:
- https://github.com/georgewfraser/vscode-javac/blob/a36635d29240ea4f460149b65e1f4281ab7725c3/lib/Main.ts#L63
- https://github.com/georgewfraser/vscode-javac/blob/92a11c89fba02d0dbe94d2ce2f367622612731a9/src/main/java/org/javacs/Main.java#L100

**Comment by afroozeh** [comment]
Thanks! I replaced sockets with standard io in 'vscode-javac' and it looks like that now I can communicate with the server:

```
{ jsonrpc: '2.0',
  method: 'window/logMessage',
  params: { type: 3, message: 'java.version is 1.8.0_131' } }
{ jsonrpc: '2.0',
  id: '0',
  result: 
   { capabilities: 
      { textDocumentSync: 2,
        hoverProvider: true,
        completionProvider: [Object],
        signatureHelpProvider: [Object],
        definitionProvider: true,
        referencesProvider: true,
        documentSymbolProvider: true,
        workspaceSymbolProvider: true,
        codeActionProvider: true,
        executeCommandProvider: [Object] } } }
{ jsonrpc: '2.0', method: 'initialized', params: {} }
```
However, nothing happens after this point. I think this is because the monaco-editor is not linked to a file on the server. Is there a way to identify a document on the server instead of 'inmemory://..'

**Comment by akosyakov** [comment]
There are 2 things:
- when you create an instance of the Monaco editor you should provide a file URI
- the second you can provide a workspace URI when you create Monaco services: https://github.com/TypeFox/monaco-languageclient/blob/f0f2c10a66ec7f7e88e35d7e3f446a3ad219643b/src/services.ts#L24

**Comment by afroozeh** [comment]
Great! by providing the file URL, the language server can send me some diagnostic messages and provide completion. My concern is that I have to provide the full file path on the server, which may not be desirable to expose it in the client code. Is there a way around it?

Also, I noticed that I don't get Java syntax highlighting in the editor. A standalone monaco editor can show syntax highlighting even without registering the language. Is it related to the monaco version used in the examples, or some other settings?

**Comment by rcjsuen** [comment]
@afroozeh Did you try providing a valid file URI that doesn't point to the actual path of the file (for example like a `test/src2/Test.java`? It may be a limitation of the Java language server that it is incapable of working with "fake" files. As Java requires a build path and (outside of homework assignments) multiple other Java source files to compile, it is not unreasonable for the language server to need real information to where the physical files are stored.

Perhaps you can try reaching out to the Java language server team and see if they can help you. I believe the language server is used by both [Eclipse Che](https://github.com/eclipse/che/) and [Theia](https://github.com/theia-ide/theia) so it should be possible to "live in the cloud".

**Comment by afroozeh** [comment]
@rcjsuen I cannot get it working with an abstract URL, but you are right, I should contact the Java Language Server team to see if there is a way around it.

@akosyakov @rcjsuen About the syntax highlighting, a standalone monaco editor can show syntax highlighting for the 'java' language even without registering the language, but when I run the example from this repository the syntax highlighting is not there. Is it related to the monaco version used in the examples, or some other settings?

**Comment by akosyakov** [comment]
Java language should be registered, you can do it with https://github.com/Microsoft/monaco-languages

**Comment by afroozeh** [comment]
monaco-editor has all the language definitions in it: "This npm module is bundled and distributed in the monaco-editor npm module."

The problem is that monaco-languageclient has a dependency on monaco-editor-core which doesn't have the languages inside by default. I removed the dependency on monaco-editor-core and syntax highlighting works out of the box :-) I already see a PR for removing the dependency on 'monaco-editor-core', otherwise, I can create a PR from the changes.

**Comment by akosyakov** [comment]
@afroozeh I've just merged it

**Comment by afroozeh** [comment]
Great, thanks for your help. I'm closing the issue now!

**Comment by akosyakov** [comment]
You are welcome, please don't forget to :star: the repo :pray:

**Comment by Ruhshan** [comment]
> Thanks! I replaced sockets with standard io in 'vscode-javac' and it looks like that now I can communicate with the server:
> 
> ```
> { jsonrpc: '2.0',
>   method: 'window/logMessage',
>   params: { type: 3, message: 'java.version is 1.8.0_131' } }
> { jsonrpc: '2.0',
>   id: '0',
>   result: 
>    { capabilities: 
>       { textDocumentSync: 2,
>         hoverProvider: true,
>         completionProvider: [Object],
>         signatureHelpProvider: [Object],
>         definitionProvider: true,
>         referencesProvider: true,
>         documentSymbolProvider: true,
>         workspaceSymbolProvider: true,
>         codeActionProvider: true,
>         executeCommandProvider: [Object] } } }
> { jsonrpc: '2.0', method: 'initialized', params: {} }
> ```
> 
> However, nothing happens after this point. I think this is because the monaco-editor is not linked to a file on the server. Is there a way to identify a document on the server instead of 'inmemory://..'

Hello, how did you **replaced sockets with stdio**? For me without doing anything in vscode-javac I was able to get these logs:

```{
  jsonrpc: '2.0',
  id: 0,
  method: 'initialize',
  params: {
    processId: 1,
    clientInfo: { name: 'vscode' },
    rootPath: '/Users/ruhshan_admin/IdeaProjects/chacing-example/src/main/java/xyz/ruhshan/chacingexample/HelloWorld.java',
    rootUri: 'file:///Users/ruhshan_admin/IdeaProjects/chacing-example/src/main/java/xyz/ruhshan/chacingexample/HelloWorld.java',
    capabilities: { workspace: [Object], textDocument: [Object] },
    trace: 'off',
    workspaceFolders: [ [Object] ]
  }
}
JSON Server: 13:35:46.061       INFO    LSP connect     Reading messages from queue...

JSON Server: 13:35:46.061       INFO    LSP$1MessageReader run  Placing incoming messages on queue...

{
  jsonrpc: '2.0',
  id: 0,
  result: {
    capabilities: {
      textDocumentSync: 2,
      hoverProvider: true,
      completionProvider: [Object],
      signatureHelpProvider: [Object],
      referencesProvider: true,
      definitionProvider: true,
      workspaceSymbolProvider: true,
      documentSymbolProvider: true,
      documentFormattingProvider: true,
      codeLensProvider: {},
      foldingRangeProvider: true,
      codeActionProvider: true,
      renameProvider: [Object]
    }
  }
}
{ jsonrpc: '2.0', method: 'initialized', params: {} }
{
  jsonrpc: '2.0',
  method: 'client/registerCapability',
  params: {
    id: '12b07653-6279-461c-ae03-0b665c5f01ec',
    method: 'workspace/didChangeWatchedFiles',
    registerOptions: { watchers: [Array] }
  }
}
```

But syntax highlighting doesn't works nor receiving any suggestions. 
Thanks in advance @afroozeh

**Comment by rcjsuen** [comment]
> But syntax highlighting doesn't works

Syntax highlighting should be provided by the Monaco Editor by default...or are you talking about semantic highlighting?

> nor receiving any suggestions.

If you invoke code completion with <kbd>Ctrl</kbd>+<kbd>Space</kbd>, what happens? Do you see any traffic between the server and the client?
