### ISSUE TITLE
please why this question?

### ISSUE THREAD

**Issue by NightMingGit** [TypeFox/monaco-languageclient#472]
![image](https://user-images.githubusercontent.com/92633021/228506653-df667d5e-623e-4483-9f46-710dbed43d06.png)

**Comment by kaisalmen** [comment]
Hi @NightMingGit this is an error already fixed on the **update-monaco-vscode-1.76** branch that is not yet merged back.

**Comment by kaisalmen** [comment]
I just pushed an update on the main branch.

**Comment by NightMingGit** [comment]
> I just pushed an update on the main branch.

ok thank you

**Comment by NightMingGit** [comment]
Do you have any plans  add  "[Eclipse JDT Language Server](”https://github.com/eclipse/eclipse.jdt.ls“) “ a demo?

**Comment by kaisalmen** [comment]
Not right now, but if you want to contribute one you are welcome. 🙂

**Comment by kaisalmen** [comment]
There was an additional error in the start script instruction. I pushed an update and verified it works now. The external server requires the example sources to be compiled otherwise `../../dist/server/ext-json-server.js` does not exist,

**Comment by NightMingGit** [comment]
> There was an additional error in the start script instruction. I pushed an update and verified it works now. The external server requires the example sources to be compiled otherwise `../../dist/server/ext-json-server.js` does not exist,

i try tomorrow

**Comment by NightMingGit** [comment]
> There was an additional error in the start script instruction. I pushed an update and verified it works now. The external server requires the example sources to be compiled otherwise `../../dist/server/ext-json-server.js` does not exist,

excuse me, this  question Is this a Java issue？
![image](https://user-images.githubusercontent.com/92633021/228710213-7a565f3d-fd8c-4940-92fb-2e89cf7a183e.png)

**Comment by kaisalmen** [comment]
Did you check the logs of the Java Language Server (JDT). It seems `java.show.references` is not supported or not working. Try to describe what you do more precisely. A screenshot without explanation does not give is much context.

**Comment by CGNonofr** [comment]
The `java.show.references` command is registered by the vscode extension: https://github.com/redhat-developer/vscode-java/blob/7e7dfa945f87630daf7a039fa78de8e013904b0e/src/standardLanguageClient.ts#L306

**Comment by NightMingGit** [comment]
> Did you check the logs of the Java Language Server (JDT). It seems `java.show.references` is not supported or not working. Try to describe what you do more precisely. A screenshot without explanation does not give is much context.

click "0 references" not send order to javaLsp server
![image](https://user-images.githubusercontent.com/92633021/228763985-d4721aa1-376c-459d-ba0a-efeacc0ca4ea.png)

**Comment by NightMingGit** [comment]
> The java LSP loves to to create a lot of non standard commands and let the vscode extension register them
> 
> But you can copy/paste the code from the vscode extension

i will try

**Comment by NightMingGit** [comment]
> java.show.references

How should I register? in server or client?

**Comment by NightMingGit** [comment]
> 我不确定您在谈论时指的是什么`server`，[我链接的代码](https://github.com/redhat-developer/vscode-java/blob/7e7dfa945f87630daf7a039fa78de8e013904b0e/src/standardLanguageClient.ts#L306)在 vscode 中运行，所以在客户端中
> 
> =>
> 
> ```ts
> import { Location as LSLocation } from "vscode-languageclient";
> import * as vscode from 'vscode'
> 
> const disposable = vscode.commands.registerCommand('java.show.references', (uri: string, position: LSPosition, locations: LSLocation[]) => {
>     commands.executeCommand('editor.action.showReferences', Uri.parse(uri), languageClient.protocol2CodeConverter.asPosition(position), locations.map(languageClient.protocol2CodeConverter.asLocation));
> })
> ```
> 
> 请注意，您可能还需要在https://github.com/redhat-developer/vscode-java/blob/7e7dfa945f87630daf7a039fa78de8e013904b0e/src/standardLanguageClient.ts中注册的其他命令

i use this  server way
![image](https://user-images.githubusercontent.com/92633021/228767467-f3840402-6032-45e6-87b9-ad4feda03478.png)

**Comment by NightMingGit** [comment]
i Modified demo code

**Comment by NightMingGit** [comment]
this client
![image](https://user-images.githubusercontent.com/92633021/228768283-e107a2c2-823d-4cd3-bea7-b3d9a00d4255.png)

**Comment by CGNonofr** [comment]
Did you add the code I provided?

**Comment by NightMingGit** [comment]
> Did you add the code I provided?

sorry,I don't know where to add it yet

**Comment by CGNonofr** [comment]
As soon as the language client is started, you can run it (don't forgot to dispose it when the language client is disposed)

**Comment by NightMingGit** [comment]
i mean this code i need  add  where?
![image](https://user-images.githubusercontent.com/92633021/228770669-6787df71-4b0c-45be-ac86-d416244f546d.png)

**Comment by NightMingGit** [comment]
> `As soon as the language client is started` means after you call `languageClient.start()`

on the client ,
How should I register java.show.references

**Comment by NightMingGit** [comment]
> I don't understand why you keep pasting the same code.
> 
> I literally told you what to do, put the code I provided after `languageClient.start()`

sorry,I didn't understand what you meant before

**Comment by NightMingGit** [comment]
> I don't understand why you keep pasting the same code.
> 
> I literally told you what to do, put the code I provided after `languageClient.start()`

hello  now  i use     "monaco-languageclient": "^0.18.1"
How do I achieve?
`import { Location as LSLocation } from "vscode-languageclient";
import * as vscode from 'vscode'

const disposable = vscode.commands.registerCommand('java.show.references', (uri: string, position: LSPosition, locations: LSLocation[]) => {
    commands.executeCommand('editor.action.showReferences', Uri.parse(uri), languageClient.protocol2CodeConverter.asPosition(position), locations.map(languageClient.protocol2CodeConverter.asLocation));
})`

**Comment by NightMingGit** [comment]
> references

this is my vesrion 
`"@codingame/monaco-jsonrpc": "^0.3.1",
    "monaco-editor": "^0.30.0",
    "monaco-languageclient": "^0.18.1",`


![image](https://user-images.githubusercontent.com/92633021/229012859-15f397fb-58c6-4eed-8b04-17c0b3bdf4f2.png)

**Comment by NightMingGit** [comment]
this is my code
`<script>
const {ipcRenderer} = window.require('electron')
import {listen} from "@codingame/monaco-jsonrpc"
import * as monaco from 'monaco-editor'
// import 'monaco-editor/esm/vs/basic-languages/java/java.contribution'
const {
  MonacoLanguageClient,
  CloseAction,
  ErrorAction,
  MonacoServices,
  createConnection
} = require('monaco-languageclient')

export default {
  name: 'JavaEditor',
  data() {
    return {
      editor: null,
      websocket: null,
      model: null
    }
  },
  methods: {
    createLanguageClient(connection) {
      return new MonacoLanguageClient({
        name: "Java LSP client",
        clientOptions: {
          documentSelector: ['java'],
          errorHandler: {
            error: () => ErrorAction.Continue,
            closed: () => CloseAction.DoNotRestart
          }
        },
        connectionProvider: {
          get: (errorHandler, closeHandler) => {
            return Promise.resolve(createConnection(connection, errorHandler, closeHandler))
          }
        }
      })
    },
    createModel(filePath) {
      let fileContent = window.require('fs').readFileSync(filePath, 'utf-8').toString()
      return monaco.editor.createModel(fileContent, 'java', monaco.Uri.file(filePath))
    }
  },
  mounted() {

    let self = this
    MonacoServices.install(monaco)
    ipcRenderer.on('open', (event, filePath) => {
      let first = !this.model
      let model = monaco.editor.getModel(monaco.Uri.file(filePath))
      if (!model) {
        model = this.createModel(filePath)
      }
      this.model = model
      if (first) {
        this.$nextTick(() => {
          this.editor = monaco.editor.create(this.$refs.main, {
            model: model
          })
          console.log()
          const url = 'ws://127.0.0.1:3000/sampleServer'
          this.websocket = new WebSocket(url)
          listen({
            webSocket: self.websocket,
            onConnection: connection => {
              console.log("connect")
              const client = self.createLanguageClient(connection);
              const disposable = client.start()
              connection.onClose(() => disposable.dispose());
              console.log(`Connected to "${url}" and started the language client.`);
            }
          })
        })
      } else {
        this.editor.setModel(model)
      }

    })
    ipcRenderer.on('save', () => {
      if (this.model) {
        window.require('fs').writeFileSync(this.model.uri.fsPath, this.model.getValue())
      }
    })
  }

}
</script>`

**Comment by CGNonofr** [comment]
We won't offer support on old versions of the library

**Comment by NightMingGit** [comment]
> We won't offer support on old versions of the library

Can you provide a demo of electron+vite?
