### ISSUE TITLE
server configuration for new language

### ISSUE THREAD

**Issue by lyudad** [TypeFox/monaco-languageclient#48]
In example server was used  `vscode-json-languageservice` as LanguageService. But if I want use language that doesn't has existed `languageservice` packages (`javascript`). 
On client side everything clear (register language, set configuration)
```
monaco.languages.register({
            id: JAVASCRIPT_LANGUAGE_ID,
            extensions: ['.js', '.jsx'],
            aliases: [JAVASCRIPT_LANGUAGE_NAME, 'js', 'javascript'],
            mimetypes: ['text/javascript'],
 });
monaco.languages.onLanguage(JAVASCRIPT_LANGUAGE_ID, () => {
            monaco.languages.setLanguageConfiguration(JAVASCRIPT_LANGUAGE_ID, genericEditConfiguration);
            monaco.languages.setTokensProvider(JAVASCRIPT_LANGUAGE_ID, createTokenizationSupport(Language.EcmaScript5));
});
```

but on the server side I can't find what I should return on connection events (for example for `connection.onCompletion`)

**Comment by akosyakov** [comment]
@lyudad Hi, the language server for js/ts does exist: https://github.com/theia-ide/typescript-language-server

You can look at the ts extension for Theia https://github.com/theia-ide/theia/tree/master/packages/typescript/src. It is a bit involving but it shows how to integrate it with Monaco.

**Comment by lyudad** [comment]
Thanks. I will look.

**Comment by akosyakov** [comment]
You are welcome! if you find projects interesting, please :star: their repos :pray:
