### ISSUE TITLE
Critical dependency warning

### ISSUE THREAD

**Issue by todwang** [TypeFox/monaco-languageclient#487]
hi,
when  I import the package(monaco-languageclient@5.0.1) in my nextjs project I got:
`
warn  - Compiled with warnings

../../node_modules/.pnpm/vscode-languageserver-types@3.17.3/node_modules/vscode-languageserver-types/lib/umd/main.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
`

trace is
`
Import trace for requested module:
../../node_modules/.pnpm/vscode-languageserver-types@3.17.3/node_modules/vscode-languageserver-types/lib/umd/main.js
../../node_modules/.pnpm/vscode-languageserver-protocol@3.17.3/node_modules/vscode-languageserver-protocol/lib/common/api.js
../../node_modules/.pnpm/vscode-languageserver-protocol@3.17.3/node_modules/vscode-languageserver-protocol/lib/node/main.js
../../node_modules/.pnpm/vscode-languageclient@8.1.0/node_modules/vscode-languageclient/lib/common/client.js
../../node_modules/.pnpm/monaco-languageclient@5.0.1_@codingame+monaco-vscode-api@1.76.9/node_modules/monaco-languageclient/lib/monaco-language-client.js
../../node_modules/.pnpm/monaco-languageclient@5.0.1_@codingame+monaco-vscode-api@1.76.9/node_modules/monaco-languageclient/lib/index.js
`

could you tell me how to fixed this warning? pls

**Comment by kaisalmen** [comment]
Hi @todwang which underlying bundler is utilized in next.js? webpack?

**Comment by todwang** [comment]
> Hi @todwang which underlying bundler is utilized in next.js? webpack?

webpack

**Comment by kaisalmen** [comment]
Our verification example produces esm code with webpack 5, but defines some exclusion for source maps:
https://github.com/TypeFox/monaco-languageclient/blob/main/packages/verify/webpack/webpack.config.js

Maybe this can give you some idea.
If you could share your code/repository, we could try to re-produce it. Otherwise it is more guesswork. Thanks

**Comment by todwang** [comment]
this repo https://github.com/todwang/my-app.git can re-produce it

**Comment by kaisalmen** [comment]
@todwang next,js does not seem to like the UMD module it found, but it is only a waning and the build succeeds. I don't have experience with next.js, but if you want to get rid of the warning you need to dig into how to configure webpack regarding UMD module handling/transformation.

This is not an issue for this lib, IMO.
