### ISSUE TITLE
Pnpm and other hard cache based managers cannot work with patch

### ISSUE THREAD

**Issue by BusinessDuck** [TypeFox/monaco-languageclient#492]
Hi! As you may remember we had a discuss about pnpm and patching [here](https://github.com/TypeFox/monaco-languageclient/pull/485).

I know the reason of this error:

```bash
. postinstall$ monaco-treemending
. postinstall: Error: Unable to apply patch on 
```

Inside of pnpm we have hard package cache and `three-awesome` collecting all packages in to the one flat store without dependencies (symlinks used inside of internal packages deps folder) for example:

`monaco-language-client` depends from `monaco-editor`

```json
dependencies": {
    "monaco-editor": "~0.37.1",
...  },
  "peerDependencies": {
    "vscode": "npm:@codingame/monaco-vscode-api@~1.78.6",
    ...
```

pnpm will extract this packages and create single for `monaco-language-client` and root `package.json` of main project. That mean if `monaco-langauge-client` contains `postinstall` script, the patch will be applied to `symlinked` package. Then second call `postinstall` in project root inside `package.json` gonna be fall.

Possible solutions:

Remove postinstall from `monaco-languageclient` and move out from package main packgage.json to examples or something other dir

Also we need to fix treemending script patch already installed detection and show the info, "Already patched", in case when patch really installed 

Patch listing

```bash
diff --git a/package.json b/package.json
index 88c2d0ac8cac849a09c7bb534e52669323e1d7f1..dc881bc2bc5034b532429947780accd498bb7002 100644
--- a/package.json
+++ b/package.json
@@ -66,7 +66,6 @@
     }
   },
   "scripts": {
-    "postinstall": "monaco-treemending",
     "clean": "npx shx rm -fr lib *.tsbuildinfo",
     "compile": "tsc --build tsconfig.src.json",
     "build:msg": "echo Building monaco-languageclient:",
```

UPD: Patch didnt works for me :C

**Comment by BusinessDuck** [comment]
`pnpm i --ignore-scripts` works fine. Package `monaco-editor` didn't patched by `monaco-language-client`.

Can you please move out or remote postinstall from `monaco-language-client`, is that possible?

**Comment by kaisalmen** [comment]
@BusinessDuck a fix for detecting treemending was already applied is in the works (https://github.com/CodinGame/monaco-vscode-api/pull/115), but we are discussing the best wayforward currently. Then calling it n times will no longer cause problems.

**Comment by BusinessDuck** [comment]
I create my own patch by using `pnpm patch` cli, that works pretty. pnpm patch ist like `patch-package`, but out of the box. I dont know why u guys didn't use that patch software, but i see you calculates hashes manually, why? Patch-packgage already works with all corner cases inside of patch applying mechanism

**Comment by kaisalmen** [comment]
> patch-package, but out of the box. I dont know why u guys didn't use that patch software

Thanks for the hint. @CGNonofr what do you think about using https://www.npmjs.com/package/patch-package

**Comment by BusinessDuck** [comment]
Example with pnpm (i guess contracts are same)

**Step 1: Create patch**
`pnpm patch monaco-editor@0.37.1`

That will produce tmp folder to work with it for doing some modifications with package code. When you done with it go to step 2

**Step 2:  Commit patch**
`pnpm patch-commit {folder path that you receive on step 1}`

**Comment by CGNonofr** [comment]
I've considered it but AFAIK, patch-package only allows to patch a package from the final project, generating a patch file in a specific folder. Please tell me how to use it in our use case.

**Comment by BusinessDuck** [comment]
![image](https://github.com/TypeFox/monaco-languageclient/assets/10143411/bf3a5bf5-1de7-467e-b9c3-c33354078a1d)

pnpm make changes inside of package.json, when i use `pnpm i`, patches will be executed automatically.

in case with `patch-package` i guess https://github.com/ds300/patch-package#applying-patches

**Comment by CGNonofr** [comment]
Ok so with pnpm I guess you can use it, referencing `monaco-editor-treemending.patch` from monaco-vscode-api

```json
"patchedDependencies": {
  "monaco-editor@0.37.1": "node_modules/vscode/monaco-editor-treemending.patch"
}
```
?

**Comment by CGNonofr** [comment]
So what are you suggesting here?

**Comment by BusinessDuck** [comment]
Patch is absolutely same with fork in current case, because patch contains a log of changes... so much... :)

**Comment by CGNonofr** [comment]
> Move patch to the client side

What do you mean?

> completely fork monaco-editor to monaco-editor-vscode (patched) package

I've considered it, but it wouldn't allow to use other libraries using monaco-editor, like monaco-vim or monaco-emacs

**Comment by CGNonofr** [comment]
We had a fork of monaco-editor before, and we decided to give it up, it has some cons:
- We need to release a version of the fork for every version of the official monaco-editor (it can't be automated, and we would need to release both monaco-editor-core and monaco-editor)
- npm aliasing doesn't work very well when other libraries have `monaco-editor` as dependency and it creates conflicts
- webpack/rollup... aliases require configuration in the final project

At the end, it's simpler for the final user to include the postinstall script than requiring them to use a fork of monaco

**Comment by BusinessDuck** [comment]
Okay lets try do preinstall patch downloading from remote package. That may works fine with. And 

```
....
"scripts": 
    "preinstall": "monaco-patch-loader",
 },
 ....
"patchedDependencies": {
  "monaco-editor@0.37.1": "node_modules/.npm-patches/monaco-editor-treemending.patch"
```

**Comment by kaisalmen** [comment]
@BusinessDuck forking monaco-editor because we have a tool specific issue is not a good idea, IMO. In the end we create even more problems. 

If I recall correctly from what you wrote above `postinstall` did not fail the first time. I favor an approach (hash based or not) that doesn't rely on other packages or a specific package manager. It must solely rely on node.js and work cross-plattform. The postinstall script must just not complain if everything is fine and that was wrong from the start. Sorry for this.

**Comment by BusinessDuck** [comment]
Please no apologies, this is an open source project.

If none of the options I suggested are suitable, I think that this is normal, because I am not familiar with many of the nuances in your project.

Thanks, I'll be waiting for the merge. Perhaps I will contribute to this project later.

**Comment by BusinessDuck** [comment]
Do you have chat with Microsoft guys? Can i join?
