### ISSUE TITLE
How do I get syntax highlighting in version 6? The Angular example doesn't have it anymore.

### ISSUE THREAD

**Issue by jhk-mjolner** [TypeFox/monaco-languageclient#496]
I'm in the process of upgrading monaco-languageclient from 5.0.1 to 6.0.2 in an Angular app, and with the help from https://github.com/TypeFox/monaco-languageclient-ng-example I've got it mostly working.

But I'm missing syntax highlighting. It was there by default with the previous version I got working.
Now I can't find a way to enable it. Setting `'semanticHighlighting.enabled': true` does nothing, and I've been trying many things with no success.
I'm just trying to get it working for a simple json document, like the example.
I do have error highlighting and auto-completion working.

Running the example from https://github.com/TypeFox/monaco-languageclient-ng-example I can even see that it doesn't have syntax highlighting anymore either. Is that a mistake, or intended?

**Comment by kaisalmen** [comment]
@jhk-mjolner I have pushed an update to https://github.com/TypeFox/monaco-languageclient-ng-example and another one here. The default extensions were not loaded. This was wrong. We can now make use of default extensions supplied by [monaco-vscode-api](https://github.com/CodinGame/monaco-vscode-api)

**Comment by jhk-mjolner** [comment]
Since I'm going to be using monaco-editor and LSP with a DSL in the end, I probably, ultimately, won't be using the vscode-provided syntax highlighting, and then the wasm issue might not be relevant at that time.
So I'm probably not going to spend more time on it now.

I'll close this issue as I got what I wanted to work for now, working. Thanks. 👍

**Comment by kaisalmen** [comment]
> won't be using the vscode-provided syntax highlighting, and then the wasm issue might not be relevant at that time.

FYI, if you want to use textmate grammars for the DSL instead of monarch, then it will be relevant, see the Langium Statemachine DSL example where we load one:
https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/main/src/langium/main.ts

**Comment by jhk-mjolner** [comment]
I'm under the impression that it should be possible to get syntax/semantic highlighting through LSP, though I haven't really looked into it.
I know it would cause a delay between input and highlight, but in order to keep it simple and keep everything language related the responsibility of a single backend service, we would likely start there and possibly improve user experience later if need be.

Not to take much more of your time, but perhaps you have experience with this and know whether this _is_ possible with monaco-languageclient and whether it's easy/recommended?

**Comment by kaisalmen** [comment]
If you have an LSP supporting https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_semanticTokens it will work out of the box with the current version of monaco-languageclient as monaco-vscode-api supports this now (since 1.76.x release, I think).

**Comment by jhk-mjolner** [comment]
Lovely! Thank for you help! 🙂

**Comment by CGNonofr** [comment]
btw, semantic tokens are.. semantic, it's not meant to be used for syntactic coloration :)
