### ISSUE TITLE
 Failed to resolve import "vscode/monaco" from "packages\examples\main\src\common.ts"

### ISSUE THREAD

**Issue by amoalys** [TypeFox/monaco-languageclient#498]
![1685951841255](https://github.com/TypeFox/monaco-languageclient/assets/37971095/cc29d9b7-af36-47cb-a48b-c8a500e5695e)

**Comment by amoalys** [comment]
first: I run git clone https://github.com/TypeFox/monaco-languageclient.git,
second: cd monaco-languageclient,then,npm i,
third: npm i 
four:npm run dev
end：it can't workwell so i took this screenshot,need some help
 ,

**Comment by amoalys** [comment]
i click the first link , then it does't work

**Comment by kaisalmen** [comment]
Did you run `npm run build` after `npm i`?

**Comment by amoalys** [comment]
sorry,I didn't do this, now it can work well, thanks!  I still have a question,How can I use monaco-languageclient in a （Vue3+Vite+monaco-editor) project? Do you have a example in Vue client example?

**Comment by amoalys** [comment]
I created a project using Vue that integrates monaco editor and registers C language. Then, I also launched an LSP service to provide C language with intelligent prompts, code completion, and other functions. Now, I can get a good experience in a separate C file. However, I hope that clicking can jump from a variable in one C file to another file defined for that variable. How can I achieve this? Just like a WebIDE.

**Comment by kaisalmen** [comment]
You have to extend your own languageclient to achieve this. This is out of the scope of this library.
Of course, you can take a look at a complex client like this: https://github.com/redhat-developer/vscode-java/tree/master/src an get some inspiration, but maybe there are simpler examples. @CGNonofr do you have any good recommendations for this? 

It could be a good idea to extend the README with a new chapter like further reading/resources as similar questions came up in the past.

I think the issue itself is resolved. I will close it.

**Comment by amoalys** [comment]
OK,Thank you.
