### ISSUE TITLE
Electron support

### ISSUE THREAD

**Issue by afroozeh** [TypeFox/monaco-languageclient#50]
I have a working example that runs in the browser, but when I try to run it in electron, I get the error:

```
Loading "vs/editor/editor.main" failed
```
which appears to come from `main.ts` file. I also tried to run it in electron based on this example:

https://github.com/Microsoft/monaco-editor-samples/blob/master/sample-electron/index.html

but somehow cannot get it working with webpack packaging and the resulting `bundle.js`.

Any ideas how to get it working on Electron?

**Comment by akosyakov** [comment]
Have you looked at https://github.com/Microsoft/monaco-editor-samples/blob/master/sample-electron/index.html? There are special handling to be done to preserve an original require, use a proper base URI and workaround some languages.

We have to do the same in Theia: https://github.com/theia-ide/theia/blob/master/packages/monaco/src/electron-browser/monaco-electron-module.ts

**Comment by afroozeh** [comment]
@akosyakov Thanks, I think with the Theia code sample you sent, I can get it running!

**Comment by akosyakov** [comment]
welcome, opened an issue to add an example for electron: https://github.com/TypeFox/monaco-languageclient/issues/52

maybe you can look into it :)
