### ISSUE TITLE
Add or extend example with own vscode service implementation

### ISSUE THREAD

**Issue by kaisalmen** [TypeFox/monaco-languageclient#500]
Add or extend an example to show how a service can be implemented and used:
https://github.com/CodinGame/monaco-vscode-api#monaco-standalone-services

**Comment by CGNonofr** [comment]
The notification service is probably a good candidate

**Comment by kaisalmen** [comment]
@CGNonofr I started to implement a notification service stub and I now the init fails. What am I missing or am I doing it completely wrong?
![image](https://github.com/TypeFox/monaco-languageclient/assets/21079138/be80faba-e18f-4c5e-a95b-d42761b7614c)

**Comment by CGNonofr** [comment]
> @CGNonofr I started to implement a notification service stub and I now the init fails. What am I missing or am I doing it completely wrong? ![image](https://user-images.githubusercontent.com/21079138/257570417-be80faba-e18f-4c5e-a95b-d42761b7614c.png)

I missed that one

Did you import service-overrides/configuration without actually using the service override?

**Comment by kaisalmen** [comment]
Won't be done.
