### ISSUE TITLE
Can't connect Language Client to Language Server.

### ISSUE THREAD

**Issue by bjthehun** [TypeFox/monaco-languageclient#502]
I have a web app written with Preact and Webpack that contains:

1. a Monaco Code Editor in a Preact Component,
2. a Language Server written in Langium.

What I try to do, is to create a new WebWorker for the Server, then create the Monaco Editor, and manually start the Language Client with `monaco-languageclient`. (Using `monaco-editor-wrapper` to create the Worker with `UserConfig.languageClientConfig` doesn't work for me because of a [Webpack bug](https://webpack.js.org/guides/web-workers/))

However, the language client doesn't finish starting, so I'm not getting any code intelligence from the server. What am I missing?

For a minimum working example, please see: [https://github.com/bjthehun/monaco-webpack](https://github.com/bjthehun/monaco-webpack).

**Comment by bjthehun** [comment]
Ultimately this was an issue with vscode-uri, which I imported like this so that my tests would work with Node.js:
```
import pkg from 'vscode-uri';
const { URI } = pkg;
```
So since this is not an issue with the language client itself, this issue can probably be closed.

**Comment by kaisalmen** [comment]
@bjthehun that is good news. I did not get to analyzing it, yet.
