### ISSUE TITLE
upgraded to  v 6.2.0, lost syntax highlight.

### ISSUE THREAD

**Issue by OliverwengFiltered** [TypeFox/monaco-languageclient#511]
upgraded to v6.2.0, I lost syntax highlight, and language server connection seems not working either.

this is initServices config I'm using:

```
{
    enableFilesService: true,
    enableLanguagesService: true,
    configurationServiceConfig: {
        defaultWorkspaceUri: '/tmp'
    },
    debugLogging: true,
    enableConfigurationService: true,
    enableModelEditorService: true,
    enableTextmateService: true,
    enableThemeService: true,
    modelEditorServiceConfig: { useDefaultFunction: true }
}
```

any idea how to get this syntax highlight and language client work ?

cc @kaisalmen  @CGNonofr 

Thanks a lot!

<img width="635" alt="Screenshot 2023-07-17 at 12 16 34 PM" src="https://github.com/TypeFox/monaco-languageclient/assets/28814939/199b4da6-59d6-4935-a5ec-46a6d2ec68bb">

<img width="957" alt="Screenshot 2023-07-17 at 12 12 35 PM" src="https://github.com/TypeFox/monaco-languageclient/assets/28814939/23724a1d-5be2-471f-9faf-46c076d2c562">

**Comment by OliverwengFiltered** [comment]
closing this issue now.

after I loaded with monaco editor workers, it works perfectly.

**Comment by mnesarco** [comment]
Hi @OliverwengFiltered I have everything working (lsp, completion, etc...) but no syntax highlight. Can you tell what did you do exactly to make it work?

Thanks in advance.

**Comment by mnesarco** [comment]
I managed to make it work adding `monaco-editor` dependency and copying all workers from `node_modules/monaco-editor-workers/dist/workers/*`

**Comment by OliverwengFiltered** [comment]
yup, alternatively, you can just use this webpack plugin: @mnesarco `monaco-editor-webpack-plugin`

here is my code:

```
    const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');
    
     const webpackConfig = {
        plugins: [
            new MonacoWebpackPlugin(),
           ....
       ]
      }
```

**Comment by mnesarco** [comment]
Thank you.

**Comment by OliverwengFiltered** [comment]
> Thank you.

np, happy coding, @mnesarco .

**Comment by ShellarFX** [comment]
Is there solution for vite?
