### ISSUE TITLE
Update to monaco-editor 0.40.0 and fitting monaco-vscode-api

### ISSUE THREAD

**Issue by kaisalmen** [TypeFox/monaco-languageclient#512]
Started with using `monaco-vscode-api@1.80.0-next.3` based on https://github.com/CodinGame/monaco-vscode-api/pull/146

Implementing changes on branch: https://github.com/TypeFox/monaco-languageclient/tree/monaco-0.40

**Comment by kaisalmen** [comment]
@CGNonofr I updated to 0.80.0-next.5 and now resolution of onig.wasm fails with webpack and also during dev with vite. The relative resolution does not work.
Is the `extensions` service now required?

**Comment by kaisalmen** [comment]
> What is the error? We should add a webpack demo here

We have that, see `packages/verify/webpack`. It is build when you execute `npm run build`. That is the issue:
![image](https://github.com/TypeFox/monaco-languageclient/assets/21079138/5efd32d3-93b9-492b-bea8-e1ed06faf794)

The other error regarding extensions service is still there as well. I deleted node-modules and package-lock file beforehand.

**Comment by CGNonofr** [comment]
Ok I understand the issue with the first one, will have a look

Regarding the extensions service issue, I've just reproduced :+1:

**Comment by kaisalmen** [comment]
> Regarding the extensions service issue, I've just reproduced 👍

The feeling of relief when one is able to reproduce a problem 😆

**Comment by kaisalmen** [comment]
Just release a new next version based on the current progress:
https://www.npmjs.com/package/monaco-languageclient/v/6.3.0-next.0

**Comment by kaisalmen** [comment]
@CGNonofr `1.80.1-next.0` works, but I needed to init the quickAccessService with empty configuration otherwise the quickaccess menu doesn't work and I receive the following error if I`import { isEditorPartVisible } from 'vscode/service-override/views'`
![image](https://github.com/TypeFox/monaco-languageclient/assets/21079138/b79b8788-55a1-49bf-bc42-b5c696168ace)

Once I remove the import, the problem is gone. Is this expected?

**Comment by kaisalmen** [comment]
New next version is available:
https://www.npmjs.com/package/monaco-languageclient/v/6.3.0-next.1

**Comment by CGNonofr** [comment]
> @CGNonofr `1.80.1-next.0` works, but I needed to init the quickAccessService with empty configuration. If I want to configure it like you do in your demo I get the folowing error once I add `import { isEditorPartVisible } from 'vscode/service-override/views'`: ![image](https://user-images.githubusercontent.com/21079138/256626600-b79b8788-55a1-49bf-bc42-b5c696168ace.png)
> 
> Once I remove the import, the problem is gone. Is this expected?

Views service override shouldn't be imported if editor service override is. don't import `isEditorPartVisible` if you don't use the service override, just return false

**Comment by kaisalmen** [comment]
Ok, got it. I didn't realize you used the views service in the demo.

**Comment by kaisalmen** [comment]
@CGNonofr I found a nice way forward: https://github.com/TypeFox/monaco-languageclient/pull/513/commits/95e0b694b4336f1d8d38aeff8aa694cb0ab61707

**Comment by CGNonofr** [comment]
Probably not indeed...

**Comment by kaisalmen** [comment]
@CGNonofr with `1.80.2` when I enable the view service and have everything configured except for terminal and markers service I still get this (when I use the editor service instead everything is fine). Is this expected behaviour? What do I have to do to run the views service successfully?

![image](https://github.com/TypeFox/monaco-languageclient/assets/21079138/21d7055d-2d91-4335-9742-08799320eca6)

**Comment by kaisalmen** [comment]
I will push an update in a bit to #513

**Comment by kaisalmen** [comment]
@CGNonofr Official release 6.3.0 is now available:
https://www.npmjs.com/package/monaco-languageclient/v/6.3.0

**Comment by CGNonofr** [comment]
> @CGNonofr with `1.80.2` when I enable the view service and have everything configured except for terminal and markers service I still get this (when I use the editor service instead everything is fine). Is this expected behaviour? What do I have to do to run the views service successfully?
> 
> ![image](https://user-images.githubusercontent.com/21079138/258433194-21d7055d-2d91-4335-9742-08799320eca6.png)

If you use the view service override, you have to render the editor part or there will be no activeGroup, leading to this error

**Comment by kaisalmen** [comment]
> you have to render

Can you explain this or show me using your demo how this is realized?

**Comment by CGNonofr** [comment]
> > you have to render
> 
> Can you explain this or show me using your demo how this is realized?

I'm talking about https://github.com/CodinGame/monaco-vscode-api/blob/339a825ce83b5a88ec2100135c3068d76fe62bfc/demo/src/setup.ts#L86

**Comment by kaisalmen** [comment]
Thank you
