### ISSUE TITLE
Enhance documentation: service configuration, client init

### ISSUE THREAD

**Issue by kaisalmen** [TypeFox/monaco-languageclient#515]
The documentation should be expanded with regard service initialization and general init configuration of the client.
Details regarding `monaco-vscode-api` services should either be described in more detail here or links to a more detailed description should be added.

- [x] Document services exposed via `monaco-vscode-api`: https://github.com/CodinGame/monaco-vscode-api#monaco-standalone-services

Improve README:
  - [x] Make clear/document at an obvious place that enabling themes (and textmate) service prevents using monarch grammars (will come with #564)
  - [x] Explain minimal usage of `initService` and explain what it means (will come with #564)

**Comment by kaisalmen** [comment]
@CGNonofr does there already exist any further description/documentation regarding the vscode services you expose via `monaco-vscode-api`. Not written by you, I mean. Is there anything helpful available from Microsoft already?

**Comment by CGNonofr** [comment]
I'm not aware of anything. That's internal stuff so they maybe have some documentation but I doubt it's public
