### ISSUE TITLE
Importing monaco language client error in Vue

### ISSUE THREAD

**Issue by jpmateo022** [TypeFox/monaco-languageclient#518]
Does anyone encountered this on vue?

![image](https://github.com/TypeFox/monaco-languageclient/assets/26633918/8a79843b-32a8-4b54-97af-17a3c464ff46)

my packages.json
```
    "monaco-editor": "^0.40.0",
    "monaco-editor-workers": "^0.40.0",
    "monaco-languageclient": "^6.3.0",
    "terser": "^5.19.2",
    "vscode": "npm:@codingame/monaco-vscode-api",
    "vscode-languageserver": "^8.1.0",
    "vscode-ws-jsonrpc": "^3.0.0",
    "vue": "^3.3.4",

```

**Comment by kaisalmen** [comment]
Hi @jpmateo022 what package manager are you using? `vscode-textmate` is a peerDependency of `@typefox/monaco-vscode-api`. npm 7+ installs missing peerDependencies automatically. yarn for example does not.

**Comment by jpmateo022** [comment]
> Hi @jpmateo022 what package manager are you using? `vscode-textmate` is a peerDependency of `@typefox/monaco-vscode-api`. npm 7+ installs missing peerDependencies automatically. yarn for example does not.

Hi @kaisalmen Im using yarn as my package manager.

**Comment by kaisalmen** [comment]
Ok @jpmateo022 then you could either try to convince it to install the peerDependencies, define them yourself or switch to npm 🙂

**Comment by jpmateo022** [comment]
> Ok @jpmateo022 then you could either try to convince it to install the peerDependencies, define them yourself or switch to npm 🙂

npm install works! thank you!
