### ISSUE TITLE
Default api is not ready yet, do not forget to call `initialize` from 'vscode/extensions'

### ISSUE THREAD

**Issue by jpmateo022** [TypeFox/monaco-languageclient#519]
Has anyone encounter this problem?

I followed this example https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/main/src/common.ts

Though Im getting this 

![image](https://github.com/TypeFox/monaco-languageclient/assets/26633918/a1ea52dd-519f-452c-b593-bb56dfedf90b)

Im using https://github.com/python-lsp/python-lsp-server/tree/develop as my language server

WebSocket

```

        connectToPythonLSP(){
            const url  = "ws://localhost:6083"
            const webSocket = new WebSocket(url);
            webSocket.onopen = () => {
                const socket = toSocket(webSocket);
                const reader = new WebSocketMessageReader(socket);
                const writer = new WebSocketMessageWriter(socket);
                const languageClient =  this.createPythonLanguageClient({
                    reader,
                    writer
                });
                languageClient.start();
                reader.onClose(() => languageClient.stop());
            };
            return webSocket;
        },
```

Monaco Language Client
```

            return new MonacoLanguageClient({
                name: 'Client',
                clientOptions: {
                    documentSelector:  ["python"],
                    errorHandler: {
                        error: () => ({ action: ErrorAction.Continue }),
                        closed: () => ({ action: CloseAction.DoNotRestart })
                    }
                },
                connectionProvider: {
                    get: () => {
                        return Promise.resolve(transports);
                    }
                }
            })
```

**Comment by CGNonofr** [comment]
I tried to make the error message as self explanatory as possible, is it still not good enough? :grin:

**Comment by jpmateo022** [comment]
> 

Actually, I tried to call the initialize from the vscode/extensions but still the error appears.

**Comment by jpmateo022** [comment]
Yes, I tried both using with and without ```await``` but when I use await it never proceeds to the codes below it

![image](https://github.com/TypeFox/monaco-languageclient/assets/26633918/cdee4a33-daca-4f28-ae01-59fc9a3f5572)

I created a console printing console.info("====initServices started!====") and console.info("====initServices done!====") as marks but it seems that when I call await initServices() it never proceed printing console.info("===initServices done!====") 

```

            console.info("====initServices started!====")
            await initServices({
                enableThemeService: true,
                enableTextmateService: true,
                enableModelService: true,
                configureEditorOrViewsServiceConfig: {},
                enableKeybindingsService: true,
                enableLanguagesService: true,
                enableQuickaccessService: true,
                enableOutputService: true,
                enableAccessibilityService: true,
                debugLogging: true
            })
            console.info("===initServices done!====")

            this.initMonaco(file.language,file.contents);    
```

**Comment by jpmateo022** [comment]
It seems that having multiple monaco editors is causing the initServices to hang in my app. I was able to make it work with some errors like ```No file system provider found for resource 'inmemory://model/.vscode'```. I'll try again in some other time.

**Comment by CGNonofr** [comment]
What do you mean having multiple editor causes the hang? You're not supposed to create editors before service initialisation either

**Comment by jpmateo022** [comment]
My guess is all of my editor components are loading at the same time and I'm only applying initServices in one component. I'll try next time moving the initServices in the parent component to make sure I load it first before initializing all the editors.
