### ISSUE TITLE
Add pyright languageclient / languageserver example

### ISSUE THREAD

**Issue by kaisalmen** [TypeFox/monaco-languageclient#521]
People asked about more complex languageclient examples multiple time and I think porting https://github.com/microsoft/pyright/tree/main/packages/vscode-pyright is the best target. We should also be able to add the node based LSP fairly easily here.
This is a far better target (maintenance-wise and overall work-wise) than then a Java languageclient.

**Comment by kaisalmen** [comment]
@CGNonofr I started this. Connecting, but nothing more, yet.

**Comment by kaisalmen** [comment]
Code completion is now working:
![image](https://github.com/TypeFox/monaco-languageclient/assets/21079138/be31adc6-2856-4294-8cce-1c8e68e00f1b)

**Comment by snoop244** [comment]
Cheering you on @kaisalmen ! I completely agree about the need for a more substantial example. I've been checking in on the great TypeFox "glue" between Monaco and language servers over the last few years but I'm just not smart enought to make the leap from a JSON language server to a Python or Go language server.  

I'll monitor progress and test if that helps.

**Comment by kaisalmen** [comment]
I opened a draft PR. It requires some polishing and further documentation, but can already be tested.

**Comment by kaisalmen** [comment]
#526 has been merged.
