### ISSUE TITLE
Uncaught Error: Cannot have two contributions with the same id editor.contrib.referencesController

### ISSUE THREAD

**Issue by Seventysevendays** [TypeFox/monaco-languageclient#522]
![image](https://github.com/TypeFox/monaco-languageclient/assets/37206679/e29c82d4-71bc-4984-95a7-596c9300b6d2)

react example vscode initialize got error, what's the problem

**Comment by kaisalmen** [comment]
Discussed and solved here: https://github.com/CodinGame/monaco-vscode-api/issues/162
