### ISSUE TITLE
Command palette actions keybindings does not visible for user defined actions

### ISSUE THREAD

**Issue by BusinessDuck** [TypeFox/monaco-languageclient#529]
User defined action does not have hotkey bindings representation in command palette.

<img width="603" alt="image" src="https://github.com/TypeFox/monaco-languageclient/assets/10143411/d2f77d49-1621-468f-9743-415ca3cb7638">

Configuration:

```
await initServices({
    configureEditorOrViewsServiceConfig: {},
    enableQuickaccessService: true,
    enableModelService: true,
    enableKeybindingsService: true,
    enableLanguagesService: true,
    debugLogging: false,
});
```

**Comment by CGNonofr** [comment]
Indeed, the issue should be open on the monaco-vscode-api side. It's not demoed
