### ISSUE TITLE
Support textDocument/documentLink and documentLink/resolve

### ISSUE THREAD

**Issue by rcjsuen** [TypeFox/monaco-languageclient#53]
Link providers are mentioned in the [`Languages` interface](https://github.com/TypeFox/vscode-languageserver-node/blob/e0c1f194dabede0409f0d8f4e4e2eeccc65e1535/client/src/services.ts#L122) but there is no implementation for it in [`MonacoLanguages`](https://github.com/TypeFox/monaco-languageclient/blob/d3da16ce3c372478d4af574af5743601f402e968/src/languages.ts).

**Comment by akosyakov** [comment]
Does Monaco support it?

**Comment by rcjsuen** [comment]
I'm [assuming](https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#registerlinkprovider) [yes](https://github.com/Microsoft/monaco-editor/blob/bad3c34056624dca34ac8be5028ae3454172125c/monaco.d.ts#L4053).

**Comment by rcjsuen** [comment]
Likely need to add support for `documentLink/resolve` also. Though the linking story in the LSP and Monaco differs slightly so it's not as easy as it seems.

Please see Microsoft/monaco-editor#719.

**Comment by rcjsuen** [comment]
I've opened #54 to add support to both `textDocument/documentLink` and `documentLink/resolve`.

**Comment by rcjsuen** [comment]
Fixed by merging in #54.
