### ISSUE TITLE
can't install `monaco-languageclient` using `pnpm`

### ISSUE THREAD

**Issue by Yokozuna59** [TypeFox/monaco-languageclient#530]
Hi there! I'm trying to install [`monaco-editor-wrapper`](https://github.com/TypeFox/monaco-components/tree/main/packages/monaco-editor-wrapper) using `pnpm`, and since `monaco-languageclient` is [a dependency](https://github.com/TypeFox/monaco-components/blob/main/packages/monaco-editor-wrapper/package.json#L61), it's installs it and tries to execute the `postinstall` script:

<https://github.com/TypeFox/monaco-languageclient/blob/05923623781bd4bd21e895a0e9310fca5719300e/packages/client/package.json#L69>

But it appears that an error occurs while doing so:

```
$ pnpm add monaco-editor-wrapper
...
node_modules/.pnpm/monaco-languageclient@6.2.0_monaco-editor@0.41.0/node_modules/monaco-languageclient: Running postinstall script...
 ELIFECYCLE  Command failed.
```

Even when trying to install `monaco-languageclient` by it's own:

```
$ pnpm add monaco-languageclient
...
node_modules/.pnpm/monaco-languageclient@6.4.4_monaco-editor@0.41.0/node_modules/monaco-languageclient: Running postinstall script...
 ELIFECYCLE  Command failed.
```

---

I'm not sure if I should report the issue to `pnpm` team or to you guys, please let me know if I should ask `pnpm` team about it.

Thanks!

**Comment by kaisalmen** [comment]
Hi @Yokozuna59 are you aware of this pnpm verification example?
https://github.com/TypeFox/monaco-languageclient/blob/main/packages/verify/pnpm/package.json 
pnpm like yarn have problems with using peerDependencies if they are not defined as regular dependencies (see here an explanation: https://github.com/TypeFox/monaco-languageclient/issues/524#issuecomment-1683453842). So you need to define them as regular dependencies.

**Comment by Yokozuna59** [comment]
@kaisalmen I see, thanks.
