### ISSUE TITLE
Attempted import error: 'FileType' is not exported

### ISSUE THREAD

**Issue by yahorbarkouski** [TypeFox/monaco-languageclient#533]
Hi, kind people! I'm currently experimenting with `monaco-languageclient` in my NextJS 13.4.12 application. 

Examples inside this library work just fine, but once I tried to migrate one example to my application, I started to catch those exception on `client.ts` compile (let's take I'm trying to sample python for simplicity):
```bash
- error ./node_modules/vscode/dist/api.js
Attempted import error: 'FileType' is not exported from 'monaco-editor/esm/vs/platform/files/common/files.js' (imported as 'files').

Import trace for requested module:
./node_modules/vscode/dist/api.js
./lib/playground/client.ts
./components/playground/playground-editor.tsx
./app/playground/page.tsx
```

My `client.ts` imports are equivalent to example's client imports:
```ts
import { initServices, MonacoLanguageClient } from 'monaco-languageclient';
import { CloseAction, ErrorAction, MessageTransports } from 'vscode-languageclient';
import { WebSocketMessageReader, WebSocketMessageWriter, toSocket } from 'vscode-ws-jsonrpc';
import { updateUserConfiguration } from 'vscode/service-override/configuration';
import * as vscode from 'vscode';
import { LogLevel } from 'vscode';
import { ExtensionHostKind, registerExtension } from 'vscode/extensions';
```

And my relevant `package.json` looks like:
```json
{
  "scripts": {
    "postinstall": "monaco-treemending"
  },
  "dependencies": {
    "@types/node": "20.4.8",
    "@types/react": "18.2.18",
    "@types/react-dom": "18.2.7",
    "@types/vscode": "^1.81.0",
    "express": "^4.18.2",
    "monaco-editor-workers": "~0.41.0",
    "monaco-languageclient": "~6.4.4",
    "monaco-textmate": "^3.0.1",
    "monaco-themes": "^0.4.4",
    "next": "13.4.12",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "5.1.6",
    "vscode-json-languageservice": "~5.3.5",
    "vscode-languageserver": "~8.1.0",
    "vscode-ws-jsonrpc": "~3.0.0",
    "ws": "^8.13.0"
  },
  "devDependencies": {
    "@types/express": "^4.17.17",
    "@types/vscode": "^1.81.0",
    "@types/ws": "^8.5.5",
    "vscode-languageserver-types": "~3.17.3"
  }
}
```
To me, it seems like I got a version mismatch somewhere, but I can't understand where exactly. Any help is really appreciated, thank you so much!

**Comment by CGNonofr** [comment]
What is the result of `npm list monaco-editor`?

btw, by using monaco-languageclient, you use monaco-vscode-api which supports textmate grammars and vscode themes so you don't need `monaco-textmate` or `monaco-themes`

**Comment by yahorbarkouski** [comment]
`npm list monaco-editor`:
<img width="471" alt="image" src="https://github.com/TypeFox/monaco-languageclient/assets/94449298/ef867141-01b2-4411-861e-bc39ce6fe96d">
about `monaco-textmate` or `monaco-themes`, got it, thanks!

**Comment by CGNonofr** [comment]
OKay, so not a version conflict!

Was the treemending patch correctly applied? if you inspect `monaco-editor/esm/vs/platform/files/common/files.js`, does it contain a `FileType` export?

**Comment by yahorbarkouski** [comment]
Unfortunately, it is!
<img width="1078" alt="image" src="https://github.com/TypeFox/monaco-languageclient/assets/94449298/479593b6-b59f-4963-a8ed-4b40789bc2c5">

**Comment by CGNonofr** [comment]
Then I'm not sure to understand why it's complaining :thinking: isn't it a cache issue?

**Comment by kaisalmen** [comment]
@CGNonofr and @yahorbarkouski I was thinking the same: It could be vite cache (if you use that) or the browser cache.

**Comment by yahorbarkouski** [comment]
I was indeed browser cache 🙈 Thanks for your help guys!

**Comment by xueerli** [comment]
@kaisalmen Hi,
My monaco-editor version also is 0.41.0, but there are not export `FileType `.
![image](https://github.com/TypeFox/monaco-languageclient/assets/35445052/95fcc46b-20ad-4e93-babb-3fdf8f4183eb)
- "monaco-editor": "~0.41.0",
- "monaco-languageclient": "~6.4.6",
- "vscode": "npm:@codingame/monaco-vscode-api@1.81.7",
- "vscode-languageclient": "^8.1.0",


monaco-editor/esm/vs/platform/files/common/files.js:
```
//#endregion
//#region Utilities
export var FileKind;
(function (FileKind) {
    FileKind[FileKind["FILE"] = 0] = "FILE";
    FileKind[FileKind["FOLDER"] = 1] = "FOLDER";
    FileKind[FileKind["ROOT_FOLDER"] = 2] = "ROOT_FOLDER";
})(FileKind || (FileKind = {}));
//#endregion
```

**Comment by xueerli** [comment]
The reason was that I didn't perform `monaco-treemending`.
