### ISSUE TITLE
Commands not updated in readme

### ISSUE THREAD

**Issue by newfish-cmyk** [TypeFox/monaco-languageclient#534]
When I ran the example today, I encountered an error while executing the commands `npm run start:example:server:python` in the README. 
Later, I checked the package.json and found that the latest commit had modified the command `start:examples:server:python` to run the process server, but this change wasn't reflected in the readme.
Besides, thank you for creating such a great project.🌹

**Comment by kaisalmen** [comment]
Hi @newfish-cmyk thank you reporting this. I missed that, yesterday. I pushed an update to `main`that fixes the wrong naming in multiple locations.

**Comment by kaisalmen** [comment]
README is updated.
