### ISSUE TITLE
Upgrading to v6 from v4

### ISSUE THREAD

**Issue by duncanmak** [TypeFox/monaco-languageclient#535]
Hello,

I'm trying to upgrade my code that was using v4 of the language client to v6. I'm trying to figure out how to replace the existing call `MonacoServices.install()` to the newer API.

I see that there's now an async `initServices` call and it seems to take a `config` object. If I just want a one-to-one upgrade, how should I configure the init so that I get the equivalent settings as the old `MonacoServices.install()`?

**Comment by CGNonofr** [comment]
Hello,

Unfortunately, the lib changed so much it would be hard I think to provide a one-to-one upgrade

**Comment by kaisalmen** [comment]
HI @duncanmak we don't have an example with the minimal configuration and as @CGNonofr there is no one-to-one upgrade path.
You require the model service to be able use `createModelReference`, otherwise nothing else is needed. It is worth mentioning that you can set the vscode api log level directly here as well.
```javascript
await initServices({
    enableModelService: true,
    logLevel: LogLevel.Debug
});
```
Using this you get event more than old `MoancoServices.install()` as pointed out [here](https://github.com/TypeFox/monaco-languageclient/blob/main/packages/client/src/monaco-vscode-api-services.ts#L86-L94) monaco-vscode-api loads couple of services as default.

I added a point to #515

**Comment by duncanmak** [comment]
Thanks for the replies, @CGNonofr and @kaisalmen.

I got a little further along, but my rollup process is failing because it couldn't find these packages:

```
          "vscode-oniguruma",
          "vscode-textmate",
          "xterm",
          "xterm-addon-canvas",
          "xterm-addon-image",
          "xterm-addon-search",
          "xterm-addon-serialize",
          "xterm-addon-unicode11",
          "xterm-addon-webgl",
          "xterm-headless"
```

I noticed that some of these packages were also mentioned in https://github.com/CodinGame/monaco-vscode-api/pull/69

What is it that I can do to get past this? In particular, I don't have any need for the terminal services, so if I could disable that somehow (right now, I'm running `initServices({})`, but it still seems to be bringing in these dependencies), then I can at least get rid of all the xterm-related packages.

**Comment by kaisalmen** [comment]
@duncanmak are you using yarn by any chance? These are `peerDependencies` of `@codingame/monaco-vscode-api` and npm installs them automatically, but yarn and pnpm don't

Regarding services: they are conditionally imported. Thus, if no specified your output bundle should not require/depend on them.

**Comment by duncanmak** [comment]
Thanks @kaisalmen for telling me about peerDependencies, I 'm using `yarn.

I finally got it to build, but now my editor doesn't seem to have any services enabled.

I see a few errors in my console:

`Error: Lifecycle cannot go backwards`

`Uncaught (in promise) Error: Default api is not ready yet, do not forget to call `initialize` from 'vscode/extensions'`

`  ERR Unable to create workbench contribution StatusBarColorProvider2. TypeError: Cannot read properties of undefined (reading 'enableStatusBarColor')`

**Comment by kaisalmen** [comment]
> Error: Lifecycle cannot go backwards

`initServices` can only called once. If you do it again, you see this error. And you have to `await` the execution.

**Comment by duncanmak** [comment]
Thank you for all your help, using the new example, I was able to get more of my code transitioned over.

But now during `yarn build`, I see:

```
[vite]: Rollup failed to resolve import "monaco-editor/esm/vs/base/common/performance.js" from "node_modules/vscode/dist/vscode/vs/workbench/common/contributions.js".
```

**Comment by kaisalmen** [comment]
@duncanmak it seems like https://github.com/TypeFox/monaco-languageclient#treemending was not executed.

Try to run it manually again as shown here:
https://github.com/TypeFox/monaco-languageclient/blob/main/packages/verify/yarn/package.json#L13

**Comment by duncanmak** [comment]
Where is the `monaco-treemending` script? I added the `test:treemending` step to my `package.json` and I still see this:

```
[2/3] ⠂ monaco-languageclient
error /Users/duncan/git/ec/domain-adaptation-web/node_modules/monaco-languageclient: Command failed.
Exit code: 127
Command: monaco-treemending
Arguments: 
Directory: /Users/duncan/git/ec/domain-adaptation-web/node_modules/monaco-languageclient
Output:
```

**Comment by kaisalmen** [comment]
@duncanmak can you share your project or your configuration?

**Comment by duncanmak** [comment]
Using the latest examples, I'm now about to build, which is great. We did have to switch from yarn to npm, because using yarn, the treemending script doesn't get executed. This is not a problem when using npm.

Now I'm trying to get our tests running, We're using `vitest` and from my reading, it supports ESM.

```
Error: require() of ES Module node_modules/vscode/api.js from 
node_modules/vscode-languageclient/lib/node/main.js not supported.
Instead change the require of api.js in node_modules/vscode-languageclient/lib/node/main.js
to a dynamic import() which is available in all CommonJS modules.
```
So reading both `vscode/api.js` and `vscode-languageclient/lib/node/main.js`, it looks like `vscode` is an ESM and `vscode-languageclient` is a CJS module. Am I right?

Is there a way to run the entire system without any CJS modules?

**Comment by kaisalmen** [comment]
vite/vitest can handle mixed esm/cjs and usaually without configuration. 

The problem we had with vitest in `monaco-edditor-wrapper` is that `monaco-editor` only works in the experimental browser mode, because of bowser/DOM related APIs. But this is working, for example: https://github.com/TypeFox/monaco-components/actions/runs/6423611659/job/17442490953

**Comment by sigoden** [comment]
I successfully upgraded from v3.0.1 to v7.0.2, see jsona/editor#2
I only used monaco-languageclient, without monaco-edditor-wrapper.
highlight/diagrose/hover/complete/format all run perfectly like in vscode.
Try it on https://jsona.github.io/editor/schema

**Comment by kaisalmen** [comment]
@sigoden thank you for reporting back. This is very good. Makes me wonder if we should start linking project in the README making use of the project.

**Comment by sigoden** [comment]
@kaisalmen Yes. I would only be honored if you would link to my project.

**Comment by kaisalmen** [comment]
Closing this due to lack of further input for the original problem. @duncanmak If there is another specific problem / you have another specific question, please open a new issue or discussion. Thanks.
