### ISSUE TITLE
Ability to pass a container to the `initServices` method

### ISSUE THREAD

**Issue by VVeaz** [TypeFox/monaco-languageclient#537]
I use `initServices` method from this package (`monaco-language-client`)

`initServices` calls `importAllServices` (also `monaco-language-client`)

`importAllServices`  calls `initialize` (named as `initializeMonacoService` ) from `@codingame/monaco-vscode-api`

`initialize` calls `initServices` (also `@codingame/monaco-vscode-api`)

 `initServices` calls `getServiceOverride` (also `@codingame/monaco-vscode-api`) without argument.
 
 `getServiceOverride` has optional argument - `container` and I want to use it. I think that the container containing monaco-editor should be passed there. Otherwise, color "leaks" occur because the `monaco-workbench` css class is assigned to the body, e.g. the scrollbar in Firefox changes color when the editor's theme changes.
 
 Related issue: https://github.com/CodinGame/monaco-vscode-api/issues/190

**Comment by kaisalmen** [comment]
Dependent issue is closed.
