### ISSUE TITLE
SyntaxError: Unexpected non-whitespace character after JSON at position 2

### ISSUE THREAD

**Issue by Seventysevendays** [TypeFox/monaco-languageclient#538]
![image](https://github.com/TypeFox/monaco-languageclient/assets/37206679/15eebe8e-b135-4e81-a2d5-213a04711b90)

**Comment by kaisalmen** [comment]
@Seventysevendays there is no context!🤷‍♂️

**Comment by Seventysevendays** [comment]
> @Seventysevendays there is no context!🤷‍♂️

sorry, it's the react example, I just run start, 
![image](https://github.com/TypeFox/monaco-languageclient/assets/37206679/39d85d5c-462c-46e8-bc43-89cc9d45b5b9)
![image](https://github.com/TypeFox/monaco-languageclient/assets/37206679/fe8f22a0-96ba-4803-ad1a-61c0fd594b56)

**Comment by kaisalmen** [comment]
You did:
``´
npm i
npm run build
npm run dev
```
and went to to the example via http://localhost:8080/packages/examples/react.html and it doesn't work?

**Comment by cdietrich** [comment]
i remember such a problem with a bad polyfill of buffer that used `__PROTO__` which does not work on current browser

**Comment by Seventysevendays** [comment]
> You did:
> 
> ```shell
> npm i
> npm run build
> npm run dev
> ```
> 
> and went to to the example via http://localhost:8080/packages/examples/react.html and it doesn't work?

in monaco-languageclient repo, it goes well, the same code in my repo, went wrong, but it was good before, so I think maybe caused by the package version, i tried change related package version, still not work

**Comment by cdietrich** [comment]
can you do a `npm why buffer`?

**Comment by Seventysevendays** [comment]
> i remember such a problem with a bad (old) polyfill of `buffer` that used `__PROTO__` which does not work on current browser

do you know how to fix it? the buff all changed to number string, its confused

**Comment by Seventysevendays** [comment]
the normal 
![image](https://github.com/TypeFox/monaco-languageclient/assets/37206679/70793908-e27d-48c4-b84b-c3495745b0b6)
in my repo
![image](https://github.com/TypeFox/monaco-languageclient/assets/37206679/dbee09a8-fd5a-4f5c-b88a-25e7c966b39e)

**Comment by cdietrich** [comment]
we use a newer buffer dependency in resolutions in package.json

```
"resolutions": {
    "buffer": "^6.0.3",
  }
```
but this is a yarn concept

**Comment by CGNonofr** [comment]
The library checks if the Buffer class exists to use it (useful in a node/electron context)

**Comment by cdietrich** [comment]
yes but old versions use __PROTO__ to overide array methods which does not work in modern browser anymore.
newer versions uses Object.setPrototypeOf to redirect e.g. toString methods

**Comment by CGNonofr** [comment]
Maybe if you `import Buffer from 'buffer'` you get the new version, but the code just does : `const hasBuffer = (typeof Buffer !== 'undefined');`

**Comment by kaisalmen** [comment]
Thanks everyone.

**Comment by kaisalmen** [comment]
@Seventysevendays FYI added a new [sub-section](https://github.com/TypeFox/monaco-languageclient#buffer) to the troubleshooting guide.
