### ISSUE TITLE
Do we still need "postinstall" hook?

### ISSUE THREAD

**Issue by BusinessDuck** [TypeFox/monaco-languageclient#550]
Can we replace `"postinstall": "monaco-treemending",` with `monaco-editor-treemended` package?

**Comment by BusinessDuck** [comment]
If parent project using monaco-treemending instead of monaco-editor, this script throws an excpetion

```
Wrong monaco-editor version: expecting 0.43.0, got 1.82.5-next.1
```

**Comment by kaisalmen** [comment]
@BusinessDuck yes, in theory. the package version don't align and my test with npm overrides weren't successful, so far. Help/test/PR is appreciated. I will come back to it, but not immediately.

**Comment by CGNonofr** [comment]
We should update the treemending script to allow to run on monaco-editor-treemended, seems like an easy fix

**Comment by kaisalmen** [comment]
> We should update the treemending script to allow to run on monaco-editor-treemended,

Is the pnpm problem that it does not invoke the script in the first place or am I missing something here or misunderstanding something?

**Comment by CGNonofr** [comment]
I'm just talking about the `Wrong monaco-editor version: expecting 0.43.0, got 1.82.5-next.1` error

It fails to apply although it's already treemended. Here's my suggestion: https://github.com/CodinGame/monaco-vscode-api/pull/208

**Comment by kaisalmen** [comment]
> It fails to apply although it's already treemended. Here's my suggestion: https://github.com/CodinGame/monaco-vscode-api/pull/208

Got it. 👍

**Comment by BusinessDuck** [comment]
Why you didn't use `monaco-editor-treemended` instead of `monaco-editor` for all internal packages?

**Comment by BusinessDuck** [comment]
<img width="987" alt="image" src="https://github.com/TypeFox/monaco-languageclient/assets/10143411/f1f4c0ed-8737-435b-87d2-67fdafa6fa58">

For example, npm and webpack aliases for `monaco-editor` didn't override internal imports and deps from monaco-editor of language client and vscode-api packages.

**Comment by dkattan** [comment]
I'd love to get away from using the postinstall hook because it doesn't plan nice with yarn.

When I run `npm install` everything works as expected.
When I run `yarn install` it shows `'monaco-treemending' is not recognized as an internal or external command`

Yarn is pretty opinionated about not including postinstall scripts in modules:
https://yarnpkg.com/advanced/lifecycle-scripts#postinstall

**Comment by kaisalmen** [comment]
@BusinessDuck @dkattan and @CGNonofr we need to override the `monaco-editor` version and force the treemended one. My tests with npm `overrides` where not really satisfactory. yarn `resolutions` only applies to yarn and deriving from my experience with pnpm so far it will behave different anyways 😆 

Does anyone have a good idea how to solve this? I don't have a working solution currently.

**Comment by CGNonofr** [comment]
does https://www.npmjs.com/package/patch-package work well with yarn? if yes, we should take inspiration from them

**Comment by dkattan** [comment]
> does https://www.npmjs.com/package/patch-package work well with yarn? if yes, we should take inspiration from them

According to the docs it plays nice with Yarn.  Dumb question, could we use this in monaco-vscode-api to patch monaco-editor?

**Comment by kaisalmen** [comment]
Did some further tests. npm overrides in a workspace seem to be only applied when defined at top-level. On this [branch](https://github.com/TypeFox/monaco-languageclient/tree/treemend-tests) `monaco-editor` is consistently overridden by `codingame/monaco-editor-treemended`

Need to test this with a dependent package...

**Comment by kaisalmen** [comment]
⬆️ the problem comes in from the child dependencies. @CGNonofr makes me wonder if all `@codigame/...` packages should depend on `codingame/monaco-editor-treemended`

But it is good to see this here, because any project that uses `monaco-languageclient` and `monaco-editor` will face the same problem. I hope that the overrides will be obeyed. 🤷‍♂️  Will test this now ...

**Comment by dkattan** [comment]
> ⬆️ the problem comes in from the child dependencies. @CGNonofr makes me wonder if all `@codigame/...` packages should depend on `codingame/monaco-editor-treemended`
> 
> But it is good to see this here, because any project that uses `monaco-languageclient` and `monaco-editor` will face the same problem. I hope that the overrides will be obeyed. 🤷‍♂️ Will test this now ...

This is awesome. I was thinking...would it make more sense to adjust the versioning of monaco-editor-treemended to be in line with the version of monaco-editor it is mending?

https://github.com/TypeFox/monaco-languageclient/compare/main...treemend-tests#diff-26d3d28d31824ef26252df77cca08d24faea8451cb8fd3ffee2000f9e496daa0R62

**Comment by CGNonofr** [comment]
No really, because multiple versions of the treemended version can correspond to an unique version of the editor

**Comment by kaisalmen** [comment]
⬆️ @CGNonofr @dkattan @BusinessDuck important to note is that a direct dependency to `monaco-editor` should use the @codingame one as otherwise the override won't work. Dependent version will be overridden = if `monaco-editor` is somewhere in your dependency chain, then this will work. If you specify it directly you need to know what you want.

**Comment by dkattan** [comment]
> ⬆️ @CGNonofr @dkattan @BusinessDuck important to note is that a direct dependency to `monaco-editor` should use the @CodinGame one as otherwise the override won't work. Dependent version will be overridden = if `monaco-editor` is somewhere in your dependency chain, then this will work. If you specify it directly you need to know what you want.

Perfect. Testing now.

**Comment by dkattan** [comment]
> ⬆️ @CGNonofr @dkattan @BusinessDuck important to note is that a direct dependency to `monaco-editor` should use `codingame/monaco-editor-treemended` as otherwise the override won't work. Dependent version will be overridden = if `monaco-editor` is somewhere in your dependency chain, then this will work. If you specify it directly you need to know what you want.

It appears that overrides is a npm thing. Yarn's equivalent functionality appears to be "resolutions"

https://stackoverflow.com/a/64452515

This appears to work

**Comment by kaisalmen** [comment]
Here it comes (resolutions and overrides):
https://www.npmjs.com/package/monaco-languageclient/v/6.6.2-next.1

**Comment by kaisalmen** [comment]
@CGNonofr this also works one level up:
https://www.npmjs.com/package/monaco-editor-wrapper/v/3.3.1-next.0

**Comment by kaisalmen** [comment]
@CGNonofr does it make sense to define a `peerDependency` to the real `monaco-editor` to enforce the version constraint. It could be a first barrier against a mismatch. Or is it confusing as dependent projects need to use `overrides` or `resolutions` anyway. WDYT?

**Comment by kaisalmen** [comment]
Observations / results:
- I think defining `peerDepenedencies` for monaco-editor does not make sense. The necessity to have overrides instructions in a project using this lib makes them obsolete
- When you define `overrides` for the first time you either need to call `npm update` or remove the lock file as otherwise you end up in an inconsistent dependency state
- If you use a workspace project, the overrides instruction must be in the top-level `package.json` (this is an npm specific behaviour/observation)

**Comment by BusinessDuck** [comment]
The results of using latest packages list under pnpm.

Parent project has been migrated to `"@codingame/monaco-editor-treemended": "1.83.5"` instead of `monaco-editor` base package. No aliases or other hacky ways to replace we don't have. 

"monaco-languageclient": "6.6.2-next.1",
"vscode": "npm:@codingame/monaco-vscode-api@1.83.5",

```
  ERROR in ./node_modules/.pnpm/@codingame+monaco-vscode-api@1.83.5/node_modules/@codingame/monaco-vscode-api/vscode/src/vs/workbench/services/workspaces/common/workspaceTrust.js 176:47-63
  export 'isSavedWorkspace' (imported as 'isSavedWorkspace') was not found in 'monaco-editor/esm/vs/platform/workspace/common/workspace.js' (possible exports: EXTENSION_DEVELOPMENT_EMPTY_WINDOW_WORKSPACE, IWorkspaceContextService, STANDALONE_EDITOR_WORKSPACE_ID, UNKNOWN_EMPTY_WINDOW_WORKSPACE, WORKSPACE_EXTENSION, WORKSPACE_FILTER, Workspace, WorkspaceFolder, isEmptyWorkspaceIdentifier, isSingleFolderWorkspaceIdentifier, isStandaloneEditorWorkspace, isWorkspaceIdentifier, toWorkspaceIdentifier)
  ```

**Comment by kaisalmen** [comment]
@BusinessDuck https://www.npmjs.com/package/monaco-languageclient/v/7.0.0 is released.

**Comment by kaisalmen** [comment]
Version 7.0.0 now relies on `@codingame/monaco-editor-treemended` so this can be closed.
