### ISSUE TITLE
WebSocket reader prematurely closed

### ISSUE THREAD

**Issue by boan-anbo** [TypeFox/monaco-languageclient#556]
Hi! I have a quick question. I followed the examples closely and got it working (except for the LSP extension) initially. 

But for some reason, the WebSocket reader starts to get closed as soon as it's constructed which led to these exceptions within the languageClient.start() call.

```sh
> Pending response rejected since connection got disposed
> Server initialization failed.
> Connection to server got closed. Server will not be restarted.
```

The issue is that the reader is "closed" even while the socket is alive:
```ts
const createWebSocketAndCreateClientOnOpen = (url: string): WebSocket => {
    const webSocket = new WebSocket(url);

    webSocket.onopen =  (e) => {
        const socket = toSocket(webSocket);
        const reader = new WebSocketMessageReader(socket);
        const writer = new WebSocketMessageWriter(socket);

        const languageClient = createLanguageClient({
            reader, // the state is already "closed"
            writer
        });
        console.log('reader and writer created', {

            reader,
            writer
        })
         languageClient.start();

        reader.onClose(() => languageClient.stop());
    };
    return webSocket;
};
```

__My question is simply whether that indicates the problem with my LSP server (which I haven't changed), or some other setup issue I ignored__. Any pointers are appreciated!

**Comment by boan-anbo** [comment]
Close after switching the server.

**Comment by AlexeyGarbuzovPPTeam** [comment]
@boan-anbo how resolve problem?
