### ISSUE TITLE
Is there python intellisense guide

### ISSUE THREAD

**Issue by shinwonse** [TypeFox/monaco-languageclient#557]
Hello, I am recently searching about how to connect python language server with '@monaco-editor/react'. I found many examples such as typefox team's example, but it doesn't seem to be my solution.

Is there any guide about connection python language server with monaco-editor? I am using Next.js and @monaco-editor/react.

**Comment by msujew** [comment]
We have an python example (using Pyright) in [our repo](https://github.com/TypeFox/monaco-languageclient/tree/main/packages/examples/src/python).

**Comment by shinwonse** [comment]
Ok I already checked that one, and I really appreciated about that example. But it was little bit complicated to adjust on my project(Next.js), like I have to copy all utils on your repo on my repo. And also there are some type error and dependency error if I mimic your repo.

**Comment by kaisalmen** [comment]
@shinwonse if you want to contribute a next.js example or we should link an example repo, please let us know. We can also add helpful links to the README. We have an [Angular Example](https://github.com/TypeFox/monaco-languageclient-ng-example) for the JSON language that makes almost full re-use of the existing example code. Something similar should be possible with Next,js. The examples are available on npm, too:  https://www.npmjs.com/package/monaco-languageclient-examples
