### ISSUE TITLE
language client latest version 6.6.1, webpack build doesn't work.

### ISSUE THREAD

**Issue by OliverwengFiltered** [TypeFox/monaco-languageclient#558]
<img width="1097" alt="Screenshot 2023-10-22 at 10 27 17 PM" src="https://github.com/TypeFox/monaco-languageclient/assets/28814939/d34a076e-7889-405e-a380-e2efbda5fe4c">

It produces the above error when building with webpack with latest version languageclient.
the same error can be produced in the example project. 

cc @kaisalmen

**Comment by kaisalmen** [comment]
Hi @OliverwengFiltered this seems to be a not tree-mended version of monaco-editor. Try clean node_modules and see if you have mismatching `monaco-editor` versions in your dependency list. If you have a workspace and two different versions you may also end-up with a not tree-mended one. 
We need to fins a solution for: https://github.com/TypeFox/monaco-languageclient/issues/550

**Comment by CGNonofr** [comment]
The patch changes in the last version of monaco-vscode-api, removing files that were kept before, without changing the editor version, and it can produce that error. The solution is indeed to reapply the treemending (running `npm ci` should be enough)

**Comment by OliverwengFiltered** [comment]
@kaisalmen @CGNonofr 

both monaco-editor and vscode version is matching the instructions. monaco-editor is 0.44.0, and vscode is 1.83.3.

did `npm ci` , also tried removing the whole `node_module` and `package-lock.json`, it still reproduces the same error (standaloneGotoLineQuickAccess module not found on webpack build).

https://github.com/OliverwengFiltered/monaco-test

you can reproduce by using the above repo.

**Comment by CGNonofr** [comment]
Ok that's because monaco-editor-webpack-plugin relies on the monaco-editor metadata and we didn't update it

You can configure the plugin as follow:
```javascript
            new MonacoWebpackPlugin({
                features: ['!gotoLine', '!inspectTokens', '!quickCommand', '!quickHelp', '!quickOutline', '!referenceSearch', '!toggleHighContrast']
            })
```

**Comment by OliverwengFiltered** [comment]
@CGNonofr 
the configuration looks like disabling a few features so they won't be built with webpack. Wonder if there is an alternative to solve the problem instead of disabling features.

**Comment by CGNonofr** [comment]
It should be disabled because they are replaced by the vscode version of the feature

**Comment by OliverwengFiltered** [comment]
@CGNonofr  confirmed the above configuration for `monaco-editor-webpack-plugin` works, thank you!
