### ISSUE TITLE
Readonly Message not working after 6.4.6 -> 6.6.1 update

### ISSUE THREAD

**Issue by jhk-mjolner** [TypeFox/monaco-languageclient#562]
I've updated from monaco-languageclient version 6.4.6 to 6.6.1 (and monaco-editor-workers from 0.41.0 to 0.44.0, and monaco-vscode-api automatically via dependency from monaco-languageclient).

I've migrated to providing services via the `userServices` list and `...getSomethingServiceOverride()` syntax with separately installed packages for those that are not included by default.
I'm using Theme, Textmate, Model, and Language service overrides, as I was before with the old syntax.

I'm importing monaco-editor as `monaco-editor/esm/vs/editor/editor.api.js` due to having the problem described here https://github.com/CodinGame/monaco-vscode-api/issues/162 . But changing it to import just `monaco-editor` doesn't make the error reappear now, it seems.

I've based the migration on the changes I can see in https://github.com/TypeFox/monaco-languageclient-ng-example and its dependency in https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/src/common/client-commons.ts .  
I've installed and imported `@codingame/monaco-vscode-json-default-extension` and `@codingame/monaco-vscode-theme-defaults-default-extension`.
I've made the corresponding changes in the webpack configuration, which is now almost identical to the example, except I've added `experiments.topLevelAwait: true`.
Notably I had to add `vscode-oniguruma` and `vscode-textmate` to the list of `allowedCommonJsDependencies` in `angular.json`, otherwise I would get a ton of build errors about not being able to resolve the `localizeWithPath` method from `nls.js` (even though it was clearly there).

Everything I've tested seems to work, except the readonlyMessage popup/overlay at the mouse when the user tries to edit an editor set to readonly. It still locks the editor, but the message doesn't appear.
I've checked that it isn't inserted but invisible due to missing styles. I have the `.overflowingContentWidgets` div element wherein the message appeared before in a div with class `monaco-editor-overlaymessage`, but nothing is inserted now.

I don't know if I need to import/initialize more service overrides or something, or if it's a problem with some changes made in monaco-languageclient or monaco-vscode-api.

Any suggestions?

**Comment by jhk-mjolner** [comment]
I can add that the readonlyMessage functionality seems to be implemented in `node_modules/monaco-editor/esm/vs/editor/contrib/readOnlyMessage/browser/contribution.js`, and that it doesn't seem to be loaded. If I go back to before I updated, it gets loaded.

**Comment by CGNonofr** [comment]
I'm unable to reproduce.

If you are really to debug, you can check if `_onDidAttemptReadOnlyEdit` from `ReadOnlyMessageController` in `monaco-editor/esm/vs/editor/contrib/readOnlyMessage/browser/contribution.js` is properly called

**Comment by jhk-mjolner** [comment]
A bit unlucky that we commented at the same time :)
But since the file isn't even loaded, I'm pretty sure `_onDidAttemptReadOnlyEdit` isn't being properly called.
What should call it?

**Comment by CGNonofr** [comment]
It's imported by editor.all.js which is imported by editor.main

The problem is probably that you import editor.api instead of `monaco-editor` directly (which is now fine)

**Comment by jhk-mjolner** [comment]
Thanks! 😃 
I can confirm that importing it as just `monaco-editor` makes the readonly message appear again.
I thought I had tried that, but I guess it was part of making it even build in the first place that I had tried it.
