### ISSUE TITLE
Editor configuration does not works for bracket pair colorization

### ISSUE THREAD

**Issue by BusinessDuck** [TypeFox/monaco-languageclient#566]
Both of two settings kinds didn't works:

```js
'bracketPairColorization.enabled': 'false',
bracketPairColorization: {
	enabled: false
},
```

**Comment by BusinessDuck** [comment]
@kaisalmen , i guess the reason is in `@codingame/monaco-vscode-configuration-service-override`.

On monaco playground this option is working well

**Comment by CGNonofr** [comment]
What are you doing with that settings? how do you provide them?

**Comment by BusinessDuck** [comment]
i am use `import { createConfiguredEditor } from 'vscode/monaco';` and pass the settings though the `createConfiguredEditor`

**Comment by CGNonofr** [comment]
`bracketPairColorization` is not part of the settings used by the editor itself (even if in the `editor` namespace`)

In monaco, there is a "hack" that makes global settings provided to an editor persisted globally, that hack is disabled when using monaco-vscode-api configuration service override. Instead, you can use the `updateUserConfiguration` function

**Comment by BusinessDuck** [comment]
Looks like file service needed for `updateUserConfiguration` call

```
tools.js:2 Uncaught (in promise) Error: unsupported
    at FileService.unsupported (tools.js:2:1)
    at Module.updateUserConfiguration (configuration.js:39:1)
    at eval (bootstrap.ts:32:1)

**Comment by BusinessDuck** [comment]
Here is my usage:

```
await monacoLsp.initServices({
	userServices: {
		...modelService.default(),
		...configurationService.default(monaco.Uri.file('./workspace')),
		...keybindingService.default(),
	},
});

await configurationService.updateUserConfiguration('"{ editor.bracketPairColorization.enabled": false }');
```

Can you share any example of correct overriding user configuration?

**Comment by BusinessDuck** [comment]
Ok, it works now :)

**Comment by kaisalmen** [comment]
@BusinessDuck we also make user of `updateUserConfiguration` in the examples, e.g.:
https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/src/langium/statemachineClient.ts#L80-L83

**Comment by BusinessDuck** [comment]
How to determine which settings are controlled by service?

**Comment by kaisalmen** [comment]
> How to determine which settings are controlled by service?

There is no matrix. Trial an error. Check how the setting is applied in vscode desktop app. Everything monaco-editor related should work, but names likely different.
