### ISSUE TITLE
Add pure browser example

### ISSUE THREAD

**Issue by rcjsuen** [TypeFox/monaco-languageclient#57]
Would it be possible to create an example that doesn't depend on using Node.js to serve the content?

What I'm imagining is some pure JavaScript code that converts between Monaco and LSP types and then delegates to the language service (very much like what's done in [json-server.ts](https://github.com/TypeFox/monaco-languageclient/blob/cfacfcc33702cea7375ea7a37b5dc3d14b2cd4ff/example/src/json-server.ts) at the moment). This would make it easy for language servers to demonstrate their power by hosting an editor using purely HTML and JavaScript right on GitHub Pages. Of course, this means that only language servers written in JavaScript would be supported but that is to be expected if you want to demo your language server in the browser without any other dependencies.

**Comment by akosyakov** [comment]
Yes, I think it should be possible. Would you look into it?

**Comment by rcjsuen** [comment]
I tried making some changes but got some webpack warnings. It also died when I opened the file in the browser.
```
WARNING in ./~/vscode-json-languageservice/lib/jsonLanguageService.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```
```
jsonLanguageService.js:3 Uncaught Error: Cannot find module "."
    at webpackMissingModule (jsonLanguageService.js:3)
    at webpackEmptyContext.keys (jsonLanguageService.js:3)
    at Object.webpackEmptyContext.keys (jsonLanguageService.js:9)
    at __webpack_require__ (bootstrap fe168a74174926fdf4d0:19)
    at Object.window.onload (client.js:7)
    at __webpack_require__ (bootstrap fe168a74174926fdf4d0:19)
    at main.js:10
    at Function.Module._invokeFactory (loader.js:924)
    at Module.complete (loader.js:934)
    at ModuleManager._onModuleComplete (loader.js:1533)
```

**Comment by rcjsuen** [comment]
The error seems to be the same error reported in #7. I tried the `noParse` trick but then I just get other problems at runtime.
```
Uncaught Error: Check dependency list! Synchronous require cannot resolve module 'vscode-languageserver-types'. This is the first mention of this module!
    at ModuleManager.synchronousRequire (loader.js:1206)
    at _requireFunc (loader.js:1606)
    at jsonLanguageService.js:15
    at jsonLanguageService.js:3
    at Object.<anonymous> (jsonLanguageService.js:9)
    at __webpack_require__ (bootstrap b9c449dc63ed0fd34400:19)
    at Object.window.onload (client.js:7)
    at __webpack_require__ (bootstrap b9c449dc63ed0fd34400:19)
    at main.js:10
    at Function.Module._invokeFactory (loader.js:924)
```
**client.ts:**
```TypeScript
import { getLanguageService } from "vscode-json-languageservice";
import {  } from 'monaco-languageclient';

// register Monaco languages
monaco.languages.register({
    id: 'json',
    extensions: ['.json', '.bowerrc', '.jshintrc', '.jscsrc', '.eslintrc', '.babelrc'],
    aliases: ['JSON', 'json'],
    mimetypes: ['application/json'],
});

// create Monaco editor
const value = `{
    "$schema": "http://json.schemastore.org/coffeelint",
    "line_endings": "unix"
}`;
monaco.editor.create(document.getElementById("container")!, {
    model: monaco.editor.createModel(value, 'json', monaco.Uri.parse('inmemory://model.json')),
    glyphMargin: true
});

getLanguageService.toString();
```
**webpack.config.js:**
```JavaScript
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');

const buildRoot = path.resolve(__dirname, "lib");
const monacoEditorPath = '../node_modules/monaco-editor-core/dev/vs';

module.exports = {
    entry: path.resolve(buildRoot, "main.js"),
    output: {
        filename: 'bundle.js',
        path: buildRoot
    },
    module: {
        noParse: /vscode-languageserver-types|vscode-json-languageservice/
    },
    resolve: {
        extensions: ['.js'],
        alias: {
            'vs': path.resolve(buildRoot, monacoEditorPath)
        }
    },
    devtool: 'source-map',
    target: 'web',
    node: {
        fs: 'empty',
        child_process: 'empty',
        net: 'empty',
        crypto: 'empty'
    },
    plugins: [
        new CopyWebpackPlugin([
            {
                from: monacoEditorPath,
                to: 'vs'
            }
        ])
    ]
}
```

**Comment by rcjsuen** [comment]
Maybe we need to write it in a way like the [monaco-json](https://github.com/Microsoft/monaco-json) project?

**Comment by akosyakov** [comment]
`noParse` stops working as soon as umd module does require request, for Theia we switched to a bit better hack to unwrap umd modules that webpack can handle them: https://github.com/theia-ide/theia/pull/1233

**Comment by rcjsuen** [comment]
Thanks, @akosyakov. I made changes to the `package.json` and `webpack.config.js` based on the pull request you linked to and it's now building okay.

I took out a lot of dependencies to test things out so I'm going to start adding things back in bit by bit to see how far I can get. I'll submit a pull request once I have a working example that matches what's in the `/example/` folder.

Would it be preferable to have a `/example/nodejs/` and a `/example/browser/` folder or should I just put the example in a new `/browser/` folder?

**Comment by akosyakov** [comment]
I think it would be fine to have a top level `examples` folder.

**Comment by rcjsuen** [comment]
I've completed the example and have opened pull request #59.

**Comment by rcjsuen** [comment]
#59 has been merged into `master`.

**Comment by lilliesAndRoses** [comment]
How do I specify the location of the language server in the browser example?
