### ISSUE TITLE
Exception on startup: Unable to load theme

### ISSUE THREAD

**Issue by martypitt** [TypeFox/monaco-languageclient#574]
I've been working through an upgrade from 2.1.0 -> 7.0.2.

Currently facing the following exception, which is thrown when the component intializes:

```
Unhandled Promise rejection: Unable to load extension://vscode.theme-defaults/themes/light_modern.json: Problems parsing JSON theme file: Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, End of file expected ; Zone: <root> ; Task: Promise.then ; Value: Error: Unable to load extension://vscode.theme-defaults/themes/light_modern.json: Problems parsing JSON theme file: Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, Invalid symbol, End of file expected
```

![image](https://github.com/TypeFox/monaco-languageclient/assets/348852/4a18d26a-daaf-4f7e-91dd-318402802baf)

I've spent quite a bit of time digging into this, and comparing with the [reference example angular app](https://github.com/TypeFox/monaco-languageclient-ng-example) to try to work out what's going on.  Unfortunately, I'm stumped.

I've traced the error down to 

 * `ColorThemeData` -> ` ensureLoaded` -> `missing-services.js` -> `readExtensionResource(uri)` 
 * The `uri` is correctly populated:

```json
{
    "$mid": 1,
    "path": "/themes/light_modern.json",
    "scheme": "extension",
    "authority": "vscode.theme-defaults"
}
```

This eventually calls something on a `RegisteredFileSystemProvider`, where the file is correctly registered.

**However, the data within the file is the contents of my `index.html` file, not the `.json` that's expected.**  

That's very suprising. I've spun up the reference angular app, and see it correctly loading the extension. (Which, in turn, comes from `@codingame/monaco-vscode-theme-defaults-default-extension`.

I have no idea how to track down how this is happening.

### Versions
All my versions are correct, and no duplications:

```
    "monaco-editor": "npm:@codingame/monaco-editor-treemended@>=1.83.7 <1.84.0",
    "monaco-editor-workers": "~0.44.0",
    "monaco-languageclient": "^7.0.2",
    "vscode-languageclient": "~9.0.1",
    "@codingame/monaco-vscode-configuration-service-override": "1.83.7",
    "@codingame/monaco-vscode-editor-service-override": "1.83.7",
    "@codingame/monaco-vscode-api": "1.83.7",
    "@codingame/monaco-vscode-files-service-override": "1.83.7",
    "@codingame/monaco-vscode-json-default-extension": "1.83.7",
    "@codingame/monaco-vscode-keybindings-service-override": "1.83.7",
    "@codingame/monaco-vscode-python-default-extension": "1.83.7",
    "@codingame/monaco-vscode-textmate-service-override": "1.83.7",
    "@codingame/monaco-vscode-theme-defaults-default-extension": "1.83.7",
    "@codingame/monaco-vscode-theme-service-override": "1.83.7",
    "vscode-ws-jsonrpc": "^3.1.0",
```

(Full `package.json` is available [here](https://github.com/orbitalapi/orbital/blob/broken-monaco/vyne-query-service/src/main/web/package.json) )

![image](https://github.com/TypeFox/monaco-languageclient/assets/348852/2a4ac157-161b-45e0-b620-1ea990e157c6)

![image](https://github.com/TypeFox/monaco-languageclient/assets/348852/25a5b9f8-e9fa-4323-8d5c-c0201f257298)

Overrides are set, and I've specificed a version of buffer, as per [this note](https://github.com/TypeFox/monaco-languageclient#buffer).  (The note says to use `  "buffer": "~6.0.3",`, which I've tried. I've currently got it set to `5.7.1`, which is the version in the [Angular example](https://github.com/TypeFox/monaco-languageclient-ng-example)

```
  "overrides": {
    "monaco-editor": "$monaco-editor",
    "vscode": "npm:@codingame/monaco-vscode-api@1.83.7",
    "buffer": "~5.7.1"
  },
```

### Content
The actual file is correctly installed and present within my node_modules folder.  I'm not sure what's responsible for actually coping that to wherever it is, but I suspect it's a webpack thing, maybe?

![image](https://github.com/TypeFox/monaco-languageclient/assets/348852/df08b329-4fd1-484c-bf20-048403467b69)

So I checked...

### Webpack

I'm using the `custom-webpack.config.js` that's shown in the angular example. You can see the actual file [here](https://github.com/orbitalapi/orbital/blob/broken-monaco/vyne-query-service/src/main/web/custom-webpack.config.js)

I'm at a loss of what to try next.

Any help would be appreciated.

**Comment by martypitt** [comment]
OK, found the issue.

Definitely not a bug with the library. but possibly something to add to troubleshooting.

 * This version expects to be able to load `*.json` files from the webserver, which previously it didn't
 * Our app has filters to only serve expected extensions, redirecting everything back to `/index.html`.
 * Therefore, an attempt to load a json config file resulted in a redirect to index.html, which was invalid JSON.

Apologies for the noise here. Closing as fixed.

**Comment by kaisalmen** [comment]
> This version expects to be able to load *.json files from the webserver, which previously it didn't

I will add something to the troubleshooting section of the README.

**Comment by DEAN-Cherry** [comment]
I am using vite5 + vue3  and facing same Issue here. Any work around?
