### ISSUE TITLE
cannot find module

### ISSUE THREAD

**Issue by deepchhatbar658** [TypeFox/monaco-languageclient#576]
Cannot find module '@typefox/monaco-editor-react' or its corresponding type declarations

Cannot find module 'monaco-editor-wrapper' or its corresponding type declarations

i have took clone and did npm install but this gives me the error

**Comment by kaisalmen** [comment]
Hi @deepchhatbar658 do you mind providing some context?

**Comment by deepchhatbar658** [comment]
> Hi @deepchhatbar658 do you mind providing some context?

thanks for the concern but it was just a linting issue you can close this

**Comment by kaisalmen** [comment]
@deepchhatbar658  Are you aware of this? https://github.com/TypeFox/monaco-languageclient/blob/main/packages/verify/webpack/webpack.config.js
