### ISSUE TITLE
Any insight on this error?? unhandled method window/workDoneProgress/create

### ISSUE THREAD

**Issue by eye-horus** [TypeFox/monaco-languageclient#586]
I'm getting this error throw from the monaco editor client when I tried to use it with typescript language server.

**Error:**
Unhandled method window/workDoneProgress/create

Looks like the client editor is advertising it has workDoneProgress capabilities, but its not handling the above message from the server.

![image](https://github.com/TypeFox/monaco-languageclient/assets/28602033/6457210a-ed06-4341-9d02-89f9edde7969)

Really appreciate any insights into this, thank you

**Comment by kaisalmen** [comment]
Hi @eye-horus we had this question before. It is a specific problem with the TypeScript Language Server. I didn't find a solution after a short investigation: https://github.com/TypeFox/monaco-languageclient/discussions/542#discussioncomment-7223228 

You could check if you find an existing vscode languageclient implementation and look at the code. Have you already tried the latest version of the server or ask for help there?

**Comment by rchl** [comment]
Maintainer of TypeScript Language Server here.

While the server could be more fool proof here, the root issue seems to be with monaco client announcing support for `window.workDoneProgress` while not really supporting it. If so, why is that not being fixed?

**Comment by rchl** [comment]
Actually, after re-reading the spec, it appears that typescript-language-server is in the wrong for triggering `window/workDoneProgress/create` before responding to `initialize` request. Is that what causes the issue here and not the fact that `window.workDoneProgress` is not supported?

**Comment by kaisalmen** [comment]
Hi @rchl thank you for reaching out. You were referring to this, right?
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#serverInitiatedProgress

Nowadays `monaco-languageclient` directly wraps `vscode-languageclient` and no longer drops any of its default feature implementations. It announces the support for `workDoneProgress` with the **initialze** message (screenshot taken from our [pyright client example](https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/src/python/client/main.ts)):
![image](https://github.com/TypeFox/monaco-languageclient/assets/21079138/1a888ba7-8aac-4ee6-8270-3e10c57f6c62)

Are you aware of a vscode client/extension available (for testing/comparison) that relies on [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server) ?

**Comment by rchl** [comment]
After looking at `BaseLanguageClient` from `vscode-languageclient` I think the issue is with triggering request too early so I will fix that on my side.

**Comment by kaisalmen** [comment]
Should is fixed:
https://github.com/typescript-language-server/typescript-language-server/pull/846

and available in a new release::
https://www.npmjs.com/package/typescript-language-server/v/4.3.0

according to:
https://github.com/typescript-language-server/typescript-language-server/releases/tag/v4.3.0
