### ISSUE TITLE
 event.hasCorrelation is not a function

### ISSUE THREAD

**Issue by OliverwengFiltered** [TypeFox/monaco-languageclient#590]
anyway to turn off this error?

appreciate the insights!

cc @kaisalmen  @CGNonofr 

<img width="1342" alt="Screenshot 2024-01-08 at 10 30 31 AM" src="https://github.com/TypeFox/monaco-languageclient/assets/28814939/bfa4f233-7f02-4bc2-ab59-e178bd306705">

**Comment by kaisalmen** [comment]
@OliverwengFiltered do you have more context? How/when does this happen?

**Comment by OliverwengFiltered** [comment]
@kaisalmen  I had these two lines in the package.json in the overrides property.

```
    "monaco-editor": "npm:@codingame/monaco-editor-treemended@>=1.83.5 <1.84.0",
    "vscode": "npm:@codingame/monaco-vscode-api@>=1.83.5 <1.84.0",
```

after reading the release notes, I corrected them to 

```
    "monaco-editor": "npm:@codingame/monaco-editor-treemended@>=1.85.0",
    "vscode": "npm:@codingame/monaco-vscode-api@>=1.85.0",
```

which seems solved the problem.
closing it now.
