### ISSUE TITLE
Sending configurations to language server

### ISSUE THREAD

**Issue by rinkesh314e** [TypeFox/monaco-languageclient#596]
I have integrated the monaco-languageclient with my react project with groovy lsp server. I wanted to know what is the way to send configs to the server through language-client. 
Example: 
Groovy language server has a property called `groovy.classpath` that i need to use to send additional dependencies for the server to suggest from. i tried doing it through adding middleware shown below but while checking the language server logs i found that it was empty. 
```
clientOptions: {
			documentSelector: ['groovy'],
			middleware: {
				workspace: {
					configuration: (params: any, token: any, configuration: any) => {
						return [
							{
								groovy: {
									classpath: ['classpath1'],
								},
							},
						];
					},
				},
			},
```

**Comment by kaisalmen** [comment]
Hi @rinkesh314e if you look at the VSCode extension and how they [init the language client there](https://github.com/GroovyLanguageServer/groovy-language-server/blob/master/vscode-extension/src/main/ts/extension.ts#L150-L155) they don't seem to use the middleware and only pass params to the local executable. So, your use case (client and server in different environments/locations) may not been foreseen by them. You could ask them if this is the case and what are the options.

**Comment by rinkesh314e** [comment]
ok, thanks for the input.
