### ISSUE TITLE
8.0.0 status

### ISSUE THREAD

**Issue by rubenfiszel** [TypeFox/monaco-languageclient#605]
Hi, I see mention of the 8.0.0 in a few places but it doesn't seem released. Is still WIP?

**Comment by kaisalmen** [comment]
Hi @rubenfiszel #600 got delayed. I didn't have enough time to work on it in the last couple of weeks. Once that PR is merged the next major version will come. Latest release is still 7.3.0.

**Comment by kaisalmen** [comment]
@rubenfiszel soon. Next builds are available, please see: https://github.com/TypeFox/monaco-languageclient/pull/600#issue-2106106992 it will be updated.

**Comment by kaisalmen** [comment]
Final release is available: https://www.npmjs.com/package/monaco-languageclient/v/8.0.0
