### ISSUE TITLE
Using monaco-languageclient with React and an Existing Worker from Langium

### ISSUE THREAD

**Issue by Lemour-sudo** [TypeFox/monaco-languageclient#608]
I am trying to setup monaco-languageclient to work with the monaco-react `Editor` component and I need a guide on how to connect the two and have the auto-complete working too from an existing web worker for a custom language (defined in Langium).

From my limited understanding the "language-configuration.json", "statemachine.tmLanguage.json" and "statemachineServerWorker.js" files should be sufficient to have the grammar loaded and auto-complete working.

I setup an experimental repo (https://github.com/Lemour-sudo/monaco-react-example) to first work with the basic state-machine example to try this.

Everything builds well but the language client fails to start and throws the error `TypeError: this._fileService.onWillActivateFileSystemProvider is not a function` in the browser.

An explanation and a guide would help on how to do this.
And can the ReadMe be updated for the new versions of the language-client being released along with the updated package.json in the examples workspace? It is quite a struggle to find the correct exact dependencies that work.

**Comment by kaisalmen** [comment]
@Lemour-sudo #600 will introduce https://www.npmjs.com/package/@typefox/monaco-editor-react and https://www.npmjs.com/package/monaco-editor-wrapper into this repo and the examples will make use of it. This will reduce the amount of boiler plate and configuration.

**Comment by Lemour-sudo** [comment]
Thank you for the replies.

I see that version 8.0.0-next.3 solves a lot of dependency issues and I managed to run it successfully too. @kaisalmen 
Any estimate of when the final version 8.0.0 will be out yet?

**Comment by Lemour-sudo** [comment]
Great work! Thanks @kaisalmen !
