### ISSUE TITLE
Starting react project with custom language server

### ISSUE THREAD

**Issue by empfaze** [TypeFox/monaco-languageclient#609]
@kaisalmen Hello Kai. Thank you for providing implementation of monaco-languageclient with react in examples section. I am trying to implement monaco-languageclient in my project based on react example. But I am getting the following error:
<img width="577" alt="Снимок экрана 2024-03-13 в 17 49 16" src="https://github.com/TypeFox/monaco-languageclient/assets/80310253/aa8dc64d-fb51-4aa7-97ad-7a91df978a3d">
It seems that one of the services has not been initialized and at the moment I don't know how to handle this error. Maybe it occurs, because I started project via "create react app"...I also noticed that in [this issue](https://github.com/TypeFox/monaco-languageclient/issues/608) topic starter is facing the similar problem. Am I right, that package in your answer will potentially solve the problem?

**Comment by kaisalmen** [comment]
The linked issue got closed/ is resolved in the meantime. Is this issue also resolved for you as well?

**Comment by empfaze** [comment]
> @empfaze The linked issue got closed/ is resolved in the meantime. Is this issue also resolved for you as well?

Hello. I managed to fix the error by upgrading monaco-languageclient to "8.0.0-next.5". In the end, the services were initialized successfully.
