### ISSUE TITLE
Update to Monaco 0.11.x

### ISSUE THREAD

**Issue by rcjsuen** [TypeFox/monaco-languageclient#61]
A new version of Monaco has been published. We should update `monaco-languageclient` to the new version. This will allow us to close #39.

I would consider Microsoft/monaco-editor#756 a blocker at the moment though... :(

**Comment by akosyakov** [comment]
Cool! But we can start working on a PR anyway?

**Comment by rcjsuen** [comment]
@akosyakov Of course. I went over the changes this morning so I have something ready already. I have opened #63.

**Comment by akosyakov** [comment]
@rcjsuen thank you!
