### ISSUE TITLE
`initServices` not exported in monaco-languageclient 8.0.0

### ISSUE THREAD

**Issue by maxdekrieger** [TypeFox/monaco-languageclient#610]
First of all, many thanks for this project! I enjoy it a lot and I'm looking forward to the release of 8.0.0.

While trying out my setup and upgrading to `8.0.0-next.5`, I found I can no longer import `initServices` from the monaco-languageclient module. I am upgrading from an older version (6.6.0) and adjusted my code according to the changelogs etc. but I am unsure how to resolve this one.

Any pointers are appreciated. Thanks!

**Comment by kaisalmen** [comment]
Hi @maxdekrieger service related functions are now exported via `monaco-languageclient/vscode/services`. The CHANGELOGs are not yet updated on the PR branch. I will get to that.

**Comment by maxdekrieger** [comment]
Thanks for your reply, works like a charm!
