### ISSUE TITLE
[MonacoEditorReactComp] onLoad() should expose editor refrence 

### ISSUE THREAD

**Issue by Stainless2k** [TypeFox/monaco-languageclient#612]
It would be nice if the onLoad callback would have the editor reference as a parameter 
e.g `onLoad(editor: IStandaloneCodeEditor)`

This would make it more convenient to use `addAction`, scroll something in to view on load or focus the editor.
Right now you need to get and store the ref yourself, which is fine but unnecessary imo.

```ts
const editorRef = useRef<mEditor.IStandaloneCodeEditor>();
return (
  <MonacoEditorReactComp
    ref={(ref) => {
      editorRef.current = ref?.getEditorWrapper().getEditor();
    }}
  />
)
```

More convenient:  
```ts
return ( 
  <MonacoEditorReactComp
    onLoad={(editor) => {
      editor.addAction( . . . );
      editor.revealLineInCenter( . . . );
      editor.setSelection( . . . );
      editor.focus( . . . );
    }}
  />
)
```

**Comment by kaisalmen** [comment]
@Stainless2k actually it makes more sense to get the wrapper back, because you then have access to all resources (e.g. the `LanguageClientWrapper` as well)?

**Comment by kaisalmen** [comment]
Implemented: https://github.com/TypeFox/monaco-languageclient/pull/630
Released: https://www.npmjs.com/package/@typefox/monaco-editor-react/v/3.1.0

**Comment by Stainless2k** [comment]
@kaisalmen thank you for the quick work 🙏
