### ISSUE TITLE
Multiple Monaco editor issue

### ISSUE THREAD

**Issue by bguo3** [TypeFox/monaco-languageclient#620]
I want to add multiple Monaco editors on one page. [Demo code](https://github.com/bguo3/stDemo). Seems they share the same objects.
Declare "Aaa" in one editor could be referenced in the other.
![image](https://user-images.githubusercontent.com/100554455/215686458-ce6b1650-0b86-4c23-b027-1185ad156337.png)

**Comment by wa8f7192** [comment]
Hi, I am facing the same issue, would this be addressed in future version / is there a workaround for this?

**Comment by kaisalmen** [comment]
> Hi, I am facing the same issue, would this be addressed in future version / is there a workaround for this?

Hi @wa8f7192 No, there is no workaround for this, yet. We need to properly fix it.

**Comment by kaisalmen** [comment]
Hi @bguo3  and @kaisalmen I have finally started to solve this issue on this branch:
https://github.com/TypeFox/monaco-languageclient/tree/issue-620

I now use two editors with just one language server worker and this removes the double completions, but both editor contents get mixed up with a completion request. This may be a Langium Language Server bug. I will come back with more info.

**Comment by kaisalmen** [comment]
> but both editor contents get mixed up with a completion request. This may be a Langium Language Server bug. I will come back with more info.

The observed behavior is correct. Top-level definitions are shared by the language server, therefore the completion request contains all top-level definitions in completion requests from both editors/documents.

**Comment by SimonCockx** [comment]
@kaisalmen Any chance you can point me to an example repository somewhere with this setup?

I'm trying to set up an application where I would like to have multiple monaco clients on a single page. Whether or not they share the same language server is more of a detail to me - each document is independent, so I am able to launch a separate server for each client, but I suppose if one does the job that could be more efficient than having multiple web workers running in the background.

I have tried setting this up with multiple language servers, but it seems each change triggers events for all language servers at once, as if the clients reuse the same connection somehow... I'm not sure how to disconnect them.

**Comment by kaisalmen** [comment]
Hi @SimonCockx language clients for a specifc language need to be created and registerd only once. It is done globally and will be available for all monaco instances. You can treat the life-cycle of the language client(s) independently of the life-cycles of the editor(s). This is demonstrated in the following example:
https://github.com/TypeFox/monaco-languageclient/blob/bare-example-lcwrapper/packages/examples/src/multi/twoLanguageClients.ts

Here two editors share one language servers (that was the reason why this issue was opened in the first place):
https://github.com/TypeFox/monaco-languageclient/blob/bare-example-lcwrapper/packages/examples/src/langium/statemachine/main.ts

**Comment by SimonCockx** [comment]
Hi @kaisalmen, thank you for the pointers. That should get me started.

One use case I had was to listen for specific language server messages coming back to the client for each editor. The fact that I can only have a single language client, does that mean that the only way to distinguish between messages for different editors is to look at the text document URI of the message? I.e., all editor need to share the same (virtual) file system.

**Comment by SimonCockx** [comment]
I ended up with writing a slight variation of the `MonacoEditorLanguageClientWrapper` class, which supports multiple editors. (`MonacoMultipleEditorsLanguageClientWrapper`) Thanks for the pointers @kaisalmen!

For reference:
```
export interface ModelConfig {
  id: string;
  code?: string;
  codeUri: string;
}

export class MonacoMultipleEditorsLanguageClientWrapper {
  private id!: string;

  private userConfig!: UserConfig;
  private editorApps: EditorAppClassic[] = [];
  private languageClientWrapper?: LanguageClientWrapper;
  private logger!: Logger;
  private initDone = false;

  /**
   * Perform an isolated initialization of the user services and the languageclient wrapper (if used).
   */
  async init(userConfig: UserConfig): Promise<void> {
    if (this.initDone) {
      throw new Error(
        'init was already performed. Please call dispose first if you want to re-start.',
      );
    }
    this.userConfig = userConfig;
    const editorAppConfig = userConfig.wrapperConfig.editorAppConfig;
    // Always dispose old instances before start
    this.editorApps.forEach((editorApp) => editorApp.disposeApp());

    this.id = userConfig.id ?? Math.floor(Math.random() * 101).toString();
    this.logger = new Logger(userConfig.loggerConfig);

    // editorApps init their own service thats why they have to be created first
    const serviceConfig = await configureServices({
      serviceConfig: userConfig.wrapperConfig.serviceConfig,
      specificServices: {},
      logger: this.logger,
    });
    await initServices(
      serviceConfig,
      `monaco-editor (${this.id})`,
      checkServiceConsistency,
    );

    this.languageClientWrapper = new LanguageClientWrapper();
    await this.languageClientWrapper.init({
      languageId: editorAppConfig.languageId,
      languageClientConfig: userConfig.languageClientConfig,
      logger: this.logger,
    });

    if (this.languageClientWrapper?.haveLanguageClientConfig()) {
      await this.languageClientWrapper.start();
    }

    this.initDone = true;
  }

  /**
   * Does not perform any user configuration or other application init and just starts the application.
   */
  async start(
    htmlElement: HTMLElement,
    modelConfig: ModelConfig,
  ): Promise<EditorAppClassic> {
    if (!this.initDone) {
      throw new Error(
        'No init was performed. Please call init() before start()',
      );
    }

    const editorConfig = {
      ...this.userConfig,
      wrapperConfig: {
        ...this.userConfig.wrapperConfig,
        editorAppConfig: {
          ...this.userConfig.wrapperConfig.editorAppConfig,
          ...modelConfig,
        },
      },
    };

    this.logger.info(`Starting monaco-editor (${this.id})`);
    const editorApp = new EditorAppClassic(
      modelConfig.id,
      editorConfig,
      this.logger,
    );
    this.editorApps.push(editorApp);
    await editorApp?.init();
    await editorApp?.createEditors(htmlElement);

    return editorApp;
  }

  getLanguageClientWrapper(): LanguageClientWrapper | undefined {
    return this.languageClientWrapper;
  }

  getLanguageClient(): MonacoLanguageClient | undefined {
    return this.languageClientWrapper?.getLanguageClient();
  }

  getWorker(): Worker | undefined {
    return this.languageClientWrapper?.getWorker();
  }

  public reportStatus(): string[] {
    const status: string[] = [];
    status.push('Wrapper status:');
    for (let i = 0; i < this.editorApps.length; i++) {
      status.push(`Editor ${i}: ${this.editorApps[i].getEditor()}`);
    }
    return status;
  }

  /**
   * Disposes all application and editor resources, plus the languageclient (if used).
   */
  async dispose(): Promise<void> {
    this.editorApps.forEach((editorApp) => editorApp.disposeApp());
    this.editorApps = [];

    if (this.languageClientWrapper?.haveLanguageClient()) {
      await this.languageClientWrapper.disposeLanguageClient(false);
      this.logger.info('Monaco editor and languageclient completed disposed.');
    } else {
      this.logger.info('Monaco editor has been disposed.');
    }
    this.initDone = false;
  }
}
```

**Comment by kaisalmen** [comment]
Hi @SimonCockx why don't you use multiple `MonacoEditorLanguageClientWrapper`, only one `LanguageClientWrapper` and treat the LanguageClientWrapper completely independent/external?

Btw, if you generally need more editors you should think about using the ViewsService to compose a "partial" VSCode, like here:
https://typefox.github.io/monaco-languageclient/ghp_appPlayground.html (online example), [source code](https://github.com/TypeFox/monaco-languageclient/tree/main/packages/examples/src/appPlayground)

**Comment by SimonCockx** [comment]
Hi @kaisalmen, I think what you are suggesting is more or less what I ended up doing. The `MonacoMultipleEditorsLanguageClientWrapper` has a single `LanguageClientWrapper`, and multiple `EditorAppClassic` instances. I think your suggestion of having a `MonacoEditorLanguageClientWrapper` per editor would be doing too much: it would still instantiate a `LanguageClientWrapper` during initialization for each editor, as can be seen in the `init()` method of `MonacoEditorLanguageClientWrapper`.
