### ISSUE TITLE
[MonacoEditorReactComp] onLoad() does not get called when there is any error

### ISSUE THREAD

**Issue by Stainless2k** [TypeFox/monaco-languageclient#628]
this is probably intended behavior, but is sometimes annoying.

For example in our app we add editor actions, like ctrl+s to save, inside the `onLoad()`. If the language server is not online, we still want to use the editor, so we just show an error alert with the `onError()` and move on. But now the `onLoad()` did not get called and we don't have our custom editor actions.

**Comment by kaisalmen** [comment]
@Stainless2k do you want to propose an alternate/configurable approach (=PR)?

**Comment by Stainless2k** [comment]
Could you point me to the code that's relevant for this, I will have a look at it.

**Comment by Stainless2k** [comment]
Actually this got fixed already, this was in issue with our e2e test. Sorry for not checking this before creating this issue. :pray:
