### ISSUE TITLE
@typefox/monaco-editor-react does not work with React StrictMode enabled

### ISSUE THREAD

**Issue by zzullick** [TypeFox/monaco-languageclient#631]
Hi, I was looking to adopt your React wrapper for Monaco to use the language client services. An issue I ran into was, whenever `<StrictMode>` was enabled in React, the editor would fail to load properly and initialize the model. If you remove `<StrictMode>`, it works as expected.

I've reproduced the issue in a [codesandbox for your review/testing.](https://codesandbox.io/p/devbox/typefox-react-strictmode-issue-6q5jr2).

**Comment by kaisalmen** [comment]
Hi @zzullick thanks for reporting. We need to fix. It was already brought up some time ago, but know I have an idea what could be the root cause. I will work on a fix in the upcoming days.
