### ISSUE TITLE
docs: out dated usage for `wrapper-react`: `htmlElement` is no longer part of `UserConfig`

### ISSUE THREAD

**Issue by alissa-tung** [TypeFox/monaco-languageclient#637]
https://github.com/TypeFox/monaco-components/pull/51

https://github.com/TypeFox/monaco-languageclient/blob/f465bc90799554ff43bd9cd8f1499994fd59fdc5/packages/wrapper-react/README.md#usage

**Comment by kaisalmen** [comment]
Hi @alissa-tung thank you for spotting that. I have pushed an update to main already. It will be contained in the next release of the npm package.
