### ISSUE TITLE
Monaco Editor Wrapper for Multiple Languages

### ISSUE THREAD

**Issue by Plochem** [TypeFox/monaco-languageclient#643]
Add support for multiple dependent languages in the editor through createModel and setModel. I want to be able to create multiple "tabs"/models where I can set the language for each and they can "see" each other. This probably overlaps with #639, but I'm just creating this issue just in case.

**Comment by kaisalmen** [comment]
@Plochem a new major version of `monaco-editor-wrapper` is available: https://www.npmjs.com/package/monaco-editor-wrapper/v/5.0.0 It makes text / model updates and handling more flexible and removes the required `languageId` in the `UserConfig`

Please check the [CHANGELOG](https://github.com/TypeFox/monaco-languageclient/blob/main/packages/wrapper/CHANGELOG.md#500---2024-05-15).

**Comment by kaisalmen** [comment]
Multiple language clients will be made available with a fix for: https://github.com/TypeFox/monaco-languageclient/issues/677
