### ISSUE TITLE
monaco-vscode-python-default-extension not getting registered

### ISSUE THREAD

**Issue by iam-abdul** [TypeFox/monaco-languageclient#647]
I am trying to reimplement the python-lsp with react wrapper example, but i am having hard time getting the syntax highlighting for python.

editor not requesting the python language configuration
<img width="1440" alt="Screenshot 2024-04-30 at 12 55 41 AM" src="https://github.com/TypeFox/monaco-languageclient/assets/47693205/81978972-0b5b-42c2-8193-4aa7ab96e035">

I have imported the python-default-extension. I see the requests for "@codingame/monaco-vscode-theme-defaults-default-extension/resources/light_modern.json" but not for the python configuration.
<img width="1440" alt="Screenshot 2024-04-30 at 12 57 03 AM" src="https://github.com/TypeFox/monaco-languageclient/assets/47693205/529832f3-3379-4cbf-839b-7c1ca94786de">

VITE config
[
<img width="1440" alt="Screenshot 2024-04-30 at 12 59 28 AM" src="https://github.com/TypeFox/monaco-languageclient/assets/47693205/8e8976a4-039c-4663-967d-e2dfc12c35a6">
](url)

I don't understand if it is an issue or i might have missed something, please correct me if that is the case.
🙏 thanks

**Comment by iam-abdul** [comment]
i got the syntax highlighting to work by modifying the index.js file inside "monaco-vscode-theme-defaults-default-extension", here i am registering the python extension here in this file.

<img width="1440" alt="Screenshot 2024-04-30 at 9 04 47 AM" src="https://github.com/TypeFox/monaco-languageclient/assets/47693205/8c6cb046-bd8c-46ac-a213-01f77ed6ce34">

**Comment by kaisalmen** [comment]
Hi @iam-abdul if you use the wrapper with extended config (see [here](https://github.com/TypeFox/monaco-languageclient/tree/main/packages/wrapper#configuration)) you only have to import [the python higlighting](https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/src/python/client/config.ts#L9)

**Comment by iam-abdul** [comment]
hey hi @kaisalmen, i guess there is some issue with my configuration the syntax highlighting is working out of the box when i clone and run this repo.
