### ISSUE TITLE
Syntax highlighting issue with `MonacoEditorReactComp` and CRA with Webpack

### ISSUE THREAD

**Issue by metehansenol** [TypeFox/monaco-languageclient#654]
I created an empty react app with `create-react-app`, installed and imported necessary packages;

```
import { MonacoEditorReactComp } from '@typefox/monaco-editor-react';
import '@codingame/monaco-vscode-json-default-extension';

<MonacoEditorReactComp
  userConfig={{
    wrapperConfig: {
      editorAppConfig: {
        $type: 'extended',
        languageId: 'json',
        code: '{ "hello": "world" }',
        useDiffEditor: false,
        codeUri: `/hello.json`,
      },
    },
  }}
  style={{ height: '100%' }}
/>
```

In documentation says that `monaco-editor-webpack-plugin` can't be used anymore.

What's wrong with syntax highlighting. Btw. language server integration working fine only issue is syntax highlighting.

Thanks.

**Comment by kaisalmen** [comment]
@metehansenol regarding `monaco-editor-webpack-plugin`, please see here: https://github.com/CodinGame/monaco-vscode-api#if-you-use-webpack

**Comment by metehansenol** [comment]
Hi @kaisalmen,

Can you be more specific or any examples how to specify those alternatives because I checked that section couple times but I thought that I already imported json default extensions so it should be enough. Should I add another config by extending my Webpack config?

**Comment by kaisalmen** [comment]
@metehansenol the python client config (se [here](https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/src/python/client/config.ts)) also only imports `import '@codingame/monaco-vscode-python-default-extension';`. So what you do looks alright. Can you share a complete example. The issue must be with bundling or eventually a mismatch of imported monaco-vscode api packages. They have to match the same minor version.

**Comment by metehansenol** [comment]
Hi @kaisalmen, I've just seen the [change log here](https://github.com/TypeFox/monaco-languageclient/blob/main/packages/wrapper-react/CHANGELOG.md) and figured out yes I was trying extension package version 5.0.1 with react component v3.2.1, added correct version and it's working now. Thanks.

And you guys doing a great work I appreciate please let me know if I can help for anything.
