### ISSUE TITLE
monaco-vscode-editor-api is missing some files

### ISSUE THREAD

**Issue by xueerli** [TypeFox/monaco-languageclient#655]
### Description
I upgraded from version 7 to 8 and used `monaco-vscode-editor-api` to replace `monaco-editor-treemended` as per the docs.
But `monaco-vscode-editor-api` miss some files. e.g. `metadata.js` which is used by `monaco-editor-webpack-plugin`.

Before:
```
"monaco-editor": "npm:@codingame/monaco-editor-treemended@>=1.83.16 <1.84.0",
"monaco-languageclient": "~7.2.0",
"vscode": "npm:@codingame/monaco-vscode-api@>=1.83.16 <1.84.0",
```

Now:
```
"monaco-editor": "npm:@codingame/monaco-vscode-editor-api@4.3.2",
"monaco-languageclient": "8.3.1",
"vscode": "npm:@codingame/monaco-vscode-api@4.3.2",
```

Here is a list of files for `monaco-vscode-editor-api`：
![1](https://github.com/TypeFox/monaco-languageclient/assets/35445052/e844f691-8aca-4686-8020-33ecd6c62d3d)
Here is a list of files for `monaco-editor-treemended`:
![2](https://github.com/TypeFox/monaco-languageclient/assets/35445052/32ed81c1-9e53-463a-b65a-638a41aad6bd)

### Expectation
Upgrade to v8 with minimal changes. 

Thanks.

**Comment by kaisalmen** [comment]
@xueerli see here: https://github.com/CodinGame/monaco-vscode-api#if-you-use-webpack

**Comment by xueerli** [comment]
Thank you for your response.
In addition to `monaco-editor-webpack-plugin`, there is no `setLocale` method in `monaco-editor/esm/vs/nls` .
There is also no `monaco-editor/esm/vs/platform/actions/common/actions` to handle context menus.

**Comment by xueerli** [comment]
@CGNonofr 
I use `vs/nls setLocale` to set locale language.
I use `vs/platform/actions/common/actions` to delete some actions.

**Comment by CGNonofr** [comment]
I'm not sure why you would want to call setLocale by hands?

You should be able to import `vscode/vscode/XXX` instead of `monaco-editor/esm/XXX` though

**Comment by kaisalmen** [comment]
@xueerli we even have a utility for loading locales available:
https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/wrapper_statemachine.html#L18-L22

It must be loaded before anything else. 
Usage is demonstrate here:
https://github.com/TypeFox/monaco-languageclient/blob/main/index.html#L41

**Comment by xueerli** [comment]
@CGNonofr 
I use ESM. Shouldn't I set Locale manually? 
I couldn't find a better way. Here's a related issue [https://github.com/microsoft/monaco-editor/issues/1514](https://github.com/microsoft/monaco-editor/issues/1514).

**Comment by CGNonofr** [comment]
We are using our own localization mechanism here, inspired by what is used in VSCode, adpated to work in ESM (VScode is built into commonjs/umd and they inject the localization at runtime, which is not possible with ESM)

setLocale is an internal api and you're not supposed to call it by hands. you would need to give the localization content as parameter

**Comment by xueerli** [comment]
@CGNonofr @kaisalmen 
Thank you so much. Referring to your implementation, I'll try `registerLocalization` in `vscode/l10n`.

**Comment by CGNonofr** [comment]
Why don't you use what @kaisalmen suggested?

**Comment by kaisalmen** [comment]
https://github.com/TypeFox/monaco-languageclient/issues/655#issuecomment-2144469817 describes the best way forward.
