### ISSUE TITLE
Can the server support custom code prompts?

### ISSUE THREAD

**Issue by wrf1998** [TypeFox/monaco-languageclient#656]
I am currently using the python server in the example, and I find that its code hints only support the data provided by pyright, but I have some packages that are internal to the company, and I want to be able to hint and hover the mouse to see some specific information about the package, etc. How do I need to modify my server side

**Comment by kaisalmen** [comment]
Hi @wrf1998 this is a pyright configuration issue. Did you check the [documentation ](https://microsoft.github.io/pyright/#/) or did you test try this within VSCode already?

**Comment by wrf1998** [comment]
> Hi @wrf1998 this is a pyright configuration issue. Did you check the [documentation ](https://microsoft.github.io/pyright/#/) or did you test try this within VSCode already?

I did not use vscode software, I used monago-edit, and on the server side I started the node service directly following the documentation tutorial without making any changes.
At the same time, most of what I see in the pyright documentation is for vscode configuration, not like this to start a node to provide web socket service, so I do not know how to configure


<img width="1098" alt="image" src="https://github.com/TypeFox/monaco-languageclient/assets/33780900/aec5c8fe-53d0-497c-9034-641b477ff016">
