### ISSUE TITLE
How to use it in ipynb multi-cell situation?

### ISSUE THREAD

**Issue by FoSuCloud** [TypeFox/monaco-languageclient#662]
Hello, will you provide examples of ipynb in the future?

**Comment by FoSuCloud** [comment]
I want to use multiple monaco instances as a model, how to use the same uri? Just like jupyter does

**Comment by msujew** [comment]
@FoSuCloud I'm not aware of how it's implemented in Jupyter, but in VSCode, every cell is its own document. Cells don't share document data between them. Note that VSCode uses a specificially crafted cell uri that looks like `vscode-notebook-cell://<file>#<cell-handle>`.

**Comment by FoSuCloud** [comment]
> @FoSuCloud I'm not aware of how it's implemented in Jupyter, but in VSCode, every cell is its own document. Cells don't share document data between them. Note that VSCode uses a specificially crafted cell uri that looks like `vscode-notebook-cell://<file>#<cell-handle>`.

Thank you for your help!
