### ISSUE TITLE
Click lightbulb context menu && How to register a command with the specified id?

### ISSUE THREAD

**Issue by vincentLiuxiang** [TypeFox/monaco-languageclient#67]
hi，@akosyakov  could you give me some idea?

[Click lightbulb context menu && How to register a command with the specified id?](https://github.com/Microsoft/monaco-editor/issues/782)

**Comment by rcjsuen** [comment]
@vincentLiuxiang Which version of Monaco and monaco-languageclient are you using?

Please paste your package.json file here.

**Comment by vincentLiuxiang** [comment]
@rcjsuen I clone the latest version from this repo today.

and import `monaco-editor` from 

`https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/editor/editor.main.js` 

monaco vesion: 0.11.6.

And then, could you compile the package `vscode-base-languageclient` from ts to es5? or My project will uglify failed!

Because of this reason I have to compile `vscode-base-languageclient` and  `monaco-languageclient` package with source.

**Comment by rcjsuen** [comment]
@vincentLiuxiang Please put debugging print statements or whatever and see what commands get registered in the `MonacoCommands` class.

https://github.com/TypeFox/monaco-languageclient/blob/557ef39258b05da48c4e403b39465094c3d3f86a/src/commands.ts#L11-L16

**Comment by akosyakov** [comment]
@vincentLiuxiang you can implement this command with https://github.com/TypeFox/monaco-languageclient/blob/master/src/workspace.ts#L94 and register it for Monaco

> And then, could you compile the package vscode-base-languageclient from ts to es5? or My project will uglify failed! Because of this reason I have to compile vscode-base-languageclient and monaco-languageclient package with source.

You are welcome to open a PR.
