### ISSUE TITLE
Update the Example Code in `README.md` of `wrapper-react` and `wrapper`

### ISSUE THREAD

**Issue by Yokozuna59** [TypeFox/monaco-languageclient#673]
Hey there,

The current example code in https://github.com/TypeFox/monaco-languageclient/blob/1a1595c9160d1027621e51f0e5ae2ddc186e1815/packages/wrapper-react/README.md and https://github.com/TypeFox/monaco-languageclient/blob/1a1595c9160d1027621e51f0e5ae2ddc186e1815/packages/wrapper/README.md aren't updated to the latest version:

https://github.com/TypeFox/monaco-languageclient/blob/1a1595c9160d1027621e51f0e5ae2ddc186e1815/packages/wrapper-react/README.md?plain=1#L30_L31

https://github.com/TypeFox/monaco-languageclient/blob/1a1595c9160d1027621e51f0e5ae2ddc186e1815/packages/wrapper/README.md?plain=1#L61_L62

**Comment by kaisalmen** [comment]
@Yokozuna59 thank you, forgot to update those. Will do...

**Comment by kaisalmen** [comment]
Was fixed on main branch. New releases are available:
https://www.npmjs.com/package/monaco-languageclient/v/8.5.0
https://www.npmjs.com/package/vscode-ws-jsonrpc/v/3.3.2
https://www.npmjs.com/package/monaco-editor-wrapper/v/5.2.0
https://www.npmjs.com/package/@typefox/monaco-editor-react/v/4.2.0
