### ISSUE TITLE
Typescript incorrect type highlighting

### ISSUE THREAD

**Issue by KornelijusS** [TypeFox/monaco-languageclient#695]
Hey,

I recently started using this library for web code editor side project. I have copied over wrapperTs, but cannot get Typescript errors to be highlighted. Is there some setting that has to be checked?

This is my monaco.ts that is basically a copy of wrapperTs.ts.

```import * as vscode from 'vscode';
import * as monaco from 'monaco-editor';
import getKeybindingsServiceOverride from '@codingame/monaco-vscode-keybindings-service-override';
import '@codingame/monaco-vscode-theme-defaults-default-extension';
import '@codingame/monaco-vscode-typescript-basics-default-extension';
import '@codingame/monaco-vscode-typescript-language-features-default-extension';
import { CodePlusUri, MonacoEditorLanguageClientWrapper, UserConfig } from 'monaco-editor-wrapper';
import { useWorkerFactory } from 'monaco-editor-wrapper/workerFactory';

export const configureMonacoWorkers = () => {
    useWorkerFactory({
        ignoreMapping: true,
        workerLoaders: {
            editorWorkerService: () => new Worker(new URL('monaco-editor/esm/vs/editor/editor.worker.js', import.meta.url), { type: 'module' })
        }
    });
};

export const runTsWrapper = async () => {
    const codeUri = '/workspace/hello.ts';
    const code = `function sayHello(): string {
    return "Hello";
};`;

    const codeOriginalUri = '/workspace/goodbye.ts';
    const codeOriginal = `function sayGoodbye(): string {
    return "Goodbye";
};`;

    const monacoEditorConfig = {
        glyphMargin: true,
        guides: {
            bracketPairs: true
        },
        lightbulb: {
            enabled: monaco.editor.ShowLightbulbIconMode.On
        },
        theme: 'vs-light'
    };

    const monacoDiffEditorConfig = {
        ...monacoEditorConfig,
        renderSideBySide: false
    };

    const userConfig: UserConfig = {
        wrapperConfig: {
            serviceConfig: {
                userServices: {
                    ...getKeybindingsServiceOverride()
                },

                enableExtHostWorker: true,
                debugLogging: true
            },
            editorAppConfig: {
                $type: 'extended',
                codeResources: {
                    main: {
                        text: code,
                        uri: codeUri,
                        fileExt: 'ts'
                    },
                    original: {
                        text: codeOriginal,
                        uri: codeOriginalUri,
                        fileExt: 'ts'
                    }
                },
                useDiffEditor: false,
                editorOptions: monacoEditorConfig,
                diffEditorOptions: monacoDiffEditorConfig
            }
        }
    };
```

What should I include in the code to get errors highlighted. For example, this should show an error:
```
console.abc();

Property 'abc' does not exist on type 'Console'. Did you mean 'log'?(2551)
```

**Comment by kaisalmen** [comment]
Hi @KornelijusS both the original TS example/your config make use of the TypeScript extension host and I thought as well this is marked as an error. Don't know if that is true for the regular monaco-editor TS Worker.

@CGNonofr I see that in https://monaco-vscode-api.netlify.app/ `console.abc()` is also not marked as error when you add it to a TS file. Is this usually available in the extension worker or did something break recently?

**Comment by kaisalmen** [comment]
Or is it related to this? https://github.com/CodinGame/monaco-vscode-api?tab=readme-ov-file#the-typescript-language-features-extension-is-not-providing-project-wide-intellisense

**Comment by KornelijusS** [comment]
Hey, found a solution. It seems that this options must be enabled in userConfig to work: `"typescript.tsserver.web.projectWideIntellisense.suppressSemanticErrors": false`. Thanks for pointing me on the right track. I hope I didn't take too much of your time

**Comment by CGNonofr** [comment]
You were faster than me :) that what I was going to answer, not really sure why they disable it by default...

**Comment by kaisalmen** [comment]
@KornelijusS and @CGNonofr thank you. TIL something new. I should add this in the example.

**Comment by CGNonofr** [comment]
Btw, keep it mind that even from microsoft perspectives, the typescript worker project wide intellisense is still experimental and only enabled in the insider version.

At CodinGame we chose to not use it and go back to the monaco worker instead (with some glue)

**Comment by KornelijusS** [comment]
Okay, thanks. In my use-case it's more that I need one workspace to have intellisense and all other parts will be included as d.ts files only to get only the definitions

**Comment by kaisalmen** [comment]
> Btw, keep it mind that even from microsoft perspectives, the typescript worker project wide intellisense is still experimental and only enabled in the insider version.

@CGNonofr I pushed an update to main where the config of the TS example is changed, but it does not have the desired effect

**Comment by CGNonofr** [comment]
> > Btw, keep it mind that even from microsoft perspectives, the typescript worker project wide intellisense is still experimental and only enabled in the insider version.
> 
> @CGNonofr I pushed an update to main where the config of the TS example is changed, but it does not have the desired effect

What do you mean?

**Comment by kaisalmen** [comment]
It seems the error marking does not work even if `"typescript.tsserver.web.projectWideIntellisense.suppressSemanticErrors": false` is set to true (see [here](https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/src/ts/wrapperTs.ts#L56-L65):

![image](https://github.com/TypeFox/monaco-languageclient/assets/21079138/7002f229-397b-4a98-8348-02d826def995)

**Comment by KornelijusS** [comment]
I had to recreate the whole vscode demo and it works then. It seems at least to me in the ts example the ts semantic server is not registered, might this be the reason why it does not work?

**Comment by CGNonofr** [comment]
are you sure corssOriginIsolated is true?

**Comment by kaisalmen** [comment]
> are you sure corssOriginIsolated is true?

Ok, overlooked that (see my own comment  https://github.com/TypeFox/monaco-languageclient/issues/695#issuecomment-2202114867 😅 ). Is this relevant in local dev env as well?

**Comment by KornelijusS** [comment]
<img width="1632" alt="Screenshot 2024-07-02 at 12 59 05" src="https://github.com/TypeFox/monaco-languageclient/assets/150260563/746de7b3-b878-41e3-b2b3-b67c60db99b2">
Maybe you know something about this issue? after updating all dependencies to 6.0.3 I cannot build the project. I'm using this vite config: 
```
export default defineConfig({
  plugins: [vue()],
  resolve: {
    dedupe: ['vscode']
  },
  base: './',
  build: {
    target: 'esnext',
    rollupOptions: {
      external: ['vue'],
      output: {
        assetFileNames: '[name][extname]',
        chunkFileNames: '[name]-[hash].js',
        entryFileNames: '[name].js',
      },
    }
  },

  optimizeDeps: {
    esbuildOptions: {
      plugins: [importMetaUrlPlugin]
    }
  }
})
```

**Comment by CGNonofr** [comment]
No idea, there is NO import to anything related to issue service in extensionBisect.js

**Comment by kaisalmen** [comment]
You need to use the newest version, see if `npm list` shows mismatching monaco-vscode-api versions.
```yaml
    "monaco-editor-wrapper": "^5.2.0",
    "monaco-languageclient": "^8.5.0",
```

**Comment by kaisalmen** [comment]
Did you get a peerDependency warning by any chance?

**Comment by KornelijusS** [comment]
No, but updated the dependencies and it worked. Thank you!

**Comment by KornelijusS** [comment]
crossOriginIsolated is turned on, but it does not seem to register the TS semantic server still. I guess this is the reason the compiler does not work and no errors a shown

**Comment by KornelijusS** [comment]
@CGNonofr Hey, could you maybe provide an example how you implemented the tsserver using monaco worker? :/

**Comment by CGNonofr** [comment]
Sure, everything is here: https://github.com/CodinGame/monaco-editor-wrapper/blob/main/src/features/typescriptStandalone.ts

**Comment by KornelijusS** [comment]
One last question I have is: Is there some way to get TS semantic server to work/register when not running a server, but just from build index.html? As I am trying to run it as a worker, but only syntax server registers. Or the only way would be to turn to monaco worker?

**Comment by CGNonofr** [comment]
Are you trying to put everything into a single html file? why?

**Comment by KornelijusS** [comment]
I'm just using the npm run build and then running the resulting index.html, which loads everything that is in the assets folder. So everything loads and works fine from the demo, the only missing part is the TS semantic server, which does not load for some reason, but no errors are shown. I need this particular way, because to integrate into my existing project I can't create a new server to run the editor. For this reason I upload the resulting build files to CDN as a library and then run the index.js, which loads everything else.

**Comment by CGNonofr** [comment]
I'm not sure why you expect to need a "new server" nor what it would do.

It the worker doesn't work, we can help you but we would need to see your code

**Comment by KornelijusS** [comment]
I have forked the monaco-vscode-api repository and ran all the steps needed to run npm run build on demo folder. Then I just opened the resulting index.html in a browser. Haven't changed any code there, just what is from the fork. Everything loads except the TS semantic server, which is needed for the errors to be shown.

**Comment by KornelijusS** [comment]
<img width="358" alt="Screenshot 2024-07-03 at 11 24 48" src="https://github.com/TypeFox/monaco-languageclient/assets/150260563/7abda793-3a8a-4286-ac78-bdd4ac4bea2c">
This is from your demo site. As I understand the TS semantic server is needed for errors to be shown. As without it I don't get any errors like `console.abc()` should throw one, but it does not if. the TS semantic server is not running, but if I run the demo from my fork with `npm run start` - the TS semantic server registers and the `console.abc()` does show an error.
