### ISSUE TITLE
'vscode-languageclient/lib/common/client.js' doesn't provide an export named: 'BaseLanguageClient'

### ISSUE THREAD

**Issue by Mw3y** [TypeFox/monaco-languageclient#713]
Hey @kaisalmen,

I've been getting an error only in vite dev which I couldn't fix. I'm using the same dep versions as in your examples.
Full error:
```
The requested module 'http://localhost:3000/_nuxt/node_modules/vscode-languageclient/lib/common/client.js?v=100d8800' doesn't provide an export named: 'BaseLanguageClient'
```

Do you have idea on how I could fix it?

**Comment by CGNonofr** [comment]
What bundler are you using? because vscode-languageclient is in commonjs, and `BaseLanguageClient` is exported from `vscode-languageclient/lib/common/client.js` so I don't know what else it can be

**Comment by Mw3y** [comment]
I'm using Nuxt with vite.

**Comment by pbrostean** [comment]
Hello, I'm getting the same Error. Could you please tell me if you were able to resolve that issue and how?

**Comment by Mw3y** [comment]
Hey! It was some mismatched versions. I think you can find the compatibility table in the README.

**Comment by pbrostean** [comment]
Thank you for your quick reply! I'm trying to look into that compativility table, but I'm not sure if that's the cause of it. I'm able to build the project, just running it with the vite dev seems to be throwing that error.

**Comment by ajuvercr** [comment]
For me I copied some vite config from somewhere which had `exclude: ["monaco-editor", "vscode-ws-jsonrpc", "monaco-languageclient"],` removing this fixed it.

For reference my 'minimal', or small enough working vite config is as follows

```js
import importMetaUrlPlugin from "@codingame/esbuild-import-meta-url-plugin";
export default {
  worker: {
    format: "es",
  },
  build: {
    target: "esnext",
  },
  resolve: {
    dedupe: ["vscode"],
  },
};
```
Maybe the tsconfig is also important
```json
{
  "compilerOptions": {
    "target": "ES6",
    "module": "NodeNext",
    "moduleResolution": "nodenext",
    "esModuleInterop": true,
    "sourceMap": true
  }
}
```

**Comment by Aaron2599** [comment]
Hi, I encountered this same error while running in dev mode with Vite. The fix was to add these lines to my Vite config.
```
    worker: {
        format: "es",
    },
    build: {
        target: "esnext",
    },
    resolve: {
        dedupe: ["vscode"],
    },
```
