### ISSUE TITLE
Question about using monaco-vscode-editor-api vs monaco-editor for LSP Integration

### ISSUE THREAD

**Issue by shivam6543** [TypeFox/monaco-languageclient#717]
Hello team,

First of all, I would like to thank for developing such an amazing library.

I have a question regarding the usage of `monaco-vscode-editor-api` instead of directly using `monaco-editor` in the examples. What are the benefits of using it?

Recently, I was trying to use `monaco-languageclient` to connect `monaco-editor` with a WebSocket LSP server. However, it was not making any `didOpen` calls from the client when I was using `monaco-editor` version `0.50.0`. When I changed it to `npm:@codingame/monaco-vscode-editor-api@~7.0.7`, it started making this call. 

Someone else faced the [same issue](https://github.com/TypeFox/monaco-languageclient/issues/712#issuecomment-2239428498) and was able to solve it by using this version: `npm:@codingame/monaco-vscode-editor-api@~7.0.7`. I would like to understand why this behavior occurs. I tried to find the documentation for the new package but was not able to locate it. Can someone explain why this is happening and when we should use the new package?

I'm unable to find the documentation for the `monaco-vscode-editor-api` package. Can you please point me in the right direction?

Thank you for your help!

**Comment by cdietrich** [comment]
i cant answer your question but the package is at https://github.com/CodinGame/monaco-vscode-api

**Comment by CGNonofr** [comment]
the `monaco-editor` package contains the actual code of monaco-editor, which is extracted from the VSCode codebase, going through an intense treeshaking.

`monaco-vscode-api` also use the VSCode codebase widely, including what `monaco-editor` includes and much more

At some point, we were using the offical monaco-editor, which we "patched" to restore the treeshaken part, but it was really complicated to use and had a lot of downside (doesn't work well with pnpm for instance)

Now, we don't rely on the monaco-editor package at all, and bundle everything ourselves in the `monaco-vscode-api` package.

The `@codingame/monaco-vscode-editor-api` package just exposes the monaco-editor api bundled in `monaco-vscode-api`. If you install `monaco-editor` you just get another totally independent version of monaco-editor.

**Comment by shivam6543** [comment]
@CGNonofr Thanks for the detailed explanation!

One thing that is not clear to me is: when I use `monaco-editor` directly, it doesn't make a `didOpen` call, but when I use `@codingame/monaco-vscode-editor-api`, it does make the `didOpen` call. Can you explain why this is happening? Are we doing something in this package that's causing that call? In the older version of monaco-editor, it used to make `didOpen` call.

One more question I have: We're already installing the `@codingame/monaco-vscode-editor-api` package so I think we don't need to install the `"vscode": "npm:@codingame/monaco-vscode-api@~7.0.7"` package separately. Am I right?

**Comment by CGNonofr** [comment]
> One thing that is not clear to me is: when I use monaco-editor directly, it doesn't make a didOpen call, but when I use @codingame/monaco-vscode-editor-api, it does make the didOpen call. Can you explain why this is happening? Are we doing something in this package that's causing that call? In the older version of monaco-editor, it used to make didOpen call.

As I said, if you install/use `monaco-editor`, it has absolutely nothing to do with monaco-vscode-api or monaco-languageclient, so nothing you can do with it will have any effect on your `monaco-editor`

> One more question I have: We're already installing the @codingame/monaco-vscode-editor-api package so I think we don't need to install the "vscode": "npm:@codingame/monaco-vscode-api@~7.0.7" package separately. Am I right?

It's probably not required to work but I would still recommend having as direct dependency anything you use directly in your code

**Comment by shivam6543** [comment]
Yes, I understand that both are different packages. In the examples, we install the `monaco-vscode-editor-api` as an alias to the `monaco-editor` package, right? My question is: when I install it using `npm i monaco-editor`, the client doesn't make a `didOpen` call, and none of the LSP features work. However, when I install it using `npm install monaco-editor@npm:@codingame/monaco-vscode-editor-api`, everything works fine. Do you have any idea why this behavior occurs?

**Comment by CGNonofr** [comment]
It seems there is a misunderstanding here.

> we install the monaco-vscode-editor-api as an alias to the monaco-editor package, right

I'm not sure you understood it the right way: it doesn't mean monaco-vscode-editor-api links to monaco-editor, it means monaco-editor links to monaco-vscode-editor-api. The official monaco-editor is NEVER involved here.

**Comment by shivam6543** [comment]
Ok, got it now! Thanks you so much for the help!
