### ISSUE TITLE
Error: file 'extension-file://publisher.github-themes/colorthemes/github-dark-default.json/' already exists

### ISSUE THREAD

**Issue by Mw3y** [TypeFox/monaco-languageclient#720]
Hey 👋🏻,

I'm having an issue with a custom theme extension. It works as intended but when I try to create a second `MonacoEditorLanguageClientWrapper` instance in extended config mode with the theme service override it fails with:

```
Error: file 'extension-file://publisher.github-themes/colorthemes/github-dark-default.json/' already exists
```

Here is the extension code:

```ts
import githubDarkDefaultTheme from '@/assets/vscode-themes/github-dark-default.json?raw';
import githubLightDefaultTheme from '@/assets/vscode-themes/github-light-default.json?raw';
import type { ExtensionConfig } from 'monaco-editor-wrapper';

export const lightTheme = {
  id: 'Github Light Default',
  label: 'Github Light Default',
  uiTheme: 'vs',
  path: './colorthemes/github-light-default.json',
};

export const darkTheme = {
  id: 'Github Dark Default',
  label: 'Github Dark Default',
  uiTheme: 'vs-dark',
  path: './colorthemes/github-dark-default.json',
};

export const themeExtension: ExtensionConfig = {
  config: {
    name: 'github-themes',
    publisher: 's4s',
    version: '1.0.0',
    engines: {
      vscode: '*',
    },
    contributes: {
      themes: [lightTheme, darkTheme],
    },
  },
  filesOrContents: new Map<string, string | URL>([
    ['./colorthemes/github-dark-default.json', githubDarkDefaultTheme],
    ['./colorthemes/github-light-default.json', githubLightDefaultTheme],
  ]),
};

```

What am I missing?

**Comment by Mw3y** [comment]
I don't really need the second instance. What I simply want is to have two files: only displaying one at a time but being able to freely change between them.

**Comment by Mw3y** [comment]
I need to add that no registering the extension for the second instance fixes it. This is only a bad workaround. How could I detect another instance or how could I simply fix the extension?

**Comment by kaisalmen** [comment]
Hey @Mw3y what about you do this registration completely independent of the wrapper and use the function supplied by `monaco-vscode-api` directly. This is how the wrapper handles the registration internally:
https://github.com/TypeFox/monaco-languageclient/blob/main/packages/wrapper/src/editorAppExtended.ts#L90-L91

Then you just omit the extension configuration section of the `UserConfig`.

**Comment by Mw3y** [comment]
That worked well! I had some issues with typescript but it's all working now! Thank you for helping me :)
