### ISSUE TITLE
Creating files/directories within a java language server

### ISSUE THREAD

**Issue by Sin-Yone** [TypeFox/monaco-languageclient#731]
Hi everyone, I have a question about the implementation using a Java language server (eclipse.jdt.ls). I followed the example to set up a Java language server with the Monaco editor. So I have a docker container running a server which then starts the java language server. Just like the example in this repo. 

I am using the @typefox/monaco-editor-react package within next.js. The monaco client connects to the language server and works fine. However, I only get autocomplete if the file exists within the Java language server workspace in docker. This makes sense, otherwise the server can't know if the file exists or read content from it. So I created a sample file manually and I get autocompletion and all the other features. Now I want to dynamically create new files and folders from the client, which need to be created inside the language server workspace. But I am stuck and do not know how to do this. I have tried calling `vscode.workspace.fs.createDirectory` which does nothing. When I check `vscode.workspace.workspaceFolders` the array is empty. But shouldn't it be the workspace folder set in the user config that is parsed to the monaco editor react component? I have also tried `fileSystemProvider.mkdirSync` which also does nothing. I think I am confusing the concepts of file systems. As far as I understand, the filesystemprovider from @codingame/monaco-vscode-files-service-override is used for the editor to create a virtual filesystem. But how do I create files and directories on the server? I thought that was what the vscode.workspace api was for. I've been trying to figure this out for a few days now, but I haven't succeeded. So maybe someone could help me out.

Not a problem for this repo, but maybe someone can help me:
I get the following warning
![image](https://github.com/user-attachments/assets/17f250a2-6d72-4d97-9ffd-ca354338ae75)
The first time the client connects to the language server, a `jdt.ls-java-project' is created. I guess it automatically created a java project. Do I need to put my files in there to get rid of the warning?

Since both of these are probably not an issue of this package, perhaps its better to turn this into a discussion.

Either way an awesome package and many thanks already :)

**Comment by kaisalmen** [comment]
@Sin-Yone this is a common problem and I am working on some kind of language server protocol extension/enhancement allowing to sync files (it is not visible yet / not yet ready for review).
Even if you use something like `vscode.workspace.openTextDocument` there is no guarantee a language server handles this. Pyright for example does not. Usually vscode and the language server have access to the same file system. With monaco-languageclient this is not the case (same for LS connected over web socket or LS running as web worker)

**Comment by Sin-Yone** [comment]
@kaisalmen Thanks for the quick reply. Is there any starting point for me to get started as I really need it right now for my masters thesis? The only way I can see now is to mount the workspace of the docker container with the project and then trigger a server action in next.js (basically an api call) and then create the files/folders in that workspace. Then they should be inside the docker container since its mounted. Or is there a better way?

Also, could you maybe clarify for me what exactly `vscode.workspace.xxx` does? What workspace does it access? The virtual filesystem I created via registerFileSystemOverlay? Or the workspace on the server? I'm kinda having a hard time understanding what exactly it does.

**Comment by CGNonofr** [comment]
By default, the accessible filesystem in the client is just a memory filesystem. But you are free to replace it by whatever you want, you can make your over file system provider implementation that remotely manipulate the server filesystem.

Then using `vscode.workspace.fs` will allow you to manipulate the server filesystem.

> When I check vscode.workspace.workspaceFolders the array is empty. 

> Not a problem for this repo, but maybe someone can help me: I get the following warning ![image](https://private-user-images.githubusercontent.com/85801975/359462140-17f250a2-6d72-4d97-9ffd-ca354338ae75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTY3NDEsIm5iZiI6MTcyNDE1NjQ0MSwicGF0aCI6Ii84NTgwMTk3NS8zNTk0NjIxNDAtMTdmMjUwYTItNmQ3Mi00ZDk3LTlmZmQtY2EzNTQzMzhhZTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDEyMjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYTg4NjdlODQ5MWEzYTY3ZTM2OTNhNTI3Y2E5MzU5YmYxZGUzZjZjMDhmNmU3ZmE0MjA2NTIwOWU5NjA4Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B5i_rqBUf2G2Ia6hHWitH1McDEGFSMloqR0B3aFeNgM) The first time the client connects to the language server, a `jdt.ls-java-project' is created. I guess it automatically created a java project. Do I need to put my files in there to get rid of the warning?

The 2 are probably related: you don't have any configured workspace folder

**Comment by Sin-Yone** [comment]
@kaisalmen @CGNonofr Thanks both of you for the quick help. I'll look into it and see if I can get it working!

**Comment by Sin-Yone** [comment]
@kaisalmen Should I close the issue, since it's not really an issue? I managed to solve my problems and make it work for my application.

**Comment by kaisalmen** [comment]
@Sin-Yone thanks for reporting back. I will close this now.
