### ISSUE TITLE
Missing example using normal tsWorker and languages.typescript.typescriptDefaults

### ISSUE THREAD

**Issue by rubenfiszel** [TypeFox/monaco-languageclient#735]
Hi,

I'm migrating from an old version of monaco-languageclient.

I'd like to keep using the tsWorker of monaco but I couldn't figure out from the examples. I also saw a message that codinggame itself keeps using the tsWorker so I suppose it is feasible (to some extent, I'd like to use all the original workers from monaco).

Separately but somehow related, no matter what imports I do:
`monaco.languages.typescript.typescriptDefaults.setCompilerOptions`

always fail because typescript is missing from the monaco.languages. I couldn't figure out when it's loaded and how to do so.

I would suppose it's possible since I see it being used here: https://github.com/CodinGame/monaco-editor-wrapper/blob/f44392a4aef135dc694cf255dfe3dbb67a59334a/src/features/typescriptStandalone.ts#L95

**Comment by CGNonofr** [comment]
Hello!

Did you install and import `@codingame/monaco-vscode-standalone-typescript-language-features`?

**Comment by rubenfiszel** [comment]
I didn't, and now that part is solved. Somehow I was sure I had added all the typescript imports but I was missing that one. Thanks!

**Comment by rubenfiszel** [comment]
@CGNonofr I no more have the issue with ` monaco.languages.typescript.typescriptDefaults.setCompilerOptions` but the tsWorker is not loaded even though:
`MonacoEnvironment.getWorker = getWorker`

Is there anything special that need to be done to tell the editor to load those workers in the bare setup?

**Comment by kaisalmen** [comment]
Hi @rubenfiszel try it like this:
https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/src/ts/wrapperAdvanced.ts#L13-L19
Then you are in full control and can specify the paths as needed. The pre-configured setup has its limits.

**Comment by rubenfiszel** [comment]
Worked, here is our full migration PR if it can be useful for anyone else. Was much less than I anticipated in the end: https://github.com/windmill-labs/windmill/pull/4285

**Comment by Its-its** [comment]
> Worked, here is our full migration PR if it can be useful for anyone else. Was much less than I anticipated in the end: [windmill-labs/windmill#4285](https://github.com/windmill-labs/windmill/pull/4285)

Thank you @rubenfiszel! Somehow I overlooked how to define the worker definitions. Also, this project has so many different packages its' hard to figure out what to install.

(Side Note: Love that you guys also use a Rust + Svelte combo - my current large website builder project is the same)
