### ISSUE TITLE
monaco-editor-wrapper vs @codingame/monaco-editor-wrapper

### ISSUE THREAD

**Issue by rubenfiszel** [TypeFox/monaco-languageclient#736]
Hi, there are 2 libraries with same name but different namespaces.

Can they be both used together (for instance to use the vim keyboard service from '@codingame/monaco-editor-wrapper' ? Why are they separated but have the same name?

**Comment by CGNonofr** [comment]
The CodinGame version of the wrapper is very tied to our needs (including the languages and tools we need). It's open-source because why not, but it wasn't really designed to be generic and to be widely used

**Comment by kaisalmen** [comment]
The question was answered. Closing the issue.
