### ISSUE TITLE
monaco-graphql not working

### ISSUE THREAD

**Issue by rubenfiszel** [TypeFox/monaco-languageclient#737]
Sorry I know this was fixed previously but I have this error:
```
Failed to resolve import "vscode/vscode/vs/editor/contrib/hover/browser/hover" from "node_modules/monaco-editor/esm/vs/editor/contrib/hover/browser/hover.js
```

monaco-graphql depends on:
`monaco-editor/esm/vs/editor/contrib/hover/browser/hover.js`

and if I cat its content I have:
```
cat node_modules/monaco-editor/esm/vs/editor/contrib/hover/browser/hover.js
export * from 'vscode/vscode/vs/editor/contrib/hover/browser/hover'
```

There is nothing at that path, the node_modules for vscode seems to contain the source only, which if I list:
```
ls node_modules/vscode/vscode/src/vs/editor/contrib/hover/browser 
contentHoverComputer.js
contentHoverController.js
contentHoverRendered.js
contentHoverStatusBar.js
contentHoverTypes.js
contentHoverWidget.js
getHover.js
hoverAccessibleViews.js
hoverActionIds.js
hoverActions.js
hoverContribution.js
hoverController.js
hover.css.js
hoverOperation.js
hoverTypes.js
marginHoverComputer.js
marginHoverWidget.js
markdownHoverParticipant.js
markerHoverParticipant.js
resizableContentWidget.js
```

doesn't seem to contain an hover.js. However it seems that previous versions of vscode did have such file. Is it a matter of doing a PR on monaco-graphql ?

**Comment by rubenfiszel** [comment]
fix in the meantime: 
```
	resolve: {
		alias: {
			'vscode/vscode/vs/editor/contrib/hover/browser/hover':
				'vscode/vscode/vs/editor/contrib/hover/browser/hoverController'
		},
	}
```
might not be a monaco-languageclient issue but likely an issue with graphql in the first place. However, when they do update, vscode-api should expose that hoverController

**Comment by kaisalmen** [comment]
> However, when they do update, vscode-api should expose that hoverController

@CGNonofr WDYT?

**Comment by CGNonofr** [comment]
I'm afraid the `vs/editor/contrib/hover/browser/hover` file was moved (in [this commit](https://github.com/microsoft/vscode/commit/9deb01df504be7108c8d2aa79aec5ebe3eefa5ef))

so both monaco-vscode-api AND monaco-graphql need an update

Here's the monaco-vscode-api one: https://github.com/CodinGame/monaco-vscode-api/pull/493
