### ISSUE TITLE
Connecting monaco with Xtext language server

### ISSUE THREAD

**Issue by nils-christian** [TypeFox/monaco-languageclient#75]
Hi,

First of all: Thank you for providing us with an extension for monaco to use the lsp. However, I am having trouble to use this (unfortunately, I have to say also due to the lack of good documentation) in my context. I am trying to implement a (web socket based) language server. I used more or less the example from [here](https://github.com/cdietrich/xtext-languageserver-example/blob/master/org.xtext.example.mydsl.websockets/src/org/xtext/example/mydsl/websockets/RunWebSocketServer.xtend). So it is basically just a server which would listen to a port and delegate to the Xtext language server. 

Your example always tries to connect to the same adress that provided the index.html file, so I tried to change this by editing the js file:
```
function createUrl(path) {
  // var protocol = location.protocol === 'https:' ? 'wss' : 'ws';
  // return normalizeUrl(protocol + "://" + location.host + location.pathname + path);
  return normalizeUrl('ws://localhost:4389');
}
```
Now the languageclient seems to try to connect to by language server. However, the language server simply blocks in the _org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen_ method, as it seems to expect more data, which the language client does not provide.

Can you help me find the reason for this or do you perhaps even know it? Your description [here ](http://typefox.io/teaching-the-language-server-protocol-to-microsofts-monaco-editor) is currently not enough to implement a runnable example on my own.. A lot of details are missing. Furthermore, the examples are unfortunately now very helpful in my opinion.

Thank you and best regards

  Nils

**Comment by akosyakov** [comment]
@nils-christian We don't have an example with Java-based server you are welcome to add one. Although it should not be Xtext-based but something simple and common.

If you stick with the node-based server from examples then it should be possible to connect it to the Xtext LS over the stdin by changing https://github.com/TypeFox/monaco-languageclient/blob/beca1e697bef460a721c2889d3b4afd5369b7ea7/example/src/json-server-launcher.ts#L17-L19 as @rcjsuen mentioned.

@spoenemann demonstrated [here](http://typefox.io/building-a-vs-code-extension-with-xtext-and-the-language-server-protocol) how to connect the Xtext LS to the VS Code over the stdin. The similar approach should work with Monaco.

**Comment by cdietrich** [comment]
i tried that using websockets and the main problem was that one: https://github.com/TypeFox/vscode-ws-jsonrpc/issues/6

**Comment by spoenemann** [comment]
Find an example of integrating monaco-languageclient with an Xtext language server here:

https://github.com/OpenKieler/elkgraph-web
