### ISSUE TITLE
run time error when clicking the Start button in the Groovy demo

### ISSUE THREAD

**Issue by ls-infra** [TypeFox/monaco-languageclient#758]
<img width="948" alt="image" src="https://github.com/user-attachments/assets/8c20477d-0f10-4b91-918e-7a02abe5f14a">

**Comment by kaisalmen** [comment]
@ls-infra  did you start the docker container as noted in the main index.html, see `docker compose -f ./packages/examples/resources/groovy/docker-compose.yml up -d`
