### ISSUE TITLE
Connect my project with language server 

### ISSUE THREAD

**Issue by Louis-7** [TypeFox/monaco-languageclient#76]
Hi,

I'm trying to connect my own project with language server which in example. I use angular-cli create the project and use [ngx-monaco-editor](https://github.com/atularen/ngx-monaco-editor). I copy the example code into my project and it can connect to language server but when I edit source code in monaco, it didn't send/receive message from language server which unlike the example provided in this library.

I almost copy/paste the code from example folder and only change some variable names. **Anyone know why no web socket connection while I'm editing in Monaco?**

Below is screen shot I took from Chrome, only one message return by server and no further response/request while update code in Monaco.
![image](https://user-images.githubusercontent.com/12605300/39697341-325065cc-5223-11e8-9e05-891426b85931.png)

Here is the code (re-edit for better understanding):
monaco-editor.html

```html
<ngx-monaco-editor class="monaco-code-editor" [options]="options" [(ngModel)]="code" (onInit)="onMonacoInit($event)"></ngx-monaco-editor>
```

monaco-editor.ts
```typescript
public options = {
    glyphMargin: true,
    lightbulb: {
      enabled: true
    }
  };

  public code = `{
    "$schema": "http://json.schemastore.org/coffeelint",
    "line_endings": "unix"
  }`;

  public model: NgxEditorModel = {
    value: this.code,
    language: 'json',
    // uri: 'inmemory://model.json',
  };
```
monaco configuration:
```typescript
export let MonacoConfig: NgxMonacoEditorConfig = {
    baseUrl: './assets', // configure base path for monaco editor
    defaultOptions: { scrollBeyondLastLine: false }, // pass default options to be used
    onMonacoLoad: () => {
        // here monaco object will be available as window.monaco use this function to extend monaco editor functionalities.
        console.log((<any>window).monaco);

        monaco.languages.register({
          id: 'json',
          extensions: ['.json', '.bowerrc', '.jshintrc', '.jscsrc', '.eslintrc', '.babelrc'],
          aliases: ['JSON', 'json'],
          mimetypes: ['application/json'],
      });
    }
};
```
monaco onInit handler:
```typescript
onMonacoInit(editor) {
    // create the web socket
    const url = createUrl('/sampleServer');
    const webSocket = createWebSocket(url);
    // listen when the web socket is opened
    listen({
      webSocket,
      onConnection: connection => {
        // create and start the language client
        const languageClient = createLanguageClient(connection);
        const disposable = languageClient.start();
        connection.onClose(() => disposable.dispose());
      }
    });

    const services = createMonacoServices(editor);
    function createLanguageClient(connection: MessageConnection): BaseLanguageClient {
      return new BaseLanguageClient({
        name: 'Sample Language Client',
        clientOptions: {
          // use a language id as a document selector
          documentSelector: ['json'],
          // disable the default error handler
          errorHandler: {
            error: () => ErrorAction.Continue,
            closed: () => CloseAction.DoNotRestart
          }
        },
        services,
        // create a language client connection from the JSON RPC connection on demand
        connectionProvider: {
          get: (errorHandler, closeHandler) => {
            return Promise.resolve(createConnection(connection, errorHandler, closeHandler));
          }
        }
      });
    }

    function createUrl(path: string): string {
      // const protocol = location.protocol === 'https:' ? 'wss' : 'ws';
      // return normalizeUrl(`${protocol}://${location.host}${location.pathname}${path}`);
      return 'ws://localhost:3000/sampleServer';
    }

    function createWebSocket(wsUrl: string): WebSocket {
      const socketOptions = {
        maxReconnectionDelay: 10000,
        minReconnectionDelay: 1000,
        reconnectionDelayGrowFactor: 1.3,
        connectionTimeout: 10000,
        maxRetries: Infinity,
        debug: false
      };
      return new ReconnectingWebSocket(wsUrl, undefined, socketOptions);
    }
  }
```

**Comment by akosyakov** [comment]
Hi! It would help if you can share a project.

**Comment by Louis-7** [comment]
@akosyakov Sure, I will work on it then back here.

**Comment by akosyakov** [comment]
There were changes in vscode-ws-jsonrpc to pass JSON-RPC messages as is. It seems that you are running the language server with this changes, but the client is still using the old version: https://github.com/Louis-7/angular-monaco-languageclient/blob/c211f83cc773a068e7606cce82fe4c43b9f2a4ed/package.json#L30

**Comment by Louis-7** [comment]
I update the dependency as you said, but there is a new error in browser.

`Uncaught ReferenceError: setImmediate is not defined`

I also tried use version@0.0.2-1, but I got same error. Seems the error is occur when _vscode-ws-jsonrpc_ call some method in _vscode-jsonrpc_

**Comment by Louis-7** [comment]
I update my code to fix some build error and it still have the error I mentioned. I also try to modify vscode-jsonrpc library, but it still not working at all.

**Comment by Louis-7** [comment]
I found the root cause. It's because the version of monaco I use have a defect. I close this issue now.

**Comment by rcjsuen** [comment]
@Louis-7 Interesting. Which bug was it?

**Comment by Louis-7** [comment]
@rcjsuen you can find it [here](https://github.com/Microsoft/monaco-editor/issues/839).

`MarkerSeverity ` is not exported and monaco-languageclient is using it in [converter.ts](https://github.com/TypeFox/monaco-languageclient/blob/master/src/converter.ts). That's why I got the errors I mentioned and it's a bug with ESM (I use angular-cli).

**Comment by mariomurrent-softwaresolutions** [comment]
> @rcjsuen you can find it [here](https://github.com/Microsoft/monaco-editor/issues/839).
> 
> `MarkerSeverity ` is not exported and monaco-languageclient is using it in [converter.ts](https://github.com/TypeFox/monaco-languageclient/blob/master/src/converter.ts). That's why I got the errors I mentioned and it's a bug with ESM (I use angular-cli).

@rcjsuen Do you have a working example for connecting the language server to ng-monaco? It does not work for me :(

**Comment by rcjsuen** [comment]
@mariomurrent-softwaresolutions I think you were looking for @Louis-7?

**Comment by mariomurrent-softwaresolutions** [comment]
Well yes, thank you.

**Comment by Louis-7** [comment]
@mariomurrent-softwaresolutions check this out. 

https://github.com/Louis-7/angular-monaco-languageclient
