### ISSUE TITLE
Documentation here is lacking

### ISSUE THREAD

**Issue by rnmalonebb** [TypeFox/monaco-languageclient#760]
Integrating with this library has been very challenging due to a distinct lack of documentation on how to create a language client.

The README immediately lists off multiple libraries that implement it - that's great but we don't need those, we want our own standalone language client wired up to an existing editor instance. 

The examples don't even show a monaco-languageclient being created or what the API is, they all use the `monaco-editor-wrapper` library which does not suit our use case.

All in all, when working with complex subjects like LSP, there is limited resources online with how to implement it. I think with kind of library there needs to be a basic setup guide and API documentation, on top of the existing type declaration files that do very little to guide users on how to integrate with the package.

**Comment by rnmalonebb** [comment]
I'll be happy to contribute once I've grasped it! 

Another very frustrating issue is the examples use an API for a release candidate not publicly available.

**Comment by kaisalmen** [comment]
> Another very frustrating issue is the examples use an API for a release candidate not publicly available.

Yes, I know, it will come. I busy with other things and unable to continue the work. I want to update to the latest monaco-vscode-api version first and push out an new next version.

> they all use the monaco-editor-wrapper library which does not suit our use case.

There is the bare example: https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/src/bare/client.ts It is also mentioned in the README.

There is room for doc improvement. On the other hand, many of the examples pose answers to questions some-one else had in the past. As @CGNonofr said, help is welcome. 🙂

**Comment by kaisalmen** [comment]
@rnmalonebb next.2 versions of the packages are now available

**Comment by kaisalmen** [comment]
I have added the request for better documentation to our enhancement idea discussion: https://github.com/TypeFox/monaco-languageclient/discussions/773
