### ISSUE TITLE
README build instructions out of date

### ISSUE THREAD

**Issue by simark** [TypeFox/monaco-languageclient#78]
The README says to use `npm run build`, but the `build` script doesn't exist.

**Comment by rcjsuen** [comment]
@simark Those instructions are for the example. The `build` script seems to be there.

https://github.com/TypeFox/monaco-languageclient/blob/beca1e697bef460a721c2889d3b4afd5369b7ea7/examples/browser/package.json#L20-L31

https://github.com/TypeFox/monaco-languageclient/blob/beca1e697bef460a721c2889d3b4afd5369b7ea7/example/package.json#L31-L40

**Comment by simark** [comment]
Ah yes sorry, it's actually quite clear as-is.
