### ISSUE TITLE
Upgrade to Monaco 0.13.x

### ISSUE THREAD

**Issue by rcjsuen** [TypeFox/monaco-languageclient#79]
Looks like Monaco 0.13.0 has been [released](https://github.com/Microsoft/monaco-editor/commit/6dc4fba5deb2b730d3ef8fc99262a1d5dbcb3b4d).

**Comment by akosyakov** [comment]
We need it to support the folding range provider: https://github.com/Microsoft/monaco-editor/blob/14f6229243233f456eb688c0dbdf505c61731b64/monaco.d.ts#L4132

I will look into it after getting rid of vscode-base-languageclient.
