### ISSUE TITLE
The `startOptions.onCall` function is not triggered when `$type = 'WebSocketDirect'`.

### ISSUE THREAD

**Issue by jinchaofs** [TypeFox/monaco-languageclient#799]
In the `LanguageClientWrapper` class, the `start` method checks the WebSocket connection type as follows:

```ts
if (conOptions.$type === 'WebSocketDirect' || conOptions.$type === 'WebSocketParams' || conOptions.$type === 'WebSocketUrl') {
    const webSocket = conOptions.$type === 'WebSocketDirect' ? conOptions.webSocket : new WebSocket(createUrl(conOptions));
    this.initMessageTransportWebSocket(webSocket, resolve, reject);
}
```

However, in the `performLanguageClientStart` method, the condition for triggering `startOptions.onCall` is :

```ts
await this.languageClient.start();

if ((conOptions.$type === 'WebSocketParams' || conOptions.$type === 'WebSocketUrl') && conOptions.startOptions !== undefined) {
    const startOptions = conOptions.startOptions;
    startOptions.onCall(this.getLanguageClient());
    if (startOptions.reportStatus !== undefined) {
        this.logger?.info(this.reportStatus().join('\n'));
    }
}
```

This discrepancy means that when `conOptions.$type === 'WebSocketDirect'`, the `startOptions.onCall` function is not executed.

**Comment by kaisalmen** [comment]
Hi @jinchaofs thank you for spotting that. Do you want to submit a PR that corrects it?

**Comment by jinchaofs** [comment]
> Hi @jinchaofs thank you for spotting that. Do you want to submit a PR that corrects it?

Sure ~
