### ISSUE TITLE
Example build fails with Node.js 8

### ISSUE THREAD

**Issue by franzbecker** [TypeFox/monaco-languageclient#8]
I cannot build the example on my machine with:
```
$ node --version
v8.2.0
$ npm --version
5.3.0
```

That seems to be a problem when using a newer Node.js / NPM version as you can see on Travis:
https://travis-ci.org/franzbecker/monaco-languageclient/jobs/255741802

The error occurs while compiling TypeScript:
```
> tsc

src/client.ts(60,57): error TS2345: Argument of type 'MessageConnection' is not assignable to parameter of type 'MessageConnection'.
  Types of property 'sendRequest' are incompatible.
    Type '{ <R, E, RO>(type: RequestType0<R, E, RO>, token?: CancellationToken | undefined): Thenable<R>; <...' is not assignable to type '{ <R, E, RO>(type: RequestType0<R, E, RO>, token?: CancellationToken | undefined): Thenable<R>; <...'. Two different types with this name exist, but they are unrelated.
      Types of parameters 'type' and 'type' are incompatible.
        Type 'RequestType0<any, any, any>' is not assignable to type 'RequestType0<any, any, any>'. Two different types with this name exist, but they are unrelated.
          Types have separate declarations of a private property '_'.
```

**Comment by Phantomape** [comment]
Any idea how to solve it ?

**Comment by franzbecker** [comment]
Haven't had any time to research it any further, but it might be a TypeScript issue, see this discussion: https://github.com/Microsoft/TypeScript/issues/16985 

The project should definitely use NPM 5 or Yarn in order to tie down the dependencies that are used for the build.

**Comment by franzbecker** [comment]
Didn't have the time to research it any further, a quick Google searched revealed this issue: https://github.com/Microsoft/TypeScript/issues/16985 but not sure if it applies.

The project should definitely use NPM 5 or Yarn in order to tie down the dependencies that are used for the build.

**Comment by Phantomape** [comment]
I changed "import { listen, MessageConnection } from 'vscode-ws-jsonrpc';" to "import { MessageConnection } from 'vscode-jsonrpc'; import { listen } from 'vscode-ws-jsonrpc';", and somehow got it working. Not sure that is the actual reason behind this error cause I also have some other modifications besides this change. As I dig deeper into the package vscode-ws-jsonrpc, I found out that MessageConnection in it is actually imported from vscode-jsonrpc, which confuses me; because as I see it, importing from vscode-jsonrpc or vscode-ws-jsonrpc doesn't make any difference.

**Comment by Phantomape** [comment]
I fixed this error using js8. I changed the dependency to `"monaco-languageclient": "^0.1.0"` in package.json instead of using source files in parent folder. Also, I change the compiler option to support es6 in addition to some other dependency paths. :)

**Comment by akosyakov** [comment]
It is because of npm5: https://github.com/TypeFox/monaco-languageclient/pull/19#issuecomment-324984839

Should be fixed by: https://github.com/TypeFox/monaco-languageclient/pull/25

**Comment by akosyakov** [comment]
Fixed by https://github.com/TypeFox/monaco-languageclient/pull/25
