### ISSUE TITLE
Question: Best practice for Browser-Side LS integration

### ISSUE THREAD

**Issue by nikeee** [TypeFox/monaco-languageclient#80]
I've got a language serivce written in TypeScript. It uses the types from `vscode-languageserver-types` to define a service, so that I can just delegate the actual LSP calls to the TS implementation. This is in a base library, which I want to use in the browser aswell.

I want this to be completely client-side and currently, I've provoded most features with some glue code similar to the code in [this sample](https://github.com/TypeFox/monaco-languageclient/blob/master/examples/browser/src/client.ts). IMHO this is fine as it has an acceptable overhead.

However, I now want to provide CodeActions and I realized that I have to provide a `Command` or a `CodeAction`. The latter also includes the actual edits. As the edits get computed in a different LSP method (`executeCommand`), the only way to get them is to compute all edits for all code actions, even if they are not executed by the user.

I don't want to do this. Sadly, monaco has no `executeCommand` equivalent in its `CodeActionProvider` interface. I've seen some references to `applyEdit` and a whole workspace implementation. However, it seemed to me that it's not that straigt-forward to implement CodeAction with the simple glue-code I am using right now. Or is it? Whats the status on that? Is there a best-practice?

I came across `class MonacoCommands implements Commands` which provides a method called `registerCommand`. Is this somehow relevant for me in this case? It seems that I have to register the command on an editor-level. I'd like to do it on a language-level (or something similar).

**Comment by rcjsuen** [comment]
You don't technically have to provide all the edits immediately. You can ask the language service only when the `Command` gets executed. This does require the use of Monaco internals though.

Please review my example code [here](https://github.com/rcjsuen/dockerfile-language-service/blob/b64359866f52581b22b0e10ae9f774cfdb5802b0/example/src/client.ts#L47-L70). Perhaps it may be of some help to you. You can go [here](https://rcjsuen.github.io/dockerfile-language-service/) to see my language server in action on the web.

**Comment by nikeee** [comment]
Accessing the private field of the editor seems like a hack to me. This is a basic feature, is there not better way?

**Comment by rcjsuen** [comment]
> Accessing the private field of the editor seems like a hack to me.

Unfortunately, that's the world we live in here, @nikeee.

> This is a basic feature, is there not better way?

Not that I know of. You can take it up with the [Microsoft/monaco-editor team](https://github.com/Microsoft/monaco-editor). Their [`addCommand` function](https://github.com/Microsoft/monaco-editor/blob/d7ef525b1d2ab817b9542644bf53af7ce2bd4042/monaco.d.ts#L1054-L1058) does not let one define an id so...

**Comment by rcjsuen** [comment]
> I think this is a command that you invoke by using a hotkey. This might not be the same as a "lightbulb command".

I believe when I last debugged it they both went through the same code, @nikeee. I could be wrong though.

If you can find an alternative way that works without using internals you could perhaps contribute a fix to [`commands.ts`](https://github.com/TypeFox/monaco-languageclient/blob/beca1e697bef460a721c2889d3b4afd5369b7ea7/src/commands.ts).

> is it really necessary to register a command every time one is provided? Couldn't we just register a command after we created the editor? The handler sould always remain the same. And we've got all command IDs anyways since we have to provide it when we initialize a language server.

What you described seems to make sense to me. You're right I probably don't have to add them again and again.

**Comment by rcjsuen** [comment]
I see you have opened Microsoft/monaco-editor#900. :)
