### ISSUE TITLE
feature: app playground file navigation

### ISSUE THREAD

**Issue by rubenfiszel** [TypeFox/monaco-languageclient#801]
Hi,

I'm experimenting with the app playground. It works fantastic and I've been able to customize it to our needs. There is just one issue which is that "Search workspace" and Ctrl+P doesn't seem to be able to navigate to existing files like it does in vscode. I've tested in the vanilla app playground app example and that's the case. Is there a straightforward way to make that work?

**Comment by rubenfiszel** [comment]
@kaisalmen I've tried by defining:
```
    function registerSearch() {
        const { getApi } = registerExtension(
            {
                name: "searchProvider",
                publisher: "codingame",
                version: "1.0.0",
                engines: {
                    vscode: "*",
                },
                enabledApiProposals: ["fileSearchProvider"],
            },
            ExtensionHostKind.LocalProcess,
            {
                system: true, // to be able to use api proposals
            }
        );

        getApi().then(async (api) => {
            console.log("Registering search provider");
            api.workspace.registerFileSearchProvider("file", {
                async provideFileSearchResults() {
                    console.log("XX");
                    return ["/workspace/foo.text"].map((x) => {
                        return vscode.Uri.file(x);
                    });
                },
            });
       }
      ```
      and calling registerSearch after `await wrapper.init(wrapperConfig)` in the main.ts of the playground but pressing Ctrl+P still doesn't allow doing quick navigation to `foo.text`

**Comment by kaisalmen** [comment]
@rubenfiszel have you added the additional service override
https://github.com/CodinGame/monaco-vscode-api/blob/main/demo/src/setup.common.ts#L38
https://github.com/CodinGame/monaco-vscode-api/blob/main/demo/src/setup.common.ts#L423
and the additional worker?
https://github.com/CodinGame/monaco-vscode-api/blob/main/demo/src/setup.common.ts#L291

**Comment by rubenfiszel** [comment]
The search service was all that was needed, thanks!
