### ISSUE TITLE
Issues when importing a .vsix-Extension with @codingame/monaco-vscode-rollup-vsix-plugin

### ISSUE THREAD

**Issue by hweber10** [TypeFox/monaco-languageclient#803]
Hello Team,

in our Project we use the monaco-editor-wrapper to build our own Editor.

We want our Editor to support .vsix-Extensions, specifically Language-Extensions. So we installed @codingame/monaco-vscode-rollup-vsix-plugin and added the vsixPlugin as a Plugin in our vite.config. (We run our project with vite)

But if I import a .vsix Extension (one that also runs in the browser) in our wrapperConfig and set the correct fileExtension in our wrapperConfig, the highlighting works, but I dont get any errors (I mean for wrong code inside the editor) nor does the intellisense work.
I have tried the following:
for [yaml](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) and for [terraform](https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform)

When trying YAML I get the following errors:
![grafik](https://github.com/user-attachments/assets/78812ad2-e85d-4eea-980b-2e2e08b92432)

I can solve the first error by editing the Content-Security-Policy in @codingame/monaco-vscode-extensions-service-override/assets/webWorkerExtensionHostIframe.html, but editing an installed Package is not really an option.
I dont know how to fix that error, since I have read [here](https://www.stackhawk.com/blog/react-content-security-policy-guide-what-it-is-and-how-to-enable-it/) that "A policy can never override a previous policy. ".

When trying Terraform in Firefox, I get a lot of Feature-Policy warnings, saying that an unknown feature was ignored.

I am not sure If the vsix-Plugin is supposed to import Languages with a LanguageServer, since only a small portion of all Language-Extensions are supported in the Browser, or if the Plugin is only supporting for example Themes...

Do you know more about my problem and can give me a hint in the right direction?

**Comment by CGNonofr** [comment]
Hello!

I've just had a look, and I confirm it's not due to what your are doing but some issues with the libs:
- The extension path reported to the extension ends with a `/` while it's not the case in VSCode, and the extension just concat it with the file path, instead of using path resolving methods
- There are missing script-src allowed shemes

**Comment by hweber10** [comment]
Hi, thank you for looking over it.

If I understand you correctly the resulting path `extension-file://redhat.vscode-yaml//dist/languageserver-web.js` is wrong because of some reason, as well as too strict Content Security Policies.

Do you know how one could fix that?, or is what we are trying to do not possible right now?

**Comment by CGNonofr** [comment]
The PR is coming, of course it's possible :)

**Comment by CGNonofr** [comment]
The v11.1.2 is currently publishing

**Comment by CGNonofr** [comment]
Published!

**Comment by CGNonofr** [comment]
Last time I've checked, it has to do with the VSCode default extension build process injecting source map references in generated code without emitting the source map file itself. It's only an "issue" when running the extension code through a bundler so VSCode itself is not impacted

**Comment by hweber10** [comment]
ok, maybe I can find a solution with that information.
About the Feature-Policy-Warnings -> I also dont know if should bother too much about them, since they are only in firefox

Thank you for your help

**Comment by CGNonofr** [comment]
It seems those errors are also present on vscode.dev, so I don't think there is anything to do about it

**Comment by kaisalmen** [comment]
> but otherwise I think we can mark this issue as completed.

✅
