### ISSUE TITLE
import ERROR "constants from module 'node:fs/promises" - @ /monaco-languageclient\node_modules\vite\dist\node\chunks\dep-BcnkIxro.js line 3

### ISSUE THREAD

**Issue by Rahulkand** [TypeFox/monaco-languageclient#804]
import fsp, { constants as constants$9 } from 'node:fs/promises'; 
              ^^^^^^^^^
SyntaxError: The requested module 'node:fs/promises' does not provide an export named 'constants'
I am unable to import the module as it doesn't provide an export named 'constants'

**Comment by kaisalmen** [comment]
@Rahulkand would you be so kind to add some context otherwise I will close this issue.

**Comment by Rahulkand** [comment]
I am trying to build a browser based code editor and want to integrate the editor, monaco-editor, with the language server. i am executed the command one by one as follows :
git clone https://github.com/TypeFox/monaco-languageclient.git
cd monaco-languageclient
npm i
# Cleans-up, compiles and builds everything
npm run build
while executing the npm run build the above mentioned error pop up telling. import ERROR "constants from module 'node:fs/promises".

**Comment by kaisalmen** [comment]
Hi @Rahulkand which node version are you using? We require node 18+. It seems we need to set proper engines entries. We have volta settings, but not engines settings everywhere.
