### ISSUE TITLE
How do I get proper highlighting (e.g. for python)?

### ISSUE THREAD

**Issue by arogozhnikov** [TypeFox/monaco-languageclient#81]
I see that highlighting works if I replace 
```
// replace this line 
require('monaco-editor-core');
// with this line
import * as monaco from 'monaco-editor';
```
(and add `monaco-editor` as a dependency). But this breaks the client due to difference in interfaces. 
This fails  even if I use monaco 0.12.0, same as used by monaco-languageclient.

**Comment by rcjsuen** [comment]
@arogozhnikov Could you please show the errors caused by the “difference in interfaces”?

**Comment by arogozhnikov** [comment]
I'm using latest version of package
```
  "dependencies": {
    "express": "^4.15.2",
    "monaco-editor": "^0.12",
    "monaco-languageclient": "^0.6.3",
    "normalize-url": "^2.0.1",
    "reconnecting-websocket": "^3.2.2",
    "request-light": "^0.2.2",
    "vscode-json-languageservice": "^3.0.12",
    "vscode-languageserver": "^4.0.0",
    "vscode-uri": "^1.0.3",
    "vscode-ws-jsonrpc": "^0.0.2-1",
    "ws": "^5.0.0"
  },
```

**Comment by arogozhnikov** [comment]
ping. Any ideas?

**Comment by rcjsuen** [comment]
Sorry, no. I have reproduced the problem but can't figure anything out off-hand. Hacking around it by casting it to `any` does work but that is of course not ideal.

```TypeScript
const services = createMonacoServices(editor as any);
```

**Comment by arogozhnikov** [comment]
@rcjsuen ok, will try with casting.

**Comment by shubhamsony** [comment]
i am facing the same issue. Syntax highlighting is not working when use monaco-editor-core with python language server. There is no basic languages support in monaco-editor-core. On replacing it with monaco-editor it is giving some weired error i.e. try appropiate loader

```
// replace this line 
require('monaco-editor-core');
// with this line
require('monaco-editor');
```

Here is the error log -

`ERROR in ../node_modules/monaco-editor/esm/vs/base/browser/ui/codiconLabel/codicon/codicon.ttf
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ../node_modules/css-loader!../node_modules/monaco-editor/esm/vs/base/browser/ui/codiconLabel/codicon/codicon.css 7:463-487
 @ ../node_modules/monaco-editor/esm/vs/base/browser/ui/codiconLabel/codicon/codicon.css
 @ ../node_modules/monaco-editor/esm/vs/base/browser/ui/codiconLabel/codiconLabel.js
 @ ../node_modules/monaco-editor/esm/vs/editor/standalone/browser/quickOpen/quickOutline.js
 @ ../node_modules/monaco-editor/esm/vs/editor/edcore.main.js
 @ ../node_modules/monaco-editor/esm/vs/editor/editor.main.js
 @ ./lib/main.js
error Command failed with exit code 2.
`

monaco-editor-core: 0.17.0
"monaco-editor": "0.19.0",

**Comment by GNSubrahmanyam** [comment]
@rcjsuen Any update ? 

Even i am getting this error

**Comment by rcjsuen** [comment]
> @rcjsuen Any update ?

@GNSubrahmanyam I am not actively looking at this issue so I have nothing to share.

**Comment by arnoson** [comment]
Just in case anyone is searching for a solution for syntax highlighing without include the full `monaco-editor`:

```js
// Replace lua with your language of choice :)

import { languages } from 'monaco-editor-core'
import { language, conf } from 'monaco-editor/esm/vs/basic-languages/lua/lua.js'

// To get the options, checkout the lanuage's contribution file. In case of lua:
//  `monaco-editor/esm/vs/basic-languages/lua/lua.contribution.js`
languages.register({
  id: 'lua',
  extensions: ['.lua'],
  aliases: ['Lua', 'lua'],
})
languages.setMonarchTokensProvider('lua', language)
languages.setLanguageConfiguration('lua', conf)

```

**Comment by dessen-xu** [comment]
@arnoson thank you.
