### ISSUE TITLE
monaco-languageclient sending messages with no method name

### ISSUE THREAD

**Issue by tylerl0706** [TypeFox/monaco-languageclient#88]
Here's a couple screenshots for reference:

The left side is of course monaco, the right side is the PowerShell language server logs

After loading the page the first time:
![image](https://user-images.githubusercontent.com/2644648/43115154-79c69c70-8eb7-11e8-8911-3516b5596d89.png)

After I refresh the page:
![image](https://user-images.githubusercontent.com/2644648/43115179-91801a62-8eb7-11e8-82da-955c8558379b.png)

The actual node server outputs nothing but "created" from a console log I added. I changed a single line in the example:

```
const serverConnection = server.createServerProcess('JSON', 'node', [extJsonServerPath]);
```
to
```
const serverConnection = server.createServerProcess('JSON', 'pwsh-preview', ['/home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/module/PowerShellEditorServices/Start-EditorServices.ps1', '-HostName', 'monaco', '-HostProfileId', '0', '-HostVersion', '1.0.0', '-LogPath', '/home/tylerleonhardt/Desktop/pses.log.txt', '-LogLevel', 'Normal', '-BundledModulesPath', '/home/tylerleonhardt/Desktop/vscode/PowerShellEditorServices/module', '-Stdio', '-SessionDetailsPath', '/home/tylerleonhardt/Desktop/.pses_session', '-FeatureFlags', '@()']);
```

I ran the exact language server startup command that monaco-languageclient should be running and it works as intended so I don't believe this is a fault of the language server.

**Comment by akosyakov** [comment]
@tylerl0706 Could you check raw messages whether they look proper? You can do it by inspecting ws frames in the dev tool for example.

**Comment by tylerl0706** [comment]
@akosyakov ![image](https://user-images.githubusercontent.com/2644648/43117251-ac1f90d8-8ec0-11e8-9b67-2fba70d8ba33.png)

I'm actually not seeing any ws frames - very strange

**Comment by akosyakov** [comment]
You should select `WS`, not `All`. There will be only one ws connection if you select it you will be able to see all messages which are sent in both directions.

**Comment by akosyakov** [comment]
Long story short: on `monaco-languageclient` side messages are written and parsed with [vscode-jsonrpc](https://www.npmjs.com/package/vscode-jsonrpc) which is battle-tested with a lot of applications. I would look for message parsing errors somewhere else.

**Comment by tylerl0706** [comment]
Annnnd this is because I had 2 services listening on same stdio stream. Totally my bad.

After I fixed that, I'm getting completions and everything :) thanks!

**Comment by akosyakov** [comment]
> After I fixed that, I'm getting completions and everything :) thanks

@tylerl0706 cool, glad that you solved it :) please ⭐️ the repo 🙏
