### ISSUE TITLE
Any way to send and listen for custom messages to the language server? 

### ISSUE THREAD

**Issue by tylerl0706** [TypeFox/monaco-languageclient#91]
In the VSCode extension for PowerShell using the PowerShell language server, you are able to select some code and hit "F8" to run the selection. 

This sends a custom message called "execute" from VSCode to the LS.

I know this isn't a standard LSP message, but I'm wondering if there's a way to send custom messages using monaco-languageclient.

**Comment by akosyakov** [comment]
Sure, look java extension for Theia sends a custom request: https://github.com/theia-ide/theia/blob/11fcd9baff55bea8b467469f7e9668691a13d2d5/packages/java/src/browser/java-commands.ts#L77-L82 Where `client` is an instance of `LanguageClient`.

**Comment by tylerl0706** [comment]
This looks great! I'll give it a go. 👍

**Comment by tylerl0706** [comment]
Actually, I should also ask - is there a way to _listen_ for custom messages as well on the client side?

**Comment by rcjsuen** [comment]
@tylerl0706 The language extension on the client side would have to listen for these arbitrary JSON-RPC messages, yes. How that is implemented would of course depend on the editor you are trying to integrate with and their LSP library/support.

**Comment by tylerl0706** [comment]
Indeed - I've setup listening for messages in both a vscode extension (using vscode-languageclient) and a vim plugin using (NeoVim-languageclient).

I'd love to do the same with monaco-languageclient 😊

**Comment by akosyakov** [comment]
@tylerl0706 monaco-languageclient is based on vscode-languageclient, API-wise they are alike, there are `sendRequest`, `sendNotificaftion` methods to send messages and `onRequest`, `onNotification` to listen for messages.

**Comment by tylerl0706** [comment]
@akosyakov you're awesome 👍 thanks for this!
