### ISSUE TITLE
How to enable syntax coloring in the browser example?

### ISSUE THREAD

**Issue by shoorlyne** [TypeFox/monaco-languageclient#93]
Syntax coloring in the browser example looks inactive when the language is changed to C++, like this:

<img width="833" alt="screen shot 2018-07-29 at 9 54 43 pm" src="https://user-images.githubusercontent.com/20250340/43367083-102e8ff8-937a-11e8-867f-036fb30acc53.png">

I have tried to set the language on the model like this:

```
const model = monaco.editor.createModel(value, 'cpp', monaco.Uri.parse('inmemory://model.cpp'));
const editor = monaco.editor.create(document.getElementById("container")!, {
    model: model,
    glyphMargin: true,
    lightbulb: {
        enabled: true
    }
});
monaco.editor.setModelLanguage(editor.getModel(), "cpp");
```

But it does not activate syntax coloring. This client has connected to a clangd language server.

Can anyone help please?

**Comment by shoorlyne** [comment]
I have tried all the suggestions in [Monaco Editor #375](https://github.com/Microsoft/monaco-editor/issues/375), but none of them seems to work.

**Comment by akosyakov** [comment]
`monaco-languageclient` depends only on monaco core package without dependencies to monaco languages: https://github.com/Microsoft/monaco-languages. You should add it and load in your application to enable basic languages.

**Comment by shoorlyne** [comment]
Now I have added monaco-languages module dependency in package.json like this:

```
"dependencies": {
    "glob-to-regexp": "^0.3.0",
    "monaco-editor-core": "^0.12.0",
    "vscode-base-languageclient": "^0.0.1-alpha.5",
    "vscode-languageserver-types": "^3.7.0"
}
```

However, I am still not seeing syntax coloring. What else can I try?

**Comment by mediarl** [comment]
Could you give an example on how to do add syntax coloring with the examples provided with code?
I am not able to make it work. I am not so familiar with module system so I am probably missing something.
Thanks

**Comment by RahulRajput1999** [comment]
Yes, can please give any reference to how to do that?
