### ISSUE TITLE
There is an error if open file after monaco connected to the language-server

### ISSUE THREAD

**Issue by Louis-7** [TypeFox/monaco-languageclient#96]
If I open a file (create a modal) in monaco after it connected to a language-server, there is a error `code
:
-32603
message
:
"Request textDocument/codeAction failed with message: Cannot read property 'version' of undefined"`.

Is this a bug of monaco-languageclient?

**Comment by akosyakov** [comment]
Hi @Louis-7, which LS do you use? It seems like an exception happened on the server side. On your place, I would investigate messages sent from a client to a server and if a request `textDocument/codeAction` looks good then it is a server issue. You can either investigate by looking at WS frames in your dev tools or enable tracing: 
```ts
languageClient.trace = Trace.Messages;
```

**Comment by Louis-7** [comment]
Hi @akosyakov , I forgot to mention, the LS I'm using is the json language server located in example folder [here](https://github.com/TypeFox/monaco-languageclient/tree/master/example).

I believe this is a server side issue, the content sent by client is correct, it's already tested. Any idea about why version number is missing? Seems version number is not defined by client but server. If LS is running well it will return something like `{"jsonrpc":"2.0","id":50,"result":[{"title":"Upper Case Document","command":"json.documentUpper","arguments":[{"uri":"inmemory://new.json/5","version":6}]}]}` . If I open a file after LS started, it will return the error message. (I will do debugging later~)

**Comment by Louis-7** [comment]
I did some more test. Error message is showing because I updated the monaco model language with [setModelLanguage](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#setmodellanguage).
