### ISSUE TITLE
TypeScript type only imports

### ISSUE THREAD

**Issue by zewa666** [TypeFox/monaco-languageclient#98]
Starting with TS 2.9.x we can do side-effect free imports. Not only does this reduce bundle sizes without the need for tree-shaking, but also guards from unwanted side-effects.

Such an example would be the [vscode import in vscode-api.ts](https://github.com/TypeFox/monaco-languageclient/blob/master/src/vscode-api.ts#L6)

**Comment by akosyakov** [comment]
I don't understand how `vscode` can be bundled and cause side-effects. It is just a declaration file which gets completely erased during compilation.

**Comment by zewa666** [comment]
Yep, sorry my bad I dunno how I thought I'd have seen a transpiled import for vscode in the resulting lib folder.
