### ISSUE TITLE
Request textDocument/codeLens failed with jdt.ls.

### ISSUE THREAD

**Issue by shoorlyne** [TypeFox/monaco-languageclient#99]
When I connect monaco language client to an Eclipse jdt.ls server, I got a "Request textDocument/codeLens failed" error.

First, I initialized the language client like this:

```
const model = monaco.editor.createModel(value, 'java', monaco.Uri.parse('Hello.java'));
...
monaco.editor.setModelLanguage(editor.getModel(), "java");
const services = createMonacoServices(editor, { rootUri: 'src' });
...
```

On the server, I have a `my-app` project generated by Maven in /sbin/.

After I fire up the client, I see the log in the console:

```
Sample Language Client: [Info  - 4:04:56 PM] Aug 1, 2018 8:04:58 AM Main thread is waiting
console-window.ts:35 Sample Language Client: [Info  - 4:04:56 PM] Aug 1, 2018 8:04:58 AM >> initialize
console-window.ts:35 Sample Language Client: [Info  - 4:04:56 PM] Aug 1, 2018 8:04:58 AM Initializing Java Language Server 0.23.0.201808010119
console-window.ts:35 Sample Language Client: [Info  - 4:04:56 PM] Aug 1, 2018 8:04:58 AM No workspace folders or root uri was defined. Falling back on /home
console-window.ts:35 Sample Language Client: [Info  - 4:04:57 PM] Aug 1, 2018 8:04:58 AM >> initialized
console-window.ts:35 Sample Language Client: [Info  - 4:04:59 PM] Aug 1, 2018 8:04:58 AM Importing Maven project(s)
console-window.ts:35 Sample Language Client: [Info  - 4:04:59 PM] Aug 1, 2018 8:04:58 AM Workspace initialized in 2743ms
console-window.ts:35 Sample Language Client: [Info  - 4:04:59 PM] Aug 1, 2018 8:04:58 AM >> java/buildWorkspace (full)
console-window.ts:35 Sample Language Client: [Info  - 4:04:59 PM] Aug 1, 2018 8:04:58 AM >> document/didOpen
console-window.ts:35 Sample Language Client: [Info  - 4:05:19 PM] Aug 1, 2018 8:04:58 AM >> document/codeLens
console-window.ts:35 Sample Language Client: [Error - 4:05:19 PM] Request textDocument/codeLens failed.
console-window.ts:35 Sample Language Client: Error: Internal error.
    at new ResponseError (http://localhost:3008/main.bundle.js:67549:28)
    at handleResponse (http://localhost:3008/main.bundle.js:66985:48)
    at processMessageQueue (http://localhost:3008/main.bundle.js:66813:17)
    at http://localhost:3008/main.bundle.js:66797:13
    at run (http://localhost:3008/main.bundle.js:134213:13)
    at runIfPresent (http://localhost:3008/main.bundle.js:134242:21)
    at onGlobalMessage (http://localhost:3008/main.bundle.js:134282:17)
```

From Chrome's Network ws traffic frame, I can see server response to the codeLens request is:

`{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)\n\tat java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)\n\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)\n\tat java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)\n\tat java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.IllegalArgumentException: URI has an authority component\n\tat sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:53)\n\tat sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)\n\tat java.nio.file.Paths.get(Paths.java:138)\n\tat org.eclipse.jdt.ls.core.internal.JDTUtils.getFakeCompilationUnit(JDTUtils.java:186)\n\tat org.eclipse.jdt.ls.core.internal.JDTUtils.resolveCompilationUnit(JDTUtils.java:140)\n\tat org.eclipse.jdt.ls.core.internal.JDTUtils.resolveCompilationUnit(JDTUtils.java:113)\n\tat org.eclipse.jdt.ls.core.internal.handlers.CodeLensHandler.getCodeLensSymbols(CodeLensHandler.java:169)\n\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:557)\n\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$23(JDTLanguageServer.java:732)\n\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)\n\t... 3 more\n"}}`

At this point, none of the LS features works.

Does anyone know what the issue is?

**Comment by akosyakov** [comment]
Hi @shoorlyne the error is from Java LS, you will have better luck asking it there.

From `java.lang.IllegalArgumentException: URI has an authority component` looks like some URI is bogus. Maybe: `rootUri: '/sbin/maven/my-app/src`. A URI is expected no a path.

**Comment by shoorlyne** [comment]
Thanks @akosyakov for your suggestions. Will try it later.
